square/okhttp

- mockwebserver/src/test/java/com/squareup/okhttp/mockwebserver/MockWebServerTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
This test is flaky when relying on the platform's built-in
HttpURLConnectionImpl.
Instead, test it with OkHttp's API and implementation.
> Test Expect: 100-continue with OkHttp, not HttpURLConnection.

- okhttp/src/main/java/com/squareup/okhttp/internal/http/RetryableSink.java
For your consideration and review, because this has a slight behavioral problem...
This method is called from two places in two different ways:
* `SpdyTransport.writeRequestBody` calls it with an instance of `SpdyDataSink`. This class is a `Sink` implementation which adds framing around a SPDY `FrameWriter` who ultimately delegates to a `BufferedSink` around the `Socket`.
* `HttpConnection.writeRequestBody` on the other hand passes a `BufferedSink` which is directly wrapped around the `Socket`.
The distinction of the former being a `Sink` and the latter being a `BufferedSink` means that `Okio.buffer` is going to behave differently. When we ultimately call `.emit()` to ensure we're not leaking segments, one writes directly to a `Socket` whereas the other hands off to another `Buffer` and …
> Use native Okio copy for retrying.

- pom.xml
These aren't needed since the full dependency is declared directly on the plugin below.
> Remove ALPN jars from dependencies block.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
This removes the logic from inside the loop for much better readability.
> Take no action if transferring zero bytes.

- okhttp-apache/src/main/java/com/squareup/okhttp/apache/OkApacheClient.java
- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
- okhttp/src/main/java/com/squareup/okhttp/ResponseBody.java
This is a binary-compatible change, but code that currently calls
ResponseBody [contentLength()|byteStream()|source()|charStream()]
that doesn't necessarily catch or declare IOException will need
to with this change.
These methods could be performing I/O (opening streams, etc.).
Throwing IOException seems reasonable in this case.
contentType() and charset() have not been changed.
> Source-incompatible: ResponseBody methods throw IOException

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/DiskLruCacheTest.java
- okhttp/src/main/java/com/squareup/okhttp/Cache.java
- okhttp/src/main/java/com/squareup/okhttp/internal/DiskLruCache.java
For Android this defers a non-zero amount of I/O when applications are initializing. Since this is both happening on app startup and on the main thread it has a large chance of non-trivially impacting startup even though the work is relatively small.
> Lazily initialize the cache.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/DiskLruCacheTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/DiskLruCache.java
isClosed() now means "has close() been called", after
commit ea565b2e30e15cd52ddfc2ddc6db4ea8f1c3de88
it meant "has not been initialized or close() has been
called".
Introduced explicit closed state. Minor tweak to use
initialized state to determine whether cleanup will
do anything. Added a test.
> Fix isClosed() when a cache has not been initialized

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
The important thing is that the Version.userAgent() string is used and
not the exact string.
> Fix the user agent test so it works with a different user agent string

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/RouteSelectorTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RouteSelector.java
Ultimate goal: to improve the TLS fallback behavior so that
socket connections will not be created if the necessary
TLS protocols will not be supported.
To achieve this RouteSelector will be moved into Connection
and so that it can be passed the Socket or protocol information
during the route selection process.
This is a small first step: Make RouteSelector independent
of Connection so that it can later be moved inside of
Connection. It puts the RouteSelector interface in terms
of Routes, which seems logical.
> Refactoring: Make RouteSelector independent of Connection

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
On Android getByName(null) returns the first of
[IPv6 loopback, IPv4 loopback], binding the server to ::1.
The IPv6 loopback address returns "localhost". "localhost"
does not resolve to the IPv6 address.
Instead: explicitly select "localhost" ensuring
MockWebServer binds to an IP that can be looked up by name
and should also be a loopback address.
Suggested fix for https://github.com/square/okhttp/issues/1069
> Modify the way MockWebServer selects a host IP to bind to

- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
Follow up to:
https://github.com/square/okhttp/pull/1196.
Combined with an NPN bug (18705877) on Android this is the
reason why fallback connections started failing on Android
after the COMPATIBLE_TLS was changed to be TLSv1.
[The NPN bug means that once enabled on a socket from an
SSLContext then NPN must be configured for every subsequent
socket otherwise some of the NPN state will still be set,
but some will be missing, leading to negotiation issues].
The implication of this change is that the follow up request
after a handshake failure may now be HTTP/2 or SPDY
(or HTTP/1.1). Previous to this change they would always
have been HTTP/1.1.
Previous to pull 1196 they would also have been
HTTP/1.1 because COMPATIBLE_TLS was SSLv3.
> TLSv1 supports TLS extensions so they should be enabled

- okhttp/src/main/java/com/squareup/okhttp/Request.java
In #610, support was added for `DELETE` requests to allow a `RequestBody`. Although this currently works internally, there's no way to load the request body through the convenience methods that `Request.Builder` exposes (like `Request.Builder.delete()`).
This PR introduces the ability to provide a `RequestBody` when building a `delete` request
Example usage:
```java
public void run() throws Exception {
Request request = new Request.Builder()
.url("https://someApiEndpoint")
.delete(RequestBody.create(MEDIA_TYPE_JSON, postBody))
.build();
//..
}
```
----
Currently, one has to call `method`:
```java
public void run() throws Exception {
Request request = new Request.Builder()
.url("https://someApiEndpoint")
.method("DELETE", RequestBody.create(MEDIA_TYPE_JSON, postBody))
.build();
//..
}
``` …
> Bugfix - Optional DELETE RequestBody via Request.Builder

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
On Android L (and probably prior releases) it is necessary to
close a socket explicitly rather than relying on
InputStream/OutputStream to do it for you.
See bug here: https://code.google.com/p/android/issues/detail?id=97564
> Fix for MockWebServer on Android

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/HeadersTest.java
- okhttp/src/main/java/com/squareup/okhttp/Headers.java
This change set adds a method to the `Headers` class which allows users to create a new `Headers` instance from a `Map<String, String>` (similar to `Headers#of(String[])`).
> Allow to create Headers from Map

- okhttp-android-support/src/main/java/com/squareup/okhttp/AndroidInternal.java
- okhttp-android-support/src/main/java/com/squareup/okhttp/AndroidShimResponseCache.java
- okhttp-android-support/src/main/java/com/squareup/okhttp/OkCacheContainer.java
- okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/android/HttpResponseCache.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/android/HttpResponseCacheTest.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/CacheAdapterTest.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java
Please see the commit comments for details.
I'd also like to propose a subsequent change to make the purpose of this code more obvious:
We move the following classes into an okhttp/okhttp-android-support sub-build + include it in the standard build (but in the same packages as they are today. The okhttp-android-support code would only be for Android to use, but by keeping it in the okhttp git repository we avoid future pain when Android pull from upstream, plus we reduce the amount of Android-specific junk in okhttp-httpurlconnection.
Move these:
1) AndroidShimResponseCache
2) OkCacheContainer
3) android/HttpResponseCache + Test
4) internal/huc/JavaApiConverter.java + Test
5) internal/huc/CacheAdapter.java
AFAIK, the only thing stopping this is the following method on OkUrlFactory. We …
> Fix ResponseCache handling for Android usecases

- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
ConnectionSpec instances will usually originate from
final statics, particularly ConnectionSpec.CLEARTEXT. This seems
like a no-brainer to avoid array comparisons.
> Trivial optimization for comparing ConnectionSpecs

- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
- okhttp/src/main/java/com/squareup/okhttp/Dispatcher.java
The LinkedBlockingQueue and core pool size of 0 do not interact well.
This prevents more threads from being created, harming overall
concurrency for async requests.
> Fix a major bug where threads weren't being created.

- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CacheTest.java
- okhttp-urlconnection/src/test/java/com/squareup/okhttp/UrlConnectionCacheTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/CacheStrategy.java
Related to https://github.com/square/okhttp/issues/831
Closes: https://github.com/square/okhttp/issues/1354
> Send at most one condition.

- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionSpecTest.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
I would like to be able to create ConnectionSpec's, like so:
``` java
ConnectionSpec mySpec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
.cipherSuites( ... strings or enums ... ).build();
```
* Users can use the String... API to set CiperSuites and TLS versions, enabling forward-compatibility. You may wish to encourage users to continue to use the enums, but we already have a use case where the enum is insufficient.
Thank you in advance for your review, and thank you for the library!
> ConnectionSpec: Allow custom specifications

- okhttp/src/main/java/com/squareup/okhttp/Connection.java
> Throw SSLPeerUnverifiedException when host verification fails, instead of IOException

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RouteSelector.java
This makes the HTTP stack throw java.net.UnknownServiceException if
a request is attempted using a protocol which matches none of the
configured connection specs. For example, this will happen if a cleartext
HTTP request is attempted when ConnectionSpec.CLEARTEXT is not
configured.
Fixes #1392
> A way to catch that cleartext HTTP request was attempted.

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RouteSelector.java
Closes https://github.com/square/okhttp/issues/1358
> Fail properly when a port is out of range.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/ws/WebSocketReaderTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/ws/WebSocketWriterTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ws/WebSocketProtocol.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ws/WebSocketReader.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ws/WebSocketWriter.java
The short and long continuations of payload length should be treated as unsigned values. Due to the sheer size of an unsigned long, any value over the signed Long.MAX_VALUE is forbidden.
Closes #1464.
> Payload length continuations are unsigned values.

- okhttp-tests/src/test/java/com/squareup/okhttp/RequestTest.java
- okhttp/src/main/java/com/squareup/okhttp/Request.java
If you have a request that has called `Request.url` a URL will be initialized and cached on the object. If you then call `Request.newBuilder` on the same request object it will copy over `url` and `urlString` to the builder.  If you then call `Request.Builder.url(String)` on the builder the `urlString` field is set, but not the `url` field.  Then when you call `Request.Builder.build`, you get the original `Request`'s url, *not* the url string set on the builder.
The suggested fix is to not copy `Request.url` to `Request.Builder.url` on initialization.
> null out Request.Builder.url when setting urlString

- mockwebserver/src/main/java/com/squareup/okhttp/internal/SslContextBuilder.java
MockWebServer binds to getByName("localhost"), SslContextBuilder was using
InetAddress.getByName(null) (null == any loopback). On Android, null
returns IPv6 loopback, which has the name "ip6-localhost".
> Fix for SslContextBuilder/MockWebServer disagreeing about localhost

- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
Firefox dropped these recently. I'm following their lead.
See also:
https://docs.google.com/spreadsheets/d/1C3FdZSlCBq_-qrVwG1KDIzNIB3Hyg_rKAcgmSzOsHyQ/edit#gid=0
> Drop some RC4 cipher suites.

- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/SpdyConnection.java
The latter returns a Future that we never call get() on, and
never get the exception from.
> Use ExecutorService.execute, not ExecutorService.submit.

- okcurl/src/main/java/com/squareup/okhttp/curl/Main.java
- okhttp-hpacktests/pom.xml
- okhttp-hpacktests/src/test/java/com/squareup/okhttp/internal/spdy/HpackDecodeTestBase.java
- okhttp-hpacktests/src/test/java/com/squareup/okhttp/internal/spdy/HpackRoundTripTest.java
- okhttp-hpacktests/src/test/java/com/squareup/okhttp/internal/spdy/hpackjson/HpackJsonUtil.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/HttpOverHttp2Test.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/HpackTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/Http2ConnectionTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/Http2FrameLoggerTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/Http2Test.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/MockSpdyPeer.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
- okhttp/src/main/java/com/squareup/okhttp/Protocol.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/ErrorCode.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/Hpack.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/Http2.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/Huffman.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/SpdyConnection.java
Http2 and Hpack have been [submitted] (https://www.rfc-editor.org/queue2.html#draft-ietf-httpbis-http2) to the IETF. This change removes the draft alpn identifier, and renames types accordingly.
tested with okcurl against twitter.com using ALPN.
```java
$ cd okcurl/
$ java -Xbootclasspath/p:$HOME/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/7.1.2.v20141202/alpn-boot-7.1.2.v20141202.jar -jar target/okcurl-2.3.0-SNAPSHOT-jar-with-dependencies.jar --frames https://twitter.com -X HEAD
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=utf8
>> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
>> 0x00000000     6 SETTINGS      
<< 0x00000000     6 SETTINGS      
>> 0x00000000     4 WINDOW_UPDATE 
>> 0x00000000     0 SETTINGS      ACK
>> 0x00000003    60 HEADERS …
```
> Updates to http/2 final

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/DiskLruCacheTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/FaultyFileSystem.java
- okhttp/src/main/java/com/squareup/okhttp/internal/DiskLruCache.java
- okhttp/src/main/java/com/squareup/okhttp/internal/FaultHidingSink.java
Closes https://github.com/square/okhttp/issues/1211
Working towards https://github.com/square/okhttp/issues/746
> Don't get corrupted when journal writing fails.

- samples/guide/src/main/java/com/squareup/okhttp/recipes/CustomTrust.java
To my great delight, Java and Android can read .pem files without
the BKS or JKS store files we typically use to distribute trusted
certificates.
This recipe includes a big copy-and-pasteable method for converting
an InputStream of PEM files into an SSLContext. The rest of it is
warnings about how dangerous that is.
Closes https://github.com/square/okhttp/issues/1336
> Custom trust recipe.

- pom.xml
This seems to be required for me to build successfully.
> Remove -SNAPSHOT from okio version

- samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java
This is the first draft of a (download) progress recipe, mentioned in #1471. 
Looking forward to suggestions for improvements. For example, the output is a bit verbose right now, for testing purposes, also the file is too small to actually show anything other than 100%, because it's <2KB which is the segment size of okio (from what I've gathered).
Also, am I missing something, there is no progress if I comment out line 56 (the `System.out` call), but that shouldn't influence the request afaik!?
Another thing, I'd like to provide another example for upload and split it into two files, `DownloadProgress.java` and `UploadProgress.java` or should it stay in one?
> Progress recipe

- samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java
Previously, this would pass `true` when it's not done and `false` when it's done (not that this is actually used anywhere).
> Pass correct boolean for `done` in Progress recipe

- okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/JavaApiConverterTest.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java
Android bug: https://code.google.com/p/android/issues/detail?id=160522
Fixes issue #1523
> Make badly-behaving caches cause a checked exception, not NPE

- mockwebserver/README.md
I realized that Dispatcher session in the README.md had few explanation and no quick example.
So I added one single line of explanation and a little example to quickly understanding.
> Adding more content and example to Dispatcher

- okhttp-tests/src/test/java/com/squareup/okhttp/OkHttpClientTest.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketCall.java
- okhttp/src/main/java/com/squareup/okhttp/Call.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
This will break mocks. We have a much simpler solution now, with
interceptors. Instead of mocking the HTTP client, use interceptors
to change its behavior.
Fix a bug where interceptor lists aren't independent after cloning
the OkHttpClient.
> Make OkHttpClient and Call final.

- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
I found an issue when using interceptors to change the `"User-Agent"` header, that `response.request().headers()` was showing the me the old default `"User-Agent"`.
I took a peek and noticed that `networkRequest` does not update with the *possibly* modified interceptors request. 
Let me know if I'm missing something here! Thanks!
> Interceptor request not returned in response

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionPoolTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionSpecTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/ConnectionSpecSelectorTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/RouteSelectorTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/URLConnectionTest.java
- okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java
- okhttp/src/main/java/com/squareup/okhttp/Address.java
- okhttp/src/main/java/com/squareup/okhttp/Call.java
- okhttp/src/main/java/com/squareup/okhttp/Connection.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
- okhttp/src/main/java/com/squareup/okhttp/Route.java
- okhttp/src/main/java/com/squareup/okhttp/TlsVersion.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ConnectionSpecSelector.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Internal.java
- okhttp/src/main/java/com/squareup/okhttp/internal/RouteDatabase.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RequestException.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RouteException.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RouteSelector.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/SocketConnector.java
API changes:
1) Added: Address.getCertificatePinner()
2) Incompatible API change: Address constructor no longer
includes ConnectionSpecs. Removed getConnectionSpecs().
3) Added: ConnectionSpec.isCompatible(SSLSocket)
4) Added: TlsVersion.javaNames()
Implicit / semantic / internal changes:
1) Connection now handles all attempts to connect via a route
(effectively a {proxy, socket address} pair), rather than just
one attempt. i.e. Connection now handles all the TLS negotiation
fallbacks internally.
2) Route no longer deals with TLS versions. Individual TLS
failures are not counted against a Route. If no connection
attempts to a route were successful the failure is counted
against the route.
3) The code makes a distinction between when various
IOExceptions occur, with the intention making …
> Move TLS retries / fallback into Connection.

- okhttp/src/main/java/com/squareup/okhttp/Dispatcher.java
goal: add monitoring around how many requests are queued, in-flight, and maximum capacity.
> Expose running and queued call counts for monitoring

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp/src/main/java/com/squareup/okhttp/Call.java
Closes https://github.com/square/okhttp/issues/1512
> Don't return null on call.proceed().

- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/WebSocketWriterTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/AutobahnTester.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketReader.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketWriter.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketCall.java
- okhttp/src/main/java/com/squareup/okhttp/Connection.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Internal.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java
* Ensure onOpen is called before the reader thread starts.
* Allow close reason without code.
* Use ProtocolException for protocol errors to ensure a close response is written.
Closes #1071. Closes #1296.
> Do not rebuffer socket streams for web sockets, other fixes.

- okhttp/src/main/java/com/squareup/okhttp/CertificatePinner.java
This addition to Javadoc will help developers who want to use `CertificatePinner` to pin self-signed certificates. 
See https://github.com/square/okhttp/issues/1352
P.S. When I saw `CertificatePinner` I decided to pin self-signed certificate via without configuring `TrustManager` & `SSLSocketFactory`, of course I failed :)
But I didn't find any info about self-signed certificates in [CertificatePinner's Javadoc](http://square.github.io/okhttp/javadoc/com/squareup/okhttp/CertificatePinner.html), so I decided to help others
> Add Javadoc about self-signed certificates

- okhttp-android-support/src/main/java/com/squareup/okhttp/AndroidShimResponseCache.java
- okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/CacheAdapter.java
- okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/JavaApiConverterTest.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java
- okhttp/src/main/java/com/squareup/okhttp/Headers.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Internal.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/OkHeaders.java
Keep the embedded OkHttp on Android working with Vary headers:
It breaks if an app bundles OkHttp and uses the platform's
android.net.http.HttpResponseCache: the OkHttp caching
requires a networkResponse to check the vary headers and it was
not being provided, leading to a NullPointerException. Further
changes were needed to actually retain the request headers
needed for the vary check itself.
To avoid regressions the existing ResponseCacheTest has been
changed to use the real cache. Previously, the use of
InMemoryResponseCache was hiding the Vary problem.
The ResponseCacheTest is now run with an AndroidShimResponseCache
to prove the tests work with real cases. The case without the shim
is covered with the CacheTest.
Switching the test to a real cache revealed a problem in the …
> Fix for issue #1589: Vary caching on Android

- mockwebserver/pom.xml
- okcurl/pom.xml
- okhttp-android-support/pom.xml
- okhttp-apache/pom.xml
- okhttp-hpacktests/pom.xml
- okhttp-testing-support/pom.xml
- okhttp-testing-support/src/main/java/com/squareup/okhttp/testing/InstallUncaughtExceptionHandlerListener.java
- okhttp-tests/pom.xml
- okhttp-urlconnection/pom.xml
- okhttp-ws-tests/pom.xml
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/SpdyConnection.java
- pom.xml
This is to make the tests more brittle around uncaught exceptions
as they are on Android. No uncaught exceptions should escape.
For issue #1552 .
Probably not necessary to say this but right now it will cause the CI to fail. Needs #1554 to pass.
> Install an UncaughtExceptionHandler during tests

- okhttp-tests/pom.xml
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformTestRun.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTestData.java
- okhttp-tests/src/test/resources/web-platform-test-results-url-chrome-42.0.json
- okhttp-tests/src/test/resources/web-platform-test-results-url-firefox-37.0.json
- okhttp-tests/src/test/resources/web-platform-test-results-url-safari-7.1.json
- okhttp-tests/src/test/resources/web-platform-test-urltestdata.txt
- pom.xml
This imports results from a few major browsers so we don't waste time
trying to pass tests that we shouldn't necessarily pass.
> Build a harness for web platform tests.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/UrlComponentEncodingTester.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
This works for all URL components except for host names. Those are
subject to other types of encoding.
> Implement percent encoding.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/RouteExceptionTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/URLConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RouteException.java
When performing TLS fallback, add previous exceptions to later ones as suppressed exceptions to help when debugging negotiation issues.
Results in output like this:
SSLv3-only server, SSLv3 disabled:
Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb81a4178: Failure in SSL library, usually a protocol error
error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0xb089cdf4:0x00000000)
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
at com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
at com.squareup.okhttp.Connection.connect(Connection.java:143)
at …
> Keep track of failures during negotiation for debugging

- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
I'd suggest enhancing the Javadocs to make it explicit how a Socket Factory is used. Thanks.
> Enhance Javadocs on OkHttpClient.setSocketFactory

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Avoid any risk of doing DNS during HTTP URL parsing.
Closes https://github.com/square/okhttp/issues/1613
> Do IPv6 parsing natively.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/UrlComponentEncodingTester.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Similarly for all other URL components.
Basically the decoded form now gets the shorter name.
> Rename username to encodedUsername and decodeUsername to username

- okhttp-tests/src/test/java/com/squareup/okhttp/FormEncodingBuilderTest.java
- okhttp/src/main/java/com/squareup/okhttp/FormEncodingBuilder.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
This is a behavior change: previously we'd encode '+' as plus
and encode characters that don't need it, including ','. Now
we use the same rules as HttpUrl.
> New FormEncodingBuilder.addEncoded() API.

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java
This was causing crashes.
Closes https://github.com/square/okio/issues/133
> Don't share timeouts between pooled connections.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- okhttp-testing-support/src/main/java/com/squareup/okhttp/testing/RecordingHostnameVerifier.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionPoolTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/URLConnectionTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/WebSocketCallTest.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketCall.java
- okhttp/src/main/java/com/squareup/okhttp/Request.java
I contemplated supporting them in HttpUrl, but then realized I'd
either need to document that behavior (which is weird behavior)
or return ws from the scheme (which seems arbitrary.)
Doing it in Request seems less bad: we support websockets requests.
> Accept ws: URLs in Request.Builder.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/AutobahnTester.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/WebSocketCallTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/WebSocketRecorder.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketCall.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketListener.java
- samples/guide/src/main/java/com/squareup/okhttp/recipes/WebSocketEcho.java
This also removes the explicit Request from WS open callback. It can be accessed by calling 'request()' on the supplied Response.
Closes #1639.
> Add optional Response to WS failure callback.

- okhttp/src/main/java/com/squareup/okhttp/Call.java
Monitoring libraries such as New Relic need to have the ability to subclass certain interesting classes in order to provide effective instrumentation. In previous versions of Okhttp, the Call constructor was protected, but it seems this changed in v2.4. This commit reverts Call from package-private to protected to allow for instrumentation.
> Revert Call to a protected class instead of package-private

- okhttp-tests/src/test/java/com/squareup/okhttp/FormEncodingBuilderTest.java
- okhttp/src/main/java/com/squareup/okhttp/FormEncodingBuilder.java
This PR addresses: #1704 
I was not able to build a proper artifact to test integration as it looks like `com.squareup.okhttp.internal.Version` is missing. However, commenting out the relevant code allowed for the unit tests in `FormEncodingBuilder` to run and they passed.
Edit: looks like it's not missing, I just don't know how to build the project properly. :)
> Relaxed FormEncodingBuilder to allow building empty forms.

- okhttp-tests/src/test/java/com/squareup/okhttp/FormEncodingBuilderTest.java
- okhttp/src/main/java/com/squareup/okhttp/FormEncodingBuilder.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Right now we're using the same encode set as the URL query; that's a mistake.
> Fix FormEncodingBuilder to be consistent with browsers.

- pom.xml
> Bump Okio to 1.5.0.

- okhttp/src/main/java/com/squareup/okhttp/Cache.java
- okhttp/src/main/java/com/squareup/okhttp/internal/DiskLruCache.java
The DiskLruCache’s cache does lazy initialization. The time spent in
initialization varies depending on the actual cache size and journal
file size.
On very low end device, the initialization time could be as long as
1000 ms once the cache reaches 100M for example on a 4.0 device. This
has significant performance impact on the very 1st cache hit.
So the proposed solution is to give the developer an opportunity to
explicitly do the initialization early on and in a back ground thread.
Without this change, the developer would have to call any method from
the Cache class to warm up the cache implicitly.
> make the DiskLruCache's initialize() public through the Cache interface

- benchmarks/src/main/java/com/squareup/okhttp/benchmarks/ApacheHttpClient.java
- okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/android/HttpResponseCacheTest.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/JavaApiConverterTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/HttpOverSpdyTest.java
- okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java
- okhttp/src/main/java/com/squareup/okhttp/Call.java
- okhttp/src/main/java/com/squareup/okhttp/Connection.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ConnectionSpecSelector.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Util.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/AuthenticatorAdapter.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/CacheStrategy.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/FramedTransport.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RequestLine.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RouteSelector.java
- samples/crawler/src/main/java/com/squareup/okhttp/sample/Crawler.java
- samples/guide/src/main/java/com/squareup/okhttp/recipes/LoggingInterceptors.java
Closes https://github.com/square/okhttp/issues/1044
> Use HttpUrl internally.

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/RequestTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/Headers.java
This includes potential security problems (newline characters) as well as
simple non-ASCII characters including international characters and emoji.
Closes https://github.com/square/okhttp/issues/891
> Be strict on invalid characters in request headers.

- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
- okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Util.java
See https://github.com/square/okhttp/issues/891
> Make sure the default user agent is ASCII.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Addresses #1788 
Not really sure this is the best solution, but my idea was to check the port when you're building the Url, and if the port is a default (which would be assigned from parsing a http(s)), use the default port for the scheme instead. 
I'd be glad to make changes to my approach if you had something else in mind!
> Changing the scheme will update the default port

- okhttp-tests/src/test/java/com/squareup/okhttp/TestUtil.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/framed/Http2ConnectionTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/framed/Spdy3ConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/framed/Http2.java
- okhttp/src/main/java/com/squareup/okhttp/internal/framed/Spdy3.java
We were a little too aggressive in checking our preconditions. If a previous
write failed, we don't want the following write to crash. (It'll throw an
IOException anyway.)
Closes https://github.com/square/okhttp/issues/1651
> Don't throw IllegalStateException after an IOException.

- okhttp/src/main/java/com/squareup/okhttp/Connection.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Util.java
Originally submitted by @pguilbot.
See also https://github.com/square/okhttp/issues/1684
> Recover from Android 4.2.2 EBADF crashes.

- CHANGELOG.md
The previous wording made it sound like any connection that was ongoing
for more than 10 seconds (e.g. a download of a large file) would be
disconnected.
> Change ambiguous wording for timeouts

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/DelegatingSSLSocketFactory.java
- okhttp-tests/src/test/java/com/squareup/okhttp/DelegatingServerSocketFactory.java
- okhttp-tests/src/test/java/com/squareup/okhttp/DelegatingSocketFactory.java
- okhttp-tests/src/test/java/com/squareup/okhttp/FallbackTestClientSocketFactory.java
- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/DisconnectTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/ThreadInterruptTest.java
From comments in a different PR.
Modify the various Delegating*SocketFactory implementations
to return a *Socket from configureSocket() rather than assume
configuration just modifies the object supplied. Improves
flexibility and reduces the need to override multiple methods
in some places.
> Test code refactoring

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Added additional encoding characters that cause URI to throw an `URISyntaxException` when used in a query parameter.
fixes this issue (reported on retrofit, but belongs on okhttp) https://github.com/square/retrofit/issues/1058
> Fix encoding set for query parameters

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Even though `HttpUrl` only supports http and https URLs, it should still consider a URI like `image640://480.png` as valid, even though it's unsupported. This changes `schemeDelimiterOffset()` to correctly account for digits in the scheme.
Specs: https://tools.ietf.org/html/rfc3986#page-17
> Consider digits in HttpUrl scheme as valid

- okhttp-tests/src/test/java/com/squareup/okhttp/DelegatingSSLSocketFactory.java
Commit 765a965 (pr #1835) did not modify all the necessary lines
when changing the configureSocket() method over from a
modify-in-place to a return-modified pattern. The problem
only shows up on Android where the behavior is required for
TLS_FALLBACK_SCSV tests to work.
> Fix DelegatingSSLSocketFactory for Android

- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/FramedTransport.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
Changing the request method from e.g. `GET` to `POST` in a network interceptor lead to the body not being written to the transport. That's because `HttpEngine#permitsRequestBody()` was using the original request to determine whether sending a request body was allowed.
> Allow interceptor to change method

- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/WebSocketReaderTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/WebSocketWriterTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/AutobahnTester.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/WebSocketCallTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/WebSocketRecorder.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketReader.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketWriter.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocket.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketListener.java
- samples/guide/src/main/java/com/squareup/okhttp/recipes/WebSocketEcho.java
This actually breaks the `WebSocketEcho` sample because echo.websocket.org is non-spec complaint (as far as I can tell). Because all messages are technically streamed now, we send an empty close frame which it omits from the frames it echoes back causing a `ProtocolException` by `WebSocketReader` (correctly, I might add).
> Represent WebSocket payload using RequestBody and ResponseBody.

- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/WebSocketWriterTest.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/WebSocketRecorder.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketProtocol.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketReader.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketWriter.java
- samples/guide/src/main/java/com/squareup/okhttp/recipes/WebSocketEcho.java
This eliminates the need to always send a frame for every `FrameSink#write` and to always send an empty frame for `FrameSink#close`. Now, we only emit bytes once Okio reports complete segments.
> Introduce intermediate storage for frame contents.

- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
URLConnectionTest.testWrites allocates a 16MB buffer.
It can run in less memory (and causes problems
on low-spec Android devices).
4k is the typical smallest allowable buffer size on Linux.
> Reduce the memory requirements of a test

- okhttp-testing-support/src/main/java/com/squareup/okhttp/internal/io/InMemoryFileSystem.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CacheTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/RecordingCallback.java
- okhttp-urlconnection/src/test/java/com/squareup/okhttp/OkUrlFactoryTest.java
- okhttp-urlconnection/src/test/java/com/squareup/okhttp/UrlConnectionCacheTest.java
This currently fails in 3 tests:
*  `CacheTest.emptyResponseHeaderNameFromCacheIsLenient`
java.lang.IllegalStateException: The following resources were not closed:
* Sink for /cache/6c5cbd852817bc0e3f733c8775e1e553.1.tmp
*  `CacheTest.secureResponseCaching`
java.lang.IllegalStateException: The following resources were not closed:
* Source for /cache/19787c3aab51546f8895b94f40bb7d88.1
*  `CallTest.conditionalCacheHit_Async`
java.lang.IllegalStateException: The following resources were not closed:
* Source for /cache/189d350b717aa73377fd9b12ad9b1733.1
> Add a strict mode of sorts to InMemoryFileSystem to detect handle leaks.

- okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/com/squareup/okhttp/logging/HttpLoggingInterceptorTest.java
This allows chunked responses with no specified length to be logged and have their size reported correctly.
Closes #1935.
> Remove the need for an explicit Content-Length header to log response body.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
fixes - https://github.com/square/okhttp/issues/1872
1) Use the [URI's multi-parameter](http://docs.oracle.com/javase/7/docs/api/java/net/URI.html#URI%28java.lang.String,%20java.lang.String,%20java.lang.String,%20int,%20java.lang.String,%20java.lang.String,%20java.lang.String%29) constructor does piecewise encoding. 
2) Removed test (toUriForbiddenCharacter) that expects '[' to be invalid in the path segment since it will be encoded now.
3) Updated the `invalidHost` test to expect a different exception.  It appears that URI errors earlier in the process (URI creation) using this constructor.
4) reverts previous fix (https://github.com/square/okhttp/pull/1845)
> use URI constructor for encoding

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/QueueDispatcher.java
`QueueDispatcher` currently logs favicon requests to `System.out`. We should use a `Logger` instead so these messages can be suppressed if required.
> Log favicon request instead of using standard output

- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
- okhttp/src/main/java/com/squareup/okhttp/Call.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
Previously we were treating null as a sentinel 'canceled' value
for application interceptors, and crashing on network interceptors.
Closes https://github.com/square/okhttp/issues/1921
> Throw the right exception if an interceptor returns null.

- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
Tracking Chrome and Firefox, which have also dropped this cipher suite.
This is the only cipher suite change since the last update. See our cipher
suites spreadsheet for a comparison: https://goo.gl/dWXbi0
Closes https://github.com/square/okhttp/issues/1476
> Drop our one remaining DSS cipher suite.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/allocations/ConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionPool.java
- okhttp/src/main/java/com/squareup/okhttp/internal/allocations/Connection.java
This is intended to replace some of the state machines in HttpConnection, HttpEngine,
and ConnectionPool. With this we'll keep track of all streams in flight, not just
the connections currently idle.
Note that I've sketched this out into a new Connection.java class. In a follow up
change I'll attempt to combine this with the existing Connection class.
> Connection allocations model.

- okhttp-tests/src/test/java/com/squareup/okhttp/FormEncodingBuilderTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Previously we forced %20, which offended some broken web servers.
Closes https://github.com/square/okhttp/issues/1920
> Permit space to be encoded as + or %20.

- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocket.java
This breaks apart the states used to track sending a close message and whether or not the connection has been closed. Prior to this, certain threading orders would allow multiple calls to close() which would attempt to remove ownership of the connection, the second of which would fail.
Closes #1931.
> Break apart close states. Try to send close on IOE.

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionPoolTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/Connection.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Internal.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
The tunnel is shared between requests, and it's awkward to build that with the
first request that needs it.
> Don't use the request to build the proxy tunnel.

- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocket.java
This actually un-fixes #1931, but it formalizes the consumer behavior (and ensures that it will behave correctly).
> Force consumers to call WS#close on IO error.

- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpMethod.java
> If the OPTIONS request includes an entity-body (as indicated by the presence of Content-Length or Transfer-Encoding), then the media type MUST be indicated by a Content-Type field. Although this specification does not define any use for such a body, future extensions to HTTP might use the OPTIONS body to make more detailed queries on the server. A server that does not support such an extension MAY discard the request body.
> OPTIONS allows body.

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/HeadersTest.java
- okhttp/src/main/java/com/squareup/okhttp/Connection.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Internal.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/FramedTransport.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpTransport.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RequestLine.java
This was updating the protocol as a side-effect of an HTTP/1.0 response.
This made the protocol field mutable, and the code more difficult to
trace.
One consequence of this change is that OkHttp will attempt HTTP/1.1 for
all requests, even if a server returns HTTP/1.0 from the first response.
This is closer to our implementation anyway.
> Stop returning HTTP/1.0 from Connection.getProtocol().

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
There's a race where the HTTP engine has been created, but not yet connected
and the cancel isn't as immediate as it could be. Fix the test by making sure
there's a response to be retrieved.
With the upcoming connection pool changes we might make the implementation
more robust.
Closes: https://github.com/square/okhttp/issues/2001
> Fix flakiness in CallTest.cancelTagImmediatelyAfterEnqueue()

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/HeadersTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/FramedTransport.java
When multiple headers have the same value in SPDY/3, they are concantenated
and separated by \u0000.
When multiple headers have the same value in HTTP/2, they are each written
independently.
This fixes the problem and rearranges the code to share less behavior than
previously. It gets us closer to being able to drop SPDY/3.
Closes https://github.com/square/okhttp/issues/1906
> Fix HTTP/2 bug where we were using SPDY/3 style header concatenation.

- okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/com/squareup/okhttp/logging/HttpLoggingInterceptorTest.java
@swankjesse as promised in twitter discussion.
JFYI: this is actually a little breaking change because in recently released 2.6 `null` value breaks the logic of the interceptor and it works as `Level.BASIC` (at first glance I thought it'll work as `NONE`, but, in fact, it works as `BASIC`). Not sure that @JakeWharton wanted such behavior (though if it was intended — just close this PR).
> Add null check to HttpLoggingInterceptor.setLevel()

- okhttp-tests/src/test/java/com/squareup/okhttp/NewConnectionPoolTest.java
These use the Call APIs. They're high-level so they won't break with the
implementation rewrite.
> Write some new connection pool tests.

- okhttp/src/main/java/com/squareup/okhttp/CertificatePinner.java
"sha1/BOGUSPIN" throws an `IllegalArgumentException` because `BOGUSPIN` is not valid base64.
> Use bogus pin that doesn’t throw an exception

- okhttp-tests/src/test/java/com/squareup/okhttp/SocksProxy.java
- okhttp-tests/src/test/java/com/squareup/okhttp/SocksProxyTest.java
- okhttp/src/main/java/com/squareup/okhttp/Connection.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/RouteSelector.java
This small patch ensures that a connection through a SOCKS proxy will have its hostname resolved through the proxy as well. It includes a test case for that behaviour.
> Remote DNS resolving for connections through a SOCKS proxy

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/Http2xStream.java
- okhttp/src/main/java/com/squareup/okhttp/internal/io/RealConnection.java
Previously we could close an SSL socket which does synchronous I/O. This
made it unreasonable to cancel a call on a UI thread.
Closes: https://github.com/square/okhttp/issues/1592
> Change async cancel to cancel the raw socket only.

- mockwebserver/src/main/java/com/squareup/okhttp/internal/framed/FramedServer.java
- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/framed/Http2ConnectionTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/framed/Spdy3ConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/framed/FramedConnection.java
- okhttp/src/main/java/com/squareup/okhttp/internal/io/RealConnection.java
Previously we had a BufferedSource in the RealConnection and another
independent BufferedSource in the FramedConnection. We only need one.
> Fewer buffers in FramedConnections.

- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionPoolTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/NewConnectionPoolTest.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionPool.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/StreamAllocation.java
- okhttp/src/main/java/com/squareup/okhttp/internal/io/RealConnection.java
We still don't implement a limit on the number of open connections.
That needs to come afterwards, and will be difficult because we'll
need to add policy on which connections to evict.
> Restore time-based eviction.

- okhttp-logging-interceptor/src/test/java/com/squareup/okhttp/logging/HttpLoggingInterceptorTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
- okhttp/src/main/java/com/squareup/okhttp/Call.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/Http1xStream.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/StreamAllocation.java
There's a few places where OkHttp could leak a connection that needed to be
closed. With our new connection pool model this is easier to find. This fixes
two specific problems:
- too many redirects doesn't release the last used connection
- interceptors that throw runtime exceptions don't release the connection
There are likely more situations. I have hacked together a small little test
harness to make finding these leaks easier; that's not included in this PR.
> Fix some stream leaks.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/SocketPolicy.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/URLConnectionTest.java
Android has been receiving reports of some tests being flaky
on what are probably lower-spec devices.
This introduces delays into tests where sockets are being
poisoned after the entire response body has been written to
them *and* where there are follow-up requests.
This change also improves the documentation for the problematic
SocketPolicy values.
> Reduce flakiness and document reasons for flakiness

- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
Yay stream allocations.
Closes: https://github.com/square/okhttp/issues/1502
> We don't have resource leaks in interceptor crashes anymore.

- okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/CacheAdapter.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/JavaApiConverterTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/RequestTest.java
- okhttp-urlconnection/src/test/java/com/squareup/okhttp/internal/huc/URLEncodingTest.java
- okhttp/src/main/java/com/squareup/okhttp/Request.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
There's a mostly-academic corner case on URLs like http://host/%xx that
have a malformed escape sequence. This changes the exceptions on those
URLs from checked to unchecked.
I think we may want a separate change to HttpUrl to fix those URLs to
be encoded as http://host/%25xx which avoids the problem altogether.
Closes: https://github.com/square/okhttp/issues/2106
> Drop Request.uri(). Just use Request.url().uri().

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp-tests/src/test/java/okhttp3/internal/RecordingOkAuthenticator.java
- okhttp/src/main/java/okhttp3/Address.java
- okhttp/src/main/java/okhttp3/Authenticator.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/http/AuthenticatorAdapter.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/http/OkHeaders.java
- okhttp/src/main/java/okhttp3/internal/io/RealConnection.java
- samples/guide/src/main/java/okhttp3/recipes/Authenticate.java
Instead of having one instance of Authenticator, and that interface
defines two methods, we now have two instances of Authenticator and
that interface defines one method.
This prevents leaking request-specific configuration (the authenticator)
into shared connection configuration (the proxy authenticator).
> One authenticate method on the authenticator interface.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/MockSpdyPeer.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/Spdy3ConnectionTest.java
Closes: https://github.com/square/okhttp/issues/1797
> Reduce flakiness in Spdy3ConnectionTest.headersOnlyStreamIsClosedAfterReply

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/RecordingProxySelector.java
- okhttp-tests/src/test/java/okhttp3/internal/http/RouteSelectorTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpURLConnectionImpl.java
- okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java
- okhttp/src/main/java/okhttp3/Call.java
- okhttp/src/main/java/okhttp3/internal/http/Http1xStream.java
- okhttp/src/main/java/okhttp3/internal/http/Http2xStream.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/http/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/io/RealConnection.java
This changes the new allocations model to keep the same route unless it
has been specifically found to have connectivity problems. Previously we
attempted to null out the route selector when a route succeeded; with
this we do the opposite by nulling out a route when it fails.
Closes: https://github.com/square/okhttp/issues/1736
> Attempt an alternate route when a connect times out.

- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/JavaApiConverterTest.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/RecordedResponse.java
- okhttp/src/main/java/okhttp3/Cache.java
- okhttp/src/main/java/okhttp3/Handshake.java
This is awkward because it adds another field to the cache. I've
decided to try to keep old values in the cache working. We will
probably do a change that'll disrupt the cache later, but that
is invasive and we don't need that yet.
> Add TlsVersion to the Handshake.

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/main/java/okhttp3/FormBody.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
Just do arbitrary amounts of transformation. Sigh.
Closes https://github.com/square/okhttp/issues/2116
> Never throw converting an HttpUrl to a java.net.URI.

- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverSpdyTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/CookiesTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/JavaNetCookieJar.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/JavaNetHeaders.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpURLConnectionImpl.java
- okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java
- okhttp/src/main/java/okhttp3/CookieJar.java
- okhttp/src/main/java/okhttp3/Handshake.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/http/OkHeaders.java
No good first-party implementation yet.
There is an implementation in okhttp-urlconnection that delegates to the java.net
CookieHandler. That should be good enough for AOSP.
> New CookieJar interface.

- okcurl/src/main/java/okhttp3/curl/Main.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverSpdyTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/SystemPropertiesConnectionPool.java
- okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
Instead each new instance of OkHttpClient gets its own connection pool by
default. This makes the OkHttpClient instances a little more heavyweight
(in that two different instances yield two different connection pools, which
means two different cleanup threads) but it also means there's less weird
state sharing between instances.
One drawback of this is that if an application wants to immediately free
resources from an OkHttpClient it must call getConnectionPool().evictAll(),
otherwise the connection pool thread will remain alive for 5 minutes.
> Drop the global static shared connection pool.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-testing-support/src/main/java/okhttp3/RecordingCookieJar.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverSpdyTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/CookiesTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/JavaNetCookieJar.java
- okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java
- okhttp/src/main/java/okhttp3/CookieJar.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
There's a big consequence to this for compatible with RFC 2965 Cookies. In particular,
this drops our ability to support 'Set-Cookie2' headers, and some features used there
including quoted attributes like 'Max-Age="25"'. This is the right move for interop with
browsers, and likely to make things better for application developers, but some
people who strictly followed the RFC 2965 spec will be broken. (That spec was never
seriously adopted anywhere, which is the entire motivation of RFC 6265.)
The upside is the CookieJar interface is now much more straightforward. This is
particularly good going forward, and for clients who don't have to worry about the
strangeness of things like $Version=1 in the RFC 2965 spec.
> Change CookieJar to deal with Cookies, not Headers.

- okhttp/src/main/java/okhttp3/internal/http/StreamAllocation.java
This is imperfect, but it should save some unnecessary work and will
hopefully prevent RouteSelector from attempting a route when none is
available.
https://github.com/square/okhttp/issues/2151
> Don't do health checks on brand new connections.

- okhttp/src/main/java/okhttp3/Call.java
- okhttp/src/main/java/okhttp3/RealCall.java
In a follow up I'm going to drop support for canceling calls based on
their tag. Instead, dispatcher might be able to just expose all of the
in-flight calls, and the application layer can loop over those and
cancel based on tags or other criteria.
> Add an accessor to get a Call's Request.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetAuthenticator.java
- okhttp/src/main/java/okhttp3/Dispatcher.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
Instead Dispatcher exposes rich methods to access the in-flight calls,
which the application can cancel by whatever criteria is prefered.
> No more canceling by tag.

- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/HeadersTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpURLConnectionImpl.java
- okhttp/src/main/java/okhttp3/Headers.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
Previously we would accept invalid input, but crash when that invalid input
was used.
> Detect API use errors earlier.

- okhttp-apache/pom.xml
- okhttp-logging-interceptor/pom.xml
- okhttp-urlconnection/pom.xml
- okhttp-ws/pom.xml
- okhttp/pom.xml
- pom.xml
This PR adds basic support for OSGi to okhttp jars by adding the proper meta-data to jar's MANIFEST.
Notes:
- okhttp-urlconnection is not well supported as this artifact has the same packages as main okhttp one but as far as I understand OkHttp as now a better replacement
- it would have be better if okhttp-ws had okhttp3.ws.internal instead of okhttp3.internal.ws so that there is a clear distinction between okhttp-ws internal and okhttp ones
> Make OkHttp OSGi ready

- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
We might still need them to handle a redirect.
Closes: https://github.com/square/okhttp/issues/2198
> Don't eagerly release pools on cache hits.

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
> Logging Interceptor - Use charset specified by the request body content type

- benchmarks/src/main/java/okhttp3/benchmarks/OkHttpAsync.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/RecordingCallback.java
- okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java
- okhttp/src/main/java/okhttp3/Callback.java
- okhttp/src/main/java/okhttp3/RealCall.java
- samples/guide/src/main/java/okhttp3/recipes/AsynchronousGet.java
This makes it much easier to test if the call was canceled.
Note that the Call's request is always the original user request.
This is different than the previous request that was passed in, as
that could have been the follow up to a redirect.
> Change Callback to take a Call.

- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/internal/io/RealConnection.java
This removes some awkward code where the synchronized connection pool is calling
a synchronized methond on a connection. Nested synchronized is gross.
> Use listeners to observe allocation limit changes.

- okhttp-android-support/src/test/java/okhttp3/internal/huc/CacheAdapterTest.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-testing-support/src/main/java/okhttp3/FakeDns.java
- okhttp-testing-support/src/main/java/okhttp3/FakeProxySelector.java
- okhttp-testing-support/src/main/java/okhttp3/FakeSSLSession.java
- okhttp-testing-support/src/main/java/okhttp3/RecordingHostnameVerifier.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp-tests/src/test/java/okhttp3/RecordedResponse.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverSpdyTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/RouteSelectorTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/HostnameVerifierTest.java
- okhttp-ws-tests/src/test/java/okhttp3/ws/WebSocketCallTest.java
This is more work towards being able to later delete HttpURLConnectionImpl
without losing test coverage.
Also do some test cleanup.
> Create request/response API tests to match some URLConnectionTest tests.

- okhttp-urlconnection/src/main/java/okhttp3/OkUrlFactory.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/URLFilter.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpURLConnectionImpl.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpsURLConnectionImpl.java
- okhttp-urlconnection/src/test/java/okhttp3/OkUrlFactoryTest.java
This optional filter can be used to allow for blocking HTTP traffic to
certain URLs, for example in order to prevent accessing sensitive
content over HTTP instead of HTTPS.
This behavior is already possible for clients of OkHttpClient, this patch allows legacy clients using the HttpUrlConnection APIs to do basic blocking.
See #2269
> Add basic URLFilter for HttpURLConnection

- okhttp-tests/src/test/java/okhttp3/DelegatingSSLSocketFactory.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Platform.java
Right now there's problems with our ability to confirm certificate pins with
root certificates because we don't actually know which certificate authority
was used.
This unblocks that work.
This code is particularly fragile and gross. There's no API to get the
TrustManager from an SSLSocketFactory. We can potentially change the way
that we compute the initial SSLSocketFactory, but this approach is most
general.
This is motivated by https://github.com/square/okhttp/issues/1699
> Teach OkHttp to lookup the X509TrustManagerFactory.

- okhttp-tests/src/test/java/okhttp3/internal/framed/Http2Test.java
- okhttp/src/main/java/okhttp3/internal/framed/Http2.java
> Fix throwing with HTTP2 unknown settings frame id

- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
First draft for #1693. In my testing, both Chrome and Firefox repeat the request. Wasn't sure on best approach for the cache tests.
> Handle 408 responses by retrying the request

- mockwebserver/src/main/java/okhttp3/internal/HeldCertificate.java
- mockwebserver/src/main/java/okhttp3/internal/SslContextBuilder.java
- okhttp-tests/src/test/java/okhttp3/CertificateAuthorityCouncilTest.java
- okhttp-tests/src/test/java/okhttp3/CertificatePinnerTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/main/java/okhttp3/internal/tls/CertificateAuthorityCouncil.java
The goal of this is to get the root CA certificate into the certificate
chain, so that it can be considered by the certificate pinner. The work
to integrate CertificateAuthorityCouncil with CertificatePinner will
come in a follow-up PR.
See: https://github.com/square/okhttp/issues/1699
> New CertificateAuthorityCouncil class to normalize certificate chains.

- okhttp/src/main/java/okhttp3/CertificatePinner.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
The wiring is definitely a bit more awkward than I would like. The
CertificateAuthorityCountil is a non-public class, and this change
sneaks an instance into the CertificatePinner that couples it to
the OkHttp client's SSLSocketFactory.
A nicer solution is to expose CertificateAuthorityCouncil as a public
API type, and add it to Address.java. Unfortunately that's currently
pretty awkward, especially because I'm not ready to commit to the
name CertificateAuthorityCouncil or its API.
Closes: https://github.com/square/okhttp/issues/1699
> Start using CertificateAuthorityCouncil in CertificatePinner.

- okhttp-ws-tests/src/test/java/okhttp3/internal/ws/WebSocketWriterTest.java
- okhttp-ws/src/main/java/okhttp3/internal/ws/RealWebSocket.java
- okhttp-ws/src/main/java/okhttp3/internal/ws/WebSocketWriter.java
This allows both really small bodies and very large buffered bodies to be written as a single frame.
Closes #2270.
> Defer known-length payload writes when within a segment of completion.

- okhttp-tests/src/test/java/okhttp3/CertificateChainCleanerTest.java
- okhttp/src/main/java/okhttp3/CertificatePinner.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Platform.java
- okhttp/src/main/java/okhttp3/internal/tls/AndroidTrustRootIndex.java
- okhttp/src/main/java/okhttp3/internal/tls/CertificateChainCleaner.java
- okhttp/src/main/java/okhttp3/internal/tls/RealTrustRootIndex.java
- okhttp/src/main/java/okhttp3/internal/tls/TrustRootIndex.java
We can just cheat and use reflection to use Conscrypt's trust root index
directly. This results in a substantial savings in app startup - 500
milliseconds or more.
Closes: https://github.com/square/okhttp/issues/2321
> Don't build a trust root index on Android.

- okhttp/src/main/java/okhttp3/internal/Platform.java
Closes https://github.com/square/okhttp/issues/2323
> Support the GMS security provider when searching for the trust manager.

- okhttp-tests/src/test/java/okhttp3/CertificateChainCleanerTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
- okhttp/src/main/java/okhttp3/internal/tls/AndroidTrustRootIndex.java
- okhttp/src/main/java/okhttp3/internal/tls/CertificateChainCleaner.java
We had a bug on Android where the trust root index would return trusted
intermediate certificates when we called findTrustAnchorByIssuerAndSignature().
This would lead to a partial chain, which would fail the pin check
unnecessarily.
Also permit that method to return null, as it does when the certificate
is not trusted.
> Always build full chains with CertificateChainCleaner.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/http/Http2xStream.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/io/RealConnection.java
Previously we omitted the square braces and explicit port on CONNECT requests
and the square braces in the Host header.
Closes https://github.com/square/okhttp/issues/2344
> Make IPv6 request lines consistent with Firefox and Chrome.

- okhttp-tests/src/test/java/okhttp3/CertificateChainCleanerTest.java
- okhttp/src/main/java/okhttp3/internal/tls/CertificateChainCleaner.java
Some root certificates may not be.
Also test the limits of the certificate chain length, and put defense
in for weird unexpected cycles in the trusted certificates.
> Don't require the CA root to be self-signed.

- okhttp-tests/src/test/java/okhttp3/internal/DiskLruCacheTest.java
- okhttp-tests/src/test/java/okhttp3/internal/FaultyFileSystem.java
- okhttp/src/main/java/okhttp3/internal/DiskLruCache.java
A first go at trying to gracefully recover from a failure to trim the cache to size. It took me awhile to reason through the various failure states, hopefully I didn't miss anything major. Assuming we can hash this one out, I can try to work through the rebuildJournal() case as a follow up.
> Gracefully recover from a failure to trim cache to size.

- okhttp-testing-support/src/main/java/okhttp3/internal/io/InMemoryFileSystem.java
- okhttp-tests/src/test/java/okhttp3/internal/DiskLruCacheTest.java
- okhttp-tests/src/test/java/okhttp3/internal/FaultyFileSystem.java
- okhttp/src/main/java/okhttp3/internal/io/FileSystem.java
I noticed that File#exists() doesn't throw IOException but FileSystem does. I wasn't sure if this was by design.
> Removed IOException from FileSystem exists method as this should never occur.

- okhttp-tests/src/test/java/okhttp3/internal/DiskLruCacheTest.java
OEMs have found some configurations of Android devices that cannot
meet the timeout. This change doubles the timeout from 30 to 60
seconds.
The Android bug reference is 27273056.
> Increase test timeout for slow devices

- okhttp-tests/src/test/java/okhttp3/internal/DiskLruCacheTest.java
- okhttp-tests/src/test/java/okhttp3/internal/FaultyFileSystem.java
- okhttp/src/main/java/okhttp3/internal/DiskLruCache.java
I think I have something functional, but it's dependent on the answer to this question: if the rebuild fails, should we attempt to re-open the journal writer?
For now I said 'no' and treated the rebuild action as an atomic operation. That means writes are not allowed so we don't leak files. Reads are allowed and same with removals. If an entry is removed while in this state, and the cache is then closed, on a subsequent open the metadata will be inaccurate. To cope with this, an entry will be removed if we discover it's cache files are missing.
> Gracefully recover from a failure to rebuild the DiskLruCache journal.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
We were using the regular authenticator, not the proxy authenticator.
Closes: https://github.com/square/okhttp/issues/2414
> Fix a regression in authenticating HTTP proxies.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
Looks like we don't support this, and supporting this is a bit awkward.
https://github.com/square/okhttp/issues/2426
> Failing test for 'Connection: close' with HTTPS proxy auth challenges.

- okhttp/src/main/java/okhttp3/Request.java
It was replaced by `.url().uri()`
> Remove unused javaNetUri field from Request

- okhttp/src/main/java/okhttp3/Response.java
See https://github.com/square/okhttp/issues/2217#issuecomment-203189400
> Add javadoc for Response.body()

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/io/RealConnection.java
A fix for #2426. This was mainly a rejiggering of the existing connection code.
> Accommodate tunneling proxies that close the connection after an auth challenge.

- okcurl/src/main/java/okhttp3/curl/Main.java
Before:
```
$ okcurl/target/okcurl-3.3.0-SNAPSHOT-jar-with-dependencies.jar -k https://www.howsmyssl.com/a/check
Exception in thread "main" java.lang.NullPointerException
at okhttp3.internal.tls.TrustRootIndex$BasicTrustRootIndex.<init>(TrustRootIndex.java:90)
at okhttp3.internal.tls.TrustRootIndex.get(TrustRootIndex.java:48)
at okhttp3.internal.tls.TrustRootIndex.get(TrustRootIndex.java:43)
at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:56)
at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:554)
at okhttp3.curl.Main.createClient(Main.java:180)
at okhttp3.curl.Main.run(Main.java:141)
at okhttp3.curl.Main.main(Main.java:66)
```
> fix NPE with okcurl insecure mode

- mockwebserver/src/main/java/okhttp3/internal/framed/FramedServer.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/Spdy3ConnectionTest.java
- okhttp/src/main/java/okhttp3/internal/framed/FramedConnection.java
- okhttp/src/main/java/okhttp3/internal/io/RealConnection.java
This is slightly more work than ideal because our tests don't bother with the
connection preface. That makes the tests both simpler, and further from reality.
The workaround is a package-private method to keep the tests working as they
are currently.
Closes https://github.com/square/okhttp/issues/2469
> Don't start the reader thread until after the connection preface.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpURLConnectionImpl.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/http/StreamAllocation.java
Don't recover if we encounter a read timeout after sending the request, but
do recover if we encounter a timeout building a connection.
See https://github.com/square/okhttp/issues/2394
> Further constrain when we recover from failed routes.

- okhttp/src/main/java/okhttp3/CertificatePinner.java
The provided example wouldn't compile because OkHttpClient doesn't have
a `setCertificatePinner()` method.
> Fix CertificatePinner javadoc to use a Builder

- okhttp/src/main/java/okhttp3/RealCall.java
We don't want to accidentally leak sensitive information that may be
embedded in the url.
For #2481.
> Redact the full url in AsyncCall thread name.

- okcurl/src/main/java/okhttp3/curl/Main.java
This is nasty.  I'm open to suggestions but frame logging doesn't work without this.
https://docs.oracle.com/javase/8/docs/api/java/util/logging/LogManager.html#getLogger-java.lang.String-
> retain logger instance to actually log things

- okhttp/src/main/java/okhttp3/internal/Platform.java
I looked into adding via SSLParameters, but I think okhttp already uses the correct path to make this work.  Can you confirm?
Do you know of a test server to check against?
Java 7
```
$ $(/usr/libexec/java_home -v 1.7)/bin/java -Djavax.net.debug=ssl:handshake -jar okcurl/target/okcurl-3.3.0-SNAPSHOT-jar-with-dependencies.jar -k https://testssl-valid-r2i2.disig.sk/index.en.html | grep -e server_name -e Hello
*** ClientHello, TLSv1
Extension server_name, server_name: [host_name: testssl-valid-r2i2.disig.sk]
*** ServerHello, TLSv1
Extension server_name, server_name:
*** ServerHelloDone
```
Java 8
```
$ $(/usr/libexec/java_home -v 1.8)/bin/java -Djavax.net.debug=ssl:handshake -jar okcurl/target/okcurl-3.3.0-SNAPSHOT-jar-with-dependencies.jar -k …
```
> document support for SNI in OpenJDK

- okhttp/src/main/java/okhttp3/internal/Platform.java
Use SSLParameters.setApplicationProtocols(String[]) and SSLSocket.getApplicationProtocol()
> Java 9 support for ALPN without alpn-boot

- pom.xml
When including MockWebServer as 'compile' into my Android build instead of 'testCompile' there are dependency conflicts when using a different version of JUnit in testCompile and compile:
`Error:Conflict with dependency 'junit:junit'. Resolved versions for app (4.11) and test app (4.12) differ. See http://g.co/androidstudio/app-test-app-conflict for details.`
Was there a reason for keeping JUnit 4.11 that I'm not aware of?
> updates junit version to v4.12

- okhttp-tests/src/test/java/okhttp3/internal/Jdk9PlatformTest.java
- okhttp-tests/src/test/java/okhttp3/internal/JdkWithJettyBootPlatformTest.java
- okhttp-tests/src/test/java/okhttp3/internal/PlatformTest.java
- okhttp/src/main/java/okhttp3/internal/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/Jdk9Platform.java
- okhttp/src/main/java/okhttp3/internal/JdkWithJettyBootPlatform.java
- okhttp/src/main/java/okhttp3/internal/Platform.java
- pom.xml
Want to be able to add some tests for JDK 9, but only run when we have a profile active.
Also fix a bug with JDK 9 profile activation.
> split out platform and test them based on active profile

- mockwebserver/src/main/java/okhttp3/internal/framed/FramedServer.java
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/HttpURLConnectionImpl.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/DiskLruCache.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/JdkWithJettyBootPlatform.java
- okhttp/src/main/java/okhttp3/internal/Platform.java
- okhttp/src/main/java/okhttp3/internal/framed/FramedConnection.java
Avoid using System.out.
Use the best logging implementation on the host platform. On Java this is
java.util.logging. On Android it's Android.util.Log.
Closes https://github.com/square/okhttp/issues/2505
> Make logging more consistent throughout OkHttp.

- mockwebserver/src/main/java/okhttp3/mockwebserver/Dispatcher.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/QueueDispatcher.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
Closes https://github.com/square/okhttp/issues/2521
> Unblock waiting dispatchers on MockWebServer shutdown.

- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/JavaApiConverterTest.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/RecordedResponse.java
- okhttp-tests/src/test/java/okhttp3/internal/http/HeadersTest.java
- okhttp-urlconnection/src/test/java/okhttp3/internal/huc/URLEncodingTest.java
- okhttp/src/main/java/okhttp3/Cache.java
- okhttp/src/main/java/okhttp3/Headers.java
- okhttp/src/main/java/okhttp3/Response.java
- okhttp/src/main/java/okhttp3/internal/http/CacheStrategy.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
I'm currently keeping these as longs. That's easy an unambiguous, but it also
feels rather primitive.
This was more work than I expected, but it doesn't seem particularly risky.
It's also potentially more efficient, since there's fewer places where we're
converting from string to long and vice versa.
Closes: https://github.com/square/okhttp/issues/2035
> Promote sent and received timestamps to fields on Response.

- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
Closes: https://github.com/square/okhttp/issues/2409
> Don't crash when a stream hasn't been closed.

- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
The previous approach Just Works if users have fancy or interesting interceptors
that genuinely need to swap the response body in an interceptor and keep the
original body.
One problem with that solution is that although it gives expert users a powerful
way to separate response bodies, it also allows normal users to accidentally leak
response bodies in their interceptors.
This is an alternate solution that forbids the expert use case and requires that
closing the response body stream also closes the underlying socket stream. It
throws an exception if that implicit contract is not honored.
I'm fine with either solution but think we should consider both.
> Another approach to handling strange interceptor bodies.

- okhttp-tests/src/test/java/okhttp3/internal/framed/Http2ConnectionTest.java
- okhttp/src/main/java/okhttp3/internal/framed/FramedConnection.java
Otherwise we can deadlock, with OkHttp waiting for the server to send a larger
window and the server not knowing that there's a stream that even wants it.
> Flush streams if the window size is zero.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/SocketPolicy.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverSpdyTest.java
- okhttp/src/main/java/okhttp3/internal/framed/FramedStream.java
- okhttp/src/main/java/okhttp3/internal/framed/StreamResetException.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/http/StreamAllocation.java
This implements the following policy:
- If a REFUSED_STREAM error is received, OkHttp will retry the same stream
on the same socket 1x.
- If any other error is received, or an additional REFUSED_STREAM error is
received, OkHttp will retry on a different route if one exists.
We may want to follow up by going through HTTP/2 error codes and deciding
a per-code retry policy, but this should be good enough for now.
Closes: https://github.com/square/okhttp/issues/2543
> Recover from REFUSED_STREAM errors in HTTP/2.

- okhttp-ws-tests/src/test/java/okhttp3/ws/WebSocketCallTest.java
- okhttp-ws-tests/src/test/java/okhttp3/ws/WebSocketRecorder.java
- okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
This change also fixes an edge case where a server returns a response
that allows a follow up request. Previously, this would cause an
exception because the body was being ignored.
> Retain response body when web socket returns non-101 response code.

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
Unfortunately our plaintext detector treats \r and \n as non-plaintext
characters, and they're completely fine.
Closes: https://github.com/square/okhttp/issues/2579
> Fix HttpLoggingInterceptor to be cool with newlines.

- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverSpdyTest.java
- okhttp/src/main/java/okhttp3/internal/http/Http2xStream.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
This doesn't completely support ISO-8859-1 headers; instead they will most likely
be mangled when they are decoded as UTF-8. If we decide we absolutely must support
ISO-8859-1 here we can do that in another change. (I'm not currently enthusiastic
about this idea.)
But this does prevent OkHttp from crashing when it encounters non-ASCII characters
in headers for HTTP/2, SPDY, and cached responses.
Closes: https://github.com/square/okhttp/issues/1998
> Don't crash reading non-ASCII characters from the server or the cache.

- pom.xml
Currently the ALPN version used for Java 8 builds is hard coded for a version only compatible with jdk8 updates 71-74. This PR adds separate maven activated profiles for each jdk8 release up to 92, setting “alpn.jdk8.version” based on the jdk minor version. I pulled the jdk-alpn version pairs from this table:
http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions.
It would be nice to be able to use okhttp with any build of Java 8, and it’s simple to add new profiles for jdk8 releases to the pom file while still supporting older releases.
> Add alpn version support for all Java 8 versions

- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
MockWebServer.readRequest() was accumulating the request body (1 GByte)
into an unbounded buffer held in memory. This caused the test to fail
with an OutOfMemoryError on low-memory devices. Due to the OOME, not
even a stacktrace was available.
This CL introduces setBodyLimit() to limit the amount of data held in
memory. Note that this is similar to the call to setBodyLimit(0) that
already exists in URLConnectionTest.veryLargeFixedLengthRequest().
> Reduce memory requirements for MockWebServerTest.disconnectHalfway().

- okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/http/RouteException.java
- okhttp/src/main/java/okhttp3/internal/http/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/io/RealConnection.java
Previously we had an awkward, arbitrary separation because RealCall contained
the stuff that wasn't in HttpURLConnection, and HttpEngine contained everything
that was shared.
It was also awkward because HttpEngine could be interrupted in various parts
of the HttpURLConnection flow: after connecting, while transmitting the request
body, etc. With this change we no longer need to handle API calls while we're
in these intermediate states, which means we can reduce the scope of certain
things from fields to local variables.
There's still a way to go here but this is more easy wins.
> Begin to fold together parts of RealCall and HttpEngine.

- okhttp-tests/src/test/java/okhttp3/SocksProxy.java
This fixes SocksProxyTest failing on some systems. The problem was that
MockWebServer is listening on InetAddress.getByName("localhost") but
SocksProxy was trying to connect to InetAddress.getLoopbackAddress().
This is not guaranteed to work, for example on recent AOSP, "localhost"
resolves to 127.0.0.1 (IPv4) but getLoopbackAddress() is ::1 (IPv6).
This CL makes the simplest change to make the two consistent so that
SocksProxyTest passes. In the long run, OkHttp may want to consider
using getLoopbackAddress().getHostName() everywhere instead of hard
coding the hostname "localhost" at all.
> Let SocksProxy use the same definition of localhost as MockWebServer.

- okhttp-tests/src/test/java/okhttp3/internal/framed/HpackTest.java
- okhttp/src/main/java/okhttp3/internal/framed/Hpack.java
This will automatically add all the headers into the dynamic table of HPACK if it is not in the static table.
I didn't write new unit test for checking the new added logic, e.g., the eviction of the dynamic table. This is just for a quick review. If the algorithm I used looks good, I'll add them.
> Add a simple version dynamic table of HPACK to the writer client.

- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-urlconnection/src/main/java/okhttp3/OkUrlFactory.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpsURLConnection.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OutputStreamRequestBody.java
- okhttp-urlconnection/src/test/java/okhttp3/OkUrlFactoryTest.java
- okhttp/src/main/java/okhttp3/Cache.java
- okhttp/src/main/java/okhttp3/internal/http/OkHeaders.java
This is an internal class so nobody should see the name. But having a
completely different name will make it much easier to diagnose future
stacktraces because the internal implementation has changed so much
recently.
Also share fewer internal details with the rest of OkHttp. In particular
remove the OkHttp-Selected-Protocol and OkHttp-Response-Source headers
from the core.
> Rename HttpURLConnectionImpl to OkHttpURLConnection.

- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/http/Http1xStream.java
- okhttp/src/main/java/okhttp3/internal/http/Http2xStream.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.java
Instead of having a chain of application interceptors and a separate chain
of network interceptors, this makes a single heterogeneous chain. It makes
the OkHttp core and network caller into interceptors.
> Collapse interceptors into a single chain.

- okhttp-tests/src/test/java/okhttp3/internal/framed/Http2ConnectionTest.java
- okhttp/src/main/java/okhttp3/internal/framed/Http2.java
It's my understanding this setting is meant to signal the amount of memory the _encoder_ can use, not the _decoder_. I think we'll want to respect this value with the new HPACK writer. I was going to see if I can incorporate that change but wanted to make sure I was reading the spec right.
> Do not allow remote peer to arbitrarily size the HPACK decoder dynamic table.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.java
These are currently being encoded in UTF-8, and the charset is not
otherwise specified, so the result is not necessarily going to
succeed at caching.
But this avoids crashing when the server returns an unexpected ETag.
Closes: https://github.com/square/okhttp/issues/2628
> Permit non-ASCII ETag headers.

- okhttp-tests/src/test/java/okhttp3/internal/framed/HpackTest.java
- okhttp/src/main/java/okhttp3/internal/framed/Hpack.java
Previously, we exposed this method and called it when receiving the
header table size setting from a remote peer. We concluded this was not
the intent of the spec and removed that code.
> Removed ability to change the HPACK decoder header table size setting.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
Previously we were misinterpretting which hosts this method applied to.
Suppose an Android app was configured to require TLS for bank.com and
not for any other address. The NetworkSecurityPolicy.isCleartextTrafficPermitted()
method would return false because cleartext traffic wasn't universally
permitted. And OkHttp would incorrectly forbid cleartext communication
to other hosts like puppies.com.
Closes: https://github.com/square/okhttp/issues/2640
> Always pass a host to NetworkSecurityPolicy.isCleartextTrafficPermitted

- mockwebserver/src/main/java/okhttp3/internal/tls/SslClient.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
ConnectionReuseTest
builder.sslSocketFactory(sslSocketFactory2) always fails on JDK9, so using a non-deprecated form
URLConnectionTest
enable SSL in the JDK9 specific tests to avoid ClassCastException
Http2ConnectionTest
settings value is unpredictable due to async nature of test
CertificatePinnerChainValidationTest
fails before serve can be started due to JDK9 moving to PKCS12
> Java9 tests

- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
Any limits enforced here would be awkward because there's an application
thread blocked on the work anyway.
Closes: https://github.com/square/okhttp/issues/2667
> Don't share the OkHttpClient's Dispatcher in HttpURLConnection.

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
Minor fix for a typo in the Javadoc for the `HttpLoggingInterceptor.Level` enum
> Fix logging-interceptor Javadoc typo

- okhttp-tests/src/test/java/okhttp3/internal/framed/HpackTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/Http2Test.java
- okhttp/src/main/java/okhttp3/internal/framed/FrameWriter.java
- okhttp/src/main/java/okhttp3/internal/framed/FramedConnection.java
- okhttp/src/main/java/okhttp3/internal/framed/Hpack.java
- okhttp/src/main/java/okhttp3/internal/framed/Http2.java
- okhttp/src/main/java/okhttp3/internal/framed/Spdy3.java
This is a first pass, and based on:
- https://tools.ietf.org/html/rfc7541#section-4.2
- https://lists.w3.org/Archives/Public/ietf-http-wg/2015OctDec/0088.html
- https://chromium.googlesource.com/chromium/src/+/master/net/spdy/hpack/hpack_encoder.cc
As it turns out, I had some trouble testing this in practice. nginx for example doesn't expose an option to change the default value.
> Add support for dynamic table size changes to HPACK Encoder.

- okhttp-hpacktests/pom.xml
- okhttp/src/main/java/okhttp3/ConnectionSpec.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/framed/Hpack.java
Running the HPACK regression suite shows that in some cases we may
use the wrong dynamic index after the dynamic table has been resized.
This fixes the problem and simplifies the implementation to avoid
maps with Integer values, which were difficult to reason about and
easy to get out-of-sync with the main table.
> Fix a major bug in our HPACK encoder.

- okhttp-tests/src/test/java/okhttp3/MediaTypeTest.java
- okhttp/src/main/java/okhttp3/MediaType.java
It's what Chrome does. Firefox and Safari ignore it. I'd love to ignore
it, but in our API that really just means the caller needs to handle an
InvalidCharsetNameException and nobody is expecting that.
Closes: https://github.com/square/okhttp/issues/2677
> Be lenient if a character set is 'single-quoted'.

- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
This might be an unexpected upside of the migration to the Call API.
Closes: https://github.com/square/okhttp/issues/2178
> Fix a test to not require a fallback IP address.

- okhttp-tests/src/test/java/okhttp3/internal/http2/HpackTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HuffmanTest.java
- okhttp/src/main/java/okhttp3/internal/http2/Hpack.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Writer.java
- okhttp/src/main/java/okhttp3/internal/http2/Huffman.java
This change was inspired by my investigation of the Chrome HPACK Encoder: https://chromium.googlesource.com/chromium/src/net/+/master/spdy/hpack/hpack_encoder.cc#145
In my testing locally, both Chrome and Firefox use Huffman when it saves bytes.
> Huffman encode string literals to save bytes in HPACK encoder.

- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
As suggested here: https://github.com/square/okhttp/pull/2597/files
> Guard allocation changes by the connection pool lock.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/http/HttpMethod.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
the fact that all redirects strip the request body is somewhat unusual.
In WEBDAV the body contains restrictions such as the depth of how much
data you want to receive. Stripping this off will produce an unlimited
request with unlimited depth (where the initial request had depth 1).
* havent checked other WEBDAV methods though whether they require similar
treatment.
> PROPFIND redirects should maintain request body

- okhttp-tests/src/test/java/okhttp3/internal/cache2/RelayTest.java
- okhttp/src/main/java/okhttp3/internal/cache2/Relay.java
At the moment there are some things still incomplete:
- Timeouts. Not yet tested, and no great implementation plan.
- Thread interrupts. This has been quite problematic for
the original DiskLruCache. We should test and support this
in Relay.
- File system problems. If the host file system is full or not
accepting writes, we should fallback gracefully. This may
be difficult.
- Metadata updates. At the moment the metadata is permanent
and immutable.
That said, many nice features are already implemented:
- Metadata and stream data in one file.
- No locks held during file I/O or network I/O.
- Read from the buffer, the file, or the socket in that order.
- Reference counting on open sources. It is assumed that the
creator of each Relay will take a source, and that guarantees
that the count …
> Relay. This is a single entry in the upcoming DiskLruCache2.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp-tests/src/test/java/okhttp3/TestLogHandler.java
- okhttp-tests/src/test/java/okhttp3/TestUtil.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
Also plugged some leaks discovered after running the tests with this
change in place.
https://github.com/square/okhttp/issues/2127
> Provide capability to capture the Call stack trace on leaked connections.

- samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java
Shutdown the executor upon close or failure. This avoids the program
hanging after finished the execution.
Set the client read timeout to 0 (the default timeout is 10s). A read
timeout doesn't make sense for a WebSocket.
> Improve WebSocketEcho example

- mockwebserver/src/main/java/okhttp3/internal/tls/SslClient.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
JDK example of server wanting or needing client auth.  Also covers failure cases which show awkward response e.g. generic ConnectException
> Clientauth example

- okhttp-tests/src/test/java/okhttp3/ResponseBodyTest.java
- okhttp/src/main/java/okhttp3/ResponseBody.java
- okhttp/src/main/java/okhttp3/internal/Util.java
> Make string() and charStream() BOM-aware.

- okhttp-tests/src/test/java/okhttp3/internal/http2/HpackTest.java
- okhttp/src/main/java/okhttp3/internal/http2/Header.java
- okhttp/src/main/java/okhttp3/internal/http2/Hpack.java
Previously, if a header name was in the static table we'd avoid adding it
to the dynamic table. Since most common headers are in the static table,
we were missing the chance to save on bytes sent.
> Be more liberal adding headers to the HPACK encoder dynamic table.

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp-tests/src/test/java/okhttp3/RequestTest.java
- okhttp/src/main/java/okhttp3/Headers.java
RFC 7230 section 3.2 allows HTAB ('\t', '\u0009') inside header
values as long as there is not more than one in a row:
https://tools.ietf.org/html/rfc7230#section-3.2
Before this CL, OkHttp previously disallowed HTAB in header values.
This CL changes behavior to allow any number of consecutive HTABs
inside a header value; this is more permissive than the RFC, but
is consistent with how OkHttp currently treats space characters
(' ', '\u0020').
> Allow HTAB in header values.

- okhttp/src/main/java/okhttp3/Cookie.java
It was claiming that returns true if the cookie expires and the end of the session and really is the opposite behavior.
> Corrected javadoc of the Cookie persistent() method

- okhttp/src/main/java/okhttp3/ConnectionSpec.java
Utils.immutableList makes a defensive copy of the passed in List, which for tlsVersions and cipherSuites is unneeded.
> Avoid unnecessary copying in ConnectionSpec

- okhttp/src/main/java/okhttp3/ConnectionSpec.java
- okhttp/src/main/java/okhttp3/TlsVersion.java
This adjusts TLS protocol selection logic to leave TLSv1.3 enabled if
it's enabled in the underlying TLS stack. Prior to this change,
TLSv1.3 was disabled unless the user of okhttp explicitly enabled it
via a custom ConnectionSpec.
Fixes #2867
> Do not disable TLSv1.3 by default

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/main/java/okhttp3/AutobahnTester.java
- okhttp-tests/src/test/java/okhttp3/TestLogHandler.java
- okhttp-tests/src/test/java/okhttp3/WebSocketCallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/EmptyWebSocketListener.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/RealWebSocketCall.java
- okhttp/src/main/java/okhttp3/WebSocketListener.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.java
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.java
- samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java
* onFailure callback's exception type widened to Throwable. This allows runtime exceptions from other callbacks to be passed along.
* Ensure the connection is closed properly for all failures.
* Fix and document the threading inside RealWebSocket. This ensures the listener is always called on the same thread and replies always happen from the correct thread.
Closes #2455. Closes #1701.
> Web socket API and implementation improvements.

- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketProtocol.java
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.java
These are used for an close frame that does not specify a status code and for when a network error occurs while trying to read data, respectively.
Closes #2696.
> Use web socket close codes 1005 and 1006 correctly.

- okhttp/src/main/java/okhttp3/OkHttpClient.java
Title says it all! I copied over the docs from `setInternalCache()` as I figured it was an accurate description for this call.
> Add javadoc for cache call in the builder

- okhttp-tests/src/test/java/okhttp3/WebSocketCallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
> Forbid writes from reader thread.

- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp-tests/src/test/java/okhttp3/SocksProxyTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/WebSocketCallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/DisconnectTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/ThreadInterruptTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
The client it returns is less susceptible to environment-specific flakiness.
I suspect that some of our tests that pass locally and fail in continuous
integration may be due to such environment-specific behaviors.
> Use TestUtil.defaultClient in more tests.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
OkHttp never returns null bodies for any request. But empty response
bodies are fine.
Closes: https://github.com/square/okhttp/issues/2879
> Add tests to confirm HEAD response bodies are empty.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/SocketPolicy.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
Rather than immediately and violently closing the HTTP/2 stream,
we initiate the shutdown sequence for a graceful disconnect.
This fixes StreamAllocation to avoid creating new streams on
shutdown connections. That behavior is not well tested, however.
That will come by integrating dave-r12's PR:
See https://github.com/square/okhttp/pull/2889
> Make HTTP/2's DISCONNECT_AT_END more graceful.

- okhttp/src/main/java/okhttp3/Cache.java
- okhttp/src/main/java/okhttp3/Request.java
- okhttp/src/main/java/okhttp3/Response.java
Affected:
- okhttp3.Request
- okhttp3.Response
- okhttp3.Cache
> Avoid generating synthetic accessor methods

- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
I fixed most of these 2 years ago when it was problematic, but I missed
one.
> Prefer Executor.execute() over Executor.submit().

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/connection/RouteSelectorTest.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.java
Falling back to no proxy causes problems, particularly when the proxy is
adding some value.
Closes: https://github.com/square/okhttp/issues/2525
> Don't fallback to no proxy after all configured proxies have failed.

- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
Previously we would prefer the cached response if it had a newer
Last-Modified date.
Closes: https://github.com/square/okhttp/issues/2886
> Always prefer the server's returned response body.

- okhttp-tests/src/test/java/okhttp3/NewWebSocketTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/NewWebSocketRecorder.java
- okhttp/src/main/java/okhttp3/NewWebSocket.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/ws/RealNewWebSocket.java
Currently this uses a placholder name, NewWebSocket. I'd like to get this
reviewed, expand it to cover MockWebServer's needs, and then I'll delete
the current blocking API.
Still undecided is which APIs to add - if any - to expose the state of the
web socket.
https://github.com/square/okhttp/issues/2902
> New non-blocking API for websockets.

- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http2/ConnectionShutdownException.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
This was work started while addressing #2756, and is very much an edge case. I got sidetracked with the issue around violently and abruptly closing a socket and wanted to close the loop here.
> Gracefully recover from an HTTP/2 connection shutdown at start of request.

- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
Closes: https://github.com/square/okhttp/issues/2892
> Avoid sending empty HTTP/2 data frames when there is no request body.

- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
Closes: https://github.com/square/okhttp/issues/2940
> Confirm that we correctly handle close frames without a code.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp-tests/src/test/java/okhttp3/WebSocketHttpTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
This changes RealWebSocket from using a shared ThreadPoolExecutor to
using a private ScheduledExecutorService. This make some of the code
simpler but it means that applications will hold 1 writer thread for
each websocket, even if it is mostly not writing.
Testing automatic pings is awkward. This refactors much of
RealWebSocketTest to make it more natural to reinitialize the
configuration.
> Automatically ping the peer on a user-specified interval.

- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2Test.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/MockHttp2Peer.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Reader.java
Closes: https://github.com/square/okhttp/issues/2474
> Fail the HTTP/2 connection if first frame isn't SETTINGS.

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
Delightfully we pass 100% of them. On the corner case of 'http:g' we're
classified as a 'backwards-compatible' implementation, not a strict one.
> Add examples from RFC 3986 as tests for HttpUrl.

- okhttp-tests/src/test/java/okhttp3/internal/SocketRecorder.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
I recently made a change in https://github.com/square/okhttp/pull/2995 and did not include a test case. The primary reason was a lack of visibility in MWS. The goal of this PR is to provide that visibility.
> Introduce SocketRecorder: a means to inspect all bytes written/read to a socket.

- pom.xml
Fails when maven run with Java 9
```
[INFO] --- animal-sniffer-maven-plugin:1.11:check (default) @ okhttp ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[ERROR] /Users/yuri/workspace/okhttp/okhttp/src/main/java/okhttp3/internal/cache2/FileOperator.java:57: Undefined reference: java.nio.ByteBuffer java.nio.ByteBuffer.limit(int)
[ERROR] /Users/yuri/workspace/okhttp/okhttp/src/main/java/okhttp3/internal/cache2/FileOperator.java:67: Undefined reference: java.nio.ByteBuffer java.nio.ByteBuffer.clear()
[ERROR] /Users/yuri/workspace/okhttp/okhttp/src/main/java/okhttp3/internal/cache2/FileOperator.java:67: Undefined reference: java.nio.ByteBuffer java.nio.ByteBuffer.clear()
[ERROR] /Users/yuri/workspace/okhttp/okhttp/src/main/java/okhttp3/internal/cache2/FileOp …
```
> animal sniffer update for Java 9

- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
For discussion - not sure what the right fix is.  It looks like an issue introduced by Java 9
```
$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+149)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+149, mixed mode)
```
> temporarily ignore failures with java 9

- okhttp-tests/src/test/java/okhttp3/CertificateChainCleanerTest.java
Use a TrustManager created using SslClient to avoid a dependency on < JDK9
> Fix CertificateChainCleanerTest for Java 9

- mockwebserver/src/main/java/okhttp3/internal/http2/Http2Server.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/SocketPolicy.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http/HttpCodec.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
This will stall reading the response body until the server returns
an intermediate '100 Continue' response.
Closes: https://github.com/square/okhttp/issues/675
> Support 'Expect: 100-continue' as a request header.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/RecordedResponse.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This was fixed recently but we didn't update the corresponding test case. This
updates the test and adds a few more to confirm that HTTP/2 failure recovery
works as it should.
Closes: https://github.com/square/okhttp/issues/578
> Confirm that HTTP/2 failure recovery is decent.

- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
I'm working towards making OkHttp limit itself to a single HTTP/2 connection
to a single host. In this work I found we're not sufficiently safe on
allocationLimit - connections are added to the pool when this is 0, and
the value is updated without any synchronization.
This change also reduces the visibility of some connection fields in
RealConnection and organizes the fields into two sets: those that are
immutable after connect and those that are guarded by connectionPool.
https://github.com/square/okhttp/issues/373
> Fix RealConnection to guard allocationLimit by connectionPool.

- samples/crawler/src/main/java/okhttp3/sample/Crawler.java
Name threads by their URLs. Don't follow all fragments of the same URL.
> Make the crawler a little better.

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
If we make concurrent requests to an HTTP/2 server, close all but
the first connection. Creating multiple connections and then later
releasing them is somewhat pessimistic; it's also much safer for
awkward cases like connect attempts being canceled.
Closes: https://github.com/square/okhttp/issues/373
> Release duplicated multiplexed connections.

- website/index.html
This changes the first example on the website from using try/finally to using try with resources.
This fixes 2 issues with my previous PR for the first website example.
- The actual linked GetExample.java uses try with resources (not try finally so my change didn't match the linked GetExample.java)
- My try/finally example had issues.  It didn't initialise the Response properly and close if non-null etc
Apologies for getting this wrong in the first PR. I think this fixes those 2 issues in my previous PR and I think it is nice if the first example code seen is as simple and clean (and correct) as possible (I think try with resources is a bit cleaner/nicer than try/finally).
> Website only: Update first example to use try with resources

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
This makes it possible to do domain fronting.
Closes https://github.com/square/okhttp/issues/3103
> Permit network interceptors to rewrite the host header.

- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
Versions prior to Android 4.4 (aka Java 6) did not have Socket implementing Closeable.
Closes #3124.
> Use Socket instead of Closeable for compatibility.

- okhttp-tests/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.java
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java
Closes: https://github.com/square/okhttp/issues/3115
> Recover from a severe cache initialization failure.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
Junit 5 support for MockWebServer via extending a known base class.
http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-rulesupport
> junit 5 compatibility for MockWebServer

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
We were creating threads and not shutting them down as eagerly as we could have.
> Fix a thread leak in MockWebServer's web socket tests.

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/MediaTypeTest.java
- okhttp/src/main/java/okhttp3/MediaType.java
As-is it throws unchecked exceptions on unexpected charsets. This is a problem
because it can cause a misbehaving webserver to crash the client.
I don't expect this to break existing clients; returning 'null' has always
been a possibility; it's just returned in more cases.
> Change MediaType's failure mode to not crash on charset problems.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/RecordedResponse.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
Insecure TLS version fallback is a compatibility workaround to connect
to servers that do not implement TLS protocol version negotiation
correctly; it is vulnerable to man-in-the-middle-attacks (POODLE).
Support for TLS version fallback was removed in Firefox 37 (Mar 2015)
and Chrome 50 (Apr 2016). As of late 2015, fewer than 0.01% of web
servers relied on protocol fallback.
After this commit, OkHttp still supports TLS version fallback, but it
is now opt-in rather than opt-out.
Existing tests for fallback functionality were modified to opt-in
to the fallback; new tests in CallTest and URLConnectionTest
assert that no fallback happens by default (when not opted-in).
> Do not fall back to COMPATIBLE_TLS (TLSv1) by default.

- okhttp-tests/src/test/java/okhttp3/internal/tls/DistinguishedNameParserTest.java
Port the test from http://r.android.com/183814 . This consists of two commits:
(1.) minimal changes to make the test compile and runnable, (2.) update
expectations to current behavior to make the test pass.
DistinguishedNameParser is an internal API, so this test is mostly to ensure
that any future behavior changes are deliberate.
> Port basic DistinguishedNameParserTest from AOSP

- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2Test.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Reader.java
This is my first PR to this repository!
When I had run some tests with tool that will check about http2 spec violation,
I found that when okhttp client didn't handle well when received DATA frame on streamId=0
sending DATA(streamId=0) frame to okhttp client with a custom mock server
okhttp client should treat it as connection error with type PROTOCOL_ERROR
okhttp send RST_STREAM on streamId=0
[rfc7540#section-6.1](https://tools.ietf.org/html/rfc7540#section-6.1)
> DATA frames MUST be associated with a stream.  If a DATA frame is
received whose stream identifier field is 0x0, the recipient MUST
respond with a connection error (Section 5.4.1) of type
PROTOCOL_ERROR.
> HTTP/2 reject DATA frame on streamId is zero

- mockwebserver/src/main/java/okhttp3/mockwebserver/RecordedRequest.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
It might be helpful for example when dealing with lots of query parameters in tests because all the URL parsing facilities from `HttpUrl` can be reused.  I'm not sure that the suggested change is the best possible solution and I'm open for suggestions.
> MockWebServer: Expose request URL as HttpUrl

- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp/src/main/java/okhttp3/Address.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.java
- okhttp/src/main/java/okhttp3/internal/tls/OkHostnameVerifier.java
As described here:
https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/
https://hpbn.co/optimizing-application-delivery/#eliminate-domain-sharding
https://tools.ietf.org/html/rfc7540#section-9.1.1
When the following is true
- HTTP/2 so we don't overload non multiplexed connections.
- HTTPS since we need subjectAltNames (n.b. RFC 7540 defines as safe to use over plaintext, based purely on DNS).
- Desired url host is part of the subjectAltNames for an existing connection.
- One of the DNS results for desired host match the established connection.
- HostnameVerifier is *not* overridden.
- ConnectionPinner accepts the existing certificate chain.
From https://tools.ietf.org/html/rfc7540#section-9.1.1
> A server that does not wish clients to reuse connections can indicate
> that …
> Connection coalescing

- okhttp-tests/src/test/java/okhttp3/CookieTest.java
- okhttp/src/main/java/okhttp3/Cookie.java
- okhttp/src/main/java/okhttp3/internal/publicsuffix/PublicSuffixDatabase.java
https://github.com/square/okhttp/pull/3141
I ran some preliminary tests by creating a simple cookie jar, and executing the Crawler (which is fun.) I didn't see any major issues while doing this.
> Restrict cookies with a domain that is a public suffix.

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
Per RFC 5952, section 4.2.2, a single 16-bit field must not be shortened.
Improper canonicalization can break TLS hostname verification because
the canonicalized name will not match the server certificate.
This change adds the examples from the RFC to the tests.
> Fix canonicalization of IPv6 addresses in HttpUrl

- okhttp/src/main/java/okhttp3/OkHttpClient.java
Some broken Android devices have problems with 'new SecureRandom()' and it's easier
to not use SecureRandom than to work-around this.
Closes: https://github.com/square/okhttp/issues/3135
> Don't use a cryptographic RNG for web sockets.

- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp/src/main/java/okhttp3/CookieJar.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http2/Settings.java
Closes: https://github.com/square/okhttp/issues/3203
> Invalidate the cache even if the response has no body.

- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
The server will receive an EOFException when the client errors out.
But because that didn't usually happen immediately our test got away
with confirming there were no further events.
Also fix WebSocketHttpTest.readTimeoutAppliesToHttpRequest().
Closes: https://github.com/square/okhttp/issues/3228
Closes: https://github.com/square/okhttp/issues/3090
> Fix WebSocketHttpTest.throwingOnMessageClosesImmediatelyAndFails().

- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
> Hide EventListener from the public API for OkHttp 3.7.

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
Looks like the tests were passing for an unintended reason!
```
$ mvn clean verify
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OkHttp (Parent) .................................... SUCCESS [  1.637 s]
[INFO] OkHttp ............................................. SUCCESS [  6.418 s]
[INFO] OkHttp test support classes ........................ SUCCESS [  0.790 s]
[INFO] MockWebServer ...................................... SUCCESS [  8.441 s]
[INFO] OkHttp URLConnection ............................... SUCCESS [ 10.314 s]
[INFO] OkHttp Tests ....................................... SUCCESS [01:43 min]
[INFO] OkHttp Android Platform Support .................... …
```
> Fix for HttpUrl's IPv6 tests 

- okhttp/src/main/java/okhttp3/OkHttpClient.java
contains() is already iterating the list so we might as well just be doing the remove() operation on that pass.
> Only make a single pass when removing protocols.

- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/JavaApiConverterTest.java
- okhttp/src/main/java/okhttp3/Cache.java
- okhttp/src/main/java/okhttp3/Handshake.java
This value is almost always non-null. The only exception is when it was
persisted by a version of OkHttp prior to 3.0.
Rather than accepting null, and forcing clients to handle that value,
I'm changing the API to reject null. I'm forcing a default of SSL_3_0
for responses that we don't have a version for. I don't anticipate this
causing problems in practice.
> Forbid null for a handshake's TLS version.

- okhttp/src/main/java/okhttp3/Challenge.java
These were never null in practice.
> Forbid null schemes and realms in Challenge.

- okhttp-tests/src/test/java/okhttp3/ResponseTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/okhttp3/Response.java
This was only ever null in test code. Everything that parses responses from
the network gets a non-null value. The message may be empty.
> Forbid null for a response's message.

- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
Fix the crash reported in https://github.com/square/okhttp/issues/3245
> Fix for NPE Crash due to a bug on Android 7.0 

- okhttp-android-support/pom.xml
- okhttp-testing-support/pom.xml
- okhttp-tests/pom.xml
- okhttp-urlconnection/pom.xml
Because multiple modules share a package we need to share the dependency on
everything in package-info.java.
> Fix Javadoc builds with the jsr305 dependency.

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
I've created a project to reproduce the issue and published it along with a bundled snapshot that contains the fix: https://github.com/Egorand/okhttp-android-tests
> #3325: Add proper fallback to parameterless isCleartextTrafficPermitted() method on API 23

- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2Test.java
- okhttp/src/main/java/okhttp3/internal/http2/Settings.java
Currently HTTP/2 setting ids in the [designated experimental range](http://httpwg.org/specs/rfc7540.html#iana-settings), `#f000` to `#ffff`, cause an index-out-of-bounds exception when consumed by `Http2Reader#readSettings`, as `readShort()` interprets the bytes as negative integers. This expands the out-of-bounds check in `Settings#set` to check for a negative index. Without the code change, the added test fails, demonstrating the bug.
I'm not fully familiar with OkHttp internals to know if this is the best approach for the fix, but it seemed better to add a PR with a repro case than just opening an issue. This popped up in gRPC Java (https://github.com/grpc/grpc-java/issues/3032), and extends the earlier fix from  https://github.com/square/okhttp/pull/2299.
> Avoid index out of bounds with Http/2 settings id in the experimental range

- okhttp-tests/src/test/java/okhttp3/internal/publicsuffix/PublicSuffixDatabaseTest.java
- okhttp/src/main/java/okhttp3/internal/publicsuffix/PublicSuffixDatabase.java
Fixes: https://github.com/square/okhttp/issues/3404
> Treat reading the public suffix list as uninterruptible.

- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/internal/connection/RouteSelectorTest.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
I'm interested in this one. 
I found this challenging because of the cycle between EventListener and Call. Notably, it seems like RealCall wants a reference to EventListener but the EventListener factory wants the instance of the Call. The approach in this PR is also broken 'cause someone could `execute` the call from the EventListener.
In addition, I attempted to use the EventListener for a successful DNS lookup. It became clear that this will require passing around the reference to EventListener. Also because every method takes in a Call, I think it means passing around the Call as well.
I probably am missing something here, or maybe this can help refine the EventListener class.
> Make EventListener public and begin implementing Dns events.

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
- okhttp/src/main/java/okhttp3/internal/tls/BasicTrustRootIndex.java
- okhttp/src/main/java/okhttp3/internal/tls/CertificateChainCleaner.java
- okhttp/src/main/java/okhttp3/internal/tls/TrustRootIndex.java
Split out Android TrustRootIndex into AndroidPlatform only code, avoid executing on other platforms
> Avoid android specific code for TrustRootIndex

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/SocksProxy.java
- okhttp-tests/src/test/java/okhttp3/SocksProxyTest.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
I've altered the signatures of the connect start and end methods. Notably:
- Changed from `InetAddress` and `port` to `InetSocketAddress`. Was just easier to pull this off the route, but don't have strong feelings on this one.
- Add `Proxy` to connectStart. I thought this might be useful for people using proxies.
- Changed to use `Protocol` on connectEnd. This is already a public type and felt easier to work with.
> Add support for connect start/end events.

- okhttp/src/main/java/okhttp3/Credentials.java
This saves cloning the byte array because the byte array can't be modified by the caller.
> Prefer ByteString.encodeString.

- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp-tests/src/test/java/okhttp3/internal/connection/RouteSelectorTest.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
Previously we'd only look at one route at a time. If DNS returned
results in random order it would lower our chances of finding a
coalesced connection. Now we consider all routes at once which hopefully
improves our chances.
> Consider all routes when looking for candidate coalesced connections.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
Fill out documentation clearing up the semantics of the EventListener API
Things to call out
- I've defined fetchStart/End to be from enqueue/execute to caller closing the Response body.
- There is no easy hook in request/response(Header|Body)(Start|End) except implicit ordering.  All useful classes e.g. StreamAllocation are internal.
- There is no event to signify when OkHttp really starts processing, or has handed off the response to the caller.
> Fill out documentation for EventListener

- pom.xml
Per [this comment](https://github.com/jetty-project/jetty-alpn/commit/d58174d8924eda832f22606d68abaf879f4553fa#commitcomment-23304619) & reply from @sbordet, pom.xml was modified for jdk8u141, and tests succeeded.
An update today to 8u144 and subsequent test with u144's profile also successfully tested.
My completed CLA form was submitted about five minutes ago.
> JDK 8u141 & 8u144 Compatibility

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
Checks to see if DSP is present. If it is, ALPN can be used on Android 4.x devices which facilitates HTTP/2 use. 
Addresses #3485
> Check for DSP to enable ALPN.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
Call all methods in EventListener.
Adds proxy to connectEnd to allow matching to start event unambiguously.
Test EventListener fails fast for unmatched end event.
Make RecordingEventListener a top level class.
n.b. Ordering of ResponseBodyEvent needs to be addressed in another PR.  Currently it can be delayed by client not consuming output, even if all bytes have been read off the wire.
> Complete EventListener

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
Also limit the number of retry attempts. This functionality is
consistent with how Chrome handles 408's presently.
Closes: https://github.com/square/okhttp/issues/3483
> Honor retryOnConnectionFailure on a client request timeout.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
This removes the decorator and uses the existing superclass instead.
> Use endOfInput() to trigger the end of the response body.

- okhttp-tests/src/test/java/okhttp3/FormBodyTest.java
- okhttp/src/main/java/okhttp3/FormBody.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
This is useful when accessing a web server you don't control which receives form data encoded in a charset other than UTF-8 (e.g. ISO-8859-1).
To use this you pass an encoding to FormBody.Builder constructor. The constructor is used so it's clear you shouldn't switch encodings in the middle of building a form body.
The result is undefined is a character cannot be encoded in the specified charset (as the result of Java's String.getBytes(charset) is also undefined in that case.
> Allow using a charset other than UTF-8 for creating urlencoded form bodies.

- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/okhttp3/WebSocket.java
close(0, null) still supported internally on WebSocketWriter.close, but no longer supported on public API.
> Remove WebSocket API support for optional close code

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
I think applications might be simple by tracking successful events
separately from failure events.
> Move all failures into connectFailed and callFailed.

- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
We probably want to support this, but at the moment it isn't yet
tested. Turn it off until we get something we really like.
> Don't fire events for Web Sockets.

- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp/src/main/java/okhttp3/Interceptor.java
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.java
Interceptors could use this to detect if the call has been canceled, or
cancel the call, or do other things.
> New API, Chain.call() returns the in-flight call.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This was a bug carried over from SPDY.
Closes: https://github.com/square/okhttp/issues/3484
> Omit the message from MockWebServer's HTTP/2 :status header

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/RecordingProxySelector.java
Previously we'd skip the request body unless the socket policy was
EXPECT_CONTINUE.
Closes: https://github.com/square/okhttp/issues/3498
> Fix MockWebServer handling of 'Expect: 100 Continue'

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Closing the sink while another thread is writing the sink is a
potential source for races.
Closes: https://github.com/square/okhttp/issues/3138
> Fix MockWebServer websockets to be thread safe.

- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
Currently our implementation acquires the connection early so that we have
something to close if the call is canceled. Event listeners are simpler if
they only get a connectionAcquired event once the connection has been
actually established.
> Don't report connectionAcquired until actually connected.

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
We were assuming on a client failure the server wouldn't have any
further events. But it will get a failure if we give it a moment.
This was causing some test flakiness.
> Fix a race in WebSocketHttpTest.

- okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.java
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.java
We were synchronizing to permit multiple writer threads. But that was a carry-over
from the previous design where we supported multiple writer threads. With the
current implementation only one thread writes at a time. This synchronization
was not necessary.
> The WebSocketWriter is single-threaded.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http/RealResponseBody.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
Rather than getting the content length from a header on demand, this gets it
at the time that the RealResponseBody is created. This means that HEAD requests
can have a non-zero Content-Length header while their bodies have no content.
Closes: https://github.com/square/okhttp/issues/3365
> Improve handling of HEAD requests with a Content-Length specified.

- okhttp/src/main/java/okhttp3/Connection.java
Small typo in JavaDoc. Fixing causes a bit of line overflow.
> Add 'of' to Connection JavaDoc.

- samples/guide/src/main/java/okhttp3/recipes/PrintEvents.java
Failing on unrelated PRs
`[ERROR] /home/travis/build/square/okhttp/samples/guide/src/main/java/okhttp3/recipes/PrintEvents.java:90:5: Redundant 'public' modifier. [RedundantModifier]`
> Fix travis build

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/RecordedResponse.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
Two main goals
- Don't allow a malicious server to flood a client
- Turn these hangs into clear failures, e.g. "no header line received within X characters: content starting 'XXXXXXXXX'"
> 256kB header limit

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
> Add workaround for https://issuetracker.google.com/issues/63649622

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
Before updating the call to `delimiterOffset`, the test failed with: 
```
org.junit.ComparisonFailure: 
Expected :
Actual   :#fragment
<Click to see difference>
```
I did a quick check of other calls to `delimiterOffset`, and those looked fine.
> Ensure encodedQuery doesn't include the URL's fragment

- okhttp/src/main/java/okhttp3/Dns.java
Not ideal, but some Android phones fails at least some Dns requests.  The OkHttp Dns fails in a non-recoverable way, so instead catch this and treat it as a zero length result.
> workaround broken system dns behaviour

- okhttp-tests/src/test/java/okhttp3/internal/UtilTest.java
- okhttp/src/main/java/okhttp3/internal/Util.java
This can't happen but obviously does.  Be super tolerant as we want to always get the root cause on these dodgy phone JVMs.
https://github.com/square/okhttp/issues/3595#issuecomment-345655811
> Assertion error super careful

- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
One of our clients uses the android version of okhttp and runs into the following issue:
Our api used to respond the content without gzip. The response is cached on the clients with corresponding etags. Now our api returns the content with "Content-Encoding: gzip", even in case of 304 Not Modified.
okhttp fails with:
```
java.io.EOFException
at okio.RealBufferedSource.require(RealBufferedSource.java:60)
at okio.GzipSource.consumeHeader(GzipSource.java:114)
at okio.GzipSource.read(GzipSource.java:73)
at okio.RealBufferedSource.request(RealBufferedSource.java:67)
at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:408)
at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:392)
at okhttp3.internal.Util.bomAwareCharset(Util.java:449)
at …
```
> 304 Not Modified overrides Content-Encoding and breaks cache

- README.md
- mockwebserver/README.md
- okhttp-logging-interceptor/README.md
Signed-off-by: shaishavgandhi05 <shaishgandhi@gmail.com>
> Update to new Gradle dependency configurations

- okhttp/src/main/java/okhttp3/internal/http2/Http2Reader.java
settings is an unsigned int, no observable external change but useful if debugging with experimental settings.
https://http2.github.io/http2-spec/#rfc.section.11.3.p.1
> Settings id is unsigned short

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
Two effective changes 
- Support for 503, with 0 Retry-After meaning retry automatically
- Check with 408, and don't do automatic retry if there is a delay
> Retry-After support 

- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/HostnameVerifierTest.java
- okhttp/src/main/java/okhttp3/internal/tls/OkHostnameVerifier.java
The use of Common Name was deprecated in RFC 2818 (May 2000), section 3.1:
>  Although the use of the Common Name is existing practice, it is
>  deprecated and Certification Authorities are encouraged to use the
>  dNSName instead.
In 2017, Chrome 58, Firefox 48, and Opera 45 web browsers removed this
fallback, with Chrome leaving it configurable for enterprise deployments
(see https://www.chromestatus.com/feature/4981025180483584).
Android is removing it in http://r.android.com/581382 .
> OkHostnameVerifier: Don't fall back to CN verification.

- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
- okhttp/src/main/java/okhttp3/EventListener.java
These look like accidents, but it's very possible I missed some context on why these were nullable.
> Mark some EventListener parameters as non-null.

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
Makes HttpLoggingInterceptor decompress and log the body of a response which is gzip encoded when used as a networkInterceptor (where previously it just logged that an encoded body was seen).
This is useful in the case where you want to log both any redirects which occur during the call and the response bodies. 
Fixes issue #3780
(My first time touching any of the okio stuff directly - very happy to hear if I've missed a better way to do something)
> Log gzipped bodies when HttpLoggingInterceptor is used as a NetworkInterceptor

- mockwebserver/src/main/java/okhttp3/internal/tls/SslClient.java
- okcurl/src/main/java/okhttp3/curl/Main.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
The SSL Provider may not always be the default one e.g. for Android (GMS) or Conscrypt, so move this logic in to the internal Provider API.
> Build Provider through the Platform

- okhttp/src/main/java/okhttp3/Protocol.java
Before
```
[ERROR] /Users/yschimke/workspace/okhttp/okhttp/src/main/java/okhttp3/Credentials.java:29: warning: no @param for username
[ERROR]   public static String basic(String username, String password) {
[ERROR]                        ^
[ERROR] /Users/yschimke/workspace/okhttp/okhttp/src/main/java/okhttp3/Protocol.java:99: error: incorrect use of inline tag
[ERROR]    * @link https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml
[ERROR]      ^
[ERROR]
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/Users/yschimke/workspace/okhttp/okhttp/target/apidocs' dir.
```
After
```
[WARNING] …
```
> fix javadoc link

- .buildscript/deploy_snapshot.sh
- .travis.yml
Build javadoc and sources in normal build for travis instead of waiting for post build script
> Build javadoc and source jars in normal build

- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
It was possible for a call to cancel() to not cancel because the canceling
thread wouldn't observe the streams.
I've added a local StreamAllocation variable to avoid extra volatile reads.
Closes: https://github.com/square/okhttp/issues/3834
> Make RetryAndFollowUpInterceptor.streamAllocation volatile.

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- pom.xml
Results in https://github.com/square/okhttp/pull/3857 showed that logging can be affected by prior state.
> More lenient test involving logging

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp-tests/src/test/java/okhttp3/UrlComponentEncodingTester.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
Though it's good for OkHttp to retain the user's provided encoding, we
should be encoding more characters than we are when the user provides
us with unencoded data.
Closes: https://github.com/square/okhttp/issues/3235
> Encode more characters when using addQueryParameter().

- okhttp/src/main/java/okhttp3/ConnectionSpec.java
This removes the following cipher suites as supported-by-default:
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
This tracks a similar change in Chromium 56:
https://developers.google.com/web/updates/2016/12/chrome-56-deprecations#remove_cbc-mode_ecdsa_ciphers_in_tls
OkHttp's updated cipher suites, plus comparisons to Android, Java,
Chromium, Firefox, and Square's server-site configuration is here:
https://tinyurl.com/okhttp-cipher-suites
Closes: https://github.com/square/okhttp/issues/3035
> Remove CBC-mode ECDSA cipher suites

- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
This breaks our concurrency rules. Fortunately it's only academic; only
MockWebServer ever writes settings, and it only does so in very specialized
tests.
> Don't hold a lock on the connection when writing settings.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
There are several options for when to expect the pong response. I've
chosen to overload the ping interval. This seems reasonable because the
ping interval is the maximum amount of time that should elapse before
a connection failure is detected.
Closes: https://github.com/square/okhttp/issues/3227
> Fail web sockets if the pong is not received

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
`ofMapRejectsNullCharInName` was checking for null in the value, and `ofMapRejectsNullCharInValue` was checking for null in the name.
> Fix swapped name and value tests.

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
This changes the executor services in HTTP/2 connection to split up
listener executors (of which there may be many threads) from writer
executors (of which there is one per connection).
This adds a scheduled executor job to send pings on an interval. We
don't yet fail the connection if pongs are not received.
For follow-up there's some work to remove exising APIs to send pings
through the HTTP/2 APIs. These are unused and make it awkard to
confirm that only the automatic pings are being replied to.
See https://github.com/square/okhttp/issues/3261
> First step towards HTTP/2 automatic pings.

- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpsURLConnection.java
OkHttpsURLConnection extends javax.net.ssl.HttpsURLConnection.
The super class documentation says that setSSLSocketFactory(null)
throws IllegalArgumentException, but this implementation didn't
do that.
This CL fixed OkHttpsURLConnection.setSSLSocketFactory(null) to
throw, as specified.
Test: not done locally, relying on Travis.
> OkHttpsURLConnection.setSSLSocketFactory(null): throw.

- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
This change avoids static configuration which may cause issues
for applications using both OkHttp and HttpsUrlConnections.
> fix #3895: Set Conscrypt.setUseEngineSocket per SocketFactory

- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
This might have been a difference between SPDY and HTTP/2. Reviewing the
HTTP/2 spec, only a WINDOWS_UPDATE frame can change the flow-control
window for a connection.
> Do not alter connection flow-control window on SETTINGS frame.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
Closes: https://github.com/square/okhttp/issues/3854
> Fixed flaky CallTest.cancelImmediatelyAfterEnqueue.

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
We rely on the application layer to read the response body buffer
before sending WINDOW_UPDATE's. Previously we'd immediately throw a
StreamResetException. This prevented the application layer from reading
the buffer which in turn means we would not send WINDOW_UPDATE's. This
has potential to deplete the flow-control window.
https://github.com/square/okhttp/issues/3915
> Defer StreamResetException until response body buffer is fully read.

- pom.xml
No jetty release... yet.
Nothing obviously coming from http://www.oracle.com/technetwork/java/javase/8all-relnotes-2226344.html
Should fix travis build for now
> alpn boot versions 171+172

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp-tests/src/test/java/okhttp3/ProtocolTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/Protocol.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
The string h2c is used with cleartext upgrades. We're not doing those here,
so that identifier isn't appropriate.
> Rename H2C to H2_PRIOR_KNOWLEDGE.

- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
https://github.com/square/okhttp/issues/3915
> Ensure discarded HTTP/2 data frames free flow-control space.

- okhttp/src/main/java/okhttp3/Handshake.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
Based on https://github.com/square/okhttp/issues/3973, looks like this can still happen
> Move conscrypt NONE checks internal to Handshake

- okhttp/pom.xml
- pom.xml
includes a shutdown NPE fix, and been a while since updates.
> update conscrypt to 1.1.3

- okhttp-sse/src/main/java/okhttp3/internal/sse/RealEventSource.java
- okhttp-sse/src/main/java/okhttp3/sse/EventSources.java
My existing SSE use case is simplified if I don't need to specify a SSE request beforehand.  So on checking the response a text/event-stream content-type is enough to process the result as a stream.  Expose a basic API for this.
> API for handling an unexpected SSE response

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
Public (unpaid version) of Java 1.7u80 supports TLSv1.2 only via a different provider. 
Newer paid version u95 support a system property (jdk.tls.client.protocols), and u131 defaults to supporting TLSv1.2
https://www.java.com/en/configure_crypto.html#enableTLSv1_2
> Android 4 and Java 1.7 prefer TLSv1.2 provider

- okhttp-tests/src/test/java/okhttp3/ResponseBodyTest.java
- okhttp/src/main/java/okhttp3/ResponseBody.java
We shouldn't punish people with a roundtrip through byte[] for using a superior type!
> Add ResponseBody factory overload for ByteString

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/CustomDispatcherTest.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/TestLogHandler.java
- okhttp-tests/src/test/java/okhttp3/TestUtil.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/ThreadInterruptTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/MockHttp2Peer.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
- okhttp/src/main/java/okhttp3/internal/publicsuffix/PublicSuffixDatabase.java
- samples/slack/src/main/java/okhttp3/slack/OAuthSessionFactory.java
The drawbacks seem small; the callsite needs to handle interruption anyway
because the thread is prone to interruption.
And the upside is that a single interrupt should now be sufficient to break
out an in-flight OkHttp call.
Note that although we're fixing this, thread interruption is not well tested
in OkHttp. Most users should prefer Call.cancel(), which is well tested and
doesn't rely on the caller to know which threads OkHttp is using to make
the actual HTTP request.
Closes: https://github.com/square/okhttp/issues/3945
> Retain interrupted state when throwing InterruptedIOException

- okhttp-android-support/src/test/java/okhttp3/internal/huc/JavaApiConverterTest.java
- okhttp-apache/src/main/java/okhttp3/apache/HttpEntityBody.java
- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/MediaTypeTest.java
- okhttp-tests/src/test/java/okhttp3/MultipartBodyTest.java
- okhttp-tests/src/test/java/okhttp3/RequestTest.java
- okhttp-tests/src/test/java/okhttp3/ResponseBodyTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/FormBody.java
- okhttp/src/main/java/okhttp3/MediaType.java
- okhttp/src/main/java/okhttp3/MultipartBody.java
- samples/guide/src/main/java/okhttp3/guide/PostExample.java
- samples/guide/src/main/java/okhttp3/recipes/PostFile.java
- samples/guide/src/main/java/okhttp3/recipes/PostMultipart.java
- samples/guide/src/main/java/okhttp3/recipes/PostStreaming.java
- samples/guide/src/main/java/okhttp3/recipes/PostStreamingWithPipe.java
- samples/guide/src/main/java/okhttp3/recipes/PostString.java
- samples/guide/src/main/java/okhttp3/recipes/RequestBodyCompression.java
Doing this before a `HttpUrl.getOrThrow` because it's similar. I didn't update any call sites, but can do so if this method is something we want.
Refs #3850
> Add parse overload which fails on invalid inputs

- okhttp-tests/src/test/java/okhttp3/internal/connection/RouteExceptionTest.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteException.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
Throw the first exception, with all following exceptions directly connected to the first instead of as a linked list.
> Reverse suppression of connect exceptions

- okhttp-tests/src/test/java/okhttp3/ConscryptTest.java
- okhttp/src/main/java/okhttp3/ConnectionSpec.java
We specify TLSv1.3, but without any compatible cipher suites.  So makes sense to remove for 3.11 to avoid weirdness as JVMs supporting TLSv1.3 start showing up.  n.b. JDK 11 detects this and strips anyway.
> Remove TLSv1.3 as default

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp/src/main/java/okhttp3/Headers.java
For quickly adding common headers
https://github.com/square/okhttp/issues/3923
> Add headerBuilder.addAll(headers) method

- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DohProviders.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/TestDohMain.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp-tests/src/test/java/okhttp3/CookieTest.java
- okhttp-tests/src/test/java/okhttp3/CookiesTest.java
- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/RequestTest.java
- okhttp-tests/src/test/java/okhttp3/UrlComponentEncodingTester.java
- okhttp-tests/src/test/java/okhttp3/WebPlatformUrlTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
- okhttp-urlconnection/src/test/java/okhttp3/OkUrlFactoryTest.java
- okhttp/src/main/java/okhttp3/CertificatePinner.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/Request.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- samples/crawler/src/main/java/okhttp3/sample/Crawler.java
- samples/slack/src/main/java/okhttp3/slack/SlackApi.java
This is an unchecked-throwing version of parse(String).
Closes #3850. Closes #4032.
> Add get(String) alternative which fails on invalid inputs

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.java
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
- okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java
This changes the default from the insecure 1024-bit RSA to a secure 256-bit ECDSA
key. It adds a new option to use RSA keys for interoperating with older clients.
> Fixup HeldCertificate so that it's worthy of production use.

- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.java
Also fix our calling code to have the smallest path lengths possible.
http://www.ietf.org/rfc/rfc3280.txt
> Validate the certificate's basic constraints.

- okhttp-tls/src/main/java/okhttp3/tls/TlsNode.java
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
- okhttp-tls/src/test/java/okhttp3/tls/TlsNodeTest.java
Compute the SSLContext on-demand. This has negligible impact on the performance
of the test suite.
Also create a test case for TlsNode.
> Make TlsNode more like a value object.

- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp-tests/src/test/java/okhttp3/CertificateChainCleanerTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
- okhttp-tls/src/main/java/okhttp3/tls/HandshakeCertificates.java
- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.java
- okhttp-tls/src/test/java/okhttp3/tls/HandshakeCertificatesTest.java
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Util.java
Also rename HeldCertificate.Builder.issuedBy() to signedBy(). 'Issued' is the
word used by certificates; 'signed' is the word used by cryptographers. I prefer
'signed'.
> New API, HandshakeCertificates.addPlatformTrustedCertificates()

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
I'm not fully convinced this is worth merging. I just wanted to attempt to reproduce the steps in https://github.com/square/okhttp/issues/3915.
> Confirm concurrent HTTP/2 requests with empty flow-control window.

- .travis.yml
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
- okhttp/src/main/java/okhttp3/internal/connection/ConnectionSpecSelector.java
Putting this up for discussion and reference, I'll raise this as a JDK bug and see fi the change is deliberate
> Possible JDK 11 fixes

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/SocketPolicy.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
New SocketPolicy to shutdown MockWebServer after response. More details in #4227
> Shutdown MockWebServer after response

- mockwebserver/src/main/java/okhttp3/mockwebserver/RecordedRequest.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/RecordedRequestTest.java
surround IPv6 addresses with [] to make a valid URI
https://github.com/square/okhttp/issues/4225
> MockWebserver fix for IPv6 addresses

- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.java
- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsRecordCodec.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsOverHttpsTest.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsRecordCodecTest.java
while technically inside the spec, in practice multiple DNS questions must be asked in different messages.  So make two calls instead of one.
> Make separate IPv4 and IPv6 requests for DNS over HTTPS

- okhttp/src/main/java/okhttp3/Authenticator.java
Related to https://github.com/square/okhttp/issues/4238
Currently (by code structure) route may be null when used internally.  In addition as an API for handling authentication challenges, it makes sense that route may not be always available, even though it can be useful when determining when to apply a authentication method.
> Nullable route annotation

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
https://github.com/square/okhttp/commit/30e72340e0c5a74feb347a79621b93d640ded576 fixed the issue of callEnd not being fired.
> Enable passing emptyResponseBody test

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
This implements the enhancement discussed in https://github.com/square/okhttp/issues/3826.
> Support header redaction in HttpLoggingInterceptor

- okhttp/src/main/java/okhttp3/RequestBody.java
Just a minor change.
The param name is `file` - not content.
This may leads to confusing when observed in logs.
Another solution - to match with the other methods - would be to change the param name to `content` 🤷‍♂️ 
Please give me a hint when we should do it like this 👍
> Fix exception message

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp/src/main/java/okhttp3/Headers.java
As suggested in https://github.com/square/okhttp/issues/4283#issuecomment-423703475.
> A mechanism for adding non-ASCII headers

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
It doesn't seem to be cover in `CallTest`
> Added test to cover header drops with 100-continue

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
ran into a place where I was missing the scheme in a logging call.
before:
missing host:
```
java.lang.NullPointerException
at okhttp3.HttpUrl$Builder.toString(HttpUrl.java:1273)
at okhttp3.HttpUrlTest.incompleteUrlComposition(HttpUrlTest.java:775)
```
missing scheme:
```
java.lang.NullPointerException
at okhttp3.HttpUrl.defaultPort(HttpUrl.java:510)
at okhttp3.HttpUrl$Builder.effectivePort(HttpUrl.java:1039)
at okhttp3.HttpUrl$Builder.toString(HttpUrl.java:1285)
at okhttp3.HttpUrlTest.incompleteUrlComposition(HttpUrlTest.java:782)
```
> Fail with clear message when missing scheme or host for HttpUrl.Builder.toString.

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
toString is useful for debug even when incomplete
> Allow incomplete url builder tostring

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/main/java/okhttp3/Response.java
- okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.java
Creating patterns dynamically to do comma-escaping is pretty awkward.
This is more code but I have more confidence in it.
> Limit the use of regexes in the RFC 7235 challenge parser.

- okhttp-tests/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp/src/main/java/okhttp3/Call.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
Strictly-speaking this change is backwards-incompatible because it adds
a new method to the Call interface. The method returns the call's timeout.
The trickiest part of this is signaling the end of the call, which
occurs after the last byte is consumed of the last follow up request,
or when the call fails. Fortunately this is made easier by borrowing
the sites used by EventListener, which already plots out where calls
end.
https://github.com/square/okhttp/issues/2840
> Whole operation timeouts

- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp/src/main/java/okhttp3/Dispatcher.java
- okhttp/src/main/java/okhttp3/RealCall.java
This turns out to be pretty difficult because of the way our
dispatcher works.
Calls can be rejected either immediately when the user calls
enqueue(), or later when a queued call is promoted.
It's also awkward because we don't want to hold locks when
calling the user's callFailed() method.
> Recover from executor shutdowns gracefully.

- okhttp-tests/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp-tests/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp/src/main/java/okhttp3/Call.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
This isn't independently configured in an interceptor like the other
timeouts because it's already started by the time the interceptors run.
> Add APIs to configure the client's default call timeout.

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
Closes: https://github.com/square/okhttp/issues/4258
> Fix connection leaks on failed web socket upgrades.

- okhttp/src/main/java/okhttp3/Cache.java
I was looking into the docs and could not see from the constructor what the size was in terms of. Turns out it is bytes. Hopefully this will help others save a step on figuring this out 😉
> Add some docs for Cache class

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/RecordingOkAuthenticator.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/Authenticator.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
All other forms of preemptive auth are nicely covered by interceptors,
but CONNECT doesn't get that luxury.
https://github.com/square/okhttp/issues/2435
> Preemptive auth for proxy CONNECT

- okcurl/pom.xml
- okcurl/src/main/java/okhttp3/curl/Main.java
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/LoggingEventListener.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
A basic logger, as discussed in #4315.
To install a `LoggingEventListener` that uses the platform logger:
```
builder.eventListenerFactory(new LoggingEventListener.Factory());
```
The user can also pass a custom Logger:
```
Logger logger = new Logger() {
@Override
public void log(String message) {
...
}
};
builder.eventListenerFactory(new LoggingEventListener.Factory(logger));
```
Sample output:
```
$ okcurl -v "https://httpbin.org/redirect-to?status_code=307&url=https://api.twitter.com/robots.txt"
[t=0] callStart: Request{method=GET, url=https://httpbin.org/redirect-to?status_code=307&url=https://api.twitter.com/robots.txt, tags={}}
[t=13] dnsStart: httpbin.org
[t=233] dnsEnd: [httpbin.org/54.174.228.92, httpbin.org/52.4.75.11, httpbin.org/54.173.32.212, httpbin.org/54.152.208.69, …
```
> Add a LoggingEventListener and use it in okcurl

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/LoggingEventListener.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
- okhttp/src/main/java/okhttp3/Handshake.java
Adds the handshake details to the LoggingEventListener.
`secureConnectEnd: Handshake{tlsVersion=TLS_1_2 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 peerCertificates=[CN=localhost] localCertificates=[]}`
> Log handshake in LoggingEventListener

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
FileNotFound should be treated like an UnrepeatableRequestBody, all other IOExceptions are variable.  But FileNotFoundException is most likely to represent a bad client request.  Unfortunately this is more of a heuristic, given that a Socket IOException could be FileNotFound and a different route could return something else.
> Avoid retrying when client is missing body File

- .github/CONTRIBUTING.md
We could link, but much simpler to have each be standalone to ensure it gets read.
> Change contributing guide in repo to match wiki

- okhttp-urlconnection/src/main/java/okhttp3/JavaNetAuthenticator.java
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java
- okhttp-urlconnection/src/main/java/okhttp3/OkUrlFactory.java
- okhttp-urlconnection/src/main/java/okhttp3/package-info.java
Overlaps with okhttp core, triggering build issues. Without causing pain by moving the (public API) class we can only forgo this.
> Remove overlapping package-info.java

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
part of #4267
https://tools.ietf.org/html/rfc7540#section-8.1.2.2
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.39
> Don't filter TE headers out if value is trailers

- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.java
We want the system default crypto provider to do it.
Potential fix for https://github.com/square/okhttp/issues/4443
> Don't rely on BouncyCastle algorithms for certificate building.

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
The 'Closing' and 'Closed' events sometimes fire before the test completes. Since they were not consumed by the test, the assertion in tearTown() that all events have been consumed failed.
Fixes https://github.com/square/okhttp/issues/4382.
> Fix flaky webSocketAndApplicationInterceptors test

- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
In some containers or environments, a security policy may prevent reading unknown system properties.
As a result, `Platform#isConscryptPreferred()` is throwing an exception when running OkHttp in our container - because `okhttp.platform` is not on the whitelist of System Properties which are allowed to be read.
This pull request adds handling for such exceptions so that `OkHttpClient` initialization doesn't fail.
> Handle security exception when testing if conscrypt should be used

- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- samples/unixdomainsockets/src/main/java/okhttp3/unixdomainsockets/BlockingUnixSocket.java
- samples/unixdomainsockets/src/main/java/okhttp3/unixdomainsockets/ClientAndServer.java
- samples/unixdomainsockets/src/main/java/okhttp3/unixdomainsockets/UnixDomainServerSocketFactory.java
- samples/unixdomainsockets/src/main/java/okhttp3/unixdomainsockets/UnixDomainSocketFactory.java
It turns out that the NIO dumpsterfire harms us again here. The Channels APIs
synchronize whenever reading or writing to a stream if the channel implements
SelectableChannel. If both the input stream and the output stream are on the
same channel, then it is impossible to read and write concurrently.
Fixes: https://github.com/square/okhttp/issues/4419
> Fix the UNIX sockets sample to use HTTP/2

- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
There are usually 2 requests sent to '/b' during the test:
#1 on the busted connection, attempting reuse
#2 on a new connection
On successful runs, the server recorded #1 and then #2 and added them to the queue in that order.
On failed runs, the server started reading request #1 before #2, but there was a context switch, and it finished reading #2 before #1, recording them in that order. Since #1 was the last to be recorded, the test incorrectly used it to assert that the sequence number was 0. Since #1 was the second to be received on the busted connection, it had a sequence number of 1 so the test failed.
The fix removes the assumption that #2 is the last to be recorded.
Fixes https://github.com/square/okhttp/issues/4140.
> Fix flaky URLConnectionTest.serverShutdownOutput test

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
https://github.com/square/okhttp/issues/1191 has been resolved and the test seems to pass consistently.
> Enable cancelWithStreamNotCompleted test

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
Fixes:
* an issue where call timeout doesn't fire after redirect is followed on a different connection
* https://github.com/square/okhttp/issues/4386
While I think this is the minimal fix, I'm not sure it's the best end state. It may be better to trigger call-end actions in `RetryAndFollowUpInterceptor` instead of passing a flag to `StreamAllocation.release()`. This may be a slightly bigger change and can be done as a follow-up refactoring-only PR.
> Stream release doesn't always mean call end

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
While investigating https://github.com/square/okhttp/issues/4470, I noticed there are sometimes connections left in the pool after calling ConnectionPool.evictAll() in HttpOverHttp2Test.tearDown(). As a result, tests that assume the connection pool is initially empty can appear flaky while the blame is in previous tests, making it hard to debug, and possibly hiding a connection leak bug.
So far I've noticed the new assertion fails (very rarely) when tearing down these tests:
* recoverFromMultipleCancelReusesConnection
* emptyDataFrameSentWithEmptyBody
* gzippedResponseBody
This change may increase flakiness in the short term, but will make it easier to debug, by blaming the right tests.
> Assert connection pool eviction in HttpOverHttp2Test.tearDown()

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
tearDown() takes care of this.
> Remove duplicate connection pool eviction code

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
Closes: https://github.com/square/okhttp/issues/4383
> Add an API to access MockWebServer's dispatcher.

- okhttp-tests/src/test/java/okhttp3/internal/connection/ConnectionSpecSelectorTest.java
- okhttp/src/main/java/okhttp3/ConnectionSpec.java
We no longer connect to TLSv1.0 or TLSv1.1 servers out-of-the-box; instead
it is necessary to enable COMPATIBLE_TLS in the OkHttpClient configuration.
This is in the path to later removing these TLS versions completely; that
is scheduled for March 2020 by some browsers.
https://github.com/square/okhttp/issues/4319
> Move TLSv1 and TLSv1.1 to COMPATIBLE_TLS.

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
After the recent fix, if the call is canceled while writing request headers, the stream is eventually removed from the connection. But this is done on a separate thread, and there was previously no guarantee that it would happen before tearDown() is called and the connection pool is evicted, preventing the connection from being evicted before the next test starts.
Together with https://github.com/square/okhttp/pull/4492, this will hopefully fix https://github.com/square/okhttp/issues/4470.
> Ensure streams are removed from connection within test lifetime

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
Closes: https://github.com/square/okhttp/issues/4427
> Exercise TLS with no server certificates

- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
It can be referenced from multiple threads.
I think there is still a thread safety issue with the Http2Stream class.
> Make Http2Codec.stream volatile

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
I was worried we weren't handling this case correctly. Fortunately we are.
Closes: https://github.com/square/okhttp/issues/4451
> Test malformed IPv6 addresses

- okhttp/src/main/java/okhttp3/OkHttpClient.java
Closes: https://github.com/square/okhttp/issues/4457
> Make sure default timeouts are documented explicitly.

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
Both WebSocketRecorder.onClosing() and WebSocketRecorder.onClose() currently use the string "onClose":
https://github.com/square/okhttp/blob/775d5d9d5c6a210a49fb6ef5ebfcc47dcbb0865a/okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java#L88-L89
https://github.com/square/okhttp/blob/775d5d9d5c6a210a49fb6ef5ebfcc47dcbb0865a/okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java#L100-L101
> Fix WebSocketRecorder logging

- bom/pom.xml
Although it'd probably be a better fix to change the actual artifactId of logging-interceptor to okhttp-logging-interceptor, this is a less disruptive change.
> Fix logging-interceptor artifactId in bom/pom.xml

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Fixes part of https://github.com/square/okhttp/issues/4515.
> Fix connection leaks in WebSocketHttpTest due to not closing WebSockets

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
If WebSocketListener.onOpen() throws, failWebSocket() is responsible for releasing the allocated streams. Specifically it releases this.streams. Previously WebSocketListener.onOpen() was called after the streams were allocated but before they were assigned to this.streams. As a result the streams were not allocated if WebSocketListener.onOpen() threw.
Fixes part of https://github.com/square/okhttp/issues/4515.
> Fix connection leak if WebSocketListener.onOpen() throws

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
Note that as long as there are leaking tests, I can't commit an assertion that verifies the fix. Since all tests share the same OkHttpClient and ConnectionPool, a leaking test will cause such an assertion to fail for all subsequent tests. To test the fix, I added an assertion locally and ran each fixed test individually.
> Fix connection leak on failed WebSocket handshake

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
This fixes a connection leak in WebSocketHttpTest.unplannedCloseHandledWithoutFailure().
Fixes part of https://github.com/square/okhttp/issues/4515.
> Respond to server-initiated closure with client-initiated closure

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
close() is already called on the client WebSocket in closeWebSockets().
> Fix flaky WebSocketHttpTest.webSocketAndNetworkInterceptors

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
Also removed calls to ConnectionPool.evictAll() that are now redundant.
> Test for and fix connection leaks in CallTest

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
The most awkward part of this is the changes to the way MockResponse
handled chunked encoding. It used to consider trailers a part of its
chunked response; now it does not.
> Get trailers working for HTTP/1

- okhttp/src/main/java/okhttp3/internal/duplex/DuplexRequestBody.java
- pom.xml
Use the new Pipe.fold() method to hook up the duplex sink.
> Upgrade to Okio 1.17.1.

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
- okhttp/src/main/java/okhttp3/internal/tls/BasicCertificateChainCleaner.java
- okhttp/src/main/java/okhttp3/internal/tls/BasicTrustRootIndex.java
- okhttp/src/main/java/okhttp3/internal/tls/CertificateChainCleaner.java
- okhttp/src/main/java/okhttp3/internal/tls/TrustRootIndex.java
I took this away because I thought it was only useful for Android versions
we've since dropped. But it turns out it's also necessary when there's a
custom TrustManager in use.
Closes: https://github.com/square/okhttp/issues/4592
> Restore support for custom trust managers on Android

- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/Response.java
- okhttp/src/main/java/okhttp3/internal/DeferredTrailers.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/connection/ConnectInterceptor.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
Currently this just moves all calls into StreamAllocation, RealConnection, and
HttpCodec into a new Transmitter type.
In follow-up I'll try to improve the API boundaries of this new type, possibly
by combining it with StreamAllocation. The ultimate goal is that it should be
very obvious from inspection that we don't leak connections and that we don't
miss any events.
> Initial refactoring towards a Transmitter abstraction

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
This is a mechanical refactoring that changes all code that directly
accesses a StreamAllocation to instead access a Transmitter. The
next step is to combine StreamAllocation and Transmitter into
a single class.
> Prepare to fold StreamAllocation and Transmitter

- okhttp-tests/src/test/java/okhttp3/ConnectionPoolTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
I'm working towards reducing the role StreamAllocation plays.
> Don't call callEnd() twice when application interceptors proceed twice.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
- okhttp/src/main/java/okhttp3/ConnectionPool.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
Our 'Internal' trampoline really gets in the way with this one. Just
move the actual implementation code into its own type so there isn't
as much indirection.
Unfortunately we can't easily make RealConnectionPool extend from
ConnectionPool because otherwise we'd be open to any user-provided
connection pools and our API isn't that complete yet.
> Split ConnectionPool API from implementation

- okhttp-tests/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp/src/main/java/okhttp3/internal/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/HttpCodec.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
This creates a new class ResponseBodySource that manages events and
connections. It's symmetric with our existing RequestBodySink class.
Continuing to work towards these things having their own lifecycles
that are separate from HTTP framing mechanics.
> Manage releasing connection separately from HTTP framing

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/HttpCodec.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
This changes failure recovery to only attempt when the failure
occurs when OkHttp is doing I/O. If a failure is triggered by
something else (such as a bad RequestBody or Interceptor) then
that failure will not be retried.
> Handle stream exceptions in Transmitter

- okhttp-tests/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
- okhttp/src/main/java/okhttp3/internal/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
Today we have to suppress 'connectionAcquired' events because we attach the
constructed connection and then replace it with the pooled one. This changes
the logic to use separate fields for the connecting connection vs. the
pooled one.
> Make connection coalescing less special.

- okhttp/src/main/java/okhttp3/internal/platform/Jdk8WithJettyBootPlatform.java
Fixes #4615 by ensuring that when loading the ALPN class, is can only be loaded through the bootstrap classloader.
I got this idea from what grpc-java was doing: 
https://github.com/grpc/grpc-java/blob/9a38dea91c6194f7a882e2be1c2846567e9cdcda/netty/src/main/java/io/grpc/netty/JettyTlsUtil.java#L64
I will follow-up with a currently failing test and link that onto the issue.
> Fix Jdk8WithJettyBootPlatform loading ALPN class through normal classpath

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
The change to introduce Transmitter and Exchange has caused us to report
the correct events. Yay!
> Restore tests that now report the correct events.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
We were calling responseHeadersStart() multiple times.
> Fix EventListener events for expect-continue.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
Test to reproduce the issue discussed here:
https://github.com/square/okhttp/pull/4523
> Test to confirm OkHttp doesn't loop when a request body throws.

- mockwebserver/src/main/java/okhttp3/mockwebserver/internal/duplex/MockDuplexResponseBody.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp-tests/src/test/java/okhttp3/DuplexTest.java
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.java
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
https://github.com/square/okhttp/issues/4267
> Support follow-ups for duplex requests.

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/LoggingEventListener.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/DuplexTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.java
- samples/guide/src/main/java/okhttp3/recipes/PrintEvents.java
- samples/guide/src/main/java/okhttp3/recipes/PrintEventsNonConcurrent.java
These replace requestBodyEnd() / responseBodyEnd() in some failure scenarios.
They may also be issued in cases where no event was published previously.
> Introduce EventListener.requestFailed, responseFailed events

- okhttp-tests/src/main/java/okhttp3/TestTls13Request.java
- okhttp/src/main/java/okhttp3/CipherSuite.java
- okhttp/src/main/java/okhttp3/ConnectionSpec.java
I think we made either a transcription error or grabbed a suite
from an earlier version of the spec.
> Fix the name of a TLSv1.3 cipher suite, TLS_AES_128_CCM_8_SHA256

- okhttp/src/main/java/okhttp3/ConnectionSpec.java
As far as I know we never would have used these anyway, as they're
not available on Android, Java, or Conscrypt.
They aren't enabled by default in either Firefox or Chrome.
Closes: https://github.com/square/okhttp/issues/3865
> Remove default cipher suites: TLS_AES_128_CCM_SHA256, TLS_AES_128_CCM_8_SHA256

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
Since Platform.afterHandshake() was never called, SSLSockets were not removed from ALPN's Map and could not be freed.
> Fix memory leak in MockWebServer when using ALPN

- okhttp-tests/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.java
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.java
I'm not particularly happy with the way this code looks, but I like
the result. Otherwise exceptions are like these:
* stream was reset: CANCEL
* Socket closed
* Canceled
> Include 'timeout' in exceptions when that's the root cause

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
We may want to support these eventually but for now this is
unhelpful because they won't terminate.
> Don't log duplex request bodies

- okhttp-testing-support/src/main/java/okhttp3/TestUtil.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp-tests/src/test/java/okhttp3/ConscryptTest.java
- okhttp-tests/src/test/java/okhttp3/CookiesTest.java
- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp-tests/src/test/java/okhttp3/DuplexTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/ThreadInterruptTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This will help prevent regressions and point to the leaking test, rather than to a later test that happens to checks for leaks. The change is applied to all tests that have an OkHttpClient member variable.
> Test for connection leaks in more tests

- okhttp-sse/src/test/java/okhttp3/internal/sse/EventSourceHttpTest.java
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestingRule.java
- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp-tests/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp-tests/src/test/java/okhttp3/CookiesTest.java
- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp-tests/src/test/java/okhttp3/DuplexTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/CancelTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/ThreadInterruptTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This implements the suggestion in https://github.com/square/okhttp/pull/4677.
I'm not very happy with the result and I personally prefer it not to be merged, at least not as-is: The problem is that many tests use this pattern to overwrite the `client` field:
```
client = client.newBuilder()
...
.build();
```
Since updating `OkHttpClientTestingRule.client` after every instance of this would be tedious, `OkHttpClientTestingRule` will apply its checks to the original `OkHttpClient`. This is usually OK since the original and new `OkHttpClient` instances share most of the fields, but since some fields do differ, the result is inconsistent.
> Use a TestRule to check for connection leaks

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
I'm not particularly happy with all of the moving parts here. I think
perhaps doing web sockets over duplex is a possible fix here.
Closes: https://github.com/square/okhttp/issues/4658
> Don't leak a connection if a WebSocket handshake fails

- okhttp-sse/src/main/java/okhttp3/internal/sse/RealEventSource.java
- okhttp-sse/src/test/java/okhttp3/internal/sse/EventSourceHttpTest.java
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.java
Once the response headers are received we go back to not having
any timeout enforced.
Closes: https://github.com/square/okhttp/issues/4646
> Enforce full-call timeouts on SSE setup

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Reader.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
Previously we always provided a generic StreamResetException. Now we provide
the exception that triggered the stream to be closed, if any.
> Provide better exceptions when the shared HTTP/2 stream fails

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This may help nail down the sporadic timeouts in this test (https://github.com/square/okhttp/issues/4633).
> Fail recoverFromCancelReusesConnection() on unexpected response

- .travis.yml
This causes us to fail if our own snapshots are missing. I wasn't able to
get the normal Maven options to do this, including  -DexcludeGroupIds=com.squareup.okhttp3
and -DexcludeTransitive=true which I expected to work but don't.
My expectation is that if dependencies aren't available, the build will soon
fail anyway.
> Don't fail the build if dependencies aren't available

- pom.xml
We don't change the code this exercises enough to pay for the build
time and complexity it adds.
> Remove the hpacktests module by default

- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
This will help debug flaky tests where expected events are sometimes missing. For example: https://travis-ci.org/square/okhttp/jobs/506592764.
> Dump list of events if expected event is not found in test

- okhttp-tests/src/test/java/okhttp3/CookiesTest.java
MockWebServer instances were never shut down.
Fixes https://github.com/square/okhttp/issues/4734.
> Fix MockWebServer leak in CookiesTest

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Using deterministic close sequence to prevent occasional EOF exception.
Fixes https://github.com/square/okhttp/issues/4720
> Fix flaky webSocketAndApplicationInterceptors()

- okhttp-tests/src/test/java/okhttp3/CookiesTest.java
The time delta in the cookie max-age is rounded down, so is at most 59 seconds. Possibly a GC or some other hiccup can occasionally make it lower, so allow some room for error.
Fixes https://github.com/square/okhttp/issues/4733.
> Fix flaky testRfc2109Response()

- build.gradle
- mockwebserver/build.gradle
- okhttp-logging-interceptor/build.gradle
- okhttp-logging-interceptor/gradle.properties
- okhttp-tls/build.gradle
- okhttp-urlconnection/build.gradle
- okhttp/build.gradle
This excludes okhttp-sse and okhttp-dnsoverhttps
> Hook up japicmp for all stable artifacts

- okhttp/src/main/java/okhttp3/internal/Util.java
This is an intrinsic in the JVM so it should have better performance.
> Switch to Arrays.copyOf for expanding array

- okhttp/src/main/java/okhttp3/internal/connection/RouteException.kt
Original lastConnectException field of RouteException.java is private.
ref: https://github.com/square/okhttp/blob/parent-3.14.0/okhttp/src/main/java/okhttp3/internal/connection/RouteException.java#L28
> change visibility of lastConnectException property

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
The test fails when there is a context switch to the MockWebServer thread after the client sends the HEADERS frame but before it sends the DATA frame. The MockWebServer then reads the client's HEADER frame and sends a DATA frame with the response body. As a result, the first DATA frame that is logged is not the expected empty DATA frame sent by the client.
Fixes https://github.com/square/okhttp/issues/4757
> Fix flaky HttpOverHttp2Test.emptyDataFrameSentWithEmptyBody

- .circleci/config.yml
Found an acceptable version, even with alpn-boot and openjdk incompatibilities.
> CircleCI alternative JDK 8 build

- mockwebserver/src/main/java/okhttp3/mockwebserver/internal/duplex/MockDuplexResponseBody.java
- okhttp-tests/src/test/java/okhttp3/DuplexTest.java
- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
The test is flaky because the server sometimes acts on the 301 response and resets the stream before the action added by MockDuplexResponseBody.sendResponse() is executed. This action then fails because it tries to write to a reset stream. mockDuplexResponseBody.awaitSuccess() then throws and fails the test.
The change enforces the de-facto sequence on most runs, where the 301 response is handled only after the Duplex response is sent.
Fixes https://github.com/square/okhttp/issues/4743
> Fix flaky DuplexTest.duplexWithRedirect

- okhttp/src/main/java/okhttp3/Address.kt
- okhttp/src/main/java/okhttp3/Challenge.kt
- okhttp/src/main/java/okhttp3/Handshake.kt
I mistakenly updated the license year. Apologies!
Here are the previous files for ease of review:
[Address](https://github.com/square/okhttp/pull/4787/files#diff-78b52ad46ac301e325752067fa23cb55L2)
[Challenge](https://github.com/square/okhttp/pull/4802/files#diff-1dc7b1d5ec3edac544524a21685bc421L2)
[Handshake](https://github.com/square/okhttp/pull/4799/files#diff-a6724faeb78a8bff6be65107ece8adefL2)
> Revert license year

- okhttp/src/test/java/okhttp3/EventListenerTest.java
We should aim to have timeout on any tests we identify as slow, can't land this until we fix the terrible one
> Timeout on slow tests and fix CircleCI slow test

- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
As we start to take advantage of Kotlin language features this test will keep
us from inadvertently breaking existing callers.
> New KotlinSourceCompatibilityTest

- build.gradle
Too little information is logged today when tests fail in CI. This makes logging a little more verbose.
Before:
```
okhttp3.internal.ws.RealWebSocketTest > unexpectedPongsDoNotInterfereWithFailureDetection FAILED
java.lang.AssertionError at RealWebSocketTest.java:349
```
After:
```
okhttp3.internal.ws.RealWebSocketTest > unexpectedPongsDoNotInterfereWithFailureDetection FAILED
java.lang.AssertionError:
Expecting:
<1928.0>
to be close to:
<1500.0>
by less than <250.0> but difference was <428.0>.
(a difference of exactly <250.0> being considered valid)
at okhttp3.internal.ws.RealWebSocketTest.unexpectedPongsDoNotInterfereWithFailureDetection(RealWebSocketTest.java:349)
```
> Log full exception on test failure

- .circleci/config.yml
TL;DR it probably saves a minute per build on average, and we could debug to improve.
Aggressive build caching within gradle and circleci.  Not sure we want this, it makes re-running a flaky test potentially awkward. It should be safe, but ultimately we want any snapshot or tagged release publishing step to do a fresh build I assume.
Normal: 5:40
https://circleci.com/workflow-run/7c6cd465-9609-41bd-b63c-d98334c9a027
Cache First Run: 5:41
https://circleci.com/workflow-run/a69206f5-ef50-415b-ba90-b0f97fefa33b
Second Run: 4:53
https://circleci.com/workflow-run/0a782b8a-5db8-4f4b-b76d-9792d9fef0fd
> Use the build cache in CircleCI

- .circleci/config.yml
- Run build at midnight with checks and all JVM/platforms tests
- On PR run only checks and JDK8 tests
- On master commit, run all JVM/platforms tests
Logic is that checks shouldn't suddenly break, no point running on every master build.  Flush out those once a day.
On PRs avoid breaking checks, but don't generally worry about all platforms since this is the most delay sensitive thing we do.
On master commit, run all platforms to build record of flaky tests.
> Run cron schedule

- .circleci/config.yml
Master compile cache is built once a day by master compile job or each commit on master.
Each Test build uses a previous run on the same branch, or the Master compile cache.
Experience should generally be
PR: check and test jobs start immediately using the master build cache (or previous good run).
Master commit: Runs 3 test jobs which use master build cache.  Compile updates the cache without growing.
Daily: All jobs run and Master compile cache is updated.
> Adjust CircleCI caching

- okhttp/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
Minor correction to the `WebSocketReaderTest.reservedFlagsAreUnsupported()`.
For all 3 hex codes, `a` is pong, not ping.
`0xca00 is 0b11001010`, rsv1 flag is set
`0xaa00 is 0b10101010`, rsv2 flag is set
`0x9a00 is 0b10011010`, rsv3 flag is set
https://tools.ietf.org/html/rfc6455#section-5.2
> Fix correctness of WebSocketReader reserved flags test

- .circleci/config.yml
Was running at midnight, had 36 minute schedule delay.  Scheduled for just after 1pm at random minute.
https://circleci.com/build-insights/gh/square/okhttp/master
> Run nightly job at less loaded time

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp/src/main/java/okhttp3/Authenticator.kt
- okhttp/src/main/java/okhttp3/Call.kt
- okhttp/src/main/java/okhttp3/Dispatcher.kt
- okhttp/src/main/java/okhttp3/Dns.kt
- okhttp/src/main/java/okhttp3/EventListener.kt
- okhttp/src/main/java/okhttp3/Interceptor.kt
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/RealCall.kt
- okhttp/src/main/java/okhttp3/RequestBody.kt
- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
We had a problem where boolean vals needed to be reverted back to
boolean funs. I'd like to go back to vals later, but supporting existing
source patterns is more important.
We also had a problem where single abstract method types (SAM types)
could be supplied as lambas when calling into Java but not when calling
into Kotlin.
I found these by pointing KotlinSourceCompatibilityTest at the OkHttp
Get there like this:
```
git co 7eb897ab2e223632b3316bf46a15d37307a3d3b6^
git co 7eb897ab2e223632b3316bf46a15d37307a3d3b6 okhttp/build.gradle
git co 7eb897ab2e223632b3316bf46a15d37307a3d3b6 build.gradle
```
> Fix source compatibility for some Kotlin callsites.

- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
Unlike most of OkHttp, the API for MockWebServer is pretty rough. We don't
have Nullable annotations. Everything is mutable. There are even weird bad
things where public methods return non-public types.
> Add MockWebServer to KotlinSourceCompatibilityTest

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/LoggingEventListener.kt
- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
If I understand correctly the Kotlin SAM rules mean this case will no longer work, so just documenting.
> Fix kotlin source compatibility with logger

- okhttp/src/main/java/okhttp3/internal/http1/Http1ExchangeCodec.java
When make an HTTPS connection over an HTTP proxy, the `realConnection` is always set to `null`.
In `RealConnection.java` line 395:
`Http1ExchangeCodec tunnelCodec = new Http1ExchangeCodec(client:null, realConnection:null, source, sink);`
`...`
`Response response = tunnelCodec.readResponseHeaders(false)`
Refer to #4915 NullPointerException in Http1ExchangeCodec.readResponseHeaders() in OkHttp 3.14.0
> Fix #4915 nullPointerException caused by realConnection is null

- gradle/wrapper/gradle-wrapper.properties
```
Welcome to Gradle 5.4!
Here are the highlights of this release:
- Run builds with JDK12
- New API for Incremental Tasks
- Updates to native projects, including Swift 5 support
For more details see https://docs.gradle.org/5.4/release-notes.html
```
> Gradle 5.4 upgrade
