square/okhttp

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockResponse.java
- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/com/squareup/okhttp/mockwebserver/MockWebServerTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Util.java
> Use Sources and Sinks for all IO.

- okhttp-tests/src/test/java/com/squareup/okhttp/CacheControlTest.java
- okhttp/src/main/java/com/squareup/okhttp/CacheControl.java
> Make cache-control remember its header value.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/RecordedRequest.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Internal.java
This is an obscure API that no one was using... let's be honest. Just delete it.
> Remove old SSL protocol method.

- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionSpecTest.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
Updated commit + added test based on discussion below. Please take a look.
> Modify the cipher suite / TLS version selection behavior

- okhttp/src/main/java/com/squareup/okhttp/ConnectionPool.java
Closes https://github.com/square/okhttp/issues/1306
> Hurry up connection pool shutdown.

- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionSpecTest.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Util.java
Based on comments made during the review.
> Follow up fixes from pull request 1208

- okhttp-tests/src/test/java/com/squareup/okhttp/CacheControlTest.java
- okhttp/src/main/java/com/squareup/okhttp/CacheControl.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/CacheStrategy.java
See commit comment. Minor improvements to the cache strategy now that OkHttp is a private, not a shared cache.
> Private cache improvements

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
Provide `start(InetSocketAddress)` and `start(InetAddress, port)` to
address #1342
> Allow user to configure what mockwebserver binds to

- okhttp-tests/src/test/java/com/squareup/okhttp/OkHttpClientTest.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
> Do not allow timeouts less than 1ms.

- website/index.html
this info is present on repo README, but not on Pages.
> Add Gradle download info to project Pages

- okhttp-tests/src/test/java/com/squareup/okhttp/MultipartBuilderTest.java
- okhttp/src/main/java/com/squareup/okhttp/MultipartBuilder.java
Closes https://github.com/square/okhttp/issues/1349
> Compute the content length of multipart bodies.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/com/squareup/okhttp/mockwebserver/MockWebServerTest.java
Closes https://github.com/square/okhttp/issues/1372
> Don't crash on shutdown() before start().

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ws/WebSocketReader.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ws/WebSocketWriter.java
Just auditing the web socket code. These messages match the decided conventions and others in the project and Okio.
> Normalize web socket exception messages to match.

- okhttp/src/main/java/com/squareup/okhttp/internal/Platform.java
We're going towards HTTP/2 only, which is ALPN and requires cipher suites
only found in Android 5+. That's where we'll focus our energy.
Tested on Android 4.4 and Android 5.0 emulators. On Android 4.4 ALPN
is avoided. On Android 5.0 it is used.
> Disable ALPN on Android 4.4.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
Reported here: http://stackoverflow.com/questions/28931191/okhttp-urlconnection-test-crashes-mockwebserver-yet-passes/28934866#28934866
> Don't attempt to read a source after closing it.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/ws/WebSocketCallTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/ws/WebSocketRecorder.java
These were left in my working directory while trying to diagnose some other issues.
> Correctly determine when test code times out.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java
- okhttp/src/main/java/com/squareup/okhttp/internal/ws/WebSocketCall.java
This was feedback on https://github.com/square/okhttp/pull/1260 from @swankjesse
> Use the now-generalized reply executor for peer close.

- okhttp/src/main/java/com/squareup/okhttp/Cache.java
Fixes https://github.com/square/okhttp/issues/1461
> Update cache docs to use Call and CacheControl.

- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java
https://github.com/square/okhttp/issues/1114
> Provide context on unexpected EOFs.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/DiskLruCacheTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/io/InMemoryFileSystem.java
- okhttp/src/main/java/com/squareup/okhttp/Cache.java
- okhttp/src/main/java/com/squareup/okhttp/internal/DiskLruCache.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Util.java
- okhttp/src/main/java/com/squareup/okhttp/internal/io/FileSystem.java
Working towards https://github.com/square/okhttp/issues/1211
> New file system abstraction.

- okcurl/src/main/java/com/squareup/okhttp/curl/Main.java
Beneficial for this website in particular:
https://http2.golang.org/clockstream
> Stream the response in okcurl.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/Spdy3ConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/SpdyStream.java
Previously we'd consistently send 2048 byte frames because that was
Okio's default segment size. This increases OkHttp's typical segment
size to the 16 KiB frame size that all HTTP/2 endpoints support.
> Introduce a buffer in SpdyStream's outgoing frames.

- okhttp-tests/src/test/java/com/squareup/okhttp/InterceptorTest.java
Our behavior here is not good. Right now it looks like we're leaking
resources; nothing is releasing the socket in a 'finally' clause when
interceptors crash. We're also not notifying the callback that the
call has failed; that's left hanging.
That said, we don't expect applications to recover from these
exceptions.
Closes https://github.com/square/okhttp/issues/1482
> Add a test for interceptors throwing unchecked exceptions.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/Spdy3ConnectionTest.java
We had tests that flake because they expected the watchdog to have
completed closing a connection, but we weren't blocking until that
work was done.
Closes https://github.com/square/okhttp/issues/1328
> Fix a flaky test by waiting until the Okio watchdog is caught up.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/URLConnectionTest.java
We don't have machinery to recover from this when streamed requests
fail, and we also don't have machinery to reliably detect when they
will fail.
This is sad. Fortunately the new API doesn't suffer this problem.
> Relax expectations when streamed requests fail.

- samples/crawler/src/main/java/com/squareup/okhttp/sample/Crawler.java
We were interpretting links relative to the URLs requested, rather
than the redirect targets of those URLs.
> Fix some crawler bugs.

- okcurl/src/test/java/com/squareup/okhttp/curl/MainTest.java
- okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java
- okhttp/src/main/java/com/squareup/okhttp/Request.java
> Never convert null into an empty request body.

- okhttp-apache/src/test/java/com/squareup/okhttp/apache/OkApacheClientTest.java
> Add a test for case insensitive content type matching.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/Spdy3ConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/SpdyConnection.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/SpdyStream.java
We weren't applying the stream's timeout to writes to the underlying
connection. This was just a dumb bug.
When the stream does time out waiting on a write that's blocked inside
the connection awaiting write window, we need to break out.
Closes https://github.com/square/okhttp/issues/1560
> Don't get stuck waiting on the connection window.

- okhttp-ws-tests/src/test/java/com/squareup/okhttp/internal/ws/RealWebSocketTest.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/RealWebSocket.java
This causes the read loop to immedaitely break–the desired behvior after receiving a close frame–without having to wait for the runnable to execute.
Closes #1516.
> Update reader state on the reader thread.

- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
This is very early and subject to change. I'd like to evaluate the API first
because it's difficult to do properly and because if it's done right, the
implementation should be mostly mechanical once this is set.
> HttpUrl initial API.

- okhttp/src/main/java/com/squareup/okhttp/Call.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
@swankjesse Here's the pull request to open up again the main API classes until we figure out a different Quasar integration approach. Thanks!
> Make 'OkHttpClient' and 'Call' non-final again for Quasar integration

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/UrlComponentEncodingTester.java
It turns out that even the spec that tries to describe how browsers actually
work doesn't completely accomplish that. So I'm trying to reconcile differences
between Firefox, Chrome and the WHATWG spec. In some cases I get three different
behaviors.
This adds tests for some interesting cases.
> Some initial URL test cases.

- checkstyle.xml
- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/UrlComponentEncodingTester.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
This includes everything but character encoding. The implementation
is built around one oversized method that runs top to bottom; I found
this was easier to follow than the switch statement recommended by the
URL standard.
> HttpURL parsing.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/UrlComponentEncodingTester.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
A building block towards encoding hostnames.
> Decode paths, usernames and passwords.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Without actually implementing it.
> Get closer to IDN and IPv6 parsing.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/RouteExceptionTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/URLConnectionTest.java
> Follow up fixes for #1596

- okhttp-tests/src/test/java/com/squareup/okhttp/CertificatePinnerTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/TestUtil.java
- okhttp/src/main/java/com/squareup/okhttp/CertificatePinner.java
Part of #1454 
@swankjesse PTAL
> Wildcard hostnames support for CertificatePinner

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
This leans on InetAddress to do the work. It's not perfect, but it's
also not a lot of code. https://github.com/square/okhttp/issues/1613
> Parse IPv6 addresses.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
This is actually a little trickier than strings, partly because
we now need code to go in both directions, and partly because
paths that end with '/' are an important but awkward special
case.
The goal is that this will make accessing query parameters much
easier.
> Use lists to model paths and queries.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
The tricky part of this is '+' and ' ' management.
> Implement query parameter management.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
In queries this means transcoding '+' to '%2B' also.
> Always encode space as %20.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- okcurl/src/test/java/com/squareup/okhttp/curl/MainTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp/src/main/java/com/squareup/okhttp/Request.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Platform.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/AuthenticatorAdapter.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/SocketConnector.java
This makes URL validation more eager than it is today.
> Use HttpUrl in Request.

- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Closes https://github.com/square/okhttp/issues/1486
> Javadoc HttpUrl encoding.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
I may follow up by computing both on-demand.
> Store the decoded components in HttpURL, and encoded in HttpUrl.Builder.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/MockSpdyPeer.java
It would have crashed if close() was called before readAndWriteFrames() started.
That's fixed now.
> Fix a race closing MockSpdyPeer.

- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/FrameReader.java
- okhttp/src/main/java/com/squareup/okhttp/internal/spdy/SpdyConnection.java
Currently we're sweeping these under the rug.
> Crash on unexpected RuntimeExceptions.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/spdy/Spdy3ConnectionTest.java
Closes https://github.com/square/okhttp/issues/1660
> Fix flaky test Spdy3ConnectionTest.receiveGoAway().

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/AutobahnTester.java
- okhttp-ws-tests/src/test/java/com/squareup/okhttp/ws/WebSocketCallTest.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketCall.java
- okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketListener.java
- samples/guide/src/main/java/com/squareup/okhttp/recipes/WebSocketEcho.java
> Call onOpen on the reader thread and force writing on another thread.

- okhttp-tests/src/test/java/com/squareup/okhttp/CacheTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
> Forbid response bodies on HTTP 204 and 205 responses.

- CHANGELOG.md
- okhttp/src/main/java/com/squareup/okhttp/Request.java
Closes https://github.com/square/okhttp/issues/1673
> Better docs on new URL exceptions.

- okhttp-tests/src/test/java/com/squareup/okhttp/CacheTest.java
Closes https://github.com/square/okhttp/issues/1712
> Test that conditional misses update the cache.

- okhttp-tests/src/test/java/com/squareup/okhttp/internal/http/URLConnectionTest.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java
Change the exception on a truncated chunked body.
> More tests on truncated response bodies.

- okhttp-tests/src/test/java/com/squareup/okhttp/OkHttpClientTest.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
Closes https://github.com/square/okhttp/issues/1719
> Set default timeouts to ten seconds.

- mockwebserver/README.md
Method play is deprecated in favor of start.
> Use method start instead of play in example

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Closes https://github.com/square/okhttp/issues/1636
> IPv6 canonical string.

- okhttp/src/main/java/com/squareup/okhttp/Connection.java
Not sure this is the right way to fix it (probably not), but just in case...
> Fixes #1787

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
- okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
- okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Internal.java
This is to address issue #1827.
> Throw UnknownHostException again from HttpURLConnection

- mockwebserver/README.md
remove reference to deprecated method
> minor documentation update

- okhttp/src/main/java/com/squareup/okhttp/internal/ConnectionSpecSelector.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java
Related to issue #1790.
If there is a *connection* timeout the next route should
be tried. Timeouts during a request/response should
probably not be retried.
The timeout/interrupt behavior was changed in PR #1257
for issue #1146. This modified both connection and
request/response behavior. The issue reported was actually
about the use of Thread.interrupt(), not timeouts, but the
behavior change modified both behavior for interrupt and
timeout.
PR #1388 split the handling of exceptions so that separate
code now handles connection errors from that which handles
request/response errors. It faithfully kept the behavior
from PR #1257.
The modification of the timeout behavior during *connection*
caused problems on Android. Now that the two types of error
handling are split it's possible to deal …
> Partially revert connection timeout behavior

- mockwebserver/src/test/java/com/squareup/okhttp/mockwebserver/MockWebServerTest.java
There are a few cases in OkHttp where API calls don't exist on
Android, but this is one that we can work around with any loss
of understanding.
The same test also behaves differently on Android due to
differences between the OpenJDK and Android's
HttpURLConnection implementation.
See issue #1824.
> Make the MockWebServer tests more Android compatible.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
> Add a 3030 testcase.

- okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpMethod.java
The tests are still successful. Is there anything else required to get WebDAV support into okhttp?
> Add support for WebDAV HTTP methods (RFC 4918)

- okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java
> Use clever buffer/clone trick for duplicate response body.

- okhttp-tests/src/test/java/com/squareup/okhttp/CallTest.java
- okhttp/src/main/java/com/squareup/okhttp/Call.java
> Make AsyncCall handle interceptors that throws an IOException

- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
- okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java
Android bug: https://code.google.com/p/android/issues/detail?id=190998
> Fix Http(s)URLConnectionImpl.getInstanceFollowsRedirects()

- okcurl/src/main/java/com/squareup/okhttp/curl/Main.java
- okcurl/src/test/java/com/squareup/okhttp/curl/MainTest.java
This is the correct default mimetype for POST requests
see [POST#Use_for_submitting_web_forms](https://en.wikipedia.org/wiki/POST_(HTTP)#Use_for_submitting_web_forms)
> use application/x-www-form-urlencoded in okcurl

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/URLConnectionTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/UrlComponentEncodingTester.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Plus a bunch of test cases around this unfortunate case.
Closes https://github.com/square/okhttp/issues/1872
> Encode enough to make URI happy.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/SocketPolicy.java
- mockwebserver/src/test/java/com/squareup/okhttp/mockwebserver/MockWebServerTest.java
> Add policy for disconnecting request body halfway.

- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionSpecTest.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java
- okhttp/src/main/java/com/squareup/okhttp/TlsVersion.java
- okhttp/src/main/java/com/squareup/okhttp/internal/Util.java
Closes https://github.com/square/okhttp/issues/1831
> Make ConnectionSpec more uniform.

- okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java
- okhttp-tests/src/test/java/com/squareup/okhttp/UrlComponentEncodingTester.java
- okhttp-tests/src/test/java/com/squareup/okhttp/WebPlatformUrlTest.java
- okhttp/src/main/java/com/squareup/okhttp/FormEncodingBuilder.java
- okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java
Fixes https://github.com/square/okhttp/issues/1635
> Don't percent-encode non-ASCII characters in fragments

- samples/guide/src/main/java/com/squareup/okhttp/recipes/PostMultipart.java
Closes: https://github.com/square/okhttp/issues/1521
> Include a filename in the PostMultipart example.

- okhttp/src/main/java/com/squareup/okhttp/Call.java
Might be useful to expose this bookkeeping to app developers.
> Add Call.isExecuted().

- okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/com/squareup/okhttp/logging/HttpLoggingInterceptorTest.java
> Return this from HttpLoggingInterceptor.setLevel()

- okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/com/squareup/okhttp/logging/HttpLoggingInterceptorTest.java
> Support 204 and 205 'No Content' replies when application interceptor.

- okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/com/squareup/okhttp/logging/HttpLoggingInterceptorTest.java
> Log the full URL.

- okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/com/squareup/okhttp/logging/HttpLoggingInterceptorTest.java
> Log level getter.

- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockResponse.java
- mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/framed/HttpOverHttp2Test.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/framed/HttpOverSpdy3Test.java
- okhttp-tests/src/test/java/com/squareup/okhttp/internal/framed/HttpOverSpdyTest.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionPool.java
- okhttp/src/main/java/com/squareup/okhttp/internal/framed/FramedConnection.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/StreamAllocation.java
- okhttp/src/main/java/com/squareup/okhttp/internal/io/RealConnection.java
Closes https://github.com/square/okhttp/issues/1484
> Honor the max concurrent streams setting.

- okhttp-tests/src/test/java/com/squareup/okhttp/ConnectionPoolTest.java
- okhttp/src/main/java/com/squareup/okhttp/ConnectionPool.java
- okhttp/src/main/java/com/squareup/okhttp/internal/http/StreamAllocation.java
- okhttp/src/main/java/com/squareup/okhttp/internal/io/RealConnection.java
This is already suggesting some bugs in OkHttp itself.
> Detect leaked connections.

- okhttp-android-support/src/main/java/com/squareup/okhttp/internal/huc/JavaApiConverter.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/JavaApiConverterTest.java
- okhttp-android-support/src/test/java/com/squareup/okhttp/internal/huc/ResponseCacheTest.java
- okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketReader.java
- okhttp/src/main/java/com/squareup/okhttp/ResponseBody.java
- samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java
> Remove IOException from source() and streams.

- okhttp/src/main/java/okhttp3/ResponseBody.java
There's no action they can take as the result of them, anyway.
> Do not burden application code with close failures.

- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp/src/main/java/okhttp3/Call.java
- okhttp/src/main/java/okhttp3/Dispatcher.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
More documentation forthcoming.
> Make call an interface, and introduce Call.Factory.

- okhttp/src/main/java/okhttp3/CookieJar.java
- okhttp/src/main/java/okhttp3/ResponseBody.java
Closes: https://github.com/square/okhttp/issues/2158
> Better docs for ResponseBody.

- website/index.html
Links no longer lead to 'Not Found' message.
> Fixed URLs to 'Full Source' for Get and Post examples in index.html.

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
> Add newBuilder overload for resolving directly to a builder.

- okhttp-tests/src/test/java/okhttp3/AddressTest.java
- okhttp-tests/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverSpdyTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/RouteSelectorTest.java
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetAuthenticator.java
- okhttp/src/main/java/okhttp3/Authenticator.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
Previously we were using the system-wide default authenticator.
> Change the default authenticator to be no authenticator.

- okhttp/src/main/java/com/squareup/okhttp/internal/http/StreamAllocation.java
This is imperfect, but it should save some unnecessary work and will
hopefully prevent RouteSelector from attempting a route when none is
available.
https://github.com/square/okhttp/issues/2151
> Don't do health checks on brand new connections.

- okhttp-android-support/src/test/java/okhttp3/android/HttpResponseCacheTest.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/CacheAdapterTest.java
- okhttp-android-support/src/test/java/okhttp3/internal/huc/ResponseCacheTest.java
- okhttp-apache/src/main/java/okhttp3/apache/OkApacheClient.java
- okhttp-urlconnection/src/test/java/okhttp3/UrlConnectionCacheTest.java
- okhttp-ws-tests/src/main/java/okhttp3/ws/AutobahnTester.java
- okhttp-ws-tests/src/test/java/okhttp3/ws/WebSocketCallTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- samples/guide/src/main/java/okhttp3/guide/GetExample.java
- samples/guide/src/main/java/okhttp3/guide/PostExample.java
- samples/guide/src/main/java/okhttp3/recipes/AccessHeaders.java
- samples/guide/src/main/java/okhttp3/recipes/AsynchronousGet.java
- samples/guide/src/main/java/okhttp3/recipes/CancelCall.java
- samples/guide/src/main/java/okhttp3/recipes/ParseResponseWithGson.java
- samples/guide/src/main/java/okhttp3/recipes/PerCallSettings.java
- samples/guide/src/main/java/okhttp3/recipes/PostFile.java
- samples/guide/src/main/java/okhttp3/recipes/PostForm.java
- samples/guide/src/main/java/okhttp3/recipes/PostMultipart.java
- samples/guide/src/main/java/okhttp3/recipes/PostStreaming.java
- samples/guide/src/main/java/okhttp3/recipes/PostString.java
- samples/guide/src/main/java/okhttp3/recipes/SynchronousGet.java
- samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java
- samples/simple-client/src/main/java/okhttp3/sample/OkHttpContributors.java
This is a popular API and keeping it working is handy.
> Restore no-args constructor for OkHttpClient.

- okhttp-tests/src/test/java/okhttp3/ResponseTest.java
- okhttp/src/main/java/okhttp3/Response.java
Closes: https://github.com/square/okhttp/issues/1740
> New API: Response.peekBody

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
> Handle unknown content lengths.

- okhttp/src/main/java/okhttp3/OkHttpClient.java
> Javadoc fix for immutable Interceptors in OkHttpClient

- okhttp-logging-interceptor/README.md
Change how to use on okhttp-loging-interceptor's README.md
> Update okhttp-logging-interceptor README.md

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
> Don't leak file handles when a conditional GET throws.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp-ws-tests/src/test/java/okhttp3/ws/WebSocketCallTest.java
> Change default mock reason.

- okhttp-tests/src/test/java/okhttp3/internal/http/CookiesTest.java
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java
This brings the tests to all pass on Android.
Closes: https://github.com/square/okhttp/issues/2202
> Parse the CookieHandler request cookies in JavaNetCookieJar.

- okhttp-tests/src/test/java/okhttp3/internal/http/CookiesTest.java
See https://github.com/square/okhttp/issues/2202
> Test that JavaNetCookieJar can handle multiple cookies.

- okhttp-apache/pom.xml
- okhttp-logging-interceptor/pom.xml
- okhttp-urlconnection/pom.xml
- okhttp-ws/pom.xml
- okhttp/pom.xml
- pom.xml
This reverts commit 2b29196ee2ee0e3cac5cf1fb452d36a2d829a24f.
> Revert "Make OkHttp OSGi ready"

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/io/RealConnection.java
> Add Framed protocol to connections

- okhttp/src/main/java/okhttp3/OkHttpClient.java
Sorry for creating a new pull request.
> Add Optmizations for ClearText to avoid SSLContext

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
This is an attempt to push #1977 over the finish line.
> Handle UnsupportedCharsetException in HttpLoggingInterceptor

- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverHttp2Test.java
- okhttp-tests/src/test/java/okhttp3/internal/framed/HttpOverSpdyTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/CookiesTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http/ExternalHttp2Example.java
- okhttp-tests/src/test/java/okhttp3/internal/http/ExternalSpdyExample.java
> Migrate some tests off of OkUrlFactory.

- okhttp/src/main/java/okhttp3/OkHttpClient.java
Issue: https://github.com/square/okhttp/issues/2292
> #2292 removed final from OkHttpClient

- okhttp/src/main/java/okhttp3/internal/Platform.java
This gets trust manager extraction working, but not ALPN or other
platform features.
Also remove some unused socket tagging features.
> Hack in limited support for Robolectric.

- okhttp-tests/src/test/java/okhttp3/CertificatePinnerTest.java
- okhttp/src/main/java/okhttp3/CertificatePinner.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- samples/guide/src/main/java/okhttp3/recipes/CertificatePinning.java
Closes: https://github.com/square/okhttp/issues/1539
> Implement support for SHA-256 pins.

- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
This is for #2288 - not entirely sure if this is what you intended.
> Ensure network interceptors always have access to the underlying connection.

- okhttp-tests/src/test/java/okhttp3/internal/DiskLruCacheTest.java
- okhttp/src/main/java/okhttp3/internal/DiskLruCache.java
We had a bug where we could have two editors for the same entry. This
would occur when the cache was cleared, or if the entry was otherwise
evicted while the edit was in progress.
Previously the two editors would corrupt each other, and potentially
the cache's size. With this change the detached editor is limited and
harmless.
> Recover more gracefully when an editor is detached.

- okhttp-tests/src/test/java/okhttp3/CertificateChainCleanerTest.java
- okhttp/src/main/java/okhttp3/CertificatePinner.java
- okhttp/src/main/java/okhttp3/internal/tls/CertificateChainCleaner.java
- okhttp/src/main/java/okhttp3/internal/tls/TrustRootIndex.java
Closes: https://github.com/square/okhttp/issues/2407
> Use X509TrustManagerExtensions on Android 17+.

- okhttp-hpacktests/pom.xml
- okhttp-hpacktests/src/test/java/okhttp3/internal/framed/HpackDecodeInteropTest.java
- okhttp-hpacktests/src/test/java/okhttp3/internal/framed/HpackDecodeTestBase.java
- okhttp-hpacktests/src/test/java/okhttp3/internal/framed/HpackRoundTripTest.java
- okhttp-hpacktests/src/test/java/okhttp3/internal/framed/hpackjson/Case.java
- okhttp-hpacktests/src/test/java/okhttp3/internal/framed/hpackjson/HpackJsonUtil.java
- okhttp-hpacktests/src/test/java/okhttp3/internal/framed/hpackjson/Story.java
- okhttp-tests/pom.xml
- pom.xml
- samples/guide/pom.xml
- samples/guide/src/main/java/okhttp3/recipes/ParseResponseWithMoshi.java
- samples/guide/src/main/java/okhttp3/recipes/RequestBodyCompression.java
- samples/simple-client/pom.xml
- samples/simple-client/src/main/java/okhttp3/sample/OkHttpContributors.java
As discussed here: https://github.com/square/okhttp/pull/2492
> Use Moshi in OkHttp.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okcurl/src/main/java/okhttp3/curl/Main.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/UrlComponentEncodingTester.java
- okhttp-tests/src/test/java/okhttp3/WebPlatformUrlTestData.java
- okhttp-tests/src/test/java/okhttp3/internal/http/RecordingProxySelector.java
- okhttp-ws-tests/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
- okhttp-ws-tests/src/test/java/okhttp3/internal/ws/WebSocketWriterTest.java
- okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java
- okhttp/src/main/java/okhttp3/Headers.java
- okhttp/src/main/java/okhttp3/internal/NamedRunnable.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/framed/FramedConnection.java
- okhttp/src/main/java/okhttp3/internal/framed/Header.java
- okhttp/src/main/java/okhttp3/internal/framed/Http2.java
- okhttp/src/main/java/okhttp3/internal/framed/Spdy3.java
See #2522 for more info.
I've signed the CLA. Please review and pull.
Thanks,
Venil Noronha
> Setting default String locale to Locale.US

- samples/guide/src/main/java/okhttp3/recipes/CertificatePinning.java
Closes: https://github.com/square/okhttp/issues/2535
> Pin fewer certificates in our sample.

- okhttp/src/main/java/okhttp3/Call.java
- okhttp/src/main/java/okhttp3/Callback.java
- okhttp/src/main/java/okhttp3/Response.java
- okhttp/src/main/java/okhttp3/ResponseBody.java
- samples/guide/src/main/java/okhttp3/guide/GetExample.java
- samples/guide/src/main/java/okhttp3/guide/PostExample.java
- samples/guide/src/main/java/okhttp3/recipes/AccessHeaders.java
- samples/guide/src/main/java/okhttp3/recipes/AsynchronousGet.java
- samples/guide/src/main/java/okhttp3/recipes/Authenticate.java
- samples/guide/src/main/java/okhttp3/recipes/CacheResponse.java
- samples/guide/src/main/java/okhttp3/recipes/CancelCall.java
- samples/guide/src/main/java/okhttp3/recipes/CertificatePinning.java
- samples/guide/src/main/java/okhttp3/recipes/CheckHandshake.java
- samples/guide/src/main/java/okhttp3/recipes/ConfigureTimeouts.java
- samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java
- samples/guide/src/main/java/okhttp3/recipes/ParseResponseWithMoshi.java
- samples/guide/src/main/java/okhttp3/recipes/PerCallSettings.java
- samples/guide/src/main/java/okhttp3/recipes/PostFile.java
- samples/guide/src/main/java/okhttp3/recipes/PostForm.java
- samples/guide/src/main/java/okhttp3/recipes/PostMultipart.java
- samples/guide/src/main/java/okhttp3/recipes/PostStreaming.java
- samples/guide/src/main/java/okhttp3/recipes/PostString.java
- samples/guide/src/main/java/okhttp3/recipes/Progress.java
- samples/guide/src/main/java/okhttp3/recipes/RequestBodyCompression.java
- samples/guide/src/main/java/okhttp3/recipes/RewriteResponseCacheControl.java
- samples/guide/src/main/java/okhttp3/recipes/SynchronousGet.java
- samples/pom.xml
Also implement Closeable on Response to make it easier to do the right thing.
> Better documentation and examples on closing response bodies.

- okhttp/src/main/java/okhttp3/internal/framed/FramedConnection.java
While investigating an Android issue with these methods
I found they were not used. Tidying up.
> Remove methods from FramedConnection that are unused

- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp/src/main/java/okhttp3/Dispatcher.java
> Add support for an idle callback to Dispatcher.

- okhttp-tests/src/test/java/okhttp3/CertificatePinnerTest.java
- okhttp/src/main/java/okhttp3/CertificatePinner.java
Closes: https://github.com/square/okhttp/issues/2609
> Changed CertificatePinner to ignore case when matching pins.

- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
Previously we would sometimes delegate to the asynchronous implementation,
and that would prevent exceptions from reaching their destination.
> Fix OkHttpURLConnection to not swallow unexpected exceptions.

- okhttp/src/main/java/okhttp3/Dispatcher.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http/Http1xStream.java
- okhttp/src/main/java/okhttp3/internal/http/HttpEngine.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
> Move core interceptors into top level classes.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/TestUtil.java
- pom.xml
Otherwise we create too many threads and crash Travis.
> Fix tests to share a common Dispatcher.

- okhttp-android-support/src/main/java/okhttp3/internal/huc/CacheAdapter.java
- okhttp-apache/src/main/java/okhttp3/apache/OkApacheClient.java
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-tests/src/test/java/okhttp3/DelegatingSocketFactory.java
- okhttp-tests/src/test/java/okhttp3/FallbackTestClientSocketFactory.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/platform/OptionalMethodTest.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
- okhttp-urlconnection/src/test/java/okhttp3/internal/huc/URLEncodingTest.java
- okhttp/src/main/java/okhttp3/Cache.java
- okhttp/src/main/java/okhttp3/CipherSuite.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java
- okhttp/src/main/java/okhttp3/internal/cache/InternalCache.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/framed/ErrorCode.java
- okhttp/src/main/java/okhttp3/internal/framed/FramedConnection.java
- okhttp/src/main/java/okhttp3/internal/framed/Hpack.java
- okhttp/src/main/java/okhttp3/internal/framed/Huffman.java
- okhttp/src/main/java/okhttp3/internal/http/Http1xStream.java
- okhttp/src/main/java/okhttp3/internal/http/Http2xStream.java
- okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.java
- okhttp/src/main/java/okhttp3/internal/http/HttpStream.java
This made a few hundred suggestions, many of which are thoughtful but
I'm deliberately ignoring anyway.
The following fixes are good ideas.
> Run IntelliJ's analysis on OkHttp.

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp/src/main/java/okhttp3/Headers.java
For https://github.com/square/okhttp/issues/2701
> Use TreeMap in Headers.toMultimap()

- okhttp/src/main/java/okhttp3/HttpUrl.java
- okhttp/src/main/java/okhttp3/internal/tls/BasicCertificateChainCleaner.java
Closes: https://github.com/square/okhttp/issues/2577
Closes: https://github.com/square/okhttp/issues/2263
> More docs for HttpUrl.

- okhttp/src/main/java/okhttp3/HttpUrl.java
Per https://github.com/square/okhttp/pull/1629
> Update Javadoc example for HttpUrl.encodedPath()

- okhttp/src/main/java/okhttp3/OkHttpClient.java
Closes: https://github.com/square/okhttp/issues/2636
> Document OkHttpClient best practices.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/Call.java
- okhttp/src/main/java/okhttp3/RealCall.java
Fixes #2709.
Implementing this was pretty much straightforward, but I don't know if I missed something.
> Allow to clone calls

- okhttp-tests/src/test/java/okhttp3/CookiesTest.java
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java
- okhttp/src/main/java/okhttp3/Cookie.java
Closes: https://github.com/square/okhttp/issues/2549
> Inject a leading . for better matching under JavaNetCookieJar

- okhttp-tests/src/test/java/okhttp3/internal/cache2/FileOperatorTest.java
- okhttp/src/main/java/okhttp3/internal/cache2/FileOperator.java
This is just the basics that I need for DiskLruCache2. It's not a
particularly general purpose API and at the moment there are no
plans to expose it as such.
https://github.com/square/okhttp/issues/2682
> FileOperator, a utility for doing random access I/O with Okio.

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
- okhttp/src/main/java/okhttp3/RealCall.java
#1838 
Add HttpUrl#redactedUrl() to display only the domain name of the url
> Method redact the url in HttpUrl

- pom.xml
Added a new profile for jdk8 102 and found that there is also a new version release for org.mortbay.jetty.alpn
> Add mvn profile for ALPN version 8.1.9.v20160720 for jdk8 102

- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-apache/src/main/java/okhttp3/apache/OkApacheClient.java
- okhttp-ws-tests/src/test/java/okhttp3/ws/WebSocketCallTest.java
- okhttp/src/main/java/okhttp3/Request.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
> WebSockets should show an empty body to interceptors.

- okhttp/src/main/java/okhttp3/HttpUrl.java
I happen to find one for-loop that can be written more performance sensitively, based on this: 
https://speakerdeck.com/jakewharton/eliminating-code-overhead-square-hq-2015
> Modify for-loop more performance sensitively

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
Enables use via try-with-resources.
Closes #2854.
> Implement Closeable on MockWebServer.

- okhttp-tests/src/test/java/okhttp3/MultipartBodyTest.java
- okhttp/src/main/java/okhttp3/MultipartBody.java
> Expose Part headers and body.

- okhttp/src/main/java/okhttp3/RealWebSocketCall.java
> Remove connection read/write timeouts for web sockets.

- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.java
> Inline single-use method in web socket writer.

- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
Closes: https://github.com/square/okhttp/issues/2815
> Fix conditional cache hits to update timestamp fields.

- okhttp-tests/src/main/java/okhttp3/AutobahnTester.java
- okhttp-tests/src/test/java/okhttp3/WebSocketCallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/okhttp3/WebSocket.java
- okhttp/src/main/java/okhttp3/WebSocketListener.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
- samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java
> Remove inconsistent 'send' prefix from message/ping methods.

- checkstyle.xml
- pom.xml
- samples/pom.xml
- samples/slack/pom.xml
- samples/slack/src/main/java/okhttp3/slack/OAuthSession.java
- samples/slack/src/main/java/okhttp3/slack/OAuthSessionFactory.java
- samples/slack/src/main/java/okhttp3/slack/RtmSession.java
- samples/slack/src/main/java/okhttp3/slack/RtmStartResponse.java
- samples/slack/src/main/java/okhttp3/slack/SlackApi.java
- samples/slack/src/main/java/okhttp3/slack/SlackClient.java
Currently it just prints WebSockets messages as they arrive, never sending any.
In a follow-up I'd like to do that, and also start to use this to figure out
where and how our WebSockets client can be improved.
https://github.com/square/okhttp/issues/2902
> A WebSockets sample that uses the Slack API.

- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
See: https://github.com/square/okhttp/issues/2756
> Tests for management of HTTP/2 connections that are shutdown.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/main/java/okhttp3/AutobahnTester.java
- okhttp-tests/src/test/java/okhttp3/RecordedResponse.java
- okhttp-tests/src/test/java/okhttp3/WebSocketHttpTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/WebSocket.java
- okhttp/src/main/java/okhttp3/WebSocketListener.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
- samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java
- samples/slack/src/main/java/okhttp3/slack/RtmSession.java
- samples/slack/src/main/java/okhttp3/slack/SlackApi.java
The synchronous WebSocket class is gone.
> Rename NewWebSocket to WebSocket.

- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
We were prefering to return the networkResponse before the request
had completely failed. Instead we should return the network response
only on failure, and only for APIs that return failed responses.
Closes: https://github.com/square/okhttp/issues/2997
> Fix flakiness in authenticateWithChunkedStreaming().

- okhttp/src/main/java/okhttp3/CacheControl.java
- okhttp/src/main/java/okhttp3/CertificatePinner.java
- okhttp/src/main/java/okhttp3/ConnectionSpec.java
- okhttp/src/main/java/okhttp3/Cookie.java
- okhttp/src/main/java/okhttp3/FormBody.java
- okhttp/src/main/java/okhttp3/Headers.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/ResponseBody.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.java
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java
- okhttp/src/main/java/okhttp3/internal/cache2/Relay.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Hpack.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Reader.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
- okhttp/src/main/java/okhttp3/internal/http2/Huffman.java
- okhttp/src/main/java/okhttp3/internal/platform/JdkWithJettyBootPlatform.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
There are quite a few of them. Any of them were there by design?
> Remove creation of synthetic accessor methods.

- okhttp-tests/src/test/java/okhttp3/WebSocketHttpTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketWriterTest.java
- okhttp/src/main/java/okhttp3/Request.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketProtocol.java
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.java
Make sure interceptors and close reasons are validated thoroughly.
> More test coverage for web sockets edge cases.

- samples/slack/src/main/java/okhttp3/slack/SlackApi.java
> Fix an invalid HTML entity in the SlackApi Javadoc.

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
Closes: https://github.com/square/okhttp/issues/2788
> If a graceful close doesn't work, cancel the websocket.

- mockwebserver/src/main/java/okhttp3/internal/tls/HeldCertificate.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
Closes: https://github.com/square/okhttp/issues/3021
> Confirm that OkHttp verifies IP address certificates.

- okhttp-tests/src/test/java/okhttp3/CacheTest.java
- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.java
Closes: https://github.com/square/okhttp/issues/116
> Don't offer to do gzip if the request is partial.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp-tests/src/test/java/okhttp3/RequestTest.java
- okhttp/src/main/java/okhttp3/Headers.java
https://github.com/square/okhttp/issues/2842
> Forbid spaces in header names.

- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
> Remove creation of synthetic accessor method.

- okhttp/src/main/java/okhttp3/Authenticator.java
- samples/guide/src/main/java/okhttp3/recipes/Authenticate.java
Closes: https://github.com/square/okhttp/issues/2464
> Fix examples to give up if authentication fails.

- samples/guide/src/main/java/okhttp3/recipes/CheckHandshake.java
- samples/guide/src/main/java/okhttp3/recipes/CustomCipherSuites.java
It's a disgusting amount of code unfortunately.
Closes: https://github.com/square/okhttp/issues/2698
> Example on customizing cipher suites.

- okhttp-tests/src/test/java/okhttp3/CookieTest.java
- okhttp/src/main/java/okhttp3/Cookie.java
- okhttp/src/main/java/okhttp3/Headers.java
- okhttp/src/main/java/okhttp3/internal/Util.java
Closes https://github.com/square/okhttp/issues/2939
> Drop cookies that contain ASCII NULL and other bad characters.

- okhttp-tests/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.java
- okhttp-tests/src/test/java/okhttp3/internal/io/FaultyFileSystem.java
https://github.com/square/okhttp/issues/3115
> Added test for cache initialization failure and recovery.

- okhttp/src/main/java/okhttp3/Credentials.java
> Add charset support for Credentials.basic

- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
Prior to commit 084b06b48bae2b566bb1be3415b6c847d8ea3682 (OkHttp 3.4.0),
a HttpURLConnection.disconnect() in the middle of connecting caused an
infinite loop. HUC does not claim to be thread safe, but concurrent
disconnect should generally be supported (it is supported by HttpEngine)
and this bug occurred even when the disconnect() happened in the same
thread, e.g. through the CookieJar.
The infinite loop prior to that CL occurred because
- The loop in HttpURLConnectionImpl.java:418 did not check for the
disconnected state,
- {StreamAllocation,RetryAndFollowUpInterceptor}.recover() returns
true for canceled StreamAllocations/calls, but
StreamAllocation.newStream() immediately fails if already canceled.
This bug was specific to HUC and did not affect the Call API because …
> HUC regression test: disconnect in the middle of connecting.

- okhttp/src/main/java/okhttp3/EventListener.java
Related to the discussion in #270, this a class that could be used to add
Zipkin or other traces to OkHttp requests
> Strawman class for EventListener

- okhttp-tests/src/test/java/okhttp3/CallTest.java
> Remove locale dependency in CallTest

- okhttp-tests/src/test/java/okhttp3/CipherSuiteTest.java
- okhttp/src/main/java/okhttp3/CipherSuite.java
- okhttp/src/main/java/okhttp3/ConnectionSpec.java
- okhttp/src/main/java/okhttp3/TlsVersion.java
- okhttp/src/main/java/okhttp3/internal/Util.java
Closes: https://github.com/square/okhttp/issues/3173
> Handle either TLS_ or SSL_ prefixes for cipher suite names.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
Closes https://github.com/square/okhttp/issues/3252
> Don't reuse connections after an unsuccessful 'Expect: 100-continue'

- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
Closes: https://github.com/square/okhttp/issues/3243
> Expose public suffix info via an API in HttpUrl.

- benchmarks/src/main/java/okhttp3/benchmarks/ApacheHttpClient.java
- benchmarks/src/main/java/okhttp3/benchmarks/NettyHttpClient.java
- benchmarks/src/main/java/okhttp3/benchmarks/OkHttp.java
- benchmarks/src/main/java/okhttp3/benchmarks/UrlConnection.java
- checkstyle.xml
- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/DelegatingHttpsURLConnection.java
- okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java
- okhttp/src/main/java/okhttp3/Cache.java
- okhttp/src/main/java/okhttp3/internal/cache/FaultHidingSink.java
- okhttp/src/main/java/okhttp3/internal/cache2/FileOperator.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Reader.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Writer.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java
- okhttp/src/main/java/okhttp3/internal/platform/JdkWithJettyBootPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/OptionalMethod.java
- okhttp/src/main/java/okhttp3/internal/tls/DistinguishedNameParser.java
- okhttp/src/main/java/okhttp3/internal/tls/TrustRootIndex.java
- pom.xml
- samples/guide/src/main/java/okhttp3/recipes/CustomCipherSuites.java
- samples/guide/src/main/java/okhttp3/recipes/Progress.java
This allows us to put @Nullable immediately preceding the return type,
which is exactly where we want it.
> Upgrade to Checktyle 7.7.

- okhttp-tests/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
https://github.com/square/okhttp/issues/3308
> Recover from a stale coalesced connection.

- okhttp/src/main/java/okhttp3/Response.java
- okhttp/src/main/java/okhttp3/WebSocket.java
Closes: https://github.com/square/okhttp/issues/3383
Closes: https://github.com/square/okhttp/issues/3386
> Clarify documentation on closing WebSockets and Responses.

- okhttp-tests/src/test/java/okhttp3/CertificatePinnerTest.java
- okhttp/src/main/java/okhttp3/CertificatePinner.java
Closes: https://github.com/square/okhttp/issues/3324
> Match the entire pattern on certificate pinner patterns.

- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.java
https://github.com/square/retrofit/issues/2362
> Disallow Interceptor responses with no bodies.

- okhttp/src/main/java/okhttp3/RequestBody.java
> Fix code reference in Javadoc.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
https://github.com/square/okhttp/issues/270
> Added support for secure connect events.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/EventListener.java
I'm hopeful this makes the docs and behavior more clear. Let me know if it muddies the waters.
> Add more detail to dns/secure event docs; confirm it with test cases.

- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
Discovered missing test while looking at #2512
> Add missing test for MockResponse setHeaders

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/WebSocketListener.java
Follow up from comments on reviews
> minor cleanup of EventListener formatting

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
Request bytes and Header chars logged to EventListener API.
> EventListener payload bytes and header sizes in chars

- okhttp/src/main/java/okhttp3/CertificatePinner.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java
- okhttp/src/main/java/okhttp3/internal/platform/JdkWithJettyBootPlatform.java
Excluding any *impossible* scenarios - retain root cause to aid users in debugging without raising an issue.
> More debug for possible but unlikely assertion failures

- mockwebserver/src/main/java/okhttp3/internal/tls/SslClient.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
Update `MockWebServerTest#requestUrlReconstructed` to address issue #3546.
> Test Failure in MockWebServerTest

- README.md
> Update Proguard rules on README.md

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
Closes: https://github.com/square/okhttp/issues/3395
> Don't log a protocol when it is unknown.

- okhttp-tests/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp/src/main/java/okhttp3/CertificatePinner.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
Closes: https://github.com/square/okhttp/issues/3514
> Crash early if any interceptor is null.

- okhttp/src/main/java/okhttp3/CacheControl.java
- okhttp/src/main/java/okhttp3/Protocol.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.java
- okhttp/src/main/java/okhttp3/internal/http/HttpDate.java
https://github.com/square/okhttp/issues/930
> Update some comments to point at current RFCs

- okhttp-tests/src/test/java/okhttp3/CookieTest.java
- okhttp-tests/src/test/java/okhttp3/internal/publicsuffix/PublicSuffixDatabaseTest.java
- okhttp/src/main/java/okhttp3/Cookie.java
- okhttp/src/main/java/okhttp3/HttpUrl.java
- okhttp/src/main/java/okhttp3/internal/Util.java
Closes: https://github.com/square/okhttp/issues/3361
> Fix IPv6 handling for cookies

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
This is an edge case that can occur with HTTP/2. Since multiple requests
use the same connection, it's possible for one request to flag the
connection as bad during a follow-up request.
https://github.com/square/okhttp/issues/3521
> Recover from an already-allocated connection that restricts new streams.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp-tests/src/test/java/okhttp3/RecordingEventListener.java
- okhttp/src/main/java/okhttp3/EventListener.java
- okhttp/src/main/java/okhttp3/Headers.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
Just pass the Request and Response objects in directly.
> Don't summarize the request and response headers.

- README.md
> Update ProGuard suggested config.

- okhttp/src/main/java/okhttp3/Request.java
> Missing @Nullable

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/http/HttpMethod.java
> Allow request bodies for all HTTP methods except GET and HEAD

- okhttp-tests/src/test/java/okhttp3/DispatcherTest.java
- okhttp-tests/src/test/java/okhttp3/RecordingWebSocketListener.java
- okhttp/src/main/java/okhttp3/Dispatcher.java
> Do not count web sockets toward per-host limit.

- okhttp-tests/src/test/java/okhttp3/internal/http2/HpackTest.java
- okhttp/src/main/java/okhttp3/internal/http2/Hpack.java
Avoid any externally noticeable RuntimeExceptions due to bad server data
> Check for invalid index to avoid IOOBE

- benchmarks/pom.xml
- mockwebserver/pom.xml
- okcurl/pom.xml
- okhttp-android-support/pom.xml
- okhttp-apache/pom.xml
- okhttp-logging-interceptor/pom.xml
- okhttp-testing-support/pom.xml
- okhttp-tests/pom.xml
- okhttp-urlconnection/pom.xml
- okhttp/pom.xml
- pom.xml
Maven warnings and redirect output
> Cleanup travis output

- okhttp/src/main/java/okhttp3/Request.java
to note multiple headers may be removed.
> Add doc for Request.Builder.removeHeader.

- okhttp/src/main/java/okhttp3/OkHttpClient.java
Should have been part of 38d570a
> Fix Builder.proxy doc

- okhttp-tests/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
Rather than tracking how many have been received, just track whether we're
still awaiting a reply.
> Unexpected pongs shouldn't interfere with our ping interval.

- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
Otherwise these threads stick around forever. Yikes.
> Release writer threads when the connection is shut down.

- okhttp-testing-support/src/main/java/okhttp3/testing/InstallUncaughtExceptionHandlerListener.java
Blame any uncaught exceptions on the last test to run
> Dont System.exit the test runner

- README.md
> Readme: Update version, add ProGuard for Conscrypt

- okhttp/src/main/java/okhttp3/CipherSuite.java
- okhttp/src/main/java/okhttp3/ConnectionSpec.java
new restricted ciphers spec and one additional supported cipher
> Restricted ciphers

- okhttp/pom.xml
- pom.xml
Following major updates to conscrypt, or critical fixes.
> Conscrypt 1.1

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
Closes: https://github.com/square/okhttp/issues/3872
> Release the connection when an Authenticator throws an exception.

- pom.xml
http://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient
> update maven plugins and apache.httpcomponents/httpclient to 4.2.6

- README.md
- okhttp/src/main/resources/META-INF/proguard/okhttp3.pro
These can be read automatically by R8
> Embed R8/ProGuard rules in the jar

- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
https://github.com/square/okhttp/issues/4067
> Fix tests for now

- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
smaller epsilon with artificial delay inserted
> Better mock test fix

- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DohProviders.java
https://developers.cloudflare.com/1.1.1.1/dns-over-https/wireformat/
> Update cloudflare GET example

- okhttp-tests/pom.xml
- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
As reported here https://github.com/square/okhttp/issues/4094
> HTTP Logging interceptor breaks EventListener

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/RecordedRequest.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/internal/tls/SslClient.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/BootstrapDns.java
- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsOverHttpsTest.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsRecordCodecTest.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DohProviders.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/TestDohMain.java
- okhttp-sse/src/main/java/okhttp3/internal/sse/ServerSentEventReader.java
- okhttp-tests/src/test/java/okhttp3/ProtocolTest.java
- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
Also expose the handshake in the RecordedResponse.
https://github.com/square/okhttp/issues/3934
> Support client authentication in MockWebServer

- okhttp-tests/src/test/java/okhttp3/RequestTest.java
- okhttp-tests/src/test/java/okhttp3/internal/UtilTest.java
- okhttp/src/main/java/okhttp3/Request.java
- okhttp/src/main/java/okhttp3/internal/Util.java
This expands our single Object.class into a Map<Class<T>, T>.
Closes: https://github.com/square/okhttp/issues/4087
> Deluxe tags.

- okhttp/src/main/java/okhttp3/OkHttpClient.java
Also, add a couple other internal nullability cleanups.
> OkHttpClient.proxy() is nullable.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
https://github.com/square/okhttp/issues/4135
> Test for file not found in post body

- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DohProviders.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/TestDohMain.java
DOH Servers are converging on newer versions of the spec, content type negotiation is now simpler.
> DNS over HTTPS spec 13

- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DohProviders.java
Discussion from https://github.com/square/okhttp/issues/4223
> Enable chantra for DNS over HTTPS testing

- okhttp-tests/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/proxy/NullProxySelector.java
> Properly handle null as system default proxy selector (#4232)

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp-tests/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/main/java/okhttp3/Challenge.java
- okhttp/src/main/java/okhttp3/Response.java
- okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.java
> Properly parse RFC 7235 authentication headers (#4249)

- okhttp-tests/src/test/java/okhttp3/internal/platform/Jdk9PlatformTest.java
- okhttp-tests/src/test/java/okhttp3/internal/platform/PlatformTest.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
Various test utils end up showing ugly toString currently
> Add Friendly toString() to Platform

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
> Fix okHttp for RoboVM (and other Android-based runtimes)

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp-tests/src/test/java/okhttp3/MultipartBodyTest.java
- okhttp/src/main/java/okhttp3/Headers.java
for the validation part of #4283
> Fully validate inputs of Headers.of().

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/test/java/okhttp3/mockwebserver/internal/http2/Http2Server.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/http2/Header.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
> Send/Receive Headers via Http2 Frames

- okhttp/pom.xml
- okhttp/src/main/java/okhttp3/OkHttpClient.java
default `TimeUnit.MILLISECONDS` value can save coding time
> add methods overload support

- bom/pom.xml
- pom.xml
> Add maven bom

- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.java
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
Closes: https://github.com/square/okhttp/issues/4183
> Don't specify a crypto provider in HeldCertificate.

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
Reproduces https://github.com/square/okhttp/issues/4386.
> Test EventListener handling of redirected requests

- bom/pom.xml
Based on discussions in https://github.com/square/okhttp/issues/4407, remove the parent.
> Remove parent of BOM

- mockwebserver/src/main/java/okhttp3/internal/duplex/MwsDuplexAccess.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- mockwebserver/src/main/java/okhttp3/mockwebserver/internal/duplex/DuplexResponseBody.java
- okhttp-tests/src/test/java/okhttp3/DuplexTest.java
- okhttp-tests/src/test/java/okhttp3/internal/RecordingHeadersListener.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/Request.java
- okhttp/src/main/java/okhttp3/Response.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/duplex/HeadersListener.java
- okhttp/src/main/java/okhttp3/internal/duplex/HttpSink.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.java
- okhttp/src/main/java/okhttp3/internal/http2/Header.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
> Allow Requests and Responses to communicate in duplex

- okhttp-tests/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This pull request fixes typo/misspellings in tests.
> Fix typo/misspellings in tests

- okhttp-tests/src/test/java/okhttp3/WholeOperationTimeoutTest.java
Reproduces a bug where call timeout is not fired after following a redirect on a new connection.
This is the stack trace leading to timeoutExit() when redirection takes place:
```
timeoutExit:108, RealCall (okhttp3)
timeoutExit:194, OkHttpClient$1 (okhttp3)
release:358, StreamAllocation (okhttp3.internal.connection)
intercept:185, RetryAndFollowUpInterceptor (okhttp3.internal.http)
proceed:148, RealInterceptorChain (okhttp3.internal.http)
proceed:122, RealInterceptorChain (okhttp3.internal.http)
getResponseWithInterceptorChain:260, RealCall (okhttp3)
execute:94, RealCall (okhttp3)
timeoutAfterRedirectUsingNewConnection:279, WholeOperationTimeoutTest (okhttp3)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, …
```
> Test call timeout after following redirect on a new connection

- mockwebserver/pom.xml
- okcurl/pom.xml
- okhttp-android-support/pom.xml
- okhttp-apache/pom.xml
- okhttp-dnsoverhttps/pom.xml
- okhttp-hpacktests/pom.xml
- okhttp-logging-interceptor/pom.xml
- okhttp-sse/pom.xml
- okhttp-testing-support/pom.xml
- okhttp-tests/pom.xml
- okhttp-tls/pom.xml
- okhttp-urlconnection/pom.xml
- okhttp/pom.xml
- pom.xml
- samples/crawler/pom.xml
- samples/static-server/pom.xml
I used 'mvn versions:use-latest-versions' and also just a bunch of manual
fixing.
> Get the latest versions of things.

- mockwebserver/src/test/java/okhttp3/mockwebserver/RecordedRequestTest.java
- okhttp-tests/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/main/java/okhttp3/internal/Util.java
https://github.com/square/okhttp/issues/4451
> Don't crash on IPv4-mapped IPv6 addresses

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp/src/main/java/okhttp3/Headers.java
Closes: https://github.com/square/okhttp/issues/3921
> Use java.time in Headers

- okhttp/src/main/java/okhttp3/ResponseBody.java
Closes: https://github.com/square/okhttp/issues/4456
> Clarify how the response charset is determined.

- README.md
This is more about formalizing them than documenting them
> Specify OkHttp's requirements

- okhttp-tests/src/test/java/okhttp3/internal/UtilTest.java
- okhttp-tests/src/test/java/okhttp3/internal/platform/Jdk8WithJettyBootPlatformTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Jdk8WithJettyBootPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
Also remove the convenience method for throwing AssertionErrors.
> Rename JdkWithJettyBootPlatform to Jdk8WithJettyBootPlatform

- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
This should facilitate fixing https://github.com/square/okhttp/issues/4515.
Leaks are both in the tests and in the code under test.
> Mark leaking WebSocket tests

- pom.xml
https://github.com/jetty-project/jetty-alpn/blob/master/docs/version_mapping.properties
> Add Jetty-APLN profiles for Java 1.8.0_201 and 1.8.0_202

- okhttp-testing-support/src/main/java/okhttp3/internal/duplex/PipeDuplexRequestBody.java
- okhttp-tests/src/test/java/okhttp3/DuplexTest.java
- okhttp/src/main/java/okhttp3/internal/duplex/DuplexRequestBody.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
And later maybe a simple public method.
> Turn DuplexRequestBody into a marker interface.

- mockwebserver/src/test/java/okhttp3/mockwebserver/RecordedRequestTest.java
- okhttp-android-support/src/main/java/okhttp3/internal/huc/JavaApiConverter.java
- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp-tests/src/test/java/okhttp3/MultipartBodyTest.java
- okhttp/src/main/java/okhttp3/MultipartBody.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.java
Closes: https://github.com/square/okhttp/issues/4564
> Permit multipart filenames to contain non-ascii characters

- okhttp-tests/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
To fix https://travis-ci.org/square/okhttp/jobs/490938792
> Fix master build for JDK 11

- okhttp/src/main/java/okhttp3/internal/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
> Move connection.noNewStreams into the individual streams

- okhttp-tests/src/test/java/okhttp3/HeadersTest.java
- okhttp-tests/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java
- okhttp/src/main/java/okhttp3/internal/connection/ConnectInterceptor.java
- okhttp/src/main/java/okhttp3/internal/connection/ConnectionSpecSelector.java
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.java
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteDatabase.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteException.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.java
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/http/ExchangeCodec.java
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http1/Http1ExchangeCodec.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.java
Also address feedback from other exchange PRs.
> Rename HttpCodec to ExchangeCodec

- okhttp/src/main/java/okhttp3/Response.java
Same as https://github.com/square/okhttp/pull/3858 but for `Response.Builder`
> Add removeHeader docs to Response

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
Closes: https://github.com/square/okhttp/issues/4583
> Fix a bug where responses weren't closed on a late cancel

- pom.xml
https://github.com/jetty-project/jetty-alpn/blob/master/docs/version_mapping.properties
> Add Jetty-APLN profiles for Java 1.8.0_201 and 1.8.0_202 (3.12.x branch) 

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
Closes: https://github.com/square/okhttp/issues/4583
> Fix a bug where responses weren't closed on a late cancel (3.12.x branch)

- okhttp/src/main/resources/okhttp3/internal/publicsuffix/NOTICE
Closes: https://github.com/square/okhttp/issues/4569
> Credit The Public Suffix List for their awesome data.

- okhttp/src/main/java/okhttp3/WebSocket.java
Found a typo in the doc and it annoyed me enough to raise a PR :)
> Fix typo in WebSocket.close doc

- mockwebserver/src/main/java/okhttp3/mockwebserver/internal/duplex/MockDuplexResponseBody.java
- okhttp-tests/src/test/java/okhttp3/DuplexTest.java
- okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/main/java/okhttp3/OkHttpClient.java
- okhttp/src/main/java/okhttp3/RealCall.java
- okhttp/src/main/java/okhttp3/internal/Internal.java
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.java
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.java
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.java
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java
https://github.com/square/okhttp/issues/4646
Still need to figure out SSE.
> Apply whole-operation timeouts to setup of web sockets and duplex calls

- okhttp-tests/src/test/java/okhttp3/CallTest.java
Closes: https://github.com/square/okhttp/issues/4588
> Assume _anon_ cipher suites are unsupported.

- .travis.yml
Closes https://github.com/square/okhttp/issues/4712
> Run style check in Travis CI

- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
Closes: https://github.com/square/okhttp/issues/4679
> Exercise TLS with no server certificates (3.12.x branch)

- pom.xml
Based on https://github.com/square/okhttp/network/alert/pom.xml/com.puppycrawl.tools:checkstyle/open
> Checkstyle 8.18

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This addresses the following observed failure modes and reduces the flakinesss of the test:
1. On most runs, the first request is canceled before the client starts to read the response body. In some runs, it's canceled after the client starts to read the response body and the first call doesn't fail as expected.
2. The first request is sometimes canceled before the server dequeues the first mocked response. That response, which is set to send a body after a 10 second delay, is then used to respond to the second request, which triggers the 5 second test timeout.
https://github.com/square/okhttp/issues/4633
> Make recoverFromCancelReusesConnection() more deterministic

- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/connection/RouteException.java
This is available with the new minimum requirements.
> Use Throwable.addSuppressed directly

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt
read-only is better than var keyword!!
> AndroidPlatform.kt: change var to val

- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
Fixes https://github.com/square/okhttp/issues/4744
> Fix flaky recoverFromMultipleCancelReusesConnection

- okhttp/src/main/java/okhttp3/Headers.java
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
Intellij advises to use this form post JVM 1.6 as it's an intrinsic that performs as well or better
> Use intrinsic version of toArray

- okhttp-tests/src/test/java/okhttp3/CallTest.java
MockWebServer sometimes enforces the DISCONNECT_AFTER_REQUEST policy before the client executes exchange.finishRequest(). As a result, Http2Writer.flush() is called on a closed Http2Writer and throws. This causes a RequestFailed event to be emitted instead of the expected ResponseFailed.
This change enforces the de-facto sequence in most runs, where the policy is applied only after the client finishes writing the request.
Fixes https://github.com/square/okhttp/issues/4704
> Fix flaky CallTest.recoverWhenRetryOnConnectionFailureIsTrue_HTTP2

- okhttp/src/main/java/okhttp3/CacheControl.kt
> Make CacheControl properties private

- .circleci/config.yml
Following and testing
https://circleci.com/blog/how-to-handle-java-oom-errors/
https://circleci.com/docs/2.0/java-oom/
https://circleci.com/docs/2.0/env-vars/
> Adjust circleci memory

- .circleci/config.yml
https://circleci.com/gh/square/okhttp/152#artifacts/containers/0
Example link https://152-5152285-gh.circle-artifacts.com/0/home/circleci/reports/okhttp/build/reports/tests/test/classes/okhttp3.internal.http2.HttpOverHttp2Test.html
> Save gradle reports

- okhttp-testing-support/src/main/java/okhttp3/FakeSSLSession.java
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.java
- okhttp-testing-support/src/main/java/okhttp3/RecordingHostnameVerifier.java
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java
add @overide for subclass override method
> add @overide for subclass override method

- build.gradle
> Add Okio docs link for dokka linking

- build.gradle
Since the project targets java 8
> Specify jdk 8 for dokka

- build.gradle
- mockwebserver/Module.md
- okhttp-logging-interceptor/Module.md
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/package-info.kt
- okhttp-sse/Module.md
- okhttp-tls/Module.md
- okhttp/Module.md
This is what dokka uses to document packages and modules. Deleted the `package-info.kt` file as it doesn't do anything on its own, but can restore if it's still wanted
<kbd>
</kbd>
<kbd>
</kbd>
> Add Module.md files for different artifacts with module and package info

- build.gradle
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp/src/test/java/okhttp3/URLConnectionTest.java
Jesse we have replaced you with tooling!
> Error on missing fail in tests

- .circleci/config.yml
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/Util.java
- okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/Platform.kt
- okhttp/src/test/java/okhttp3/ConscryptTest.java
Cleanup version logic, introduce a minimum of Conscrypt 1.4.0 for version support
> Configure Conscrypt Trust Manager

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.java
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.java
https://github.com/square/okhttp/issues/4875
> Don't crash on retry when there are no more routes (3.x branch)

- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.java
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.java
- okhttp/src/test/java/okhttp3/CallTest.java
https://github.com/square/okhttp/issues/4875
> Don't crash on retry when there are no more routes (4.x branch)

- okhttp-tests/src/test/java/okhttp3/CallTest.java
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.java
https://github.com/square/okhttp/issues/4761
> Provide actionable advice when the exchange is non-null (3.x branch)

- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.java
- okhttp/src/test/java/okhttp3/CallTest.java
https://github.com/square/okhttp/issues/4761
> Provide actionable advice when the exchange is non-null (4.x branch)

- .travis.yml
resolve seems to break on internal deps
https://travis-ci.org/square/okhttp/jobs/518372391
> Ignore dependency:resolve failure on 3.14 branch

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/LoggingEventListener.kt
- okhttp/src/main/java-templates/okhttp3/internal/Version.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
https://travis-ci.org/square/okhttp/jobs/519425101
Broke because of multiple commits landing in master.  Spotless is strict.
> Fix merge conflicts after spotless applied

- okhttp/src/test/java/okhttp3/CallTest.java
Reproduces https://github.com/square/okhttp/issues/4915
> Test proxy disconnecting before sending response headers

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp/src/main/java/okhttp3/Cookie.kt
- okhttp/src/main/java/okhttp3/internal/InternalKt.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.kt
- okhttp/src/test/java/okhttp3/InterceptorTest.java
These are borderline terrible, but they flag in error prone and highlight in the IDE.  Putting this here for discussion only, what's the approach to getting a clean warning free Kotlin experience?
> Example Kotlin Cleanups

- mockwebserver/src/main/java/okhttp3/mockwebserver/QueueDispatcher.kt
- okhttp/src/main/java/okhttp3/CertificatePinner.kt
- okhttp/src/main/java/okhttp3/MultipartBody.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Writer.kt
Java to Kotlin tool seems to have a bug in handling doc.
> Fix Kotlin doc reference

- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
I was unable to write a test that reproduces https://github.com/square/okhttp/issues/4875 consistently, but this is the closest I got. When I run it repeatedly in IntelliJ, it fails about 1 out of 5 times.
> Reproduce NoSuchElementException in RouteSelector.next() in a test

- build.gradle
Release notes https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md
> Kotlin 1.3.31 upgrade

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/UtilKt.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.kt
Cleanup niggly java.lang usages
> Avoiding direct java.lang usage

- okhttp/src/main/java/okhttp3/Authenticator.kt
- okhttp/src/main/java/okhttp3/Cache.kt
- okhttp/src/main/java/okhttp3/HttpUrl.kt
- okhttp/src/main/java/okhttp3/MultipartBody.kt
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.kt
- okhttp/src/main/java/okhttp3/internal/http/StatusLine.kt
- okhttp/src/main/java/okhttp3/internal/http2/Hpack.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Reader.kt
- okhttp/src/main/java/okhttp3/internal/io/FileSystem.kt
- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.kt
- okhttp/src/main/java/okhttp3/internal/tls/OkHostnameVerifier.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketProtocol.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.kt
- okhttp/src/test/java/okhttp3/CertificatePinnerKotlinTest.kt
Doing a pass over with Intellij to cleanup and confirm our approach to quickfixes.
I expect most questionable is lifting return out of try etc, which I love.  Everything is an expression is a big win for me.
> Intellij cleanup

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.kt
- okhttp/src/main/java/okhttp3/Cache.kt
- okhttp/src/main/java/okhttp3/CipherSuite.kt
- okhttp/src/main/java/okhttp3/Cookie.kt
- okhttp/src/main/java/okhttp3/Response.kt
- okhttp/src/main/java/okhttp3/internal/InternalKt.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/cache2/FileOperator.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Reader.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Writer.kt
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.kt
- Replace `Math.min()` with `minOf`
- Use `0L` replace `0` when compared with a long var
> Replace Math.min() with minOf

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp/src/main/java/okhttp3/Cache.kt
- okhttp/src/main/java/okhttp3/CacheControl.kt
- okhttp/src/main/java/okhttp3/HttpUrl.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/connection/RouteDatabase.kt
- okhttp/src/main/java/okhttp3/internal/hostnames.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/main/java/okhttp3/internal/platform/Jdk8WithJettyBootPlatform.kt
Around string index/substring/contains and collection contains mostly.
> Kotlin improvements

- okhttp/src/main/java/okhttp3/HttpUrl.kt
Also replace url() with toUrl() and uri() with toUri().
I'm going to wait for for a follow-up to migrate OkHttp's own internal callers
to use vals and toUrl()/toUri().
> Adopt vals in HttpUrl

- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.kt
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.kt
- okhttp/src/main/java/okhttp3/Cookie.kt
- okhttp/src/main/java/okhttp3/HttpUrl.kt
- okhttp/src/main/java/okhttp3/ResponseBody.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.kt
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/main/java/okhttp3/internal/tls/OkHostnameVerifier.kt
- okhttp/src/test/java/okhttp3/internal/tls/HostnameVerifierTest.java
> Smattering of Kotlin stuff

- okhttp-tls/src/main/java/okhttp3/tls/HandshakeCertificates.kt
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.kt
- okhttp/src/main/java/okhttp3/Cookie.kt
- okhttp/src/main/java/okhttp3/HttpUrl.kt
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
Again, squash or not. Shouldn't matter.
> Smattering of Kotlin part 2

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.kt
- okhttp/src/main/java/okhttp3/Address.kt
- Use `apply` to simplify `MockResponse`
- And a `with` in `Address`
> Use apply to simplify MockResponse

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsRecordCodec.kt
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.kt
- okhttp/src/main/java/okhttp3/Cache.kt
- okhttp/src/main/java/okhttp3/Dispatcher.kt
- okhttp/src/main/java/okhttp3/HttpUrl.kt
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/RealCall.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/connection/ConnectInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/tls/BasicCertificateChainCleaner.kt
- okhttp/src/test/java/okhttp3/RecordingExecutor.kt
This isn't perfect but I think it's a bit more logical.
> Reorder the members of OkHttpClient

- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.kt
- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.kt
- okhttp/src/main/java/okhttp3/internal/http/RequestLine.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- Replace `!isEmpty` with `isNotEmpty`
- Replace a `StringBuilder` with `buildString` Statement
- Remove an unnecessary `!!`
> Replace !isEmpty with isNotEmpty

- README.md
- RELEASING.md
- mockwebserver/README.md
- okhttp-dnsoverhttps/README.md
- okhttp-logging-interceptor/README.md
- okhttp-sse/README.md
- okhttp-tls/README.md
- okhttp-urlconnection/README.md
Also make readmes offer artifacts with Gradle syntax
> New releasing guide.

- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
Removes deprecation suppressions and checks the result of Intellij Silent Code Cleanup action.  expecting it to compile.
Narrator: it did not.
> Kotlin Cleanup check

- okhttp/src/main/java/okhttp3/CertificatePinner.kt
- okhttp/src/main/java/okhttp3/Cookie.kt
- okhttp/src/main/java/okhttp3/Response.kt
- okhttp/src/main/java/okhttp3/Route.kt
Doing so makes it difficult to revise these APIs later
> Don't use data classes in public APIs

- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
> Silent Code Cleanup

- mockwebserver/src/main/java/okhttp3/mockwebserver/RecordedRequest.kt
> Adopt idiomatic Kotlin in RecordedRequest

- mockwebserver/src/main/java/okhttp3/mockwebserver/Dispatcher.kt
- mockwebserver/src/main/java/okhttp3/mockwebserver/QueueDispatcher.kt
Follow up of https://github.com/square/okhttp/pull/5144#issuecomment-497954889
> Use apply {} to adopt idiomatic Kotlin in Dispatcher and QueueDispatcher

- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.kt
We promise no API stability in this package.
> Remove the Kotlin migration bridges from DnsOverHttps

- CALLS.md
- CHANGELOG.md
- CONCURRENCY.md
- CONNECTIONS.md
- CONTRIBUTING.md
- EVENTS.md
- HTTPS.md
- INTERCEPTORS.md
- README.md
- RECIPES.md
- SECURITY.md
- TLS_CONFIGURATION_HISTORY.md
- WORKS_WITH_OKHTTP.md
- okhttp-logging-interceptor/README.md
- website/index.html
This way they're versioned with the code, and documentation changes
can happen atomically with code changes.
> Move docs from GitHub wiki into the main repo.

- UPGRADING_TO_OKHTTP_4.md
SAM improvements to Kotlin
Companion imports
R8 and ProGuard
> More notes for the upgrade guide

- HTTPS.md
> Add syntax highlighting to code snippets in HTTPS.md

- build.gradle
https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html
> Bump alpn versions

- build.gradle
- deploy_website.sh
- mkdocs.yml
- mockwebserver/build.gradle
- okhttp-dnsoverhttps/build.gradle
- okhttp-logging-interceptor/build.gradle
- okhttp-sse/build.gradle
- okhttp-tls/build.gradle
- okhttp-urlconnection/build.gradle
Retain the 3.x docs by doing a dirty MkDocs build
Build more Dokka projects
> Tweak the MkDocs build

- samples/guide/src/test/kotlin/okhttp3/AllMainsTest.kt
> Suppress AllMainsTest.

- docs/code_of_conduct.md
- mkdocs.yml
Source:
https://medium.com/square-corner-blog/open-source-code-of-conduct-e5c4dc56229e
> Import Square's Open Source Code of Conduct

- mockwebserver/src/test/java/okhttp3/mockwebserver/internal/http2/Http2Server.java
- okhttp-tls/src/test/java/okhttp3/tls/HandshakeCertificatesTest.java
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/test/java/okhttp3/internal/http2/MockHttp2Peer.java
From Java can be null
https://github.com/square/okhttp/issues/5223
> Allow nullable on Util.close

- okhttp/src/test/java/okhttp3/ConscryptTest.kt
Was failing here - https://circleci.com/gh/square/okhttp/3782
> Fix conscrypt tests

- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/test/java/okhttp3/OkHttpClientTest.java
> Tolerate null-hostile lists in public API

- build.gradle
> Kotlin upgrade to 1.3.41

- okhttp/src/main/java/okhttp3/internal/ws/WebSocketProtocol.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
https://www.iana.org/assignments/websocket/websocket.txt
Closes #5275
> Support new IANA WS close codes

- android-test/build.gradle
- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- build.gradle
- settings.gradle
Add tests for certificate pinner, and mockwebserver.
> Extended Android tests

- android-test/build.gradle
- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- okhttp-testing-support/src/main/java/okhttp3/RecordingEventListener.java
Test for https://github.com/square/okhttp/issues/5342
> Test Android session reuse

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
> Ensure overridden content length/type headers are logged

- build.gradle
Upgrade to latest kotlin release
> Kotlin 1.3.50

- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
Previously we tracked how many bytes we had left in a single value. With
this updatee we track the current value and the budget separately. I am
not worried about overflowing Long.MAX_VALUE.
I made this change in the process of diagnosing this:
https://github.com/square/okhttp/issues/5422
> Change the way flow control windows are tracked.

- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
We had a bug where a race between FramingSource.receive() and
FramingSource.close() could cause newly-received bytes to be
absent from the flow control window. If this happens enough then
eventually the connection will stall.
> Don't leak incoming bytes when we race incoming data and close (3.14.x branch)

- okhttp/src/main/java/okhttp3/RealCall.kt
- okhttp/src/test/java/okhttp3/InterceptorTest.java
Closes: https://github.com/square/okhttp/issues/5151
> Cancel calls on unexpected exceptions

- .circleci/config.yml
The compile target needs to run against Jdk 11
> Fix master build

- okhttp/src/main/java/okhttp3/Cache.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.java
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
Adopt TaskRunner in DiskLruCache. This one is pretty straightforward.
No scheduling and no canceling means we only enqueue work for
immediate execution.
> Make the FakeBackend a top-level type for testing task things.

- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
Closes: https://github.com/square/okhttp/issues/5151
> Cancel calls on unexpected exceptions (3.14.x branch)

- okhttp-tests/src/test/java/okhttp3/InterceptorTest.java
- okhttp/src/main/java/okhttp3/RealCall.java
Closes: https://github.com/square/okhttp/issues/5151
> Cancel calls on unexpected exceptions (3.12.x branch)

- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
https://github.com/square/okhttp/issues/5388
> If RST STREAM and END OF STREAM race, send RST STREAM (4.2.x branch)

- okhttp/src/main/java/okhttp3/internal/http2/ErrorCode.kt
ref https://tools.ietf.org/html/rfc7540#section-11.4
> Add missing HTTP/2 Error Code (SETTINGS_TIMEOUT, STREAM_CLOSED, FRAME_SIZE_ERROR)

- okhttp/src/main/java/okhttp3/internal/platform/android/AndroidSocketAdapter.kt
https://github.com/square/okhttp/issues/5587
and
https://github.com/google/conscrypt/issues/781
> Workaround AOSP conscrypt NPE

- docs/tls_configuration_history.md
- okhttp/src/main/java/okhttp3/ConnectionSpec.kt
- okhttp/src/main/java/okhttp3/EventListener.kt
- okhttp/src/main/java/okhttp3/internal/tls/BasicCertificateChainCleaner.kt
Closes: https://github.com/square/okhttp/issues/5593
> Don't use HTML entities in Markdown docs.

- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/test/java/okhttp3/OkHttpClientTest.java
Fixes https://github.com/square/okhttp/issues/5629
> Actually remove SPDY_3 when configuring OkHttpClient protocols

- docs/recipes.md
Fixing comment on the cache example
> Fixing example

- okhttp/src/main/java/okhttp3/internal/concurrent/TaskLogger.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/TestLogHandler.java
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskLoggerTest.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
This is intended to be useful in debugging and otherwise operating
OkHttp in anger.
> Debug logging for TaskRunner

- okhttp/src/main/java/okhttp3/HttpUrl.kt
- okhttp/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/test/java/okhttp3/UrlComponentEncodingTester.java
Closes: https://github.com/square/okhttp/issues/5667
> Fix a crash in HttpUrl.toUri().

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.kt
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
Closes: https://github.com/square/okhttp/issues/5199
> Un-deprecate some setters for chaining from Java

- android-test/README.md
- android-test/build.gradle
- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
Run a single request with the Play provider to confirm HTTP/2 and TLS 1.2
> Test Android with Play provider

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
This is a manual cherry-pick of 09da07c2c8981f88346adb818ce42512d9f2f288
See also the degraded connections proposal.
https://github.com/square/okhttp/issues/3146#issuecomment-471196032
> Degrade connections after a timeout (3.14.x branch)

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
- okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
This is a cherry-pick of 6a9a64c8f131b33bdd9b7077ce4e2456db0dcd19
See also the degraded connections proposal.
https://github.com/square/okhttp/issues/3146#issuecomment-471196032
> Degrade connections after a timeout (3.12.x branch)

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
https://github.com/square/okhttp/issues/5690
> Fix MockWebserver tests for Android 5.0

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
https://github.com/square/okhttp/issues/5690
> Handle Android 5.0 socket type in tests

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
```
> Task :android-test:compileDebugAndroidTestKotlin FAILED
e: okhttp/android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt: (164, 9): Unresolved reference: AssumptionViolatedException
```
> Fix missing import in Android Test

- docs/security_providers.md
- mkdocs.yml
Basic documentation for Security Providers
> Security Providers Documentation

- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.kt
Fix for https://app.circleci.com/jobs/github/square/okhttp/8574
> Handle Conscrypt decode behaviour

- okhttp-tls/src/test/java/okhttp3/tls/HandshakeCertificatesTest.java
Fix for https://app.circleci.com/jobs/github/square/okhttp/8574
> Handle conscrypt cert names

- okhttp-testing-support/src/main/java/okhttp3/testing/PlatformRule.kt
- okhttp-tls/src/test/java/okhttp3/tls/HandshakeCertificatesTest.java
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
Two test fixes when running with bouncycastle
> Fixes for bouncycastle tests

- okhttp/src/main/java/okhttp3/Dispatcher.kt
- okhttp/src/main/java/okhttp3/RealCall.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
Closes: https://github.com/square/okhttp/issues/5632
> Use different thread names if OkHttp is shaded

- .circleci/config.yml
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
- okhttp-testing-support/src/main/java/okhttp3/TestUtil.java
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/DuplexTest.java
- okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.java
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
> Add a windows executor to the build

- okhttp/src/main/java/okhttp3/RequestBody.kt
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http/StatusLine.kt
- okhttp/src/test/java/okhttp3/ConnectionCoalescingTest.java
Closes: https://github.com/square/okhttp/issues/5424
> Retry HTTP 421 exchanges on coalesced connections

- okhttp/src/test/java/okhttp3/CallTest.java
As a happy accident this was fixed by yesterday's changes to tidy up
the exchange lifecycle.
Closes: https://github.com/square/okhttp/issues/5727
> Add a test for truncated tunnel responses

- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.kt
- okhttp/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/test/java/okhttp3/internal/connection/RouteSelectorTest.java
Closes: https://github.com/square/okhttp/issues/5770
> Don't crash on a null host

- okhttp/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
https://github.com/square/okhttp/issues/5708
> Fixed flaky RealWebSocketTest.serverCloseThenClientClose().

- okhttp/src/main/java/okhttp3/internal/platform/Android10Platform.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
See #5840
google/conscrypt#821
> Catch IllegalArgumentException from Android internals [3.14.x]

- okhttp/src/main/java/okhttp3/internal/platform/Android10Platform.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
See #5840
google/conscrypt#821
> Catch IllegalArgumentException from Android internals [3.12.x]

- okhttp/src/main/java/okhttp3/Handshake.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/test/java/okhttp3/ConnectionCoalescingTest.java
Cherry-pick from master so I can release 4.4.1 with this fix.
> Allow for users who have disabled certificate checks in dev. (4.4.x branch)

- okhttp/src/main/java/okhttp3/WebSocket.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketExtensions.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.kt
- okhttp/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketExtensionsTest.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketWriterTest.java
It isn't yet enabled in the calling RealWebSocket, so this is only
visible to tests right now.
> Hook up compression in WebSocketReader and WebSocketWriter

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketExtensions.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.kt
- okhttp/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
The only thing left is to negotiate extensions, including failing the
call if the server returns unexpected extensions.
> Get compression working in RealWebSocketTest

- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/test/java/okhttp3/OkHttpClientTest.java
Any suggestions on naming (and general) are welcome.
> Make minimum outgoing web socket message compression size configurable

- mkdocs.yml
security.md and a few others were not linked
> Add missing documentation link

- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.kt
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsOverHttpsTest.java
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DohProviders.java
Fix for https://github.com/square/okhttp/issues/5917
> Fix for infinite caching in DoH

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
See https://github.com/bcgit/bc-java/issues/686
> Workaround bouncycastle random issue

- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
https://github.com/square/okhttp/issues/5657
> Confirm MockWebServer shutdown is idempotent

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
Explain our behaviour on different Android versions through the medium of interpretive testing.
> Test which TrustManager method called on Android

- okhttp/src/main/kotlin/okhttp3/internal/platform/AndroidPlatform.kt
Avoid reflection whereever possible, in this case via NetworkSecurityPolicy.
> Use Android API for NetworkSecurityPolicy

- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java
Fix for #5970
This will fix the exception when throw in Azul Zulu JVM. There is likely a fix to come from them to not throw, but this is defined in public API, so should be handled.
> UnsupportedOperationException from JDK8 252 onwards [3.12.x]

- build.gradle
- okhttp-testing-support/src/main/kotlin/okhttp3/TestUtil.kt
- okhttp/src/main/kotlin/okhttp3/internal/ws/MessageInflater.kt
- okhttp/src/test/java/okhttp3/internal/ws/MessageDeflaterInflaterTest.kt
Closes: https://github.com/square/okhttp/issues/5965
> Don't crash processing fragmented web sockets messages

- .circleci/config.yml
Workaround for https://github.com/square/okhttp/issues/5944
> Disable Windows Builds on master

- okhttp/src/main/kotlin/okhttp3/MultipartReader.kt
- okhttp/src/main/kotlin/okhttp3/internal/http1/HeadersReader.kt
- okhttp/src/main/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/test/java/okhttp3/MultipartReaderTest.kt
Still to do:
- API to get the boundary parameter from a MediaType
- API to create a MultipartReader from a ResponseBody
- Update to support RFC 2387 features?
> Multipart reader first steps

- docs/caching.md
- mkdocs.yml
All advise, welcome.  Please apply any and all relevant edits directly.
> Caching Docs [draft]

- okhttp/src/main/kotlin/okhttp3/Authenticator.kt
https://github.com/square/okhttp/issues/5725
> Document auth retries function

- okhttp/src/test/java/okhttp3/internal/http/CancelTest.kt
From https://github.com/square/okhttp/issues/6033
> Fix flaky CancelTest

- okhttp/src/test/java/okhttp3/InterceptorTest.java
From https://13521-5152285-gh.circle-artifacts.com/0/%7E/reports/okhttp/build/reports/tests/test/classes/okhttp3.InterceptorTest.html
> Cleanup stderr output

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/TlsUtil.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/Android10Platform.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/AndroidPlatform.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/Platform.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/Android10SocketAdapter.kt
- okhttp/src/test/java/okhttp3/internal/platform/PlatformTest.java
Fix for OkHttp platform issues in AndroidStudio (e.g. when running as a plugin)
https://github.com/square/retrofit/issues/3389
> Fix isAndroid check

- okhttp/src/main/java/okhttp3/internal/platform/Android10Platform.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
Fix for OkHttp platform issues in AndroidStudio (e.g. when running as a plugin)
square/retrofit#3389
> Fix isAndroid check [3.12.x]

- okhttp-tls/src/main/kotlin/okhttp3/tls/Certificates.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
Failing repeatedly in master nightly builds
https://app.circleci.com/pipelines/github/square/okhttp/3365/workflows/f6b1b06a-3141-4a7c-ae7c-aa6fc97e229f/jobs/14265
https://app.circleci.com/pipelines/github/square/okhttp/3330/workflows/7d8a2f66-2735-4daf-adcd-9620165e7b13/jobs/14069
> Fix for conscrypt error (public api change)

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Upgrade to latest release of Gradle and Kotlin
> Dependency upgrades

- samples/guide/src/main/java/okhttp3/recipes/kt/YubikeyClientAuth.kt
Sample for using hardware tokens on JVM to achieve client auth.
> Yubikey sample

- .circleci/config.yml
Failures seen here https://app.circleci.com/pipelines/github/square/okhttp/3441/workflows/e9cc045c-1a23-4290-9615-72f75fa5e42c/jobs/14709
> Fix openjsse CI

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/AnyValue.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/BitString.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerAdapter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerHeader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/certificates.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
My goal is to finish the implementation to support an ASN.1 DER encoder
and then to change okhttp-tls to no longer depend on BouncyCastle.
> Early implementation of an ASN.1 DER decoder

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/AnyValue.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/BitString.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerAdapter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerHeader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerWriter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/certificates.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
I haven't yet implemented certificate encoding
> DER encoder

- docs/https.md
This is ychimke's update, just moved to another file and copy-edited to cover
both Android and JVM handshakes.
> Document common security issues on older Android devices

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
We were throwing IllegalArgumentException or ParseException but
want to throw only ProtocolException or EOFException.
> Fix some issues discovered by simple fuzzing

- build.gradle
See https://github.com/JetBrains/kotlin/releases/tag/v1.4.10 for the release notes.
> Kotlin 1.4.10 Upgrade

- okhttp-testing-support/src/main/kotlin/okhttp3/internal/io/InMemoryFileSystem.kt
- okhttp/src/test/java/okhttp3/CacheCorruptionTest.kt
Base for some corruption tests, but currently passing.
> Cache Corruption Test

- build.gradle
Latest release appears to fix https://github.com/mojohaus/animal-sniffer/issues/70
But we may have some issues to allowlist now...
> Animal Sniffer upgrade

- build.gradle
https://www.bouncycastle.org/releasenotes.html
- Various bug fixes and performance improvements
Relevant for samples only
https://github.com/square/moshi/blob/master/CHANGELOG.md
-  Upgrade to Kotlin 1.4.0.
> Dependency bumps

- okhttp/src/main/kotlin/okhttp3/internal/Util.kt
Remove egregious println from live code.
> Remove println from code

- okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt
PKCS #1 is RSA-only
PKCS #8 is any key
> Fix docs on privateKeyPkcs8Pem() to not require RSA

- .circleci/config.yml
- build.gradle
- samples/guide/build.gradle
https://docs.gradle.org/current/userguide/toolchains.html#header
https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_toolchains.html#header
> Java Toolchain for splitting compile and CI test runner

- native-image-tests/build.gradle
- native-image-tests/src/main/kotlin/okhttp3/DotListener.kt
- native-image-tests/src/main/kotlin/okhttp3/GenerateClassList.kt
- native-image-tests/src/main/kotlin/okhttp3/RunTests.kt
- native-image-tests/src/main/kotlin/okhttp3/TestRegistration.kt
- native-image-tests/src/main/resources/META-INF/native-image/okhttp/nit/resource-config.json
- native-image-tests/src/main/resources/testlist.txt
- settings.gradle
Graal main method to run tests with minimal reflection and automatic settings.
Uses the test list in native-image-tests/src/main/resources/testlist.txt.
> Fixing n-i-t launcher

- native-image-tests/build.gradle
- native-image-tests/src/main/kotlin/okhttp3/GenerateClassList.kt
- native-image-tests/src/main/kotlin/okhttp3/RunTests.kt
- native-image-tests/src/main/resources/testlist.txt
- okhttp-brotli/src/main/kotlin/okhttp3/brotli/BrotliInterceptor.kt
- okhttp-brotli/src/main/kotlin/okhttp3/brotli/internal/brotli.kt
- okhttp-brotli/src/test/java/okhttp3/brotli/BrotliInterceptorTest.kt
Adds in tests from okhttp-brotli and okhttp-dnsoverhttps
> Additional n-i-t tests

- android-test/build.gradle
- build.gradle
Splitting out of https://github.com/square/okhttp/pull/6408 to make these separate actions
> Android dependency upgrade

- native-image-tests/build.gradle
- native-image-tests/src/main/kotlin/okhttp3/TestRegistration.kt
- okhttp/src/main/resources/META-INF/native-image/okhttp/okhttp/native-image.properties
Embed required options into okhttp jar.
> Simplify config for native image

- build.gradle
- regression-test/README.md
- regression-test/build.gradle
- regression-test/settings.gradle
- regression-test/src/androidTest/java/okhttp/regression/LetsEncryptTest.kt
- regression-test/src/androidTest/java/okhttp/regression/compare/ApacheHttpClientTest.kt
- regression-test/src/androidTest/java/okhttp/regression/compare/OkHttpClientTest.kt
- regression-test/src/main/AndroidManifest.xml
- regression-test/src/main/res/values/strings.xml
- regression-test/src/main/res/xml/network_security_config.xml
- settings.gradle
Regression Tests for Android.  Only using public APIs and externally observable behaviour.
Follow ups
- get it working for JVM also
- solve how to get it working across various versions, probably involves converting the tests back to java instead of kotlin for source compatibility.
> Regression Test Module

- native-image-tests/build.gradle
- okcurl/build.gradle
Release notes
https://www.graalvm.org/release-notes/20_3/
> Graal 20.3.0

- okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
- okhttp-tls/build.gradle
- okhttp/build.gradle
- okhttp/src/test/java/okhttp3/HttpUrlTest.java
- okhttp/src/test/java/okhttp3/MediaTypeTest.java
- okhttp/src/test/java/okhttp3/internal/connection/RouteSelectorTest.java
- okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
- okhttp/src/test/java/okhttp3/internal/tls/HostnameVerifierTest.java
Fixes from testing on Android.
> Quick Android Test Fixes

- .circleci/config.yml
- build.gradle
Fix for https://github.com/square/okhttp/issues/6351
> Fix for JDK8 ALPN

- build.gradle
- native-image-tests/build.gradle
- native-image-tests/src/main/resources/testlist.txt
- okcurl/build.gradle
Graal 21 Upgrade, also update the native image test list.
> Graal 21 Upgrade

- okhttp/src/main/kotlin/okhttp3/FormBody.kt
- okhttp/src/main/kotlin/okhttp3/HttpUrl.kt
Also fix a tiny typo in a comment
> Use === to compare encode sets

- build.gradle
https://blog.jetbrains.com/kotlin/2021/02/kotlin-1-4-30-released/
> Kotlin 1.4.30

- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/test/java/okhttp3/ChannelSocketFactory.kt
- okhttp/src/test/java/okhttp3/SocketChannelTest.kt
https://twitter.com/virus_dave/status/1358266888543997952
Failing on JDK 11, with SocketChannel instead of regular socket, unless pls extensions are disabled.
> Repro for channel hang with pls extensions disabled

- okhttp/src/test/java/okhttp3/HttpUrlTest.java
Test case related to cache corruption found in #6453
> Add test for empty scheme with delimiter

- okhttp/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
Our path building is very naive and it's possible to cause OkHttp to
create chains that are different from the chains previously verified
by the SSL engine.
Our preference is to use the platform's chain where possible. This includes
Android API 17+, which has an API that returns the actual chain that
was verified, not the (potentially larger) set of certificates served
by the server.
We should further lock down our chain processing. I'm reluctant to do
full graph building because it's a lot of ugly code and potentially
expensive. For now, a test that attempts to detect gaps between what
the TLS layer lets through and what our chain cleaner computes.
> Test interaction between pins and non-CA certificates

- okhttp/src/main/kotlin/okhttp3/RequestBody.kt
- okhttp/src/test/java/okhttp3/RequestBodyTest.kt
https://github.com/square/okhttp/issues/6609
> RequestBody for FileDescriptor

- mockwebserver-junit4/README.md
- mockwebserver-junit5/README.md
- mockwebserver/README.md
- okhttp-brotli/README.md
- okhttp-dnsoverhttps/README.md
- okhttp-logging-interceptor/README.md
- okhttp-sse/README.md
- okhttp-tls/README.md
- okhttp-urlconnection/README.md
Replace 4.9.0 with 4.9.1 in `README` files
> Update README files

- buildSrc/src/main/kotlin/deps.kt
Keeping in sync with latest Okio alpha builds.
> Okio alpha 4

- .github/workflows/build.yml
- okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
- okhttp/src/test/java/okhttp3/CallHandshakeTest.kt
- okhttp/src/test/java/okhttp3/SessionReuseTest.kt
OpenJSSE supports JSSE 11 features on JDK 8.
> Fix OpenJSSE build

- gradle/wrapper/gradle-wrapper.properties
> Gradle 7.0.2 version bump

- okhttp-urlconnection/src/main/kotlin/okhttp3/JavaNetCookieJar.kt
- okhttp/src/test/java/okhttp3/CookiesTest.java
> Avoid failing on single double quote in JavaNetCookieJar

- .github/workflows/build.yml
Try to set an optimal set of builds from 
https://en.wikipedia.org/wiki/Android_version_history
and
https://androiddistribution.io/#/
> Android CI variants

- .github/workflows/build.yml
- regression-test/build.gradle
- regression-test/src/androidTest/java/okhttp/regression/IssueReproductionTest.java
- settings.gradle.kts
Provides a clean test which is easily adaptable to reproduce failures on specific Android SDKs, devices or OkHttp versions (other than master).
> Clean Android Regression Test

- okhttp/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
Example https://github.com/square/okhttp/pull/6774/checks?check_run_id=3181054933
> Reduce flakiness of CertificatePinnerChainValidationTest

- .github/workflows/build.yml
- android-test/build.gradle
- build.gradle
- regression-test/build.gradle
[Android Gradle plugin 7.0](https://developer.android.com/studio/releases/gradle-plugin#7-0-0)
> Bump AGP to 7.0.0

- okhttp/src/main/kotlin/okhttp3/internal/platform/Jdk9Platform.kt
See https://www.oracle.com/java/technologies/javase/8u261-relnotes.html
> Activate TLSv1.3 on JDK 8

- android-test/build.gradle
- buildSrc/src/main/kotlin/deps.kt
- regression-test/build.gradle
- Extract dependencies in `:android-test` and `:regression-test` modules to `Dependencies`.
> Optimize dependencies in android modules

- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/RecordedRequest.kt
- mockwebserver-junit4/src/test/java/mockwebserver3/junit4/MockWebServerRuleTest.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- okcurl/src/main/kotlin/okhttp3/curl/Main.kt
- okhttp-brotli/src/main/kotlin/okhttp3/brotli/BrotliInterceptor.kt
- okhttp-dnsoverhttps/src/main/kotlin/okhttp3/dnsoverhttps/DnsOverHttps.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/FakeDns.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp/src/main/kotlin/okhttp3/Handshake.kt
- okhttp/src/main/kotlin/okhttp3/internal/NativeImageTestsAccessors.kt
- okhttp/src/main/kotlin/okhttp3/internal/http/StatusLine.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/Jdk9Platform.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/AndroidSocketAdapter.kt
- okhttp/src/test/java/okhttp3/HeadersKotlinTest.kt
- okhttp/src/test/java/okhttp3/KotlinDeprecationErrorTest.kt
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
- okhttp/src/test/java/okhttp3/OpenJSSETest.kt
- okhttp/src/test/java/okhttp3/RecordingExecutor.kt
- okhttp/src/test/java/okhttp3/SocketChannelTest.kt
- okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
- samples/guide/src/main/java/okhttp3/recipes/kt/YubikeyClientAuth.kt
- Remove unused imports.
- Remove redundant modifiers.
- Replace get with index invocation.
- Replace deprecated methods.
> Refine code

- mockwebserver/src/main/kotlin/mockwebserver3/internal/duplex/DuplexResponseBody.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/kotlin/okhttp3/Dns.kt
- okhttp/src/main/kotlin/okhttp3/internal/tls/TrustRootIndex.kt
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
- okhttp/src/test/java/okhttp3/SocketChannelTest.kt
Convert SAM for kotlin interfaces, an amended commit for #5947.
Tested [here](https://github.com/Goooler/okhttp/pull/5).
> Convert SAM

- mockwebserver-junit4/src/main/kotlin/mockwebserver3/junit4/MockWebServerRule.kt
- okhttp/src/main/kotlin/okhttp3/Authenticator.kt
- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/main/kotlin/okhttp3/Call.kt
- okhttp/src/main/kotlin/okhttp3/CertificatePinner.kt
- okhttp/src/main/kotlin/okhttp3/HttpUrl.kt
- okhttp/src/main/kotlin/okhttp3/Interceptor.kt
- okhttp/src/main/kotlin/okhttp3/MultipartReader.kt
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/ResponseBody.kt
- okhttp/src/main/kotlin/okhttp3/internal/publicsuffix/PublicSuffixDatabase.kt
Linked [here](https://github.com/square/kotlinpoet/pull/1141).
> Specify languages in kdoc code fragments

- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskQueue.kt
Follow-up to https://github.com/square/okhttp/pull/6779/files
> Reference the bug that's preventing an inline function

- okhttp-sse/src/main/kotlin/okhttp3/sse/internal/RealEventSource.kt
- okhttp-sse/src/test/java/okhttp3/sse/internal/EventSourceHttpTest.java
- okhttp-sse/src/test/java/okhttp3/sse/internal/EventSourceRecorder.java
- okhttp-sse/src/test/java/okhttp3/sse/internal/EventSourcesHttpTest.java
EventSource.cancel() did nothing if it was created by EventSources.processResponse.
All EventSources would continue to process buffered events rather than
breaking out sooner.
> Make EventSource.cancel() fail the call immediately

- okhttp/src/main/kotlin/okhttp3/Cookie.kt
- okhttp/src/main/kotlin/okhttp3/Dispatcher.kt
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/internal/graal/svm.kt
- samples/guide/src/main/java/okhttp3/recipes/kt/PostMultipart.kt
Tested [here](https://github.com/Goooler/okhttp/pull/19).
> Code cleanups

- build.gradle.kts
- buildSrc/src/main/kotlin/alpn.kt
- buildSrc/src/main/kotlin/artifacts.kt
- mockwebserver-deprecated/build.gradle.kts
- okhttp-bom/build.gradle.kts
- okhttp-brotli/build.gradle.kts
- okhttp-dnsoverhttps/build.gradle.kts
- okhttp-logging-interceptor/build.gradle.kts
- okhttp-sse/build.gradle.kts
- okhttp-tls/build.gradle.kts
- okhttp-urlconnection/build.gradle.kts
- okhttp/build.gradle.kts
> Simplify kts

- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/main/kotlin/okhttp3/HttpUrl.kt
- okhttp/src/test/java/okhttp3/HttpUrlTest.java
> Backport of Cache Corruption Fix

- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.java
Fixed by https://github.com/square/okhttp/pull/6919, effectively closes https://github.com/square/okhttp/issues/3638
> Confirm proxied request url is correct.

- build.gradle.kts
See square/leakcanary/pull/2234.
> Publish to S01

- .github/workflows/build.yml
- buildSrc/src/main/kotlin/deps.kt
- okhttp/build.gradle.kts
- okhttp/src/commonMain/kotlin/okhttp3/MediaType.kt
- okhttp/src/commonMain/kotlin/okhttp3/internal/-MediaTypeCommon.kt
- okhttp/src/commonTest/kotlin/okhttp3/MediaTypeGetTest.kt
- okhttp/src/commonTest/kotlin/okhttp3/MediaTypeTest.kt
- okhttp/src/jsTest/kotlin/okhttp3/MediaTypeJsTest.kt
- okhttp/src/jvmMain/kotlin/okhttp3/MediaType.kt
- okhttp/src/jvmTest/java/okhttp3/MediaTypeJavaTest.kt
- okhttp/src/jvmTest/java/okhttp3/MediaTypeJvmTest.kt
- okhttp/src/nonJvmMain/kotlin/okhttp3/MediaType.kt
Deprecated members and Charset specific functionality have
been left out of common.
Tests have been split up into common, java specific and js specific.
It also introduces some modules, but I can revert if it's premature.
> Media Type Multiplatform.

- okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp/src/jvmMain/kotlin/okhttp3/ResponseBody.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/internal.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/android/AndroidSocketAdapter.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/publicsuffix/PublicSuffixDatabase.kt
- okhttp/src/jvmTest/java/okhttp3/URLConnectionTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/Http2ConnectionTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
- okhttp/src/jvmTest/java/okhttp3/internal/tls/HostnameVerifierTest.kt
> Remove redundant UTF_8 params

- okhttp/src/jvmTest/java/okhttp3/HappyEyeballsTest.kt
https://github.com/square/okhttp/issues/506
> Add an initial test for Happy Eyeballs

- okhttp/src/commonMain/kotlin/okhttp3/CacheControl.kt
- okhttp/src/commonMain/kotlin/okhttp3/internal/-CacheControlCommon.kt
- okhttp/src/jvmMain/kotlin/okhttp3/CacheControl.kt
- okhttp/src/nonJvmMain/kotlin/okhttp3/CacheControl.kt
Now support for duration is available
> Cache control KMM completeness

- okhttp/src/jvmMain/kotlin/okhttp3/Address.kt
- okhttp/src/jvmMain/kotlin/okhttp3/Route.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/RouteSelectorTest.kt
I'm going to use this to name threads when connecting via
Happy Eyeballs.
> Create a nice toString() for Route

- okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/FastFallbackExchangeFinder.kt
- okhttp/src/jvmTest/java/okhttp3/FakeRoutePlanner.kt
- okhttp/src/jvmTest/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
This needed more test facets in TaskFaker.
I'm pretty happy with how the tests read.
> Tests for FastFallbackExchangeFinder

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/main/kotlin/mockwebserver3/SocketPolicy.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
Verifying https://github.com/square/okhttp/issues/7045
> Test to verify half close behaviour

- buildSrc/src/main/kotlin/deps.kt
- native-image-tests/build.gradle.kts
- native-image-tests/src/main/kotlin/okhttp3/PublicDatabaseTest.kt
- native-image-tests/src/main/kotlin/okhttp3/PublicSuffixDatabaseTest.kt
- native-image-tests/src/main/kotlin/okhttp3/SampleTest.kt
- native-image-tests/src/main/resources/testlist.txt
- okhttp/build.gradle.kts
- okhttp/src/jvmMain/kotlin/okhttp3/internal/graal/OkHttpFeature.kt
Includes public suffix database, and test to confirm.
Closes #7061
> Native Image Feature.

- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/FailedPlan.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/FastFallbackExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ReusePlan.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RoutePlanner.kt
- okhttp/src/jvmTest/java/okhttp3/FakeRoutePlanner.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
It will only attempt one TCP connection at a time.
> Change Fast Fallback to race TCP only

- native-image-tests/build.gradle.kts
> Native image tests build file cleanup

- .github/workflows/build.yml
https://github.com/actions/setup-java/releases/tag/v3.0.0
> Bump setup-java actions to v3

- build.gradle.kts
> Fix testconscrypt job build failure

- docs/security/security.md
Closes: https://github.com/square/okhttp/issues/6874
> Link to our signing key from our GitHub page

- .github/workflows/build.yml
PR builds failing with
```
> Could not create task ':samples:unixdomainsockets:spotlessKotlin'.
See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
> No such reference 'origin/master'
6 actionable tasks: 6 executed
```
https://github.com/square/okhttp/runs/5371455782?check_suite_focus=true
> Fix buids on PRs

- .github/workflows/build.yml
https://github.com/gradle/gradle-build-action
Ref https://github.com/detekt/detekt/pull/3723, it's really so fast to run jobs, and many other advantages.
> Use gradle-build-action on CI

- okhttp-coroutines/build.gradle.kts
Failure here https://github.com/square/okhttp/runs/5485654516?check_suite_focus=true
Fixes https://github.com/square/okhttp/issues/7147
> Fix coroutines publishing

- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/FastFallbackExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RoutePlanner.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/SequentialExchangeFinder.kt
- okhttp/src/jvmTest/java/okhttp3/FakeRoutePlanner.kt
I still need to figure out a test for this.
Closes: https://github.com/square/okhttp/issues/7186
> Prefer reusing the call connection over deferred plans

- okhttp/src/jvmTest/java/okhttp3/FastFallbackTest.kt
https://github.com/square/okhttp/issues/7186
> Add a regression test for the fast fallback crash

- okhttp/src/main/kotlin/okhttp3/internal/platform/android/AndroidSocketAdapter.kt
From https://github.com/square/okhttp/pull/7219
> Cherrypick: Fix Conscrypt NPE workaround

- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
> Avoid trivial warning for Optional in test code.

- okhttp/src/commonMain/kotlin/okhttp3/internal/-HostnamesCommon.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/-HostnamesJvm.kt
- okhttp/src/jvmTest/java/okhttp3/HttpUrlTest.kt
- okhttp/src/jvmTest/java/okhttp3/URLConnectionTest.kt
Closes: https://github.com/square/okhttp/issues/7301
> Enforce label length limits

- gradle/libs.versions.toml
This seems to work nicely with Intellij 2022.2.
So nice to get to a newer version.
> Bump AGP to 7.2.1

- build.gradle.kts
- gradle/libs.versions.toml
- okcurl/build.gradle.kts
Following https://github.com/square/okio/pull/1155
> Bump to Kotlin 1.7.10

- gradle/libs.versions.toml
- okhttp-testing-support/build.gradle.kts
- okhttp-testing-support/src/main/kotlin/okhttp3/RetryFlakesTestRule.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
- okhttp/src/jvmTest/java/okhttp3/FastFallbackTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/tls/ClientAuthTest.java
Trying out https://junit-pioneer.org/docs/retrying-test/
#fixes https://github.com/square/okhttp/issues/7207
> Rerun flaky tests

- okhttp/src/main/resources/META-INF/proguard/okhttp3.pro
(cherry picked from commit 9da841c24c3b3dabc1d9230ab2f1e71105768771)
> Extend Proguard Rules (#6792) 4.10.x

- okhttp/src/commonTest/kotlin/okhttp3/HeadersTest.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
- okhttp/src/jvmTest/java/okhttp3/EventListenerTest.java
- okhttp/src/jvmTest/java/okhttp3/HttpUrlTest.kt
- okhttp/src/jvmTest/java/okhttp3/KotlinDeprecationErrorTest.kt
- okhttp/src/jvmTest/java/okhttp3/KotlinSourceModernTest.kt
- okhttp/src/jvmTest/java/okhttp3/ResponseBodyJvmTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/HpackTest.java
- okhttp/src/jvmTest/java/okhttp3/internal/ws/WebSocketHttpTest.java
> Automated cleanup

- README.md
**Description:**
> Fixed incorrect JSON media type in README
> fix(incorrect media type) : README - issue #7439

- okhttp/src/jvmMain/kotlin/okhttp3/Headers.kt
* Use the `Date.from(Instant)` method.
> Use Date.from().

- buildSrc/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/jvm/tasks/KotlinJvmTest.kt
- okhttp/src/jvmTest/java/okhttp3/EventListenerTest.java
- okhttp/src/jvmTest/java/okhttp3/internal/http2/HpackTest.java
- okhttp/src/jvmTest/java/okhttp3/internal/ws/WebSocketHttpTest.java
Failures from https://github.com/square/okhttp/actions/runs/3660984983/jobs/6188729991
Discussion of related issue https://youtrack.jetbrains.com/issue/KT-54634
> Fix JDK 8 tests

- okhttp/src/jvmTest/java/okhttp3/CallKotlinTest.kt
> Retry Flaky CallKotlinTest 

- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
> Fix chain timeout not working on socket connecting

- okhttp/src/commonMain/kotlin/okhttp3/Request.kt
- okhttp/src/commonMain/kotlin/okhttp3/internal/-RequestCommon.kt
- okhttp/src/commonTest/kotlin/okhttp3/RequestCommonTest.kt
- okhttp/src/jvmMain/kotlin/okhttp3/Request.kt
- okhttp/src/nonJvmMain/kotlin/okhttp3/Request.kt
Added commonToString, and added tests.
> Improve KMP Request

- .github/workflows/build.yml
- gradle.properties
- settings.gradle.kts
Change from not null, to boolean with default in gradle.properties.  This makes it easier to toggle locally.
> Use settings the way god intended

- build.gradle
From https://github.com/square/okhttp/pull/7358, but with filtering.
> [4.x] Update Okio to 3.2.0

- mockwebserver-deprecated/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
- okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
- okhttp-tls/src/test/java/okhttp3/tls/HandshakeCertificatesTest.kt
- okhttp/src/jvmTest/java/okhttp3/CacheCorruptionTest.kt
- okhttp/src/jvmTest/java/okhttp3/CacheTest.java
- okhttp/src/jvmTest/java/okhttp3/CallHandshakeTest.kt
- okhttp/src/jvmTest/java/okhttp3/CallKotlinTest.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
- okhttp/src/jvmTest/java/okhttp3/ConnectionReuseTest.kt
- okhttp/src/jvmTest/java/okhttp3/DuplexTest.java
- okhttp/src/jvmTest/java/okhttp3/EventListenerTest.java
- okhttp/src/jvmTest/java/okhttp3/InsecureForHostTest.kt
- okhttp/src/jvmTest/java/okhttp3/JSSETest.kt
- okhttp/src/jvmTest/java/okhttp3/RouteFailureTest.kt
- okhttp/src/jvmTest/java/okhttp3/ServerTruncatesRequestTest.kt
- okhttp/src/jvmTest/java/okhttp3/SessionReuseTest.kt
- okhttp/src/jvmTest/java/okhttp3/SocketChannelTest.kt
- okhttp/src/jvmTest/java/okhttp3/URLConnectionTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http/CancelTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
- okhttp/src/jvmTest/java/okhttp3/internal/tls/HostnameVerifierTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/ws/WebSocketHttpTest.java
- samples/compare/src/test/kotlin/okhttp3/compare/OkHttpClientTest.kt
There's something up with ECDSA on BouncyCastle, and rather than figuring it out I've just switched to RSA signatures with that provider.
> Get more TLS stuff passing on BouncyCastle

- .github/workflows/build.yml
Flag things like https://github.com/square/okhttp/pull/7600 earlier.
> Compile all on checkjdk11

- .github/workflows/build.yml
- samples/compare/src/test/kotlin/okhttp3/compare/JavaHttpClientTest.kt
Flushes out an issue with Http Client.
> Add a CI build for JDK 19

- okhttp-testing-support/src/main/kotlin/okhttp3/CallEvent.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/ConnectionEvent.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/RecordingConnectionListener.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/RecordingEventListener.kt
- okhttp/api/okhttp.api
- okhttp/src/jvmMain/kotlin/okhttp3/ConnectionListener.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/jvmTest/java/okhttp3/ConnectionListenerTest.kt
Refactor `CallEvent.closes` and take same approach for ConnectionEvent.
> Check for matching ConnectionEvent

- okhttp-testing-support/src/main/kotlin/okhttp3/RecordingConnectionListener.kt
- okhttp/api/okhttp.api
- okhttp/src/jvmMain/kotlin/okhttp3/ConnectionListener.kt
> Remove RealCall from ConnectionListener

- .github/renovate.json
> Pin org.junit-pioneer:junit-pioneer

- .github/workflows/build.yml
See two in details
But only one in popup
> Update test report names

- CHANGELOG.md
- README.md
- mockwebserver-junit4/README.md
- mockwebserver-junit5/README.md
- mockwebserver/README.md
- okhttp-android/README.md
- okhttp-brotli/README.md
- okhttp-dnsoverhttps/README.md
- okhttp-logging-interceptor/README.md
- okhttp-sse/README.md
- okhttp-tls/README.md
- okhttp-urlconnection/README.md
#fixes https://github.com/square/okhttp/issues/7788
> Update Release version

- okhttp/api/okhttp.api
- okhttp/src/jvmMain/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/-UtilJvm.kt
- okhttp/src/jvmTest/java/okhttp3/internal/UtilTest.kt
#fixes https://github.com/square/okhttp/issues/5322
> Add Kotlin Duration overrides

- gradle/libs.versions.toml
- okhttp-android/build.gradle.kts
- okhttp-android/src/test/kotlin/okhttp3/android/RobolectricClientBuilderTest.kt
Breaking up larger okhttp-android test.
> Add a robolectric test to android-test

- okhttp/build.gradle.kts
Another attempt to fix https://github.com/square/okhttp/actions/runs/5099519647/jobs/9167263082
> Fix doc publishing

- okhttp-idna-mapping-table/src/main/kotlin/okhttp3/internal/idn/MappedRange.kt
- okhttp-idna-mapping-table/src/main/kotlin/okhttp3/internal/idn/MappingTables.kt
- okhttp-idna-mapping-table/src/main/kotlin/okhttp3/internal/idn/SimpleIdnaMappingTable.kt
- okhttp-idna-mapping-table/src/test/kotlin/okhttp3/internal/idn/MappingTablesTest.kt
- okhttp/src/commonMain/kotlin/okhttp3/internal/idn/IdnaMappingTable.kt
- okhttp/src/jvmTest/java/okhttp3/internal/idn/IdnaMappingTableTest.kt
This implements an optimization suggested for the IdnaMappingTable described in https://github.com/square/okhttp/pull/7789#discussion_r1181021018
> Add new inline mapping strategy to IdnaMappingTable

- native-image-tests/src/main/kotlin/okhttp3/PublicSuffixDatabaseTest.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/publicsuffix/PublicSuffixDatabase.kt
- okhttp/src/jvmTest/java/okhttp3/internal/publicsuffix/PublicSuffixDatabaseTest.kt
#fixes https://github.com/square/okhttp/issues/7749
> Make Public Suffix Database failures permanent

- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
Cherry pick of https://github.com/square/okhttp/pull/7954
> [4.x] Avoid hanging after error race condition

- settings.gradle.kts
Follow up to https://github.com/square/okhttp/pull/7918
> Tidy up settings IntelliJ check

- gradle/libs.versions.toml
> Revert "Update biz.aQute.bnd to v7 (major)"

- buildSrc/build.gradle.kts
> Revert "Update dependency biz.aQute.bnd:biz.aQute.bnd.gradle to v7"

- android-test/src/androidTest/java/okhttp/android/test/alpn/AlpnOverrideTest.kt
Testing for https://slack-chats.kotlinlang.org/t/16018419/hello-wave-i-am-currently-using-ktor-in-an-android-context-m#ee98da36-ea7a-4431-8ddc-d5204d244b4f
> Testing with ALPN Override

- android-test/build.gradle.kts
- okhttp-android/build.gradle.kts
- settings.gradle.kts
Fixing failures from https://github.com/square/okhttp/pull/8156
> Fix android test targetSdk

- okhttp/api/okhttp.api
- okhttp/src/main/kotlin/okhttp3/ExperimentalOkHttpApi.kt
I'm intending to use this to release OkHttp 5.0 before all of the new APIs are final.
> Introduce @ExperimentalOkHttpApi

- .github/workflows/build.yml
https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
master
PR
> Faster github runners

- okhttp/src/main/kotlin/okhttp3/Cache.kt
> Docs for exclusive Cache access

- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
Fixes https://github.com/square/okhttp/issues/8201
> Expand docs for callTimeoutMillis

- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/MockResponse.kt
- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/MockWebServer.kt
- okcurl/src/main/kotlin/okhttp3/curl/Main.kt
- okhttp-sse/src/main/kotlin/okhttp3/internal/sse/RealEventSource.kt
- okhttp-sse/src/main/kotlin/okhttp3/internal/sse/ServerSentEventReader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/HandshakeCertificates.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/InsecureExtendedTrustManager.kt
- okhttp-urlconnection/src/main/kotlin/okhttp3/JavaNetCookieJar.kt
- okhttp/src/main/kotlin/okhttp3/internal/Util.kt
- okhttp/src/main/kotlin/okhttp3/internal/hostnames.kt
- okhttp/src/main/kotlin/okhttp3/internal/internal.kt
This reverts commit 710bdc14472bdd1fa8e570b165d29fcbb58b2adb.
> Revert "[4.x] Avoid exposing internal functions and properties (#8137)"

- okhttp/src/main/kotlin/okhttp3/Protocol.kt
Just the symbol, not the protocol.
> Put Protocol.HTTP_3 into the public API

- container-tests/src/test/java/okhttp3/containers/BasicLoomTest.kt
Follow up comments to https://github.com/square/okhttp/pull/8289#discussion_r1551514057
> Comments on loom test

- .devcontainer/devcontainer.json
- .vscode/settings.json
- settings.gradle.kts
Not critical, but useful for occasional on the fly changes in a PR.
> Support codespaces

- okhttp/src/main/kotlin/okhttp3/internal/-UtilCommon.kt
- okhttp/src/main/kotlin/okhttp3/internal/-UtilJvm.kt
- okhttp/src/test/java/okhttp3/ResponseBodyJvmTest.kt
> Fix UTF-32 BOM inspired by  pr#8403 

- README.md
Address request to add documentation on limitations
fixes #5852
> Update README.md to describe philosophy

- build.gradle.kts
- okcurl/build.gradle.kts
Avoid this failure https://github.com/square/okhttp/actions/runs/12443850241/job/34743513329
> Build native-image on JDK 11+

- docs/works_with_okhttp.md
From https://github.com/square/okhttp/issues/8188#issuecomment-2579744100
> Add okhttp-spring-boot to works_with_okhttp.md

- okhttp/src/main/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/test/java/okhttp3/internal/http/SocketFailureTest.kt
Cherry pick of https://github.com/square/okhttp/pull/8759
> [4.x] Read response even if failed sending request headers

- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Challenge.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Cookie.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Dispatcher.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Headers.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/HttpUrl.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-HeadersCommon.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilCommon.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilJvm.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http/HttpHeaders.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Hpack.kt
- okhttp/src/jvmTest/kotlin/okhttp3/SocksProxy.kt
closes #8752 
Also changed some collection constructor parameters.
> Modify the implementation of readonly list/set

- okhttp/src/jvmTest/kotlin/okhttp3/CallTest.kt
> Add test for multiple 100 responses

- build.gradle.kts
- gradle/libs.versions.toml
- native-image-tests/build.gradle.kts
- okhttp-brotli/build.gradle.kts
- okhttp-dnsoverhttps/build.gradle.kts
- okhttp-java-net-cookiejar/build.gradle.kts
- okhttp-logging-interceptor/build.gradle.kts
- okhttp-sse/build.gradle.kts
- okhttp-testing-support/build.gradle.kts
- okhttp-tls/build.gradle.kts
- okhttp-urlconnection/build.gradle.kts
- okhttp/build.gradle.kts
> Drop the findbugs dependency

- gradle/libs.versions.toml
- okcurl/build.gradle.kts
- samples/static-server/build.gradle.kts
Required for Gradle 9 compatibility as well.
> Switch to maintained Shadow plugin

- buildSrc/src/main/kotlin/Osgi.kt
- okhttp/build.gradle.kts
This introduces a hacky workaround to a BND bug:
https://github.com/bndtools/bnd/issues/6590
> Get the OSGi plugin to work with Kotlin/Multiplatform

- CHANGELOG.md
The most recent versions had the wrong year in the changelog
> Fix some dates in changelog

- native-image-tests/build.gradle.kts
> Remove Graal init tracing

- mockwebserver/README.md
Closes: https://github.com/square/okhttp/issues/8920
> Update code samples for mockwebserver3

- okcurl/README.md
- okcurl/build.gradle.kts
- okcurl/okcurl
Addressing https://github.com/square/okhttp/issues/8945
> Fix okcurl shell command

- .github/workflows/build.yml
- android-test-app/build.gradle.kts
Run lint and assembleRelease to flush out issues.
Also androidBuild doesn't affect loading this module now, so remove from github workflows.
> Test Android release build

- okhttp/okhttp3.pro
Not needed since this is jvmMain specific now.
> Remove openjsse from proguard file

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/main/kotlin/mockwebserver3/internal/MockWebServerSocket.kt
- mockwebserver/src/test/java/mockwebserver3/internal/http2/Http2Server.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/internal/duplex/MockSocketHandler.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/InsecureExtendedTrustManager.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilJvm.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/BufferedSocket.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/ws/WebSocketWriter.kt
- okhttp/src/jvmTest/kotlin/okhttp3/CallTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/connection/ConnectionPoolTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http/HttpUpgradesTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http2/Http2ConnectionTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/ws/RealWebSocketTest.kt
I'm starting to push Okio's socket throughout OkHttp, and it turns out what I usually want is a BufferedSocket instead.
> New BufferedSocket class

- .github/workflows/build.yml
- android-test-app/proguard-rules.pro
- android-test-app/src/androidTest/kotlin/okhttp/android/testapp/IdnaTest.kt
Debugging https://github.com/square/okhttp/issues/8574
```
assertEquals("xn--n3h.net", "https://☃.net/robots.txt".toHttpUrl().host)
```
```
-whyareyoukeeping class okhttp3.internal.idn.IdnaMappingTable {
*;
}
```
> Add a test of keep rules

- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.kt
covers https://github.com/square/okhttp/issues/4698
> Add test that covers MockWebServer and URLConnection with 100-Continue

- README.md
From https://github.com/square/okhttp/pull/8767
> Fix comments from modules PR

- okhttp/api/android/okhttp.api
- okhttp/api/jvm/okhttp.api
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Request.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/RequestBody.kt
- okhttp/src/jvmTest/kotlin/okhttp3/RequestBodyTest.kt
Follow up from https://github.com/square/okhttp/pull/9107
> Add RequestBody.sha256()

- okhttp-brotli/src/main/kotlin/okhttp3/brotli/Brotli.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/CompressionInterceptor.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Gzip.kt
This doesn't have any impact on compatibility.
> Put Brotli and Gzip in top-level files
