square/okhttp

- okhttp/src/test/java/okhttp3/RequestTest.java
There is currently no test coverage for it.
> Exercise overload of RequestBody.create() that takes a ByteString

- build.gradle
Because
```
> Task :okhttp:compileJava
/Users/yuri/workspace/okhttp/okhttp/src/main/java/okhttp3/internal/Util.java:233: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
break;
^
Please report this at https://github.com/google/error-prone/issues/new and include the following:
error-prone version: 2.3.3
BugPattern: Finally
Stack Trace:
java.lang.NoSuchFieldError: com/sun/tools/javac/tree/JCTree$JCBreak.label
at com.google.errorprone.bugpatterns.Finally$FinallyJumpMatcher.<init>(Finally.java:171)
at com.google.errorprone.bugpatterns.Finally.matchBreak(Finally.java:79)
at com.google.errorprone.scanner.ErrorProneScanner$$Lambda$634.00000000315E1010.process(Unknown Source)
at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.jav …
```
> Avoid errorprone in JDK12

- okhttp/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
- okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
```
> Task :okhttp:test
okhttp3.internal.tls.CertificatePinnerChainValidationTest > unrelatedPinnedLeafCertificateInChain FAILED
java.security.KeyStoreException: Key protection algorithm not found: java.security.KeyStoreException: Certificate chain is not valid
at java.base/sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:696)
at java.base/sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:593)
at java.base/sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111)
at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1167)
at okhttp3.tls.internal.TlsUtil.newKeyManager(TlsUtil.kt:85)
at okhttp3.internal.tls.CertificatePinnerChainValidationTest.newServerSocketFactory(CertificatePinnerChainValidationTest.java:352)
at …
```
> Tests working with JDK12

- .circleci/config.yml
- .travis.yml
https://travis-ci.org/square/okhttp/jobs/518468747
```
20:07:51:343 [ERROR] Failed to execute goal on project okhttp-testing-support: Could not resolve dependencies for project com.squareup.okhttp3:okhttp-testing-support:jar:3.14.2-SNAPSHOT: Failure to find com.squareup.okhttp3:okhttp:jar:3.14.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]
20:07:51:357 [ERROR] 
20:07:51:358 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
20:07:51:360 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
20:07:51:362 [ERROR] 
20:07:51:362 [ERROR] For more information …
```
> Fix 3.14 snapshot builds in Travis after release

- .travis.yml
Fixes build on development versions by installing the okhttp-testing-support jar locally
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.691 s
[INFO] Finished at: 2019-04-24T20:23:16+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project okhttp-testing-support: Could not resolve dependencies for project com.squareup.okhttp3:okhttp-testing-support:jar:3.14.2-SNAPSHOT: Could not find artifact com.squareup.okhttp3:okhttp:jar:3.14.2-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```
> 3.14.x branch fix for travis

- okhttp-testing-support/src/main/java/okhttp3/RecordingHostnameVerifier.java
When connections are established concurrently, verify() sometimes throws a `java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0` because of unsynchronized access to the `calls` list.
> Fix race condition in RecordingHostnameVerifier

- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This test sometimes throws an IllegalArgumentException when SynchronousQueue.add() is called before or between the calls to SynchronousQueue.poll().
> Fix IllegalArgumentException in responseHeadersAfterGoaway test

- .travis.yml
No need to build all here given progress towards CircleCI.
> Travis CI builds in JDK 8 only

- okhttp/src/main/java/okhttp3/HttpUrl.kt
Add documentation for the `HttpUrl.newBuilder()` method indicating that initial values are read from the existing URL, and for `HttpUrl.Builder.scheme` indicating the legal values for the `scheme` parameter
> Increase documentation of HttpUrl.Builder

- okhttp-tests/src/test/java/okhttp3/MultipartBodyTest.java
- okhttp/src/main/java/okhttp3/MultipartBody.java
This commit is partially cherry-picked to include only relevant part of the fix
> Permit multipart filenames to contain non-ascii characters

- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
This invariant was pointed out in this PR:
https://github.com/square/okhttp/pull/4611/files
> Assume the route is non-null on HTTP 407 responses

- okhttp/build.gradle
This causes the generated pom.xml file to scope that dependency wrong.
<dependency>
<groupId>com.squareup.okio</groupId>
<artifactId>okio</artifactId>
<version>2.2.2</version>
<scope>test</scope>
</dependency>
> Don't specify Okio as a testImplementation

- mockwebserver/src/main/java/okhttp3/mockwebserver/RecordedRequest.kt
- okhttp/src/main/java/okhttp3/Cache.kt
- okhttp/src/main/java/okhttp3/Handshake.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/test/java/okhttp3/ConscryptTest.kt
I'm using DeprecationLevel.WARNING because I can't make the test
work otherwise:
https://stackoverflow.com/questions/56102107/suppress-deprecationlevel-error-in-kotlin
> Adopt idiomatic Kotlin in Handshake

- .circleci/config.yml
Ignore gh-pages for now
So much fail... https://circleci.com/gh/square/okhttp/2013
Longer term may be needed?
https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
https://github.com/DevProgress/onboarding/wiki/Using-Circle-CI-with-Github-Pages-for-Continuous-Delivery
> Ignore gh-pages branch in circleci

- .travis.yml
Build only when we actually want a snapshot built as part of .buildscript/deploy_snapshot.sh
> Build in Travis CI only on master

- okhttp/src/main/java/okhttp3/internal/UtilKt.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt
I also had a quick look at `android.os.Build.VERSION.SDK_INT` usages, and I found the following two usages, but I don't know if they could be simplified or if they were left on purpose:
https://github.com/square/okhttp/blob/fbfb5f84612d416c5977f4dd312991f36d3bb0f8/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt#L56-L60
https://github.com/square/okhttp/blob/fbfb5f84612d416c5977f4dd312991f36d3bb0f8/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt#L377-L403
> Fix #5057: Remove unnecessary `isAndroidGetsocknameError` function

- okhttp/src/main/java/okhttp3/ConnectionSpec.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
This is a singleton, although not documented as such. The use of a function allows generics to play nice.
Once we're API 24+ we can use `Comparator.naturalOrder()`
> Use Kotlin stdlib natural order comparator

- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
Otherwise we end up making multiple calls to retryCurrentRoute()
and if it returns true then false we can fail to find a route on
a retry.
Closes: https://github.com/square/okhttp/issues/4875
> Lock in a route in hasRouteToTry()

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetAuthenticator.kt
- okhttp/src/main/java/okhttp3/Cache.kt
- okhttp/src/main/java/okhttp3/RealCall.kt
- okhttp/src/main/java/okhttp3/Request.kt
- okhttp/src/main/java/okhttp3/Response.kt
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.kt
- okhttp/src/main/java/okhttp3/internal/connection/ConnectInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.kt
- okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.kt
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/main/java/okhttp3/internal/http/RequestLine.kt
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/RecordingExecutor.kt
- okhttp/src/test/java/okhttp3/RequestTest.java
- define `@get:JvmName(...)` for the following vals in constructor instead of passing `builder: Builder`.
- `url: HttpUrl`
- `method: String`
- `headers: Headers`
- `body: RequestBody?`
- `fun url(): HttpUrl`
- `fun method(): String`
- `fun headers(): Headers`
- `fun body(): RequestBody?`
- `fun cacheControl(): CacheControl`
- clean up code where `()`(parentheses) is unnecessarily used.
> Use idiomatic Kotlin in Request.kt

- okcurl/src/main/java/okhttp3/curl/Main.kt
- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.kt
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-sse/src/main/java/okhttp3/internal/sse/RealEventSource.kt
- okhttp-sse/src/main/java/okhttp3/sse/EventSources.kt
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetAuthenticator.kt
- okhttp/src/main/java/okhttp3/Cache.kt
- okhttp/src/main/java/okhttp3/Response.kt
- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.kt
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http/StatusLine.kt
- okhttp/src/main/java/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/ConscryptTest.kt
- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
- define `@get:JvmName(...)` for the following vals in constructor instead of passing `builder: Builder`.
- `request: Request`
- `protocol: Protocol`
- `message: String`
- `code: Int`
- `handshake: Handshake?`
- `headers: Headers`
- `body: ResponseBody?`
- `networkResponse: Response?`
- `cacheResponse: Response?`
- `priorResponse: Response?`
- `sentRequestAtMillis: Long`
- `receivedResponseAtMillis: Long`
- `exchange: Exchange?`
- `fun request(): Request`
- `fun protocol(): Protocol`
- `fun message(): String`
- `fun code(): Int`
- `fun handshake(): Handshake?`
- `fun headers(): Headers`
- `fun body(): ResponseBody?`
- `fun networkResponse(): Response?`
- `fun cacheResponse(): Response?`
- `fun priorResponse(): Response?`
- `fun …
> Idiomatic Kotlin for Response.kt

- SECURITY.md
Copied from  okhttp/BUG-BOUNTY.md
Seems to be a standard location e.g.
https://github.com/electron/electron/blob/master/SECURITY.md
https://github.com/standard/standard/blob/master/SECURITY.md
> Add githubs security policy

- okhttp/src/main/java/okhttp3/Dispatcher.kt
- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
This breaks Kotlin source compatibility in a small way that shouldn't be too
difficult for developers to figure out and fix.
> Use vars in Dispatcher.

- okhttp/src/main/java/okhttp3/ConnectionSpec.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
Cont. #5115 
- define the following vals in constructor instead of passing `builder: Builder`.
- `@get:JvmName("isTls") val isTls: Boolean`
- `@get:JvmName("supportsTlsExtensions") val supportsTlsExtensions: Boolean`
- `private val cipherSuitesAsString: Array<String>?`
- `private val tlsVersionsAsString: Array<String>?`
- `fun cipherSuites(): List<CipherSuite>?`
- `fun tlsVersions(): List<TlsVersion>?`
- clean up code where `()`(parentheses) is unnecessarily used.
> Idiomatic Kotlin in ConnectionSpec.kt

- okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.kt
- define the following vals in constructor instead of passing `builder: Builder`.
- `@get:JvmName(...)` val
- `client: OkHttpClient`
- `url: HttpUrl`
- `includeIPv6: Boolean`
- `post: Boolean`
- `resolvePrivateAddresses: Boolean`
- `resolvePublicAddresses: Boolean`
- `private` val
- `systemDns: Dns`
- `bootstrapDnsHosts: List<InetAddress>?`
- `fun client(): OkHttpClient`
- `fun url(): HttpUrl`
- `fun includeIPv6(): Boolean`
- `fun post(): Boolean`
- `fun resolvePrivateAddresses(): Boolean`
- `fun resolvePublicAddresses(): Boolean`
> Idiomatic Kotlin in DnsOverHttps.kt

- okhttp-tls/src/main/java/okhttp3/tls/HandshakeCertificates.kt
- define `@get:JvmName(...)` for the following vals in constructor.
- `keyManager: X509KeyManager`
- `trustManager: X509TrustManager`
- `fun keyManager(): X509KeyManager`
- `fun trustManager(): X509TrustManager`
- `fun sslSocketFactory(): SSLSocketFactory`
- `fun sslContext(): SSLContext`
> Idiomatic Kotlin in HandshakeCertificates

- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.kt
- okhttp-tls/src/main/java/okhttp3/tls/internal/TlsUtil.kt
- okhttp/src/test/java/okhttp3/CertificatePinnerKotlinTest.kt
- define `@get:JvmName(...)` for the following vals in constructor.
- `keyPair: KeyPair`
- `certificate: X509Certificate`
- `fun certificate(): X509Certificate`
- `fun keyPair(): KeyPair`
- clean up code where `()`(parentheses) is unnecessarily used.
- use `check(...)` instead of `require(...)` in `HeldCertificate#privateKeyPkcs1Pem()`
> Idiomatic Kotlin in HeldCertificate.kt

- okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
- okhttp/src/main/java/okhttp3/Request.kt
Previously it unconditionally showed tags even if empty and would not show headers.
> Beef up Request's toString

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.kt
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
Also track OkHttp 3.14.x in KotlinSourceCompatibilityTest. This shouldn't
have been updated to use new APIs.
> Fix Kotlin idioms in MockResponse. Headers and Trailers should be vals.

- UPGRADING_TO_OKHTTP_4.md
- okcurl/src/main/java/okhttp3/curl/Main.kt
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-logging-interceptor/src/main/java/okhttp3/logging/LoggingEventListener.kt
- okhttp/src/main/java/okhttp3/Authenticator.kt
- okhttp/src/main/java/okhttp3/Dispatcher.kt
- okhttp/src/main/java/okhttp3/Dns.kt
- okhttp/src/main/java/okhttp3/EventListener.kt
- okhttp/src/main/java/okhttp3/Interceptor.kt
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/test/java/okhttp3/KotlinSourceCompatibilityTest.kt
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
The ReplaceWith() on these doesn't work well.
For interceptors I expect the need to be common enough that I'm making these
new APIs that we'll keep going forward. This is for both creating interceptors
directly and as arguments to addInterceptor() and addNetworkInterceptor().
> Remove most of the SAM bridges

- okhttp/src/main/java/okhttp3/Call.kt
- okhttp/src/test/java/okhttp3/CallKotlinTest.kt
Closes: https://github.com/square/okhttp/issues/5161
> Fix the visibility of Call.clone() called from Kotlin

- UPGRADING_TO_OKHTTP_4.md
- okhttp/src/main/java/okhttp3/RequestBody.kt
- okhttp/src/main/java/okhttp3/Response.kt
- okhttp/src/main/java/okhttp3/ResponseBody.kt
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
When the returned value remembers what it was created with, we use as()
Closes: https://github.com/square/okhttp/issues/5177
> Use asX() instead of toX() when a view is returned

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver/src/test/java/okhttp3/mockwebserver/MockWebServerTest.java
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
Fixes #5208 
Previously in OkHttp3, takeRequest(...) returns RecordedRequest?.
ref. [takeRequest(timeout: Long, unit: TimeUnit) in 3.14.2](https://github.com/square/okhttp/blob/parent-3.14.2/mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.java#L308)
> Change return type of MockWebServer#takeRequest(...) to nullable to maintain backward compatibility in OkHttp4.0

- okhttp/src/main/java/okhttp3/Response.kt
- okhttp/src/test/java/okhttp3/ResponseTest.java
Fixes https://github.com/square/okhttp/issues/5209
Previously in OkHttp3, status code == 0 was acceptable.
ref. [status code validity check in 3.14.2](https://github.com/square/okhttp/blob/parent-3.14.2/okhttp/src/main/java/okhttp3/Response.java#L453)
> Allow users to set status code 0 in Response to maintain backward compatibility in OkHttp4.0

- okhttp/src/main/java/okhttp3/internal/http/HttpMethod.kt
These methods are used by some popular 3rd party SDKs.
> Retain binary-compatibility in okhttp3.internal.HttpMethod

- build.gradle
JDK 12+ is where it currently is unsupported.
> Run error-prone on JDK 11

- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Clients should be clean after use, not just from idle connections.
> OkHttpClientTestRule check connectionCount instead of idle

- .circleci/config.yml
Leaving checks on JDK 8 now, for baseline etc.  There is some unknown split for users between
JDK8 - no alpn, http/1.1
JDK8 with alpn-boot - http/2
JDK9+
Seems simpler to run with JDK11 on branch PRs.  JDK8 is probably most common in real world, but doesn't test out http/2.
> Prefer JDK 11 for tests

- .travis.yml
- build.gradle
This brings down `:okhttp:test` (the biggest bottle neck) time on my local machine from ~2m11s to ~39s.
Build scans:
* Without parallelization: https://scans.gradle.com/s/nmjkdjflng4o4
* With parallelization: https://scans.gradle.com/s/3oebsmkfwetiy
> Parallelize tests based on available processors

- .circleci/config.yml
- build.gradle
Seems to resolve JDK9 modules related warnings
https://circleci.com/gh/square/okhttp/3973
```
> Task :mockwebserver:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/root/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.60/bd47ad3bd14b8e82595c7adaa143501e60842a84/bcprov-jdk15on-1.60.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
> Bouncy castle upgrade

- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
Relates to
```
* What went wrong:
A problem occurred evaluating project ':android-test'.
> Failed to apply plugin [id 'com.android.library']
> Minimum supported Gradle version is 5.4.1. Current version is 5.4. If using the gradle wrapper, try editing the distributionUrl in /Users/yuri/.gradle/daemon/5.4/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip
```
> Gradle Wrapper 5.5

- okhttp/src/main/java/okhttp3/ConnectionSpec.kt
- okhttp/src/test/java/okhttp3/ConnectionSpecTest.java
Fix #5280 
To be compatible with OkHttp3, OkHttp4.0 doesn't use non-null assertion.
> Avoid using non-null assertion in ConnectionSpec

- .travis.yml
Addressing PR failures https://travis-ci.org/square/okhttp/builds/563227932?utm_source=github_status&utm_medium=notification
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```
> TravisCI updates

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/LoggingEventListener.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
- okhttp-testing-support/src/main/java/okhttp3/ClientRuleEventListener.kt
- okhttp/src/main/java/okhttp3/EventListener.kt
- okhttp/src/main/java/okhttp3/internal/connection/RouteSelector.kt
- okhttp/src/test/java/okhttp3/DuplexTest.java
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/RecordingEventListener.java
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- samples/guide/src/main/java/okhttp3/recipes/PrintEvents.java
- samples/guide/src/main/java/okhttp3/recipes/PrintEventsNonConcurrent.java
Since proxies are either a no-op, or a real wild west of oh-my-god what the hell were the network admins thinking, log the events around proxies.
> Add proxy event logging

- .travis.yml
Two changes
1) Externally - disabled here https://travis-ci.org/square/okhttp/settings
2) Travis config avoids assemble task
> Avoid gradle assemble in Travis

- docs/interceptors.md
when `chain.proceed(request)` is called more than once
> Mention response body must be closed in interceptors

- build.gradle
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/conscrypt/05b7227B9to/QxWewCTMCgAJ
> We're pleased to announce that we've released Conscrypt 2.2.1.  This release includes the following notable changes:
> 
> == AES-GCM-SIV ==
> 
> We've added support for the AES-GCM-SIV AEAD construction, a nonce-misuse resistant AEAD, under the identifier AES/GCM-SIV/NoPadding.  For more information on what it is and when you might want to use it, we recommend you read Adam Langley's discussion at https://www.imperialviolet.org/2017/05/14/aesgcmsiv.html.
> 
> == Other Changes ==
> 
> * Added an implementation of available() for SSLSocket's InputStream and fixed the existing implementation in the engine-based socket
> * Improved compatibility with Android Keystore keys
> * Fixed …
> Conscrypt 2.2.1 release

- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/test/java/okhttp3/ConnectionCoalescingTest.java
https://github.com/square/okhttp/issues/3308
> Recover from a coalesced connection that immediately goes unhealthy.

- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/test/java/okhttp3/OkHttpClientTest.java
We are able to access the SSLSocketFactory from the OkHttpClient but not the TrustManager used. Since there is no way to recover the used trust manager from the socket factory, we are adding explicit accessors.
> Add TrustManager accessor to OkHttpClient.

- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
If container aggressively interrupts the RealConnectionPool cleanup thread, then take notice to avoid waiting 60 seconds for daemon thread to cleanup normally.  However leave things in a sane state, so next connection established will restart it, and OkHttp will noisily log if this is done improperly without closing connections.
Related to https://github.com/square/okhttp/issues/3957 and Maven which violently interrupts daemon threads and noisily complains if they swallow interrupt exceptions.
TODO add tests if there is loose agreement this is correct logic.
> Allow interrupt of singleton cleanup thread

- okhttp/src/test/java/okhttp3/WholeOperationTimeoutTest.java
Increasing the timeout which only has 250ms tolerance after inbuilt delays etc. Issue info is here https://github.com/square/okhttp/issues/5304
> Increase timeout for flaky test

- okhttp-tests/src/test/java/okhttp3/EventListenerTest.java
Saving 128 MiB of data is too much for CI
> Fix flakiness in EventListenerTest.requestBodyFail().

- okcurl/build.gradle
I can't have both this and shadow concurrently because they both attempt
to use the same classifier when publishing.
> Remove the application plugin from okcurl

- .circleci/config.yml
- build.gradle
- okhttp/build.gradle
- okhttp/src/test/java/okhttp3/OpenJSSETest.kt
https://github.com/openjsse/openjsse from Azul
TLSv1.3 on JDK 8
At the moment, no code changes or custom support enabling HTTP/2, only a test that it works in JDK8.
> Test for OpenJSSE

- docs/works_with_okhttp.md
This prunes a few that haven't been updated and appear obsolete.
> Update the libraries that work with OkHttp

- .circleci/config.yml
- build.gradle
- okhttp-testing-support/build.gradle
- okhttp-testing-support/src/main/java/okhttp3/TestUtil.java
- okhttp-testing-support/src/main/java/okhttp3/testing/PlatformRule.kt
- okhttp/build.gradle
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/OpenJSSEPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/Platform.kt
- okhttp/src/main/java/okhttp3/internal/platform/android/StandardAndroidSocketAdapter.kt
- okhttp/src/test/java/okhttp3/CacheTest.java
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/ConscryptTest.kt
- okhttp/src/test/java/okhttp3/DuplexTest.java
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/OpenJSSETest.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Support for HTTP/2 with https://github.com/openjsse/openjsse
Caveats
1) Tests based on MockWebserver (on JDK8) won't work without larger changes
2) Unclear what the overall status is of the project is, and edge cases like cipher selections on older VMs may need testing.
> OpenJSSE Platform support

- docs/releasing.md
https://github.com/cashapp/barber/blob/master/docs/releasing.md
> Include prerequisites in the releasing guide.

- README.md
The "Post to a Server" section in the README is using the deprecated
method for creating a new `RequestBody`. This commit uses the
recommended method for the README, but also now matches the example in
`PostExample.java`
> Update README.md to match example code for POST

- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
Some Android 4.2.2 devices don't like the try/catch block
so avoid it.
https://github.com/square/okhttp/issues/3772
> Don't crash looking up an absent class on Android 4.x

- okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.kt
- okhttp/src/test/java/okhttp3/CacheTest.java
This was introduced with our migration to Kotlin. Iterating over the indices
of the header names doesn't work because header names are not distinct.
Closes: https://github.com/square/okhttp/issues/5413
> Fix a regression in combining cache headers

- okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.kt
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
I'm starting with the thing I want first; reusing a HeldCertificate
across VM invocations.
Later we might want to create entire HandshakeCertificates objects
by stringing together many certificates from a single file.
> Make it easier to decode PEM files

- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
Closes: https://github.com/square/okhttp/issues/5422
Unfortunately testing this is awkward because it's racy. I did
run a stress test that used to reproduce the problem, and now it
doesn't, so I am satisfied.
> Acknowledge and apply inbound settings atomically

- android-test/build.gradle
- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
With session ticket disabled in AndroidSocketAdapter
```
09-07 12:04:35.577 24546 25651 W OkHttp  : results HowsMySslResults(unknown_cipher_suite_supported=false, beast_vuln=false, session_ticket_supported=false, tls_compression_supported=false, ephemeral_keys_supported=true, rating=Probably Okay, tls_version=TLS 1.3, able_to_detect_n_minus_one_splitting=false, insecure_cipher_suites={}, given_cipher_suites=[TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, …
```
> Hows My Ssl test for Android

- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt
We had a bug where a race between FramingSource.receive() and
FramingSource.close() could cause newly-received bytes to be
absent from the flow control window. If this happens enough then
eventually the connection will stall.
> Don't leak incoming bytes when we race incoming data and close

- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
Closes: https://github.com/square/okhttp/issues/5422
Unfortunately testing this is awkward because it's racy. I did
run a stress test that used to reproduce the problem, and now it
doesn't, so I am satisfied.
> Acknowledge and apply inbound settings atomically (3.12.x branch)

- okhttp-tests/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java
Closes: https://github.com/square/okhttp/issues/5422
Unfortunately testing this is awkward because it's racy. I did
run a stress test that used to reproduce the problem, and now it
doesn't, so I am satisfied.
> Acknowledge and apply inbound settings atomically (3.14.x branch)

- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.java
We had a bug where a race between FramingSource.receive() and
FramingSource.close() could cause newly-received bytes to be
absent from the flow control window. If this happens enough then
eventually the connection will stall.
> Don't leak incoming bytes when we race incoming data and close (3.12.x branch)

- okhttp/src/main/java/okhttp3/Handshake.kt
- okhttp/src/test/java/okhttp3/DelegatingSSLSession.java
- okhttp/src/test/java/okhttp3/DelegatingSSLSocket.java
- okhttp/src/test/java/okhttp3/HandshakeTest.kt
Closes: https://github.com/square/okhttp/issues/5440
> Handle TLS_NULL_WITH_NULL_NULL by throwing an IOException

- okhttp/src/test/java/okhttp3/CallTest.java
Can come from here
```
Caused by: java.net.SocketException: Socket is closed
at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1542)
```
But I had this from some variant of local builds, not sure it's this one above.
> Add another connection error message

- okhttp/src/main/java/okhttp3/internal/concurrent/Task.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
I want to tighten up our executors for a few reasons
- Fix daemon vs. non-daemon problems
- Fix code unloading problems
- Be able to wait for async work to complete in tearDown()
- Fewer threads for pongs, acks, and window updates
This shouldn't be too much to layer on top of ExecutorService, but
it is not easy to do with those APIs alone.
The underlying motivation is to make scheduling work easier in
Http2Connection, which will help with differentiating between
dead streams and dead connections.
https://github.com/square/okhttp/issues/3146
> TaskRunner, an abstraction over ExecutorService

- okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
Currently, if we have a one-shot request body and try to use the logging interceptor with `Level.BODY`, the `RequestBody.writeTo` method will be called twice. This is broken behaviour.
See #5419
> HttpLoggingInterceptor: respect RequestBody.isOneShot()

- okhttp-tests/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.java
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java
Fixed a bug I found.
When using DiskLruCache, hasNext() method of Iterator<Snapshot> returned by snapshot() method iterates through lruEntries, however if entry is not completed yet, it is removed (together with dirtyFiles) as cleanFiles don't exist yet - during saving response to disk. This caused sometimes file not being cached at all.
> DiskLruCache snapshot() method removing entries that are being cached (3.14.x branch)

- okhttp-tests/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.java
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java
Fixed a bug I found.
When using DiskLruCache, hasNext() method of Iterator<Snapshot> returned by snapshot() method iterates through lruEntries, however if entry is not completed yet, it is removed (together with dirtyFiles) as cleanFiles don't exist yet - during saving response to disk. This caused sometimes file not being cached at all.
> DiskLruCache snapshot() method removing entries that are being cached (3.12.x branch)

- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/Task.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
This is attempting to balance simplicity, efficiency, and testability.
It doesn't use ScheduledExecutorService because that class wants a
permanent scheduler thread. Instead this uses a coordinator thread
that does its own wait and notify, similar to the mechanism in the
ConnectionPool that this is intended to replace.
> Implement TaskRunner.

- okhttp/src/main/java/okhttp3/internal/concurrent/Task.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerRealBackendTest.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
Also implement tests for thread interruption.
Also add a test that uses the real backend.
> Set the thread name to the currently-executing task's name.

- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/java/okhttp3/ConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/Task.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerRealBackendTest.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
This also configures tests to assert that the connection pool
isn't doing any work after the test completes.
> Adopt TaskRunner in RealConnectionPool

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver/src/test/java/okhttp3/mockwebserver/internal/http2/Http2Server.java
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
Shutting down queues makes it easier to implement HTTP/2
shutdown because we can enqueue everywhere and centralize
the logic that decides whether we're shutdown or not.
Use this new functionality to implement HTTP/2 on task queues.
It's mostly a drop-in replacement, though opting-into cancel
looks like a mistake when it's what we do most of the time.
When testing this the OkHttpClientTestRule was failing because
tasks were incomplete. I was puzzled by this until I realized
that the OkHttpClientTestRule performs that validation before
we stop the MockWebServer. I changed MockWebServer to have its
own TaskRunner and that made the problem go away.
> TaskRunner support for shutting down queues

- deploy_website.sh
I tried rendering in jekyll mode but that doesn't look as nice with
Mkdocs.
> Rewrite Dokka-generated markdown to include titles.

- okhttp-sse/src/test/java/okhttp3/internal/sse/EventSourceHttpTest.java
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/test/java/okhttp3/CallKotlinTest.kt
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp/src/test/java/okhttp3/ConscryptTest.kt
- okhttp/src/test/java/okhttp3/CookiesTest.java
- okhttp/src/test/java/okhttp3/DispatcherTest.java
- okhttp/src/test/java/okhttp3/DuplexTest.java
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/InterceptorTest.java
- okhttp/src/test/java/okhttp3/OpenJSSETest.kt
- okhttp/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
We used to do this lazily because OkHttpClient instances were
somewhat heavy: each standalone instance held its own
ExecutorService for the connection pool.
Now that we have TaskRunner each instance is much more
lightweight and the drawbacks of creating instances eagerly
is negligible.
> Create OkHttpClient instances eagerly in tests

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
The most consequential change here is that the background thread is
now a daemon thread. A program consisting of exactly one web socket
will exit when the reader reads an inbound close message. Previously
such a program would continue running until the writer acknowledged
this close.
> Use TaskRunner in web sockets.

- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Settings.kt
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp/src/test/java/okhttp3/internal/http2/SettingsTest.java
Previously we mutated one instance as directed by the peer. This
was difficult to reason about.
This change includes migration of settings listeners to TaskRunner.
TaskRunner makes it easier to notify the listener of settings
changes serially, which makes these snapshots more useful.
> Change HTTP/2 connections to track settings snapshots

- build.gradle
Since we build with jdk11 etc, default to jdk9 platform for tests unless overridden.
> Default to jdk9 platform for tests

- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/Task.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
We don't need to be called back when a call is being canceled.
This was unnecessary complexity that I thought I'd need for OkHttp
but I don't.
> Make TaskRunner cancellation less dynamic

- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/proxy/NullProxySelector.kt
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
Closes: https://github.com/square/okhttp/issues/5519
> Fix connection pooling for different clients with the same pool.

- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/proxy/NullProxySelector.kt
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/KotlinSourceModernTest.kt
Closes: https://github.com/square/okhttp/issues/5519
> Fix connection pooling for different clients with the same pool. (4.2.x branch)

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerRealBackendTest.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
Naming queues seemed good initially, but the names are mostly
mutually-redundant with task names.
This PR reduces debug information when a queue is still busy
when the test completes. I have a fix for that in a follow-up
change.
> Name tasks only in TaskRunner

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver/src/main/java/okhttp3/mockwebserver/RecordedRequest.kt
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
It now tracks inbound requests that fail with an IOException.
Also add a fix for the bug where we'd send 'END OF STREAM' on a stream
that we'd previously canceled, which raced with the 'RST STREAM' and led
to flakiness.
Before we ship the new API in RecordedRequest we should go over the
other cases where inbound HTTP requests fail and make sure they
get reported through this channel.
Closes: https://github.com/square/okhttp/issues/5388
> Add a way for MockWebServer to track truncated requests

- okhttp-logging-interceptor/README.md
There is no longer a markdown doc file on interceptors, 
but the article is available on the project website.
> Fix the broken link:

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/Task.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/CallKotlinTest.kt
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
- okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
Now we don't have to alternate between the coordinator thread and the task
thread between task runs if the task returns 0. Instead the task thread can
stay resident.
This implementation works by having task runnables that can switch from
the coordinator role (sleeping until the next task starts) and the executor
role.
https://github.com/square/okhttp/issues/5512
> Change TaskRunner to limit context switches.

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/Task.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerRealBackendTest.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
Examples:
- OkHttp TaskRunner
- MockWebServer TaskRunner
- OkHttp ConnectionPool
- MockWebServer localhost applyAndAckSettings
- OkHttp android.com applyAndAckSettings
- OkHttp android.com onSettings
- OkHttp awaitIdle
- OkHttp localhost
I'm trying to use type names where appropriate, or method names otherwise.
Names include hostname and stream name if the task is working on behalf
of a specific stream or connection.
> Be more consistent with task names

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
The utility here is negligible. We're sharing threads between HTTP,
HTTP/2 and web sockets now.
> Use TaskRunner in MockWebServer

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/Task.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
This probably should have been the case all along. Unfortunately,
ExecutorService Runnables are not cancelable by default, and that's
where we started.
After implementing all of TaskRunner it looks like where we're
cancelable and where we aren't is totally arbitrary. Making everything
cancelable simplifies the implementation and model.
The last remaining non-cancelable tasks:
* awaitIdle() which we use in our tests only.
* MockWebServer, where canceling would leak sockets
> Make all TaskRunner tasks cancelable

- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/OkHttpClientTest.java
Let's remove warnings found by errorprone.
- attempt
```
okhttp/okhttp/src/test/java/okhttp3/CallTest.java:2056: warning: [UnnecessaryParentheses] Unnecessary use of grouping parentheses
sink.writeUtf8("attempt " + (attempt++));
^
(see https://errorprone.info/bugpattern/UnnecessaryParentheses)
Did you mean 'sink.writeUtf8("attempt " + attempt++);'?
```
- isEaualTo
```
okhttp/src/test/java/okhttp3/OkHttpClientTest.java:287: warning: [UnnecessaryParentheses] Unnecessary use of grouping parentheses
assertThat(expected.getMessage()).isEqualTo(("protocols must not contain null"));
^
(see https://errorprone.info/bugpattern/UnnecessaryParentheses)
```
> Remove unnecessary use of grouping parentheses

- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/ConnectionSpecTest.java
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/HeadersTest.java
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
Let's clean up warnings caught by errorprone.
- headers
```
okhttp/src/test/java/okhttp3/HeadersTest.java:136: warning: [UnusedVariable] The local variable 'headers' is never read.
Headers headers = new Headers.Builder()
^
(see https://errorprone.info/bugpattern/UnusedVariable)
Did you mean to remove this line or 'new Headers.Builder()'?
```
- lessThan
```
okhttp/src/test/java/okhttp3/EventListenerTest.java:312: warning: [UnusedMethod] Private method 'lessThan' is never used.
private Matcher<Long> lessThan(final long value) {
^
(see https://errorprone.info/bugpattern/UnusedMethod)
Did you mean to remove this line?
```
- response
```
okhttp/src/test/java/okhttp3/CallTest.java:3312: warning: [UnusedVariable] The local variable 'response' is never read.
Response response = …
```
> Clean up unused variables/methods in Test

- okhttp/src/test/java/okhttp3/CacheTest.java
We have a warning as follows, and we should've used `t2` timestamp.
```
okhttp/okhttp/src/test/java/okhttp3/CacheTest.java:1939: warning: [UnusedVariable] The local variable 't2' is never read.
long t2 = System.currentTimeMillis();
^
(see https://errorprone.info/bugpattern/UnusedVariable)
Did you mean to remove this line or 'System.currentTimeMillis();'?
```
> Fix test in CacheTest by using t2 timestamp as expected

- okhttp/src/test/java/okhttp3/CacheTest.java
Like we discussed it in the previous PR, `t2` should be removed.
PR: https://github.com/square/okhttp/pull/5552
- Renamed `originalTimestamp` to `updatedTimestamp` since the name was not appropriate.
- Change the thread sleep time to 10ms.
> Remove unnecessary variable in CacheTest

- README.md
- docs/r8_proguard.md
Always when I search for the proguard rules of my app I jump from dependency to dependency.
okhttp makes it a little bit easier by saying "You also need the Okio rules".
But just saying it means I have to open a new tab, go to github.com/square/okio (or google it), and copy the stuff to my proguard files.
With that link we simplify the process 😇
> Add link to okio proguard rules

- okhttp-testing-support/src/main/java/okhttp3/ClientRuleEventListener.kt
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp-testing-support/src/main/java/okhttp3/RecordingEventListener.java
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/ConnectionCoalescingTest.java
- okhttp/src/test/java/okhttp3/DispatcherTest.java
- okhttp/src/test/java/okhttp3/DuplexTest.java
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Keep the client event logging for flaky tests even when another listener is applied.
Used to generate a baseline for https://github.com/square/okhttp/issues/5576
> Flaky test improvements

- README.md
The README still contains Java examples, but is missing what most Java projects would use: Maven coordinates. This PR adds that.
Note that something about the README (or the lack of an actual pom.xml file perhaps) confuses GitHub's Dependency graph page. Here https://github.com/nielsgron/quicksilver/network/dependencies it detects for com.squareup.okhttp3:okhttp the repository https://github.com/lizhangqu/PriorityOkHttp . It would be good to see with GitHub how to make this the canonical repository for OkHttp on Maven.
> Adds Maven coordinates to README

- .circleci/config.yml
- okhttp/src/test/java/okhttp3/CallTest.java
Test doesn't need to care about which response, timing related issues are secondary.  Just that it succeeds and we don't somehow disconnect and reconnect.
> Run Jdk8 on CI and fix test expectations

- android-test/build.gradle
Failing with 
```
ANDROID_SDK_ROOT=/Users/yschimke/Library/Android/sdk ./gradlew :android-test:connectedCheck
D8: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
...
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/yschimke/.gradle/caches/modules-2/files-2.1/software.amazon.cryptools/AmazonCorrettoCryptoProvider/1.1.1/a606679a20abcef643ad551bdd6793dba4a11213/AmazonCorrettoCryptoProvider-1.1.1-linux-x86_64.jar
at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:909)
at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:834)
at …
```
> Avoid Corretto and R8 incompatibility in tests

- okhttp/src/main/java/okhttp3/Dispatcher.kt
- okhttp/src/main/java/okhttp3/RealCall.kt
- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/java/okhttp3/internal/connection/Transmitter.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
Use a clear intentional method instead of kotlin assert() function vs JVM assert keyword. Guarded behind a cached assertion status check.
Addressing issue https://github.com/square/okhttp/issues/5586
> Kotlin optimized lock asserts

- .buildscript/deploy_snapshot.sh
- .travis.yml
- Build using the minimum suitable LTS (JDK11)
- Avoid running tests because Travis has old versions of JDK11 that have SSL bugs
> Bump Travis to JDK 11

- okhttp/src/main/java/okhttp3/Authenticator.kt
- okhttp/src/main/java/okhttp3/CookieJar.kt
- okhttp/src/main/java/okhttp3/Dns.kt
- okhttp/src/main/java/okhttp3/internal/http2/PushObserver.kt
There is a [known issue][2] on Kotlin which make it impossible to compile kotlin softwares to binary using native-image when using [object expressions][3] inside interfaces. By this reason okhttp4+ can't be compiled to binary using [native-image][4]. Unfortunately there is no a road map for kotlin team to fix the issue. 
To make okhttp native-image friendly I'm proposing this pull request, this way it will compiles and run on native-image binaries successfully.
[here a working sample][5] after the fix
[1]: https://github.com/oracle/graal/issues/1521
[2]: https://youtrack.jetbrains.com/issue/KT-33097
[3]: https://kotlinlang.org/docs/reference/object-declarations.html#object-expressions
[4]: https://github.com/oracle/graal/tree/master/substratevm#introduction
[5]: …
> Make okhttp native-image compatible

- README.md
The order of the two parameters seems to be *inconsistent* with the code on [another page](https://raw.githubusercontent.com/square/okhttp/master/samples/guide/src/main/java/okhttp3/guide/PostExample.java).
In [https://github.com/square/okhttp/blob/master/README.md#post-to-a-server](https://github.com/square/okhttp/blob/master/README.md#post-to-a-server) we can see
> RequestBody.create(JSON, json);
(the following pic shows the details)
But if you click the `Full source`(the link is https://raw.githubusercontent.com/square/okhttp/master/samples/guide/src/main/java/okhttp3/guide/PostExample.java)
you will see
> RequestBody.create(json, JSON);
(the following pic shows the details)
I tried both of them on my Mac with the following dependency
```xml
<dependency> …
```
> change the order of two parameters

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
This was a regression introduced with the TaskRunner changes.
I couldn't find other places where daemon threads were likely
to cause potential problems.
https://github.com/square/okhttp/issues/5512
> Don't use daemon threads in MockWebServer

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
This is based roughly on the 'Degraded Connections' proposal here
https://github.com/square/okhttp/issues/3146#issuecomment-471196032
I'm using 1000 ms instead of 500 ms. That's about the cost of a (slow)
TLS handshake, which is what callers would need to do if we degrade
unnecessarily.
> Degrade connections after a timeout

- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerRealBackendTest.kt
Previously an unchecked exception would starve the runner of
threads until another task was scheduled.
> Fix TaskRunner handling of uncaught exceptions

- .circleci/config.yml
Suggested policy
JDK 8 - minimum with/out ALPN
JDK11 - Current LTS
JDK13 - Current JDK
JDK14ea - Next EA (when supported by toolchain)
As we have flaky integration tests, this is already ambitious.  So set this as the rough size of our integration tests.
> Remove JDK 12 (non-LTS)

- mkdocs.yml
| Before | After |
| --- | --- |
| https://square.github.com/okhttp/nicolas-cage | https://saket.github.io/okhttp/nicolas-cage |
| ![image](https://user-images.githubusercontent.com/2387680/71314734-c0779200-241b-11ea-8589-e4c619cecf0b.png) | ![image](https://user-images.githubusercontent.com/2387680/71314730-b81f5700-241b-11ea-846f-8b0482ddfc91.png) |
MkDocs' 404 page uses relative links to the organization's github page by default resulting in broken resources (stylesheets, images et al). What's worse is that the links in the navigation sidebar also get affected so manually changing the url in the address bar is the only way to exit. 
The fix is to specify the site URL explicitly ([source](https://github.com/mkdocs/mkdocs/issues/77)).
> Explicitly specify site-url for mkdocs

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver/src/main/java/okhttp3/mockwebserver/internal/duplex/DuplexResponseBody.kt
- mockwebserver/src/main/java/okhttp3/mockwebserver/internal/duplex/MockDuplexResponseBody.kt
- okhttp/src/test/java/okhttp3/DuplexTest.java
It turns out it'll be a bit difficult to fix this because we don't
currently support reading the response stream after an error.
https://github.com/square/okhttp/issues/4964
> Failing test for NO_ERROR stream reset

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp-testing-support/src/main/java/okhttp3/CallEvent.kt
- okhttp-testing-support/src/main/java/okhttp3/RecordingEventListener.kt
- okhttp/src/main/java/okhttp3/EventListener.kt
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/EventListenerTest.java
This changes the timing of responseHeaderStart and responseBodyStart events to
fire when bytes are received from the server. This is a non-trivial behavior
change and should be documented as such in the release notes. In particular,
the responseFailed event may be fired without a preceding responseHeadersStart
event.
To test this I've added a timestamp to our CallEvent test facet.
Closes: https://github.com/square/okhttp/issues/5578
> Defer EventListener events until bytes are returned

- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerRealBackendTest.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
The problem was the awaitIdle() call was scheduling executor jobs after
the ExecutorService had been shut down. This fixes that and defends
against other races.
> Fix crash on repeated MockWebServer shutdown

- okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
Fixes #4948
Currently response body size is determined by `Content-Length` header value, i.e. we use the header value if it exists, otherwise set -1.
This doesn't work for some HTTP responses. For example, `response.body().contentLength()` should return 0 for a response of HEAD request instead of using the `Content-Length` value. Also it should return 0 for a 204 responses instead of providing -1 when Content-Length header is not present.
> Correctly calculate HTTP2 response body size

- okhttp/src/test/java/okhttp3/KotlinDeprecationErrorTest.kt
Without this it's too easy to typo these and make migration more difficult
for users upgrading to OkHttp 4.x.
> Confirm that deprecated symbols exist

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver/src/test/java/okhttp3/mockwebserver/internal/http2/Http2Server.java
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/platform/Android10Platform.kt
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/Jdk8WithJettyBootPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.kt
- okhttp/src/main/java/okhttp3/internal/platform/OpenJSSEPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/Platform.kt
- okhttp/src/main/java/okhttp3/internal/platform/android/Android10SocketAdapter.kt
- okhttp/src/main/java/okhttp3/internal/platform/android/AndroidSocketAdapter.kt
- okhttp/src/main/java/okhttp3/internal/platform/android/ConscryptSocketAdapter.kt
- okhttp/src/main/java/okhttp3/internal/platform/android/DeferredSocketAdapter.kt
- okhttp/src/main/java/okhttp3/internal/platform/android/SocketAdapter.kt
- okhttp/src/test/java/okhttp3/internal/platform/Jdk9PlatformTest.java
- okhttp/src/test/java/okhttp3/internal/platform/android/AndroidSocketAdapterTest.kt
Fix for https://github.com/square/okhttp/issues/5700
Android 5.0 requires explicit call to set the hostname.
> Set hostname on Android 5.0

- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Closes: https://github.com/square/okhttp/issues/5705
> Fix a regression closing WebSockets before connect

- build.gradle
- okhttp-testing-support/build.gradle
- okhttp-testing-support/src/main/java/okhttp3/testing/PlatformRule.kt
- okhttp-tls/src/test/java/okhttp3/tls/HandshakeCertificatesTest.java
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
- okhttp/src/test/java/okhttp3/BouncyCastleTest.kt
Ready to land, but mainly allows quantifying how broken some of the test assumptions or the BC library is.
If we don't add to CI, it will mainly catalog how broken we are with Bouncy Castle.
> Add bouncy castle platform for tests

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- okhttp/src/main/java/okhttp3/Handshake.kt
For discussion.  CertificateCleaner will fail for these tests, but we have overridden the TrustManager to allow it to pass.  Accessing the peerCertificates (which are lazily cleaned) directly, or via toString, equals, hashCode will therefore fail.
This seems like the minimal fix for debugging sanity.
> Allow Handshake.toString() for debugging, even when CertificateCleaner will fail

- build.gradle
- docs/releasing.md
- gradle.properties
- mockwebserver/build.gradle
- mockwebserver/gradle.properties
- okcurl/build.gradle
- okcurl/gradle.properties
- okhttp-brotli/build.gradle
- okhttp-brotli/gradle.properties
- okhttp-dnsoverhttps/build.gradle
- okhttp-dnsoverhttps/gradle.properties
- okhttp-logging-interceptor/build.gradle
- okhttp-logging-interceptor/gradle.properties
- okhttp-sse/build.gradle
- okhttp-sse/gradle.properties
- okhttp-tls/build.gradle
- okhttp-tls/gradle.properties
- okhttp-urlconnection/build.gradle
- okhttp-urlconnection/gradle.properties
- okhttp/build.gradle
- okhttp/gradle.properties
This removes a bunch of low-value stuff from the pom.xml files:
- name
- description
- licence distribution ('repo')
- developers clause
- test dependencies
I don't think any of this will be missed, and it shrinks the pom.xml
file to the minimal set of useful stuff.
This also causes us to publish a gradle .module file. This is the
motivation for this change. It'll allow us to ship a Gradle platform,
which is a more capable than a Maven BOM.
> Switch to Gradle's Maven Publishing Plugin

- build.gradle
- okhttp-bom/build.gradle
- settings.gradle
https://docs.gradle.org/current/userguide/java_platform_plugin.html
This prevents downstream applications from pulling in different
versions of various OkHttp subprojects.
> Publish a BOM for OkHttp 4.x.

- build.gradle
- okhttp-testing-support/build.gradle
- okhttp-testing-support/src/main/java/okhttp3/OkHttpDebugLogging.kt
- okhttp-tls/build.gradle
- okhttp/build.gradle
- okhttp/src/main/java/okhttp3/internal/platform/BouncyCastlePlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/Platform.kt
- okhttp/src/test/java/okhttp3/BouncyCastleTest.kt
Improves client side for BouncyCastle use.  n.b. highlights issues when properly using BouncyCastle in a server.  Fixes for that to come separately.
> Bouncy Castle Provider working with HTTP/2 on JDK 8

- okhttp/src/main/java/okhttp3/internal/connection/ConnectInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.kt
I've attempted to put RealCall's methods into a logical order; it's approximately
the order the methods get called in for a successful call.
For RealInterceptorChain I've created a copy() method inspired-by data classes.
This has the added benefit of shrinking the call stack everywhere.
> Reorganize RealCall and RealInterceptorChain

- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
**This `retryCurrentRoute()` check will always return false, because `transmitter.connection` is `null` here.**
**Reason**: 
Just a few lines above, `result` is set to `transmitter.connection`, with the condition `transmitter.connection != null`. And as `result == null` is the entry condition of this lower block, `transmitter.connection` should definitely be `null`, which makes `retryCurrentRoute()` always return `false`.
```kotlin
// findConnection()
// wrapped in a synchronized block
if (transmitter.connection != null) {
// We had an already-allocated connection and it's good.
result = transmitter.connection
releasedConnection = null
}
if (result == null) {
// Attempt to get a connection from the pool.
if (connectionPool.transmitterAcquirePooledConnection(address, transmitter, null, …
```
> Remove always-false check of retryCurrentRoute() and unreachable code.

- okhttp/build.gradle
- okhttp/src/main/java/okhttp3/Dispatcher.kt
- okhttp/src/main/java/okhttp3/RequestBody.kt
- okhttp/src/main/java/okhttp3/internal/connection/ConnectInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http/ExchangeCodec.kt
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/main/java/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/OpenJSSETest.kt
- okhttp/src/test/java/okhttp3/RecordingExecutor.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
There's four useful events:
1. When we're ready to call network interceptors. At this point
we expect an exchange to exist, as a handle to the connection
we've chosen for the network call
2. When we hold an exchange that must later be released.
3. When we release the exchange
4. When we're done calling network interceptors. Only at this point
do we no longer need to remember what the exchange was and what
connection it used.
In practice 1 and 2 happen mostly at the same time. Right now 1 is
in RetryAndFollowUpInterceptor and 2 is in ConnectInterceptor, but
we should be able to move those around without pain.
But we have a problem with 3 and 4. If the response has no response
body, then 3 will precede 4. We will release the exchange as soon as
we know there's no streams held. This means …
> Formalize the lifecycle of Exchange

- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
If we're going to end up using a pooled connection anyway we
should defer proxy selection until we need it.
> Don't do proxy selection eagerly if we're pooling

- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
We limit per-connection retries but not per-call retries, so this was
creating large numbers of connections each of which called the server
and accepted yet another REFUSED_STREAM.
Instead we fail sooner with a StreamResetException.
This shows that the ExchangeFinder interface is still somewhat inadequate
to support all of the use cases we have.
> Limit recovery attempts for REFUSED_STREAM errors

- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
I prefer the old code esthetically, but this has the behavior I want. The
core problem is we're deciding about nextRouteToTry too early, before a
failure makes that route ineligible.
Closes: https://github.com/square/okhttp/issues/5791
> Move the code that clears out the next route to try

- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
We originally had a bug where Call.cancel() would incorrectly
cause HTTP/2 connections to be closed.
The fix was to not consider HTTP/2 connections to be degraded
when a CANCEL error is received:
https://github.com/square/okhttp/pull/4052
This closes the loop to make sure that we only treat CANCEL as
expected when the call was actually canceled.
Closes: https://github.com/square/okhttp/issues/5726
> Don't do infinite retries on server-canceled calls

- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/test/java/okhttp3/CallKotlinTest.kt
- okhttp/src/test/java/okhttp3/ConnectionReuseTest.java
- okhttp/src/test/java/okhttp3/internal/UtilTest.kt
Previously we didn't do any health checks at all until a
connection completed a single exchange. This was awkward
for HTTP/2, which could have multiple exchanges in-flight
before any were health checked.
We were also doing the awkward and expensive read timeout
check on all non-GET requests on pooled connections. Now
we only perform these checks if the connection was idle
for 10 seconds or more.
Closes: https://github.com/square/okhttp/issues/5547
> Be smarter about connection health checks

- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/InterceptorTest.java
- okhttp/src/test/java/okhttp3/OkHttpClientTest.java
- okhttp/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/test/java/okhttp3/WholeOperationTimeoutTest.java
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
When compiling OkHttp, we have warnings regarding PreferJavaTimeOverload.
For example:
```
okhttp/okhttp/src/test/java/okhttp3/EventListenerTest.java:193: warning: [PreferJavaTimeOverload] Prefer using java.time-based APIs when available. Note that this checker does not and cannot guarantee that the overloads have equivalent semantics, but that is generally the case with overloaded methods.
.readTimeout(250, TimeUnit.MILLISECONDS)
^
(see https://errorprone.info/bugpattern/PreferJavaTimeOverload)
```
<details>
<summary>Click to see all the related logs!</summary>
```
okhttp/okhttp/src/test/java/okhttp3/OkHttpClientTest.java:78: warning: [PreferJavaTimeOverload] Prefer using java.time-based APIs when available. Note that this checker does not and cannot guarantee that the overloads have …
```
> Refactor OkHttpClient#xxxTimeout(...) to fix errorprone PreferJavaTimeOverload in tests

- android-test/build.gradle
- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- okhttp/src/main/java/okhttp3/internal/platform/Android10Platform.kt
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt
- okhttp/src/main/java/okhttp3/internal/platform/android/Android10SocketAdapter.kt
In order to test https://github.com/square/okhttp/issues/5816, run against Android R.
> Fixes for Android Test (including R)

- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
I was reviewing a CI test failure reported here: https://circleci.com/gh/square/okhttp/9726
Reviewing the test case everything _seemed_ fine. I noticed that if I breakpoint on the last line of the test and wait 5 seconds it'll timeout. This is expected because we have a timeout rule. But the failure is reporting as `OkHttpClientTestRule.ensureAllConnectionsReleased()`. To me I'd like to see the Timeout failure. It feels like someone might start diving into something that doesn't actually exist. The timeout implies the test didn't complete and we will probably expect leaked connections! 😄 Tricky situation though.
I also made the timeout less aggressive (60 seconds instead of 5.) I think this means we prefer a slightly slower build that likely succeeds rather than a faster build with …
> Prefer reporting a JUnit Timeout failure in HttpOverHttp2Test.

- okhttp-tests/src/test/java/okhttp3/CallTest.java
OpenJDK 9 is bad and obsolete and I'd like to avoid it. But we've got
Javadoc issues publishing on OpenJDK 11.
> Get tests passing on OpenJDK 9

- okhttp/src/main/java/okhttp3/internal/Util.kt
- okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/test/java/okhttp3/CallKotlinTest.kt
Before we have Happy Eyeballs, we currently throw the exception for the final Route.  Often a failure for an earlier Route may be more actionable, so add to suppressed.
n.b. RouteException already has a suppressed chain so this is a two level tree effectively.
> Add SuppressedExceptions for multiple Routes

- okhttp/src/main/java/okhttp3/internal/ws/WebSocketExtensions.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketExtensionsTest.kt
Originally contributed via PR #4871. This differs from that contribution
in a few ways:
- rename WebSocketOptions to WebSocketExtensions
- rename properties to track names defined in RFC 7692
- use several independent JUnit tests instead of @Parameterized
- use Util.kt to do parsing without intermediate splitting
> WebSocket permessage-deflate extension header parser

- okhttp/src/main/java/okhttp3/internal/ws/MessageDeflater.kt
- okhttp/src/main/java/okhttp3/internal/ws/MessageInflater.kt
- okhttp/src/test/java/okhttp3/internal/ws/MessageDeflaterInflaterTest.kt
Originally contributed via PR #4871. This differs from that contribution
in a few ways:
- Combined inflater and deflater into one test
- Always operate on a buffer in-place
- Support no context takeover in both reading and writing
> Web Socket message inflater and deflater

- okhttp/src/main/java/okhttp3/Handshake.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/test/java/okhttp3/ConnectionCoalescingTest.java
In dev with disabled TrustManager and hostName verifier, just checking whether we can reuse a connection across hosts can cause a failure
> Allow for users who have disabled certificate checks in dev.

- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketWriterTest.java
An old version of OkHttp web sockets supported streaming messages,
so a writer could transmit partial bytes of a message without
completing it.
When we promoted Web Sockets as a core feature we dropped support
for streaming a single message. But we still had the mechanism
that implemented it.
This PR removes that mechanism, which should make it easier to
implement compression.
> Rip out WebSocketWriter's message splitting

- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/test/java/okhttp3/ConnectionCoalescingTest.java
We attempt to minimize connection and reconnection work, but in this case we
were overly aggressive about retaining the same connection. In some deployments
services will share certificates but not DNS addresses; when redirecting
between such services we were incorrectly attempting to reuse the connection.
This would have resulted in 404s and other misdirected requests.
Closes: https://github.com/square/okhttp/issues/5859
> Don't reuse a connection on redirect if certs match but DNS does not

- okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/java/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/test/java/okhttp3/ConnectionCoalescingTest.java
We attempt to minimize connection and reconnection work, but in this case we
were overly aggressive about retaining the same connection. In some deployments
services will share certificates but not DNS addresses; when redirecting
between such services we were incorrectly attempting to reuse the connection.
This would have resulted in 404s and other misdirected requests.
Closes: https://github.com/square/okhttp/issues/5859
> Don't reuse a connection on redirect if certs match but DNS does not (4.4.x)

- .circleci/config.yml
Too noisy on PRs, just run on master post commit, and nightly.
> Don't run Windows builds in CircleCI on PRs

- okhttp/src/main/java/okhttp3/OkHttpClient.kt
- okhttp/src/main/java/okhttp3/internal/ws/MessageInflater.kt
- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/ws/MessageDeflaterInflaterTest.kt
- okhttp/src/test/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Theres a few TODOs outstanding around error cases, and I need to
run integration tests against real-world things. But the core
functionality works.
I used coverage to confirm the context takeover cases are exercised
with and without.
> Turn on web socket compression

- okhttp/src/main/java/okhttp3/internal/tls/OkHostnameVerifier.kt
- okhttp/src/test/java/okhttp3/internal/tls/HostnameVerifierTest.java
Fixes https://github.com/square/okhttp/issues/5885
> Verify IPv6 hostnames

- okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketExtensions.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.kt
- okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketReaderTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketWriterTest.java
They consume a decent amount of memory and it's possible that
they won't even be used, even if compression is negotiated.
Closes: https://github.com/square/okhttp/issues/5876
> Don't create inflaters or deflaters until they're needed

- README.md
- docs/changelog_3x.md
- docs/security.md
Our original expectations were that KitKat devices would age out in
2020. It's been a garbage year and this expectations no longer hold.
We're extending support an extra year.
We continue to support OkHttp 3.12.x because later releases are not
usable on older devices and JVMs.
OkHttp 3.14.x has no such reason to receive support, and we'll stop
updating it on June 30, 2020. Users of OkHttp 3.14.x should upgrade
to the 4.x series. Android apps should accept Kotlin libraries; it's
the platform's future. And JVM apps are less constrained by binary
size. Here's the size of OkHttp + transitive dependencies, and those
of alternatives:
* OkHttp 4.4: 2.47 MiB including Kotlin stdlib (1.51 MiB)
* Apache HTTP Client 5.0: 1.78 MiB including slf4j-api (0.04 MiB)
* Jetty HTTP Client 9.4: 1.19 MiB
> Support 3.12.x through December 31, 2021

- okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/test/java/okhttp3/CallTest.java
https://github.com/square/okhttp/issues/3308
> Give up when ExchangeFinder exhausts all routes.

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/java/okhttp3/internal/concurrent/TaskRunner.kt
Once a test leaves a client running, all other tests will fail.  But leaving things running can impact other tests, so make another attempt to cleanup.
> Force cancel all events on client

- okhttp/src/main/java/okhttp3/WebSocket.kt
This PR adds documentation to the exception which is thrown when the close reason is longer than 123 UTF-8 encoded bytes, addressing concerns from #5594. There are [preexisting tests](https://github.com/square/okhttp/blob/4c1f65d1388ae8d5720530ca9b0094f7343eb1c8/okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java#L476) for this behavior yet it is currently undocumented.
> Document maximum close reason length

- okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/test/java/okhttp3/CallTest.java
https://github.com/square/okhttp/issues/5819
> Flag connection as unhealthy when underlying socket is closed.

- build.gradle
From the project's release notes:
Defects Fixed
DLExternal would encode using DER encoding for tagged SETs. This has been fixed.
ChaCha20Poly1305 could fail for large (>~2GB) files. This has been fixed.
ChaCha20Poly1305 could fail for small updates when used via the provider. This has been fixed.
Properties.getPropertyValue could ignore system property when other local overrides set. This has been fixed.
The entropy gathering thread was not running in daemon mode, meaning there could be a delay in an application shutting down due to it. This has been fixed.
A recent change in Java 11 could cause an exception with the BC Provider's implementation of PSS. This has been fixed.
BCJSSE: TrustManager now tolerates having no trusted certificates.
BCJSSE: Choice of credentials and signing …
> Upgrade Bouncy Castle to to 1.65

- okhttp-testing-support/src/main/java/okhttp3/TestUtil.kt
- okhttp-testing-support/src/main/java/okhttp3/internal/io/InMemoryFileSystem.kt
- okhttp-testing-support/src/main/java/okhttp3/internal/io/WindowsFileSystem.kt
- okhttp/src/main/java/okhttp3/internal/io/FileSystem.kt
- okhttp/src/test/java/okhttp3/internal/io/FileSystemTest.kt
This should make it possible to get DiskLruCacheTest passing on
Windows even when Windows isn't available.
> Emulate Windows file system restrictions in a wrapper

- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
Safer for most providers, but causes failures for bc-java.
> Revert to null SecureRandom

- okhttp-testing-support/src/main/kotlin/okhttp3/TestUtil.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/internal/io/InMemoryFileSystem.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/internal/io/WindowsFileSystem.kt
- okhttp/src/main/kotlin/okhttp3/internal/Util.kt
- okhttp/src/main/kotlin/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.kt
- okhttp/src/test/java/okhttp3/internal/io/FaultyFileSystem.java
As originally designed DiskLruCache assumes an inode-like
file system, where it's fine to delete files that are
currently being read or written.
On Windows the file system forbids this, so we must be
more careful when deleting and renaming files. These
operations come up a lot internally in the cache:
- deleting to evict an entry
- renaming to commit a dirty file to a clean file
The workaround is simple if unsatisfying: we don't
permit concurrent reads and writes on Windows. We
can have multiple concurrent reders, or a single
writer.
One challenge in this implementation is detecting
whether we're running on Windows or a good operating
system. We deliberately don't look at System properties
here because the OS and file system may disagree, such
as when a Windows machine has an ext4 …
> Fix DiskLruCache to work on Windows

- okhttp/src/main/kotlin/okhttp3/CertificatePinner.kt
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/ConscryptPlatform.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/Platform.kt
Attempting a fix for https://github.com/square/okhttp/issues/5895.  At worst it should flush out poor behavior from clients or our own edge cases.
> Clean up SSL state in OkHttpClient

- .circleci/config.yml
Bumping versions apart from JDK8 builds which can't move from stretch to buster yet.
> CircleCI JDK bumps

- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java
Fix for #5970
This will fix the exception when throw in Azul Zulu JVM.  There is likely a fix to come from them to not throw, but this is defined in public API, so should be handled.
Will need to be backported to 3.12.x
> UnsupportedOperationException from JDK8 252 onwards [3.14.x]

- okhttp/src/main/kotlin/okhttp3/internal/platform/Jdk9Platform.kt
- okhttp/src/test/java/okhttp3/internal/platform/Jdk9PlatformTest.java
Fix for https://github.com/square/okhttp/issues/5970
Activates Jdk9Platform on Java 8 when the new methods are present (builds 252+).  Also handles the UnsupportedOperationException.
> UnsupportedOperationException from JDK8 252 onwards

- okhttp/src/test/java/okhttp3/internal/platform/Jdk9PlatformTest.java
Cont. https://github.com/square/okhttp/pull/5972
We can use `DelegatingSSLSocket` instead of overriding `SSLSocket` abstract class.
Ref. https://github.com/square/okhttp/pull/5972#discussion_r414232090
> Refactor Jdk9PlatformTest by using DelegatingSSLSocket

- okhttp-urlconnection/src/main/kotlin/okhttp3/JavaNetAuthenticator.kt
- okhttp/src/main/kotlin/okhttp3/Authenticator.kt
- okhttp/src/main/kotlin/okhttp3/internal/authenticator/JavaNetAuthenticator.kt
- okhttp/src/test/java/okhttp3/URLConnectionTest.java
- okhttp/src/test/java/okhttp3/internal/authenticator/JavaNetAuthenticatorTest.kt
Refactor the okhttp-urlconnection implementation.  Available as 
```
client.newBuilder()
.proxyAuthenticator(okhttp3.Authenticator.JAVA_NET_AUTHENTICATOR)
.build()
```
> Java Net Authenticator

- okhttp-urlconnection/src/main/kotlin/okhttp3/JavaNetAuthenticator.kt
- okhttp/src/main/kotlin/okhttp3/internal/authenticator/JavaNetAuthenticator.kt
Since Kdoc needs a full path to Kotliln class/function, we'll add 'okhttp3' prefix.
> Fix Kdoc class path with full package path in JavaNetAuthenticator

- okhttp/src/main/kotlin/okhttp3/MediaType.kt
- okhttp/src/test/java/okhttp3/MediaTypeTest.java
This changes our behavior for repeated charsets. Previously we would
crash; now we return the first value.
> Add an API to look up media type parameters

- okhttp/src/main/kotlin/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/test/java/okhttp3/URLConnectionTest.java
Fix for #2874 #3111 and #4229
https://tools.ietf.org/html/rfc7231#page-58
> 6.4.7.  307 Temporary Redirect
> 
>    The 307 (Temporary Redirect) status code indicates that the target
>    resource resides temporarily under a different URI and the user agent
>    MUST NOT change the request method if it performs an automatic
>    redirection to that URI.  Since the redirection can change over time,
>    the client ought to continue using the original effective request URI
>    for future requests.
> The user agent MAY
>    use the Location field value for automatic redirection.
https://tools.ietf.org/html/rfc7238
> The user agent MAY use the Location field
>    value for automatic redirection.
> Note: This status code is similar to 301 (Moved Permanently)
> ([RFC7231], Section 6.4.2), …
> Complies with rfc7231 about statuses 307 and 308

- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java
This was preventing mvn from wanting to cut a release.
> Fix a checkstyle issue

- okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java
This was preventing mvn from wanting to cut a release.
> Fix a checkstyle issue (3.14.x branch)

- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/test/java/okhttp3/CallKotlinTest.kt
Building on the centralised logging, make it easier to get a view of the activity for a failing test.
> Record Http2 Frames and TaskRunner optionally for Flaky tests

- okhttp-testing-support/src/main/kotlin/okhttp3/CallEvent.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/ClientRuleEventListener.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/RecordingEventListener.kt
- okhttp/src/main/kotlin/okhttp3/EventListener.kt
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/internal/cache/CacheInterceptor.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/test/java/okhttp3/EventListenerTest.java
Add cache events to Event Listener, mainly to avoid confusing CallStart>CallEnd or CallStart>CallFailed responses due to Cache strategy.
> Cache Events

- okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.kt
We have the compile warning below.
```
okhttp/okhttp/src/test/java/okhttp3/internal/cache/DiskLruCacheTest.kt: (57, 17): 'constructor Timeout(Int)' is deprecated. Deprecated in Java
```
To fix it, we'll follow the comment in the `Timeout` class.
```
* Instead use {@link #Timeout(long, java.util.concurrent.TimeUnit)},
* {@link Timeout#millis(long)}, or {@link Timeout#seconds(long)}.
```
> Use Timeout#seconds(long) instead of deprecated Timeout(long) constructor in DiskLruCacheTest

- okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
Fix high firing flake test in https://github.com/square/okhttp/issues/6033
> Fix flaky LoggingEventListenerTest

- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskLogger.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
Related to https://github.com/square/okhttp/issues/6033
Want to avoid failures like
```
okhttp3.internal.ws.WebSocketHttpTest > serverMaxWindowBitsTooHigh FAILED
java.lang.AssertionError: expected:<0> but was:<1>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.junit.Assert.assertEquals(Assert.java:146)
at okhttp3.OkHttpClientTestRule.ensureAllConnectionsReleased(OkHttpClientTestRule.kt:134)
at okhttp3.OkHttpClientTestRule$apply$1.evaluate(OkHttpClientTestRule.kt:178)
at okhttp3.testing.PlatformRule$apply$1.evaluate(PlatformRule.kt:69)
at okhttp3.TestLogHandler$1.evaluate(TestLogHandler.java:50)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
```
> Rethrow original failure in OkHttpClientTestRule

- okhttp/src/main/kotlin/okhttp3/internal/ws/RealWebSocket.kt
Pretty sure that with correct locking that this *already* can't be null.  The syncrhonized memory barrier in writePingFrame, which happens via the task runner, should always be after the syncrhonized memory barrier in initReaderAndWriter.
But this subtle change should be a noop but delay the ping if we find ourselves somehow with null.
To address https://github.com/square/okhttp/issues/5705
> Avoid any chance at NPE in RealWebSocket

- okhttp-sse/src/main/kotlin/okhttp3/sse/EventSources.kt
- okhttp-sse/src/test/java/okhttp3/internal/sse/EventSourceHttpTest.java
Low urgency, but easy enough to implement or close won't fix.
Addresses https://github.com/square/okhttp/issues/6038
> Set implicit Accept for EventSource

- okhttp-testing-support/src/main/kotlin/okhttp3/ClientRuleEventListener.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
https://github.com/square/okhttp/issues/6033
Assuming this is due to race conditions immediately after shutdown with websocket, allow for 500ms extra before failing.  Will record which tests see delays, so we can query for this.
> Attempt to minimise WebSocket test flakiness

- okhttp/src/main/java/okhttp3/internal/platform/Android10Platform.java
- okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java
- okhttp/src/main/java/okhttp3/internal/platform/Platform.java
Fix for OkHttp platform issues in AndroidStudio (e.g. when running as a plugin)
square/retrofit#3389
> Fix isAndroid check [3.14.x]

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/InsecureAndroidTrustManager.kt
As raised in https://github.com/square/okhttp/issues/6062 and fix suggested by @mattinger, we had a typo in the Android implementation.
> Fix for insecureHost on Android

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
We don't check for this, and leave it to the caller to avoid calling the new method on < 24.  So our tests need to do the same.
> Make the Android tests pass on <= 23

- okhttp/src/main/kotlin/okhttp3/internal/platform/Platform.kt
The Platform Companion ordering means that a Boolean field and the Platform instance field can race.
> Fix Android Platform init

- okhttp-brotli/src/main/kotlin/okhttp3/brotli/BrotliInterceptor.kt
- okhttp-brotli/src/test/java/okhttp3/brotli/BrotliInterceptorTest.kt
This PR fix `BrotliInterceptor` error when handle HEAD request, or 204 no content response:
```
java.io.IOException: Brotli stream decoding failed
at org.brotli.dec.BrotliInputStream.read(BrotliInputStream.java:167)
at okio.InputStreamSource.read(JvmOkio.kt:90)
at okio.RealBufferedSource.select(RealBufferedSource.kt:231)
at okhttp3.internal.Util.readBomAsCharset(Util.kt:259)
at okhttp3.ResponseBody.string(ResponseBody.kt:187)
at okhttp3.brotli.BrotliInterceptorTest.testSkipUncompressNoContentResponse(BrotliInterceptorTest.kt:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at …
```
> Fix BrotliInterceptor failing to handle No content response

- okhttp/src/main/kotlin/okhttp3/internal/platform/android/AndroidLog.kt
On older Android this causes a crash, other non-test loggers are handled already via AndroidLog mappings.
> Handle tests that try to log via MockWebServer

- docs/concurrency.md
- okhttp/src/main/kotlin/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.java
Previously we were locking the RealConnectionPool for all
connection-related state, including cancelation.
This changes the locks to be per-Connection, leaning heavily
on thread-confined fields in RealCall, Exchange, and
ExchangeFinder.
> Use finer-grained locks in the connection pool

- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/main/kotlin/okhttp3/internal/cache/CacheInterceptor.kt
- okhttp/src/main/kotlin/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
Recent refactorings have made it clear that there's three things
we need to be done before we can release the connection:
- the request body
- the response body
- the series of exchanges
This changes the code to invert these booleans. In a follow-up I'd
like to add some defensive code around duplex calls where the request
and response body could race when they close.
> Tidy up the code that does connection releasing in RealCall

- okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
This is mostly necessary because we have a possibility of duplex
calls.
> Add limited locking around the end of the call

- docs/interceptors.md
- okhttp/src/main/kotlin/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/test/java/okhttp3/InterceptorTest.java
Timeout mostly take effect before we have a connection, so rely on being adjusted in the application interceptors.
Instead of fixing the limitation highlighted here https://github.com/square/okhttp/issues/6100, simplify clarify that adjusting timeouts must be done in application interceptors.
An alternative implementation would simply ignore these updates, but that seems worse longer term for support requests "Why is my timeout ignored".  These are only used in ExchangeFinder before networkInterceptors fire.
> Clarify Interceptor timeout docs

- okhttp/src/test/java/okhttp3/internal/http/CancelTest.kt
BouncyCastle isn't known to work with MockWebServer.
> Avoid BouncyCastle failures

- okhttp/src/main/kotlin/okhttp3/internal/platform/Android10Platform.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/AndroidPlatform.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/Android10SocketAdapter.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/AndroidSocketAdapter.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/BouncyCastleSocketAdapter.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/ConscryptSocketAdapter.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/DeferredSocketAdapter.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/SocketAdapter.kt
- okhttp/src/main/kotlin/okhttp3/internal/platform/android/StandardAndroidSocketAdapter.kt
- okhttp/src/test/java/okhttp3/internal/platform/android/AndroidSocketAdapterTest.kt
Avoid https://github.com/square/okhttp/issues/5760, by deferring work from building the platform until when it first encounters an unknown socket type.
This is high priority because the log warning causes a lot of bad stackoverflow advice to add conscrypt dependencies, which is not the intention. https://stackoverflow.com/search?q=org.conscrypt.ConscryptHostnameVerifier
> Another layer of indirection to defer Conscrypt init

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/BasicDerAdapter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerAdapter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerHeader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerWriter.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
Previously the caller was responsible for decoding the tag on the
adapter it called. This was easy for basic tags, but proved problematic
for tags like CHOICE and ANY and typehint-dependent tags, because the
caller didn't have enough information.
This moves the tag reading and writing into the DerAdapter itself. If
it encounters a tag it can't understand, it assumes it's own value has
been skipped and returns a default.
This turns out to be a bit easier to reason about, and hopefully will
make it easier to implement AlgorithmIdentifier.parameters, which has
values that are optional or not depending on what the type hint is.
> Move tag management in DerAdapters

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerAdapter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerWriter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/ObjectIdentifiers.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/certificates.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
This gets us to the point where the byte-for-byte encoding is equiavalent
to what bouncycastle was producing.
This shook out some bugs:
- We weren't boxing the version
- We weren't clearing the constructed bit on boxed extensions
- We weren't encoding null when we needed to be
> Fix bugs so we can roundtrip certificates

- okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/ObjectIdentifiers.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/certificates.kt
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
We don't implement the full feature set that Bouncycastle has, but
we also don't need it.
In follow up changes I intend to remove the Bouncycastle dependency
for everything but some test cases.
> Use OkHttp's certificate creation code

- okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/certificates.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
PKCS8 is a PrivateKeyInfo
PKCS1 is the private key field of a PKCS8
We need to do a simple unboxing to go from one to the other.
> Stop using Bouncycastle to do PKCS8 to PKCS1

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
We switch to 4-digit years at the last possible moment.
> Honor RFC 5280 when choosing a time format

- okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/BasicDerAdapter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerAdapter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerWriter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/ObjectIdentifiers.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/certificates.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
Improve docs, fix some names, fix some internal APIs.
> Improve code style for the new DER package

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
With this change `DerReader` doesn't support reading values with a length greater than `Long.MAX_VALUE`. That shouldn't be a problem in practice.
> Add limits to what length values DerReader supports

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
This is a feature of ASN.1 that DER doesn't use, and in fact it forbids.
> Drop support for indefinite length in DER

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/BasicDerAdapter.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/test/java/okhttp3/tls/HeldCertificateTest.java
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
We don't have API support for all of them, but we shouldn't crash when an
unsupported name is encountered.
Also encode attributes using UTF-8, not PrintableString. Both are permitted,
but UTF-8 supports more data.
> Don't crash on unknown GeneralName types.

- docs/security.md
OkHttp 4.x is our only branch receiving security fixes, bug fixes, and
new features.
OkHttp 3.12.x gets security fixes only.
> Push OkHttp 3.14.x into the sea. It is no longer supported.

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/CertificateAdapters.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
If the date is before 1950-01-01, use a four-digit year
If the self-delimiting object identifer exceeds the enclosing object's
size, fail.
If a nested object exceeds its enclosing object's size, fail.
> Add defensive checks for malformed ASN.1 DER

- okhttp-tls/build.gradle
- okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt
This potentially changes behavior for applications requiring security
features that are available in Bouncy Castle but not the platform. To
mitigate this, execute this before such operations:
Security.addProvider(BouncyCastleProvider())
You will also need to configure this dependency:
implementation "org.bouncycastle:bcprov-jdk15on:1.65"
> Don't install the Bouncy Castle provider in HeldCertificate

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/certificates.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerCertificatesTest.kt
May not be present, as seen in signing (CA) certs instead of host certificates.
> Allow missing SAN in certificates

- okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp/src/main/kotlin/okhttp3/internal/io/FileSystem.kt
Graal and Kotlin don't like interfaces without any default methods. Continuation of https://github.com/square/okhttp/pull/5631/files
https://youtrack.jetbrains.com/issue/KT-33097
> Avoid DefaultImpls bug

- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/Adapters.kt
- okhttp-tls/src/test/java/okhttp3/tls/internal/der/DerTest.kt
The time zone must be 'Z', and cannot be an offset like '+0000'. That
is allowed by ASN.1 but not by DER.
Closes: https://github.com/square/okhttp/issues/6210
> Implement DER constraints on date formats

- android-test/build.gradle
- build.gradle
- okhttp/src/main/kotlin/okhttp3/internal/platform/ConscryptPlatform.kt
New release unfortunately changes the ConscryptHostnameVerifier interface
https://groups.google.com/d/msgid/conscrypt/fe34caac-4cdb-4e64-b877-ea8cd0ca8b64n%40googlegroups.com?utm_medium=email&utm_source=footer
https://github.com/google/conscrypt/issues/877
> Conscrypt 2.5.0 upgrade

- okhttp/src/main/kotlin/okhttp3/HttpUrl.kt
As flagged in https://github.com/square/okhttp/issues/6252, the HttpUrl docs refer to hosts that no longer demonstrate the equals problem.
> Fix HttpUrl documentation

- build.gradle
See stackoverflow for why this is required, related to the gradle daemon.
https://stackoverflow.com/a/34717160/1542667
I don't currently have any concern that their is a logic bug with string encodings in src/main, but rather that strings in tests are compiled assuming the wrong file encoding, changing the test meaning.
> Fix build on windows

- android-test/README.md
- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
When complete, this should allow folks running the android-test more success.
Depends on feedback in general and specifically here https://github.com/square/okhttp/pull/6008#discussion_r496553972
> Lints android-test

- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
The server can reject the request without breaking the response.
> Confirm we can read a response that completed before RST_STREAM

- okhttp-sse/src/main/kotlin/okhttp3/sse/EventSources.kt
- okhttp-sse/src/main/kotlin/okhttp3/sse/internal/RealEventSource.kt
- okhttp-sse/src/main/kotlin/okhttp3/sse/internal/ServerSentEventReader.kt
- okhttp-sse/src/test/java/okhttp3/sse/internal/Event.java
- okhttp-sse/src/test/java/okhttp3/sse/internal/EventSourceHttpTest.java
- okhttp-sse/src/test/java/okhttp3/sse/internal/EventSourceRecorder.java
- okhttp-sse/src/test/java/okhttp3/sse/internal/ServerSentEventIteratorTest.java
I think this is slightly neater from an OSGi/JPMS perspective.
> Rename okhttp3.internal.sse to okhttp3.sse.internal

- mkdocs.yml
https://github.com/square/okhttp/issues/6217#issuecomment-674831404 mentions the removal of edit links, so this closes #6217 
Ran `mkdocs build` locally.
Before:
```
<div class="md-content">
<article class="md-content__inner md-typeset">
<a href="https://github.com/square/okhttp/edit/master/docs/interceptors.md" title="Edit this page" class="md-content__button md-icon">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20.71 7.04c.39-.39.39-1.04 0-1.41l-2.34-2.34c-.37-.39-1.02-.39-1.41 0l-1.84 1.83 3.75 3.75M3 17.25V21h3.75L17.81 9.93l-3.75-3.75L3 17.25z"/></svg>
</a>
<h1 id="interceptors">Interceptors<a class="headerlink" href="#interceptors" title="Permanent link">&para;</a></h1>
<p>Interceptors are a powerful mechanism that can monitor, rewrite, and retry calls. …
```
> Disable edit links

- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/MockResponse.kt
- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/SocketPolicy.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/main/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/ServerTruncatesRequestTest.kt
> Read the response even if writing the request fails

- .github/workflows/codeql-analysis.yml
Created a `codeql-analysis.yml` to configure GitHub workflow for code scanning.
* Added Setup Java action to override default Java 8.
* Added custom build command from CircleCI yml commented out in case CodeQL autobuild fails in the future.
> Enable GitHub Code Scanning

- build.gradle
Most relevant is probably https://github.com/square/okio/pull/778
Also unblocks OSGi support.
> Okio and Moshi dependency upgrades

- native-image-tests/README.md
- native-image-tests/build.gradle
- native-image-tests/src/main/kotlin/okhttp3/SampleTest.kt
- settings.gradle
I want to confirm all of OkHttp works with Graalvm, and I'm hoping
to demonstrate that by getting the entire test suite running inside
Graalvm.
https://github.com/square/okhttp/issues/6296
If we get that all working, we’re good. For bonus points it’d be nice to upstream this mechanism into the Graal plugin, or something standalone. It’d be quite rad to make Graalvm unit testing not dramatically more complicated than regular unit testing.
> Initial steps towards running tests in Graalvm

- okhttp/src/main/resources/META-INF/proguard/okhttp3.pro
Update Proguard rule to hide the following warning:
`Missing class: org.conscrypt.ConscryptHostnameVerifier`
> R8 warning during the build OkHttp 4.9.0 #6299

- mockwebserverwrapper/build.gradle
- mockwebserverwrapper/src/main/kotlin/okhttp3/mockwebserverwrapper/Dispatcher.kt
- mockwebserverwrapper/src/main/kotlin/okhttp3/mockwebserverwrapper/MockResponse.kt
- mockwebserverwrapper/src/main/kotlin/okhttp3/mockwebserverwrapper/MockWebServer.kt
- mockwebserverwrapper/src/main/kotlin/okhttp3/mockwebserverwrapper/PushPromise.kt
- mockwebserverwrapper/src/main/kotlin/okhttp3/mockwebserverwrapper/QueueDispatcher.kt
- mockwebserverwrapper/src/main/kotlin/okhttp3/mockwebserverwrapper/RecordedRequest.kt
- mockwebserverwrapper/src/main/kotlin/okhttp3/mockwebserverwrapper/SocketPolicy.kt
- mockwebserverwrapper/src/main/kotlin/okhttp3/mockwebserverwrapper/bridge.kt
- mockwebserverwrapper/src/test/java/okhttp3/mockwebserverwrapper/MockWebServerTest.java
- settings.gradle
This is step 1 of a plan to break MockWebServer's dependency on JUnit 4.
1. New module, mockwebserverwrapper: implement almost all of the mockwebserver
API by delegating to the real mockwebserver API.
2. Swap the names. Rename the package okhttp3.mockwebserver to mockwebserver3,
and rename okhttp3.mockwebserverwrapper to okhttp3.mockwebserver. With this
rename all users of MockWebServer are now using the wrapper instead.
3. Change mockwebserver3 to not depend on JUnit 4.
4. Migrate callers from the okhttp3.mockwebserver wrapper to mockwebserver3,
dropping their JUnit dependency along the way. It may take a very long time
for callers to migrate. That's okay; the wrapper isn't much code to maintain.
Notable breaks in binary compatibility:
- Duplex is not supported in the wrapper. This was …
> MockWebServer wrapper

- okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/internal/utf8.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/IsProbablyUtf8Test.kt
As part of review comments from https://github.com/square/okhttp/pull/6340/files, cleaning up unrelated changes.
> Move isProbablyUtf8 from kotlin internal to package named internal.

- okhttp/src/main/kotlin/okhttp3/CacheControl.kt
Building with JDK15 and Kotlin 1.4 is bad juju.
https://youtrack.jetbrains.com/issue/KT-42721
> Avoid isEmpty() in CacheControl

- native-image-tests/build.gradle
"android.injected.invoked.from.ide" is tied to the Android plugin.  XPC_SERVICE_NAME seems to be set by Intellij.
https://stackoverflow.com/questions/64726619/how-to-detect-if-gradle-plugin-is-running-inside-of-intellij/64726656#64726656
> Avoid duplicate source roots in Intellij

- native-image-tests/build.gradle
On windows the existing checks aren't enough
https://github.com/JetBrains/intellij-community/blob/f396a4f0777cc1e79908a637f9f814eda794d3f8/native/WinLauncher/WinLauncher/WinLauncher.cpp#L1199
> Fix windows IDE detection

- native-image-tests/build.gradle
- native-image-tests/src/main/kotlin/okhttp3/TestRegistration.kt
- okhttp/src/main/resources/META-INF/native-image/okhttp/okhttp/reflect-config.json
```
├─ noRecoveryFromTwoRefusedStreams(Protocol, MockWebServer) ✔
│  ├─ [1] h2_prior_knowledge ✘ Could not initialize class kotlin.internal.PlatformImplementationsKt
│  └─ [2] h2 ✘ Could not initialize class kotlin.internal.PlatformImplementationsKt
```
and
```
│  ├─ readerBomUtf16Be() ✔
│  ├─ readerBomUtf16Le() ✔
│  ├─ readerBomUtf32Be() ✘ UTF-32BE
│  ├─ readerBomUtf32Le() ✘ UTF-32LE
```
> Workaround native image charset and kotlin issue

- okhttp/src/test/java/okhttp3/CallHandshakeTest.kt
First PR to confirm ordering of existing functionality.  Relates to https://github.com/square/okhttp/issues/6390
> Test current behaviour of cipher suite ordering

- okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
- okhttp/src/main/kotlin/okhttp3/ConnectionSpec.kt
- okhttp/src/main/kotlin/okhttp3/internal/internal.kt
- okhttp/src/test/java/okhttp3/CallHandshakeTest.kt
Without changing any behaviour, document and test the effective order of ciphers before any changes in 4.11.
> Assert on effective order

- okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
Another attempt at  https://github.com/square/okhttp/pull/6405
This broken native-image-tests
```
➜  okhttp git:(master) ✗ ./native-image-tests/build/graal/ConsoleLauncher 
FF
╷
└─ JUnit Jupiter ✔
└─ CacheCorruptionTest ✔
├─ corruptedCipher() ✘ java.lang.ExceptionInInitializerError
└─ truncatedMetadataEntry() ✘ Could not initialize class org.assertj.core.api.Assumptions
```
> Fix for native image and assumptions

- android-test/build.gradle
Avoids the following
```
org.bouncycastle.jsse.provider.test.KeyManagerFactoryTest > testRSAServerTrustEE[2.7_QVGA_API_22(AVD) - 5.1.1] FAILED
java.security.KeyStoreException: java.security.NoSuchAlgorithmException: KeyStore JKS implementation not found
at java.security.KeyStore.getInstance(KeyStore.java:119)
org.bouncycastle.jsse.provider.test.KeyManagerFactoryTest > testRSAServerWithClientAuth[2.7_QVGA_API_22(AVD) - 5.1.1] FAILED
java.security.KeyStoreException: java.security.NoSuchAlgorithmException: KeyStore JKS implementation not found
at java.security.KeyStore.getInstance(KeyStore.java:119)
org.bouncycastle.jsse.provider.test.PSSCredentialsTest > testPSSCredentials[2.7_QVGA_API_22(AVD) - 5.1.1] FAILED
java.security.NoSuchAlgorithmException: KeyPairGenerator RSASSA-PSS implementation …
```
> Avoid bouncy castle tests in Android

- android-test/build.gradle
- regression-test/build.gradle
- regression-test/src/androidTest/java/okhttp/regression/LetsEncryptTest.java
Test confirming example code to workaround the Let's Encrypt expiry event.
https://stackoverflow.com/questions/64844311/certpathvalidatorexception-connecting-to-a-lets-encrypt-host-on-android-n-or-ea
> Let's encrypt regression test

- native-image-tests/src/main/kotlin/okhttp3/DotListener.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/TestUtil.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
```
h2 ✘ Cannot determine correct type for matchesSafely() method.
```
from Hamcrest
```
fun fromMajor(version: Int): Matcher<PlatformVersion> {
return object : TypeSafeMatcher<PlatformVersion>() {
override fun describeTo(description: Description) {
description.appendText("JDK with version from $version")
}
override fun matchesSafely(item: PlatformVersion): Boolean {
return item.majorVersion >= version
}
}
}
```
> Fix single failing graal test

- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
Add extra explication and context to better understand newBuilder impact.
inform that the configuration of the original instance is kept
inform that a configuration of the original instance may be overriden
> Patch doc shareinstance / new builder

- README.md
It is hard to find evidence of OkHttp BOM existing, since it is mentioned only in [release notes to 4.4.0 version](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-440). For example, I didn't know about it until needed to read through changes for a few versions. Today had a conversation with a friend who also wasn't aware about BOM being available.
To help more people discover OkHttp BOM I updated the README to mention it clearly, so it will be easy to find.
> Add BOM mention to Releases section

- okhttp/src/main/kotlin/okhttp3/internal/platform/Jdk9Platform.kt
JDK 9 doesn't support reflection to get the trust manager.  (Un)Fortunately this code path is also used on JDK8 now that it supports ALPN, so make the message clearer.
> Fix trustManager message on JDK 8

- okhttp-tls/src/main/kotlin/okhttp3/tls/HandshakeCertificates.kt
Fail early and predictably on unencodable keys.
Meant to catch
https://github.com/square/okhttp/issues/5172
https://github.com/square/okhttp/issues/6116
https://github.com/square/okhttp/issues/5684
> Fail on unencodable keys

- okhttp/src/main/kotlin/okhttp3/internal/platform/ConscryptPlatform.kt
In certain cases, Conscrypt returns a null version. Treat Conscrypt as
not available in these cases, since the version information is unknown.
Fixes #6502.
> Gracefully handle null Conscrypt version

- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/main/kotlin/okhttp3/HttpUrl.kt
- okhttp/src/test/java/okhttp3/CacheCorruptionTest.kt
- okhttp/src/test/java/okhttp3/HttpUrlTest.java
Fail earlier on cache corruption, log warning instead of failing terminally.
> Fail earlier on cache corruptions

- okhttp/src/main/kotlin/okhttp3/FormBody.kt
- okhttp/src/main/kotlin/okhttp3/HttpUrl.kt
- okhttp/src/test/java/okhttp3/FormBodyTest.java
url-encoded form data should encode ` `   into `+` for percent-encoding when content-type is `application/x-www-form-urlencoded `
Also, `FORM_ENCODE_SET` updated with `+` sign to align with w3 character set to be encoded.
Reference: [W3 url encoded form data](https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1)
Issue: #6323
> url encoded form data uses '+' for ' ' according to w3

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Update to Gradle 6.8.1.  Use specific toolchain vendor, and move repositories out of submodules to settings.
> Gradle upgrade, more specific toolchain

- okhttp/src/test/java/okhttp3/CallHandshakeTest.kt
- okhttp/src/test/java/okhttp3/RecordedResponse.java
- okhttp/src/test/java/okhttp3/internal/tls/HostnameVerifierTest.java
Failures from unrelated latest build https://github.com/square/okhttp/commit/51211ea63954073908bc21471527a0e01057a4b3
JDK 8 now supporting TLS 1.3 https://www.oracle.com/java/technologies/javase/8u261-relnotes.html
> Handle specific test failures on master

- okhttp/src/main/kotlin/okhttp3/internal/Util.kt
Closes: https://github.com/square/okhttp/issues/6509
> Silently ignore 'bio == null' NullPointerExceptions (4.9.x)

- okhttp/src/main/java/okhttp3/internal/Util.java
Closes: https://github.com/square/okhttp/issues/6509
> Silently ignore 'bio == null' NullPointerExceptions (3.12.x)

- okhttp/src/main/kotlin/okhttp3/internal/Util.kt
Closes: https://github.com/square/okhttp/issues/6509
> Silently ignore 'bio == null' NullPointerExceptions

- native-image-tests/build.gradle
- okhttp/src/test/java/okhttp3/CallTest.java
- okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
From https://app.circleci.com/pipelines/github/square/okhttp/4491/workflows/e4faf0ea-4127-400c-a66f-43d18a8d515e/jobs/20378
Recent JDK8 improvements are making being specific about behaviour on JDK 8 awkward.
> Fix build for jdk8

- okhttp/src/main/kotlin/okhttp3/HttpUrl.kt
If an attacker is leveraging the fact that ™ might render as tm, they
would use ho™ail.com as the domain to masquerade hotmail.com.
> Fix ho™ail.com example.

- okhttp/src/main/kotlin/okhttp3/Cache.kt
Now that `Cache$Entry.url` is an `HttpUrl`, we can delegate the call to `HttpUrl.isHttps`.
> Replace custom isHttps with HttpUrl's

- okhttp-testing-support/src/main/kotlin/okhttp3/JsseDebugLogging.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpDebugLogging.kt
Simplifies the tedious work to setup java.util.logging to capture the useful bits of JSSE handshakes.
Example usage:
```
val logSubscription = JsseDebugLogging.enableJsseDebugLogging {
if (it.type == JsseDebugLogging.JsseDebugMessage.Type.Handshake) {
println(it)
}
}
...
logSubscription.close()
```
```
No session to resume.
Produced ClientHello handshake message
"ClientHello": {
"client version"      : "TLSv1.2",
"random"              : "00 EA 5D 1C 75 39 7B 1A A4 31 8D 5F CD F8 27 58 74 1C 66 2B 07 3B B4 37 A3 EB F8 8C 2F 30 64 48",
"session id"          : "66 9B 0D 68 5B 47 CC 8C AB E5 6B 74 4A C7 CD 01 8F 39 0F C2 B1 79 86 A0 E2 D7 92 A6 2B 61 BD AB",
"cipher suites"       : "[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_CHACHA20_POLY1305_SHA256(0x1303), …
```
> Add debug helper for JSSE Handshakes

- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/test/java/okhttp3/CacheTest.java
Make Cache API public, and test capturing events.
> Public Cache API and test

- okhttp/src/main/kotlin/okhttp3/internal/internal.kt
- okhttp/src/test/java/okhttp3/JSSETest.kt
```
$ ./gradlew :native-image-tests:compileKotlin
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
> Task :native-image-tests:compileKotlin
w: /Users/yschimke/workspace/okhttp/native-image-tests/src/main/kotlin/okhttp3/SampleTest.kt: (64, 18): Parameter 'mode' is never used
w: /Users/yschimke/workspace/okhttp/okhttp/src/test/java/okhttp3/SessionReuseTest.kt: (58, 9): Name shadowed: tlsVersion
w: /Users/yschimke/workspace/okhttp/okhttp/src/test/java/okhttp3/SocketChannelTest.kt: (123, 18): 'supportsTlsExtensions(Boolean): ConnectionSpec.Builder' is deprecated. since OkHttp 3.13 all TLS-connections are expected to support TLS extensions.
In a future release setting this to true will be unnecessary and setting it to false
will have no effect. …
```
> Add internal accessor for connection

- android-test/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- native-image-tests/build.gradle
- settings.gradle.kts
Being automatic was a lofty goal that makes the experience in IDE unpredictable.  Particularly while IDE and command line are sharing daemons. Switch to a simpler model.
- By default build in IDE and command line/daemon without Android and Graal builds
- Allow -PandroidBuild or -PgraalBuild to include additional modules and overlapping source paths
This isn't a great situation, but OkHttp has so many different builds to consider
- JDK vs Android vs Graal
- JDK 8, 11, 16
- Platform - JSSE, Conscrypt, etc
And ultimately it seems really tough to get something that works automatically within Intellij without finding weirdness with plugins or on branch switches when reimporting gradle.
> Simplify our secondary gradle modules

- .github/workflows/build.yml
8.0.242 is the last alpn-boot relevant JDK.  Want a setup that could mostly work locally or in CI to replicate compiling against 11, then running tests against 8.0.242.
> ALPN builds

- .gitignore
No use configuring as names can vary locally. Since we use gradle toolchains, it's basically only a default for ./gradlew to avoid pain when having a bleeding edge JDK like 16/17 installed.
> Ignore jenv file

- okhttp/src/test/java/okhttp3/ConscryptTest.kt
- okhttp/src/test/java/okhttp3/CorrettoTest.kt
- okhttp/src/test/java/okhttp3/internal/platform/android/AndroidSocketAdapterTest.kt
Avoid a potential source of providers conflict
```
JSSETest > testSupportedProtocols() FAILED
org.opentest4j.AssertionFailedError:
Expecting:
<"org.conscrypt.OpenSSLSocketFactoryImpl">
to be equal to:
<"sun.security.ssl.SSLSocketFactoryImpl">
but was not.
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at okhttp3.JSSETest.testSupportedProtocols(JSSETest.kt:87)
```
> Avoid actively setting conscrypt

- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java
Seeing this in CI a few times
```
HttpOverHttp2Test > responseHeadersAfterGoaway(Protocol, MockWebServer) > okhttp3.internal.http2.HttpOverHttp2Test.responseHeadersAfterGoaway(Protocol, MockWebServer)[2] FAILED
org.opentest4j.AssertionFailedError: 
Expecting:
<null>
to be equal to:
<"ABC">
but was not.
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at okhttp3.internal.http2.HttpOverHttp2Test.responseHeadersAfterGoaway(HttpOverHttp2Test.java:1814)
```
> Slightly more generous timeout in HttpOverHttp2Test

- okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
Seeing in CI
```
ClientAuthTest > missingClientAuthFailsForNeeds() FAILED
java.io.IOException: exhausted all routes
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:132)
at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
at …
```
> Allow exhausted all routes in ClientAuthTest

- README.md
From https://github.com/square/okhttp/issues/6704
> Document that GraalVM support is on 5.0.0-alpha.2 and later.

- .github/workflows/build.yml
Make sure we have a good set of builds on the 4.9.x branch.
> Github 4.9.x builds

- .github/workflows/build.yml
- okhttp/src/main/kotlin/okhttp3/internal/platform/Platform.kt
After confirmed results on original bug report, this will need to be backported to 4.9.x and 3.12.x
https://github.com/square/okhttp/issues/6694
> Handle strict module handling on JDK17

- android-test/build.gradle
- okhttp-dnsoverhttps/build.gradle
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsOverHttpsTest.java
DnsOverHttpsTest.usesCache presumably used an invalid path on Android, now using a Fake FileSystem.
> Fix tests for android

- mockwebserver/src/main/kotlin/mockwebserver3/QueueDispatcher.kt
- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.java
Regarding https://github.com/square/okhttp/issues/6620
The main patch is `mockwebserver/src/main/kotlin/mockwebserver3/QueueDispatcher.kt` with the test in `mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.java`.
Everything else was just fixed to satisfy the interface class. If you want a smaller patch or do not want a change in the interface I could also make `clear()` with a default implementation that does nothing. The only drawback would be that new implementations of the Dispatcher interface would then miss to override the clear method. But on the other hand, who would ever want to add another implementation anyway. Your choice.
> Added Dispatched.clear() method for testing

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- okhttp-sse/src/main/kotlin/okhttp3/sse/internal/ServerSentEventReader.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/RecordingEventListener.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerReader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/der/DerWriter.kt
- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/main/kotlin/okhttp3/Challenge.kt
- okhttp/src/main/kotlin/okhttp3/Cookie.kt
- okhttp/src/main/kotlin/okhttp3/FormBody.kt
- okhttp/src/main/kotlin/okhttp3/Headers.kt
- okhttp/src/main/kotlin/okhttp3/HttpUrl.kt
- okhttp/src/main/kotlin/okhttp3/MediaType.kt
- okhttp/src/main/kotlin/okhttp3/MultipartBody.kt
- okhttp/src/main/kotlin/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/main/kotlin/okhttp3/internal/hostnames.kt
- okhttp/src/main/kotlin/okhttp3/internal/http/HttpHeaders.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Hpack.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/main/kotlin/okhttp3/internal/publicsuffix/PublicSuffixDatabase.kt
- okhttp/src/main/kotlin/okhttp3/internal/tls/OkHostnameVerifier.kt
```kotlin
@Deprecated("Conversion of Char to Number is deprecated. Use Char.code property instead.", ReplaceWith("this.code"))
@DeprecatedSinceKotlin(warningSince = "1.5")
public fun toInt(): Int
```
```kotlin
@Deprecated("Conversion of Char to Number is deprecated. Use Char.code property instead.", ReplaceWith("this.code.toByte()"))
@DeprecatedSinceKotlin(warningSince = "1.5")
public fun toByte(): Byte
```
> Replace deprecated methods

- okhttp/src/test/java/okhttp3/JSSETest.kt
See https://java.com/en/configure_crypto.html#DisableTLS
> Remove older TLS versions on JDK 291+

- okhttp/src/test/java/okhttp3/CallHandshakeTest.kt
Security backports to JDK8 are correcting behaviour on openjdk 1.8.
> Allow test passing on JDK 8

- okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
With recent JDK 8 changes, some of the JDK 9 behaviour is also seen on JDK 8 also.
This removes some checks last edited here https://github.com/square/okhttp/pull/5263/files for conscrypt.
> Allow ClientAuthTest changes on JDK8 after security updates.

- okcurl/build.gradle.kts
According to the [picocli-codegen document](https://github.com/remkop/picocli/blob/master/picocli-codegen/README.adoc#kotlin-projects-using-gradle), the `picocliCompiler` should be used with `kapt`.
> Kapt picocliCompiler in okcurl module

- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskLogger.kt
- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/TestLogHandler.java
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
Seeing this a lot recently, bleedover from another test with delayed logging.
```
TaskRunnerTest > cancelReturnsTruePreventsNextExecution() FAILED
java.lang.AssertionError: 
Expecting:
<["FINE: Q10000 scheduled after 100 µs: task",
"FINE: Q10001 finished run in 498 ms: MockWebServer /127.0.0.1:50232",
"FINE: Q10000 canceled              : task"]>
to contain exactly (and in same order):
<["FINE: Q10000 scheduled after 100 µs: task",
"FINE: Q10000 canceled              : task"]>
but some elements were not expected:
<["FINE: Q10001 finished run in 498 ms: MockWebServer /127.0.0.1:50232"]>
at okhttp3.internal.concurrent.TaskRunnerTest.cancelReturnsTruePreventsNextExecution(TaskRunnerTest.kt:184)
```
> Avoid task logger flakes due to shared logger.

- docs/recipes.md
Markdown coverts text with four leading spaces into a code block. Fenced code blocks in this file had four leading spaces in addition to the being wrapped with ```, because of this the code blocks weren't being rendered properly in the markdown preview.
Removing the two out of the four leading spaces fixed the issue.
> Fixed leading spaces for code blocks in recipes.md

- samples/crawler/build.gradle.kts
@JakeWharton 
Basic usage:
```
$ gradlew samples:crawler:run
Configuration on demand is an incubating feature.
> Task :samples:crawler:run
Usage: Crawler <cache dir> <root>
BUILD SUCCESSFUL in 1s
14 actionable tasks: 1 executed, 13 up-to-date
```
Usage with website:
```
$ gradlew samples:crawler:run
> Task :samples:crawler:run
200: https://jaredsburrows.com/ (cache)
200: https://jaredsburrows.com/presentations (cache)
200: https://jaredsburrows.com/the-road-to-single-dex/ (cache)
```
> Apply application plugin to crawler sample

- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.java
The server can reject the request without breaking the response.
(cherry picked from commit 480c20e46bb1745e280e42607bbcc73b2c953d97)
This fix is so Wire can update its dependency on OkHttp and fix https://github.com/square/wire/issues/2026
> [4.9.x]: Confirm we can read a response that completed before RST_STREAM (#6293)

- okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
When we get an 'exhausted all routes' error, it's important that one of
those exhausted routes is available in the stack trace.
See https://github.com/square/okhttp/pull/6712/files
> Confirm the original TLS exception is available on client auth failures

- okhttp-tests/src/test/java/okhttp3/CookiesTest.java
- okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java
Backport of https://github.com/square/okhttp/pull/6729
Fix for https://github.com/square/okhttp/issues/6897
> Fix quote handling on 3.12 branch

- mockwebserver/src/main/kotlin/mockwebserver3/RecordedRequest.kt
- mockwebserver/src/test/java/mockwebserver3/RecordedRequestTest.java
- okhttp/src/test/java/okhttp3/CallTest.java
Previously we did a reverse DNS lookup. But the correct strategy
is to look at the inbound ':authority' (HTTP/2) or 'Host' (HTTP/1)
header.
See: https://github.com/square/okhttp/pull/6774
> Change how we get a hostname for RecordedRequest.requestUrl

- okhttp/src/main/kotlin/okhttp3/internal/tls/BasicCertificateChainCleaner.kt
- okhttp/src/test/java/okhttp3/CertificateChainCleanerTest.java
- okhttp/src/test/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
This impacts Conscrypt when the server's presented certificates form both
a trusted-but-unpinned chain and an untrusted-but-pinned chain.
Note that the newly-added test passes without any code changes.
See https://github.com/square/okhttp/issues/6648
> Enforce max intermediates in BasicCertificateChainCleaner

- build.gradle.kts
Bintray is not necessary after #6929.
> Remove bintray repo

- buildSrc/src/main/kotlin/artifacts.kt
- okhttp/build.gradle.kts
Follow up PR for #6959, to use extensions and replace deprecated `BundleTaskConvention`.
```java
/**
* BundleTaskConvention for Gradle.
*
* @deprecated Replaced by BundleTaskExtension.
*/
@Deprecated
public class BundleTaskConvention
```
copy the constructor from
```java
private static BundleTaskExtension getBundleTaskExtension(org.gradle.api.tasks.bundling.Jar task) {
BundleTaskExtension extension = task.getExtensions()
.findByType(BundleTaskExtension.class);
if (extension != null) {
return extension;
}
return task.getExtensions()
.create(BundleTaskExtension.NAME, BundleTaskExtension.class, task);
}
```
> Simplify kts

- okhttp/src/commonMain/kotlin/okhttp3/Protocol.kt
HTTP/3 uses the token "h3" in the Application-Layer Protocol Negotiation. The definition is necessary for an interceptor, which implemented HTTP/3.
> Define protocol http3 for the third-part support

- okhttp/src/commonMain/kotlin/okhttp3/Protocol.kt
- okhttp/src/jvmTest/java/okhttp3/ProtocolTest.java
It is better to support HTTP3 draft like h3-29. We can remove this code when drafts are no longer used.
> Support HTTP3 draft as h3-29 as an ALPN token

- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealConnection.kt
Each exchange has 3 places for a connection
- the connection on the call (from a previous redirect, auth challenge, etc.)
- a connection from the pool
- a fresh connection
We query the pool after each blocking step to give ourselves the maximum
chance or connection reuse.
This changes code structure without changing behavior.
> Tidy up ExchangeFinder to split pooling and reuse logic

- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
One behavior change here is we won't fire connectionAcquired()
followed by connectionReleased() if we take an connection from the
pool only to immediately find it's unhealthy.
I'm working towards moving the loop over connect attempts and
fails from RetryAndFollowUpInterceptor and into ExchangeFinder.
(We'll still need some recovery in RetryAndFollowUpInterceptor,
but not connection recovery.)
> Move Connection.isHealthy() checks to where reuse happens

- okhttp-logging-interceptor/src/test/java/okhttp3/logging/LoggingEventListenerTest.java
- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/jvmMain/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/FastFallbackExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RoutePlanner.kt
- okhttp/src/jvmTest/java/okhttp3/FakeRoutePlanner.kt
- okhttp/src/jvmTest/java/okhttp3/FastFallbackTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
This doesn't yet introduce any mechanism to enable or disable
happy eyeballs.
It also doesn't sort IP addresses to alternate IPv6, IPv4
for best success.
It also doesn't limit how many connections are attempted
simultaneously.
It also lacks an appropriate number of tests.
> HappyEyeballs

- okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/jvmTest/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
In order to deterministically test FastFallbackExchangeFinder I need
a test facet that supports several test coordinating:
- the call thread is waiting for either a connection to connect
or for the next-connection timeout (250 ms) to elapse
- the in-flight connection needs to connect
TaskFaker wasn't up to the task for this because it assumed at most
two threads, the test thread and the task thread.
With this change TaskFaker can coordinate multiple task threads
that each run sequentially, as directed by a test thread.
> Rewrite TaskFaker to permit mutiple stalled tasks

- CHANGELOG.md
- docs/4.x/upgrading_to_okhttp_4.md
- docs/changelogs/changelog_3x.md
These sites redirect to [code.cash.app](https://code.cash.app).
> Migrate cashapp.github.io

- docs/assets/css/app.css
Closes #7060 
Removes the CSS responsible for adding the External link icon to URLs pointing away from the Docs.
I initially tried to alter the CSS in such a way that a differently colored icon would be used depending on the color scheme, but this was impossible with my basic skills, so I went ahead and removed it instead.
> Remove external link icon

- okhttp/src/jvmMain/kotlin/okhttp3/EventListener.kt
If handshake fails we won't have a secureConnectEnd.
> Fix typo in event ordering.

- android-test/build.gradle.kts
- mockwebserver-deprecated/build.gradle.kts
- mockwebserver-junit4/build.gradle.kts
- mockwebserver-junit5/build.gradle.kts
- mockwebserver/build.gradle.kts
- native-image-tests/build.gradle.kts
- okcurl/build.gradle.kts
- okhttp-brotli/build.gradle.kts
- okhttp-dnsoverhttps/build.gradle.kts
- okhttp-hpacktests/build.gradle.kts
- okhttp-logging-interceptor/build.gradle.kts
- okhttp-sse/build.gradle.kts
- okhttp-testing-support/build.gradle.kts
- okhttp-tls/build.gradle.kts
- okhttp-urlconnection/build.gradle.kts
- okhttp/build.gradle.kts
- samples/compare/build.gradle.kts
- samples/crawler/build.gradle.kts
- samples/guide/build.gradle.kts
- samples/simple-client/build.gradle.kts
- samples/slack/build.gradle.kts
- samples/static-server/build.gradle.kts
- samples/unixdomainsockets/build.gradle.kts
- settings.gradle.kts
https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors
Ref detekt/detekt/pull/3742
> Enable Gradle's type-safe project accessors

- okhttp/build.gradle.kts
Assertk was previously being brought in as a runtime dependency. It's only used in tests, so let's move it over.
> Move assertk to tests dependencies

- build.gradle.kts
- samples/compare/src/test/kotlin/okhttp3/compare/ApacheHttpClientTest.kt
- samples/guide/build.gradle.kts
Installing on new laptop.
Node 14 missing arm64 https://youtrack.jetbrains.com/issue/KT-49109
JDK 14 doesn't have a downloadable build, so bumping to 17.
> Arm64 Fixes

- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/FastFallbackExchangeFinder.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
We had a bug where we'd attempt multiple new connects if previous connects
failed near-simultaneously.
> Get strict about delaying new connect launches

- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/Exchange.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/FastFallbackExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RoutePlanner.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/SequentialExchangeFinder.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http/RealInterceptorChain.kt
- okhttp/src/jvmTest/java/okhttp3/FakeRoutePlanner.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
This model doesn't work now that we're pulling routes concurrently.
Instead rely on the exchange and connection to track failures.
> Stop tracking failures in RoutePlanner

- docs/features/connections.md
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RoutePlanner.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
We had a bug where calling ConnectPlan.cancel() before ConnectPlan.connectTcp()
would drop the cancel. This is because the rawSocket wasn't created yet to
cancel.
Also document fast fallback on our documentation site.
> Don't leak a connection that's canceled before it connects

- okhttp/src/jvmMain/kotlin/okhttp3/Response.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http/BridgeInterceptor.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt
- okhttp/src/jvmTest/java/okhttp3/CallKotlinTest.kt
Also change internal interceptors to explicitly retain the requests
that were forwarded down the chain.
> Update Response.request docs to track behavior

- docs/works_with_okhttp.md
This PR adds [Failsafe](https://failsafe.dev/okhttp/) to the "works with OkHttp" page. I'm not positive what the scope of that page is meant to be, so hopefully this fits, but if not that's cool. 
Also, I'm not sure what the process is for generating actual docs to the gh-pages branch, but if that's something I should do, I can followup with another PR.
> Add Failsafe to the "works with OkHttp" page

- build.gradle.kts
- buildSrc/src/main/kotlin/artifacts.kt
- gradle/libs.versions.toml
- mockwebserver-deprecated/build.gradle.kts
- okhttp-logging-interceptor/build.gradle.kts
- okhttp-sse/build.gradle.kts
- okhttp-tls/build.gradle.kts
- okhttp-urlconnection/build.gradle.kts
- okhttp/build.gradle.kts
This plugin served us very well for a long time. But the binary
compatibility plugin is better suited for our current situation.
> Remove japicmp

- renovate.json
Grabbed the identified targets from here https://app.renovatebot.com/dashboard#github/square/okhttp/589151568
And https://docs.renovatebot.com/configuration-options/#ignoredeps
> Ignore legacy okttp versions

- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- build.gradle.kts
```
okhttp.android.test.OkHttpTest > testRequest[test(AVD) - 10] FAILED 
org.opentest4j.AssertionFailedError: expected: <200> but was: <404>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
```
> Fix a failing android test and cleanup

- okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/FastFallbackExchangeFinder.kt
- okhttp/src/jvmTest/java/okhttp3/FakeRoutePlanner.kt
- okhttp/src/jvmTest/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
In a race this could cause us to prefer a new connection over
a pooled connection, which violates our invariant that pooled
connections are always used if they're found.
Closes: https://github.com/square/okhttp/issues/7152
> Never put pooled connections in the result queue

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/Http2ConnectionTest.kt
This only occurs when the response body is empty.
Closes: https://github.com/square/okhttp/issues/7167
> Don't interpret headers as trailers after a 100 response

- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/bridge.kt
- mockwebserver/api/mockwebserver3.api
- mockwebserver/src/main/kotlin/mockwebserver3/MockResponse.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/main/kotlin/mockwebserver3/SocketPolicy.kt
- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.java
- okhttp/src/jvmMain/kotlin/okhttp3/Headers.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
- okhttp/src/jvmTest/java/okhttp3/DuplexTest.java
- okhttp/src/jvmTest/java/okhttp3/EventListenerTest.java
Previously this was a SocketPolicy. With this change each
response may carry 0 or more informational responses which
are transmitted before the ultimate response.
> Change how HTTP 1xx responses work in MockWebServer

- okcurl/okcurl
The existing script failed to build and use the okcurl CLI with the following exception:
```
okhttp/okcurl on master via ☕ v11.0.14
❯ ./okcurl
FAILURE: Build failed with an exception.
* What went wrong:
Task 'installDist' not found in project ':okcurl'.
* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 883ms
```
> Fix ./okcurl delegate executable

- build.gradle.kts
- buildSrc/src/main/kotlin/artifacts.kt
> Adopt Kotlin 1.6.20

- okhttp/src/commonMain/kotlin/okhttp3/internal/-ResponseCommon.kt
- okhttp/src/jvmTest/java/okhttp3/internal/ws/WebSocketHttpTest.java
https://github.com/square/okhttp/pull/7205
> Use internal visibility for unreadable response bodies

- okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/android/AndroidSocketAdapter.kt
After turning on HTTPS with MockWebServer 4.9.2 we started seeing the transient `ssl == null` failure described in #5587 on older emulators. 
#5590 attempted to fix the problem, but I don't think the catch it introduced will ever be hit because the problematic NPE is wrapped in an `InvocationTargetException`:
```
11-05 11:53:36.557  5607 23163 E AndroidRuntime: FATAL EXCEPTION: MockWebServer
11-05 11:53:36.557  5607 23163 E AndroidRuntime: Process: com.xxx.xxx.xxx, PID: 5607
11-05 11:53:36.557  5607 23163 E AndroidRuntime: java.lang.AssertionError: java.lang.reflect.InvocationTargetException
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at okhttp3.internal.platform.android.AndroidSocketAdapter.a(SourceFile:86)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at …
```
> Fix Conscrypt NPE workaround

- okhttp/api/okhttp.api
- okhttp/src/jvmMain/kotlin/okhttp3/Call.kt
- okhttp/src/jvmMain/kotlin/okhttp3/OkHttpClient.kt
This was an accident from the time before OkHttpClient was immutable.
> API change: OkHttpClient shouldn't be cloneable

- .github/workflows/build.yml
- android-test/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Bump Kotlin to both fix a CVE (without any clear attack), and also to provide a 4.x version of OkHttp with the major upgrade hit taken early.
This should be a 4.10 build not 4.9.4
> 4.10: Version bump of kotlin, okio.

- okhttp/src/commonMain/kotlin/okhttp3/OkHttp.kt
- okhttp/src/commonMain/kotlin/okhttp3/internal/-UtilCommon.kt
- okhttp/src/commonMain/kotlinTemplates/okhttp3/internal/-InternalVersion.kt
Downstream projects should get the current version, even if they're
not recompiled.
> The version shouldn't be const

- okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/jvmTest/java/okhttp3/DuplexTest.java
Fixes #https://github.com/square/wire/issues/2174
> Delay timeouts on response readings for duplex

- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/bridge.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockResponse.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/main/kotlin/mockwebserver3/SocketPolicy.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
- okhttp/src/jvmTest/java/okhttp3/EventListenerTest.java
- okhttp/src/jvmTest/java/okhttp3/URLConnectionTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
This is the MockWebServer side of changing how HTTP/2 prior knowledge
works with proxies.
https://github.com/square/okhttp/issues/7289
> Change how tunnels are configured with MockWebServer

- mockwebserver/api/mockwebserver3.api
- okhttp/src/jvmMain/kotlin/okhttp3/Route.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
Closes: https://github.com/square/okhttp/issues/7289
> Implement CONNECT tunnels for HTTP/2 prior knowledge

- okhttp/src/jvmMain/kotlin/okhttp3/Request.kt
We've got two overloads that only differ by type arguments.
We need to suppress one to prevent Dokka from crashing.
See: https://github.com/Kotlin/dokka/issues/2473
> Suppress documentation on Request.tag

- okhttp/src/jvmMain/kotlin/okhttp3/MultipartBody.kt
- okhttp/src/jvmTest/java/okhttp3/MultipartBodyTest.java
- okhttp/src/jvmTest/java/okhttp3/MultipartReaderTest.kt
This causes our users grief:
https://github.com/square/okhttp/issues/2604
https://github.com/square/okhttp/issues/2138
I've resisted removing it because it seemed like it'd
break compatibility in a significant way. But with OkHttp 5
it's a good time to break compatibility.
As far as I can tell the behavior of including Content-Length
in multipart bodies is not performed by web browsers or other
HTTP clients.
> Drop the Content-Length header from multipart parts

- okhttp/src/commonMain/kotlin/okhttp3/internal/-CacheControlCommon.kt
The toDuration() function was only introduced in Kotlin 1.6. If using
okhttp3 as part of a gradle 7.4.2 plugin it will run with Kotlin 1.5.31
in the runtime classpath, which results in a NoSuchMethodError.
> Remove usage of toDuration()

- build.gradle.kts
Warning from build
```
w: '-Xjvm-default=compatibility' is deprecated, please use '-Xjvm-default=all|all-compatibility'
```
> jvm-default=all

- okhttp/src/commonMain/kotlin/okhttp3/internal/-CacheControlCommon.kt
- okhttp/src/jvmMain/kotlin/okhttp3/CacheControl.kt
I tried to fix this in https://github.com/square/okhttp/pull/7329 but that didn't work. This reverts that attempt and applies a different fix that seems to work better. See individual commit messages for details.
> Improve runtime compatibility with kotlin 1.5.31

- build.gradle.kts
This should prevent Maven users from needing to change
their dependencies from okhttp to okhttp-jvm. More importantly,
it should also prevent them from inadvertently getting two
different OkHttp JVM artifacts on their classpaths at once.
> Make pom.xml depend on the JVM artifact

- gradle/libs.versions.toml
Addressing issue #7105 
Code blocks were not being rendered properly using KDocs inline markdown in Kotlin classes. I tried to change syntax and still saw formatting issues. This appears to be a bug with Dokka version 1.6.21 for which I raised this issue: https://github.com/Kotlin/dokka/issues/2624
Upgrading Dokka plugin to 1.7.10 seems to fix the issue and code blocks are now rendering, along with syntax highlighting.
Before:
After:
> bugfix(fix_docs_code_blocks): Upgrade Dokka to fix bug with KDocs code blocks

- okhttp/src/jvmMain/kotlin/okhttp3/Dispatcher.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/jvmTest/java/okhttp3/DispatcherCleanupTest.kt
- okhttp/src/jvmTest/java/okhttp3/RecordingExecutor.kt
Testing of https://github.com/square/okhttp/issues/7410
Consider this fix for discussion.  Open to suggestions.
Issue happens because RealCall.executeOn has rejected execute call and falls back to recursive handling.
> Avoid failing on shutdown executor

- deploy_website.sh
Fix the Dokka -> Mkdocs pipeline with md.
#fixes https://github.com/square/okhttp/issues/7338#issuecomment-1221245181
> Post process md links in package-list files.

- okhttp/src/jvmMain/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
Ignore for now to solve https://github.com/square/okhttp/issues/7430
Initial PR from https://github.com/square/okhttp/pull/7196
> Ignore Early Hints (5.x)

- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/MockResponse.kt
- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/SocketPolicy.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/Exchange.kt
- okhttp/src/main/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/main/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/test/java/okhttp3/EventListenerTest.java
- okhttp/src/test/java/okhttp3/ServerTruncatesRequestTest.kt
Addresses https://github.com/square/okhttp/issues/1001
Backported from an early 5.x
> [4.10.x] Read the response even if writing the request fails

- .gitmodules
Move from git to https for cloning hpack-test-case, see here https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Move from git protocol due to deprecation

- okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
Follow up from https://github.com/square/okhttp/issues/6601#issuecomment-1356051159
No point logging SSE and it breaks the request.  So check and avoid any known streaming types.
> Avoid logging SSE

- build.gradle.kts
- deploy_website.sh
- docs/features/https.md
- gradle.properties
- gradle/libs.versions.toml
- mkdocs.yml
- test_docs.sh
Seems to fix the generation, already used by https://square.github.io/workflow/
> Use HTML for docs

- mockwebserver/api/mockwebserver3.api
- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/SpecificHostSocketFactory.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RouteDatabase.kt
- okhttp/src/jvmTest/java/okhttp3/RouteFailureTest.kt
Test for IPv4, IPv6 multiple routes.  When the RouteDatabase is updated, how many follow up requests are made.
> Add tests for multiple routes

- okhttp/src/jvmTest/java/okhttp3/CallKotlinTest.kt
Failing in https://github.com/square/okhttp/actions/runs/3727162591/jobs/6321061224
```
Caused by:
java.lang.AssertionError: 
Expecting actual not to be null
at okhttp3.CallKotlinTest.testHeadAfterPut(CallKotlinTest.kt:186)
```
> Fix testHeadAfterPut failures

- build.gradle.kts
- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.java
When we split jvmTest and jsTest, we lost the tests of JVM-only modules.
> Run all the tests in CI

- samples/compare/src/test/kotlin/okhttp3/compare/JavaHttpClientTest.kt
Invert the logic for testing Content Length of JavaHttpClientTest.
> Fix JavaHttpClientTest tests on JDK 19

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- okhttp-android/src/androidTest/kotlin/okhttp3/android/AndroidAsyncDnsTest.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/testing/PlatformRule.kt
- okhttp-tls/README.md
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/TlsUtil.kt
- okhttp/src/jvmTest/java/okhttp3/OpenJSSETest.kt
- samples/guide/src/main/java/okhttp3/recipes/HttpsServer.java
Just hard-coding 'localhost' is simpler and avoids problems where the host machine's IP address has additional DNS registrations.
Closes: https://github.com/square/okhttp/issues/7603
> Avoid InetAddress.getCanonicalHostName().

- okhttp/src/jvmTest/java/okhttp3/internal/tls/CertificatePinnerChainValidationTest.java
See failure https://github.com/square/okhttp/actions/runs/3834111360/jobs/6526194017
```
CertificatePinnerChainValidationTest[jvm] > unrelatedPinnedIntermediateCertificateInChain()[jvm] FAILED
org.opentest4j.AssertionFailedError: JDK with version from 19 expected to fail with exception that ANYTHING
at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)`
```
> Make tolerant of JDK 19 quirks

- okhttp/src/jvmMain/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/jvmTest/java/okhttp3/CallTest.kt
The basic implementation for https://github.com/square/okhttp/issues/2257
Continuation of https://github.com/square/okhttp/pull/7479
It doesn't have special handling of 102, such as resetting any timeouts.
> Expand 103 handling to other non-specific 1XX messages.

- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/main/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/test/java/okhttp3/CacheTest.java
- okhttp/src/test/java/okhttp3/InformationalResponseCodeTest.kt
In progress, test is difficult without informational responses.
> [4.x] Backport 1XX handling from master

- okhttp/src/main/kotlin/okhttp3/internal/connection/RouteSelector.kt
- okhttp/src/test/java/okhttp3/EventListenerTest.java
From https://github.com/square/okhttp/pull/7073/files
> [4.x] Cherry pick: fix DoH error when using ip address as hostname

- okhttp/src/jvmMain/kotlin/okhttp3/Cookie.kt
The Cookie.expiresAt doc is currently worded in a way that implies persistent is the case of expiring at the end of the session.
As it says in the Cookie.persistent javadoc, it is the contrary of a session expiring cookie.
> fix Cookie.expiresAt doc

- build.gradle
- okhttp/build.gradle
fixes https://github.com/square/okhttp/issues/7654
> Add a Kotlin dependency to work around CVE-2022-24329

- build.gradle.kts
- gradle/libs.versions.toml
- mockwebserver-junit5/README.md
- okhttp/src/jvmMain/kotlin/okhttp3/Headers.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/Platform.kt
- samples/tlssurvey/src/main/kotlin/okhttp3/survey/ssllabs/UserAgentCapabilities.kt
It wasn't working because we weren't configuring the dependency type correctly.
https://github.com/xvik/gradle-animalsniffer-plugin/issues/64
Closes: https://github.com/square/okhttp/issues/7652
> Restore AnimalSniffer support

- CONTRIBUTING.md
- android-test/README.md
- android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt
- docs/contribute/contributing.md
- okhttp-android/src/androidTest/kotlin/okhttp3/android/AndroidAsyncDnsTest.kt
Refine doc and comments about how to run android test.
We need add an parameter `-PandroidBuild=true` so Gradle can know about `android-test ` project.
> Refine doc and comments about how to run android test

- README.md
This date has long since past, so lets just keep it as the general warning to not use this version.
> Remove outdated notice from README

- .github/workflows/build.yml
Currently shows a failed build after check finishes, but before the next job with tests completes.
> Don't publish junit results for check job

- okhttp/src/jvmTest/java/okhttp3/internal/idn/IdnaMappingTable.kt
- okhttp/src/jvmTest/java/okhttp3/internal/idn/IdnaMappingTableTest.kt
- okhttp/src/jvmTest/java/okhttp3/internal/idn/PlainTextIdnaMappingTable.kt
- okhttp/src/jvmTest/resources/okhttp3/internal/idna/IdnaMappingTable.txt
As described in UTS #46, https://www.unicode.org/reports/tr46
This is working towards OkHttp's own implementation of what IDN.toASCII() does on the JVM.
> Straightforward implementation of IDNA mapping, for tests only

- okhttp-testing-support/src/main/kotlin/okhttp3/internal/http2/Http2FlowControlConnectionListener.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/FlowControlListener.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/flowcontrol/WindowCounter.kt
- okhttp/src/jvmTest/java/okhttp3/internal/http2/Http2ConnectionTest.kt
Add an internal API for receiving HTTP/2 flow control information, definitely not complete.
This shows
Connection - unacked on connection - this is not true in the first, as connection doesn't bump until consumed via a stream
3 - The unacked on stream 3 (the stalled request)
3-buffer - The data sitting inside the Buffer to be read
5 & 5-buffer - same as 3.
As an example used before and after this fix https://github.com/square/okhttp/pull/7801/files
> Add flow control observability

- okhttp-testing-support/src/jvmMain/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/jvmTest/java/okhttp3/internal/ws/WebSocketHttpTest.java
Debugging flakyness introduced in https://github.com/square/okhttp/pull/7815
> Evict connection pool a second time after tests

- okhttp/src/main/kotlin/okhttp3/internal/Util.kt
I think this may have been left in from some println-debugging? Not sure.
Fixes #7851
> Stop printing suppressed exceptions to stdout

- okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java
Currently only the time to receive the headers is logged, which is often a much smaller duration than the total duration of receiving the headers and the body.
> Log total time of request when buffering body

- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp/src/main/kotlin/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.java
(cherry picked from commit f62fd4787653d8dd9035f6727c253b6cd900e0fd)
> [4.x] Fix websocket reconnect race condition (#7815)

- mockwebserver-deprecated/build.gradle.kts
- mockwebserver-junit4/build.gradle.kts
- mockwebserver-junit5/build.gradle.kts
- mockwebserver/build.gradle.kts
- okcurl/build.gradle.kts
- okhttp-brotli/build.gradle.kts
- okhttp-coroutines/build.gradle.kts
- okhttp-dnsoverhttps/build.gradle.kts
- okhttp-logging-interceptor/build.gradle.kts
- okhttp-sse/build.gradle.kts
- okhttp-tls/build.gradle.kts
- okhttp-urlconnection/build.gradle.kts
- okhttp/build.gradle.kts
Failing currently https://github.com/square/okhttp/actions/runs/6198721220/job/16829730445
```
Reason: Task ':logging-interceptor:dokkaJavadocJar' uses this output of task ':mockwebserver:dokkaGfm' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task ':mockwebserver:dokkaGfm' as an input of ':logging-interceptor:dokkaJavadocJar'.
2. Declare an explicit dependency on ':mockwebserver:dokkaG
3. 
```
> Disable javadoc temporarily

- okhttp/src/jvmMain/kotlin/okhttp3/Cache.kt
- okhttp/src/jvmTest/java/okhttp3/CacheTest.java
Avoid NPE and throw IOException
#fixes https://github.com/square/okhttp/issues/7978
> Handle certificate corruption

- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/test/java/okhttp3/CacheTest.java
Avoid NPE and throw IOException
#fixes https://github.com/square/okhttp/issues/7978
> [4.x] Handle certificate corruption

- okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/Http2Stream.kt
From https://github.com/square/okhttp/pull/7938
Avoid hanging on takeHeaders (incorrect 103 handling) when response body is empty.
If we mess up our logic (103 and so on), we call closeInternal on the stream from the timeout, but only if if source.isFinished() is false.  For an empty body, this will be true, so the next waitForIo, would wait indefinitely.
> Avoid infinite wait on bad response handling.

- okhttp/src/jvmTest/java/okhttp3/CacheTest.java
```
CacheTest[jvm] > secureResponseCachingWithCorruption()[jvm] FAILED
java.lang.NoSuchMethodError: java.util.Optional.orElseThrow()Ljava/lang/Object;
at okhttp3.CacheTest.secureResponseCachingWithCorruption(CacheTest.java:367)
```
> Fix JDK 8 test

- okhttp-coroutines/README.md
Fix wrong syntax in okhttp-coroutines/README.md
> Fix: Add explicit argument name in use lambda function in okhttp-coroutines/README.md

- okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/android/AndroidLog.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/android/StandardAndroidSocketAdapter.kt
From https://github.com/square/okhttp/issues/8116
Fix on master, before backporting.
> Fix Android logging call

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/jvmMain/kotlin/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/jvmTest/java/okhttp3/internal/ws/RealWebSocketTest.java
- okhttp/src/jvmTest/java/okhttp3/internal/ws/WebSocketHttpTest.java
We were seeing crashes in Deflater.deflate with a root cause of closing the deflater while it was in use.
The underlying problem is that web socket streams were closed when the web socket was canceled, but not by the thread that owned those streams.
This moves stream cleanup to always run on the owning thread:
- writer cleanup happens on the task queue
- reader cleanup happens after loopReader
This also introduces a new function, Streams.cancel() so a failed writer can break an active reader, and vise-versa. Previously we were using close() to do this job.
There's a lot of test changes but it's mostly in adding the TaskFaker facet to RealWebSocketTest. The test now runs with a fake clock, with the deterministic benefits that brings.
See also: https://github.com/square/okhttp/issues/6719
> Fix a concurrency problem with web socket cleanup

- okhttp/src/jvmMain/kotlin/okhttp3/internal/cache/CacheStrategy.kt
OkHttp would incorrectly use a cached response for a second request if the server's first response did not contain caching headers, if the system time was adjusted backward between the two requests。
> Fix: Staled cache response used when system time adjusted backward

- okhttp/src/jvmMain/kotlin/okhttp3/internal/ws/MessageInflater.kt
- okhttp/src/jvmTest/java/okhttp3/internal/ws/MessageDeflaterInflaterTest.kt
Closes: https://github.com/square/okhttp/issues/8078
> Don't infinite loop on self-terminating compressed websocket messages

- okhttp-sse/api/okhttp-sse.api
- okhttp-sse/src/main/kotlin/okhttp3/sse/EventSources.kt
- okhttp-sse/src/main/kotlin/okhttp3/sse/internal/RealEventSource.kt
- okhttp-sse/src/test/java/okhttp3/sse/internal/EventSourceHttpTest.java
Previously we prevented end-users from using their own implementations of Call.Factory because we casted down to RealCall in RealEventSource.
With this change we're implementing SSE without depending on any OkHttp implementation details.
This also introduces a new function in EventSources to create an EventSource.Factory from a Call.Factory, and hides the previous implementation that required a concrete OkHttpClient.
Finally this fixes SSE to publish the same EventListener events as regular HTTP calls.
> Change SSE to use the OkHttp public API only

- .github/workflows/build.yml
- android-test-app/build.gradle.kts
- android-test-app/proguard-rules.pro
- android-test-app/src/androidTest/kotlin/okhttp/android/testapp/PublicSuffixDatabaseTest.kt
- android-test-app/src/main/AndroidManifest.xml
- android-test-app/src/main/kotlin/okhttp/android/testapp/MainActivity.kt
- android-test-app/src/main/kotlin/okhttp/android/testapp/TestApplication.kt
- android-test-app/src/main/res/values/strings.xml
- android-test-app/src/main/res/xml/network_security_config.xml
- android-test-app/test-proguard-rules.pro
- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- okhttp-testing-support/src/main/resources/META-INF/proguard/okhttp3.pro
- okhttp/src/main/resources/META-INF/proguard/okhttp3.pro
- regression-test/build.gradle.kts
- settings.gradle.kts
Fix for https://github.com/square/okhttp/issues/8154
Keep the DB package name since it's now a literal.
Also add a test of a release build of an app.
> Test with release build & update proguard config.

- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/MockResponse.kt
- mockwebserver/src/main/kotlin/okhttp3/mockwebserver/MockWebServer.kt
- okcurl/src/main/kotlin/okhttp3/curl/Main.kt
- okhttp-sse/src/main/kotlin/okhttp3/internal/sse/RealEventSource.kt
- okhttp-sse/src/main/kotlin/okhttp3/internal/sse/ServerSentEventReader.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/HandshakeCertificates.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt
- okhttp-tls/src/main/kotlin/okhttp3/tls/internal/InsecureExtendedTrustManager.kt
- okhttp-urlconnection/src/main/kotlin/okhttp3/JavaNetCookieJar.kt
- okhttp/src/main/kotlin/okhttp3/internal/Util.kt
- okhttp/src/main/kotlin/okhttp3/internal/hostnames.kt
- okhttp/src/main/kotlin/okhttp3/internal/internal.kt
This is a backport for 4.x branch from #7734.
> [4.x] Avoid exposing internal functions and properties

- native-image-tests/src/main/kotlin/okhttp3/PublicSuffixDatabaseTest.kt
Failing in https://github.com/square/okhttp/actions/runs/7313504687/job/19925152167
> Avoid checking file metadata in graal tests

- okhttp/api/okhttp.api
- okhttp/src/main/kotlin/okhttp3/MultipartBody.kt
- okhttp/src/test/java/okhttp3/MultipartBodyTest.kt
If a multipart form has a oneshot Part, then it is also oneshot.
Fix for https://github.com/square/okhttp/issues/8138
> Support oneshot forms

- settings.gradle.kts
Without this, developers need to prepare their environments or they might see failures like this:
Execution failed for task ':okhttp-idna-mapping-table:test'.
> Error while evaluating property 'javaLauncher' of task ':okhttp-idna-mapping-table:test'.
> Failed to calculate the value of task ':okhttp-idna-mapping-table:test' property 'javaLauncher'.
> No matching toolchains found for requested specification: {languageVersion=21, vendor=any, implementation=vendor-specific} for MAC_OS on aarch64.
> No locally installed toolchains match and toolchain download repositories have not been configured.
> Resolve JDKs if necessary

- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
First step of https://github.com/square/okhttp/issues/8206
> Minimise HttpOverHttp2Test flakes

- build.gradle.kts
- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver-junit4/src/main/kotlin/mockwebserver3/junit4/MockWebServerRule.kt
- mockwebserver-junit5/src/main/kotlin/mockwebserver3/junit5/internal/MockWebServerExtension.kt
- mockwebserver-junit5/src/main/kotlin/mockwebserver3/junit5/internal/MockWebServerInstance.kt
- mockwebserver/src/main/kotlin/mockwebserver3/Dispatcher.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockResponse.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockResponseBody.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/main/kotlin/mockwebserver3/PushPromise.kt
- mockwebserver/src/main/kotlin/mockwebserver3/QueueDispatcher.kt
- mockwebserver/src/main/kotlin/mockwebserver3/RecordedRequest.kt
- mockwebserver/src/main/kotlin/mockwebserver3/SocketPolicy.kt
- mockwebserver/src/main/kotlin/mockwebserver3/Stream.kt
- mockwebserver/src/main/kotlin/mockwebserver3/StreamHandler.kt
- okhttp-android/src/main/kotlin/okhttp3/android/AndroidAsyncDns.kt
- okhttp-coroutines/src/main/kotlin/okhttp3/JvmCallExtensions.kt
- okhttp-java-net-cookiejar/src/main/kotlin/okhttp3/java/net/cookiejar/JavaNetCookieJar.kt
- okhttp-sse/src/main/kotlin/okhttp3/sse/EventSources.kt
- okhttp/src/main/kotlin/okhttp3/AsyncDns.kt
- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/main/kotlin/okhttp3/CacheControl.kt
- okhttp/src/main/kotlin/okhttp3/ConnectionListener.kt
- okhttp/src/main/kotlin/okhttp3/ConnectionPool.kt
- okhttp/src/main/kotlin/okhttp3/Cookie.kt
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/Protocol.kt
- okhttp/src/main/kotlin/okhttp3/Request.kt
- okhttp/src/main/kotlin/okhttp3/RequestBody.kt
- okhttp/src/main/kotlin/okhttp3/Response.kt
In a follow-up PR I intend to remove the annotation on any API that we're willing to commit to for OkHttp 5.0.0.
In a follow-up PR I'd also like to hide all remaining APIs from Java langauge callers.
> Mechanically tag all new APIs as @ExperimentalOkHttpApi

- okhttp-brotli/src/main/kotlin/okhttp3/brotli/internal/DecompressionBombChecker.kt
- okhttp-brotli/src/main/kotlin/okhttp3/brotli/internal/Uncompress.kt
- okhttp-brotli/src/test/java/okhttp3/brotli/BrotliBombTest.kt
This uses the same ratio technique as Envoy. It's a quick hack and it gets out of the way.
Closes: https://github.com/square/okhttp/issues/7738
> Defend against brotli decompression bombs

- container-tests/src/test/java/okhttp3/containers/BasicProxyTest.kt
Investigating https://github.com/square/okhttp/issues/8233
Will check in with one test disabled until a fix is made.
> HTTP Proxy test

- okhttp-dnsoverhttps/src/main/kotlin/okhttp3/dnsoverhttps/DnsOverHttps.kt
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsOverHttpsTest.kt
- okhttp/api/okhttp.api
- okhttp/src/main/kotlin/okhttp3/Request.kt
- okhttp/src/main/kotlin/okhttp3/internal/cache/CacheInterceptor.kt
- okhttp/src/main/kotlin/okhttp3/internal/cache/CacheStrategy.kt
- okhttp/src/test/java/okhttp3/CacheTest.kt
A minimal change to allow a cacheUrlOverride on request for the following examples
- Define the canonical resource this request represents, such as the origin server for a CDN request
- Remove transient query params such as S3 tokens
- A narrow window of POST support - by declaring a POST should otherwise be treated as a GET, and define an appropriate unique url to represent the body if relevant.
It is implemented almost entirely within CacheInterceptor, mutating the request/response that Cache sees to avoid a broader change such as supporting POSTs.
Addresses https://github.com/square/okhttp/issues/8211 also https://github.com/square/okhttp/issues/8113
> Cache URL Override

- regression-test/src/androidTest/java/okhttp/regression/compare/AndroidHttpEngineTest.kt
Comparing results between HttpClient h3 and OkHttp.
Enable HTTP/3
> Test using Http/3

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- okhttp/api/okhttp.api
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/OkHttpClientTest.kt
- okhttp/src/test/java/okhttp3/internal/ws/RealWebSocketTest.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.kt
The default timeout of 60 seconds is too high for one of my use cases. I tried my best to match the existing API. Please feel free to give me feedback on how I can make this as good as possible to increase the likelihood of it being merged.
PS Thanks for the efforts maintaining critical infrastructure like this library.
<details>
<summary><em>Edit: Figured it out. My JVM was set to Java 8 SDK.</em> I sadly could not run `./gradlew checks`. I included the errors I got.</summary>
```
❯ ./gradlew checks                                                  
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.5/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will …
```
> allow configuring web socket close timeout

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- okhttp/api/okhttp.api
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/test/java/okhttp3/OkHttpClientTest.kt
- okhttp/src/test/java/okhttp3/internal/ws/WebSocketHttpTest.kt
The name closeTimeout might be mistaken as a regular HTTP option.
> Use the name webSocketCloseTimeout

- samples/tlssurvey/build.gradle.kts
IntelliJ grabs the wrong one which is quite confusing.
> Don't depend on external OkHttp from within OkHttp

- container-tests/src/test/java/okhttp3/containers/BasicProxyTest.kt
This test is disabled, and it refers to a closed bug.
> Don't test MockServer's HTTP proxy of an HTTP/2 call

- okhttp-testing-support/src/main/kotlin/okhttp3/TestValueFactory.kt
- okhttp/api/okhttp.api
- okhttp/src/main/kotlin/okhttp3/ConnectionPool.kt
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/ForceConnectRoutePlanner.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/PoolConnectionUser.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
- okhttp/src/test/java/okhttp3/FakeRoutePlanner.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
This PR adds support for configuring the connection pool to proactively create connections to specified hosts. This is useful for "prewarming" the connection pool before it starts being used.
The main public API change is adding `ConnectionPool.setPolicy(Address, AddressPolicy)`. A policy specifies how many _concurrent streams_ should be supported by the pool (which might be satisfied by a single http/2 connection or by N http/1.1 connections).
The main internal change is adding a new task queue to `RealConnectionPool` which checks to see if it needs to create new connections to satisfy existing policies. This task is enqueued any time a policy changes, a connection is closed, or an http/2 connection's settings decrease the number of concurrent streams supported.
> Support minimum connection pool size

- okhttp-coroutines/src/main/kotlin/okhttp3/JvmCallExtensions.kt
- okhttp-coroutines/src/test/kotlin/okhttp3/SuspendCallTest.kt
Also make callers opt in to an unstable coroutines API. If the resource
cleanup coroutines API changes, we'll have to change this API.
Remove the OkHttp experimental API. This is a good enough API as far
as OkHttp is concerned.
> Don't leak response bodies in executeAsync

- okhttp-logging-interceptor/api/logging-interceptor.api
- okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.kt
For logging interceptor: add an option to hide the value of sensitive query parameters in the request and response URL. 
Inspired by the implementation of header redaction in `okhttp3.logging.HttpLoggingInterceptor`
**To use**
Call the method `redactQueryParams(the list of query parameters to hide value, separated by commas)` from a `okhttp3.logging.HttpLoggingInterceptor` instance. For example, to hide the value of "user" and "password" query parameters, use `interceptor.redactQueryParams("user", "password")`.
- Original URL: `http://localhost:8000/api/login?user=user1&authentication=basic&password=confidential_password"`
- With the method applied: `http://localhost:8000/api/login?user=██&authentication=basic&password=██"`
> Hide the value of sensitive query parameters in log

- okhttp-android/src/test/kotlin/okhttp3/android/RobolectricOkHttpClientTest.kt
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsOverHttpsTest.kt
- okhttp/api/okhttp.api
- okhttp/src/main/kotlin/okhttp3/Cache.kt
- okhttp/src/main/kotlin/okhttp3/internal/NativeImageTestsAccessors.kt
- okhttp/src/test/java/okhttp3/CacheTest.kt
- okhttp/src/test/java/okhttp3/CallTest.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
- samples/tlssurvey/src/main/kotlin/okhttp3/survey/RunSurvey.kt
Put FileSystem before Path, as is convention.
Also put this new constructor in the public API.
> Change parameter order for Cache constructor

- okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/test/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
- okhttp/src/test/java/okhttp3/internal/ws/RealWebSocketTest.kt
Previously this used locks to stop threads from executing. Now it uses a custom 'yield' function to accomplish a similar purpose. The main benefit of the new approach is we're no longer subject to unspecified lock release order - we maintain our own queue and get true deterministic order of execution.
> Redo TaskFaker's internal queue

- okhttp-testing-support/src/main/kotlin/okhttp3/TestUtilJvm.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp-tls/src/test/java/okhttp3/tls/HandshakeCertificatesTest.kt
- okhttp/src/test/java/okhttp3/SocksProxy.kt
- okhttp/src/test/java/okhttp3/internal/cache2/RelayTest.kt
- okhttp/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.kt
- okhttp/src/test/java/okhttp3/internal/http2/MockHttp2Peer.kt
This is different from the production thread factory:
- No daemon threads in tests. We don't need 'em.
- Threads are numbered in tests. We do need that.
> Extract a test thread factory

- okhttp/src/test/java/okhttp3/FakeRoutePlanner.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
1. The first test just needed to be uncommented now that https://github.com/square/okhttp/pull/8348 is merged
2. A second test was added to exercise http2-specific functionality
> Add connection pool pre-warming tests

- okhttp-testing-support/src/main/kotlin/okhttp3/TestValueFactory.kt
- okhttp/src/main/kotlin/okhttp3/Dispatcher.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Writer.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
Main fix for https://github.com/square/okhttp/issues/8284
replace synchronized with ReentrantLock.withLock, and wait/notify with lock.newCondition.signal/await.
Relies on test results from BasicLoomTest
> Move RealCall and RealConnection to loom safe locks

- okhttp/api/okhttp.api
- okhttp/src/main/kotlin/okhttp3/CacheControl.kt
- okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/main/kotlin/okhttp3/internal/-CacheControlCommon.kt
- okhttp/src/test/java/okhttp3/CacheControlTest.kt
Use this as our preferred API for accepting a duration in OkHttpClient and CacheControl.
Also hide these functions from the Java API.
> Fix public APIs for kotlin.time.Duration

- okhttp-testing-support/src/main/kotlin/okhttp3/TestValueFactory.kt
- okhttp/src/main/kotlin/okhttp3/Dispatcher.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Writer.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
Reverts square/okhttp#8290
Unfortunately I think this PR is missing some `synchronized` blocks that needed to be converted to `withLock {}` blocks. Mixing and matching the two definitely doesn’t work, and our tests aren’t sophisticated enough to cover that.
I think this is a good idea; we just need to be particularly precise with the implementation. Every occurrence of a lock needs to be fixed together; otherwise we split the lock.
> Revert "Move RealCall and RealConnection to loom safe locks"

- build.gradle.kts
- okhttp-coroutines/api/okhttp-coroutines.api
- okhttp-coroutines/src/main/kotlin/okhttp3/coroutines/ExecuteAsync.kt
- okhttp-coroutines/src/test/kotlin/okhttp3/coroutines/ExecuteAsyncTest.kt
- okhttp/src/test/java/okhttp3/internal/publicsuffix/PublicSuffixListGenerator.kt
- samples/tlssurvey/src/main/kotlin/okhttp3/survey/Iana.kt
This has the side-effect of fixing our packaging of this module. Previously the okhttp-coroutines.jar contained the code from the :okhttp artifact, not the :okhttp-coroutines artifact. I suspect something in one of our build steps is incorrectly using the package names (only) as a cache key, and it should instead be using the package contents.
> Move coroutines extensions to okhttp3.coroutines

- okhttp-testing-support/src/main/kotlin/okhttp3/TestValueFactory.kt
- okhttp/src/main/kotlin/okhttp3/Dispatcher.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/Locks.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Writer.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
- okhttp/src/test/java/okhttp3/internal/http2/Http2ConnectionTest.kt
Mostly https://github.com/square/okhttp/pull/8290
But with a centralised lock definition.  Draft for discussion, but possibly we could encode the rules from docs/contribute/concurrency.md, so we fail fast if we ever break them.
> Move to centralised loom safe locks

- okhttp/src/test/java/okhttp3/FakeRoutePlanner.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
- okhttp/src/test/java/okhttp3/internal/connection/FastFallbackExchangeFinderTest.kt
1. Advance taskFaker time forward to the present when the test starts.
* Fixes a problem introduced in https://github.com/square/okhttp/pull/8360
3. Stop having multiple factories and taskfakers floating around.
> Fix ConnectionPoolTest bug

- okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
We've got a race where we'll start a thread when we need one, even if we've already started a thread. This changes TaskRunner's behavior to never add a thread if we're still waiting for a recently-added one to start running.
This is intended to reduce the number of threads contenting for the TaskRunner lock as reported in this issue:
https://github.com/square/okhttp/issues/8388
> Start fewer threads in TaskRunner

- okhttp/src/test/java/okhttp3/RouteFailureTest.kt
InetSocketAddress's constructor will try to resolve the host to an IP address. As a result, if you're on a network that happens to have a resolvable `myproxy` host, this test would fail -- and as it turns out, my home network does.
Instead, use InetSocketAddress.createUnresolved().
> Fix an environment-specific bug in RouteFailureTest

- okhttp/src/main/kotlin/okhttp3/Dispatcher.kt
Allow nullable executorService parameter in Dispatcher.kt constructor to maintain backwards compatibility with OkHttp 3.x migration to 4.x and beyond.
For some more context: 
In my internal company's library, there were some code snippets using OkHttp 3.x that passed null into the Dispatcher constructor for the `executorService` parameter. This worked with the Java implementation of OkHttp library, but with the migration to Kotlin in 4.x and the `executorService` parameter not being nullable in Dispatcher constructor, this caused some projects to fail after upgrading from OkHttp 3.x to 4.x
> Allow nullable executorService parameter in Dispatcher class constructor

- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
Want to clear out a bunch of dependency PRs which will be less noisy with this disabled for now
Tracking reenabling in https://github.com/square/okhttp/issues/8451
> Disable connectionPreWarmingHttp2 for now

- okhttp/src/main/kotlin/okhttp3/Response.kt
Previous doc shows that body is always null for cacheResponse, networkResponse and priorResponse. It's confusing since the body property can't be null. This pull request updates the doc to show that we'll get an unreadable body from the listed responses.
> update javadoc for `Response#body`

- okhttp-dnsoverhttps/src/main/kotlin/okhttp3/dnsoverhttps/DnsOverHttps.kt
When using an interceptor to handle HTTP/3, this warning is constantly output in the log, which is unnecessary.
> Incorrect protocol: quic

- okhttp/src/main/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/test/java/okhttp3/CallTest.kt
This change updates the client to handle multiple 1xx (Processing etc) responses from the server. The client now waits for the final response with a status code other than 1xx before proceeding.
From https://datatracker.ietf.org/doc/html/rfc7231#section-6.2
>    A client MUST be able to parse one or more 1xx responses received
prior to a final response, even if the client does not expect one.  A
user agent MAY ignore unexpected 1xx responses.
fixes #8568
> Fix: Handle multiple 1xx responses

- okhttp-testing-support/src/main/kotlin/okhttp3/OkHttpClientTestRule.kt
- okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/ConnectPlan.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/Locks.kt
- okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt
Investigating https://github.com/square/okhttp/issues/8388 - trying to ensure we have a central place to reason about our locks.
> Centralise more locks

- okhttp-dnsoverhttps/src/main/kotlin/okhttp3/dnsoverhttps/DnsOverHttps.kt
- okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DnsOverHttpsTest.kt
Rely on OkHttpClient caching, instead of a cache only request.
Possibly a slight performance regression, making extra conditional requests, but it's unclear that that is not intended.
> Simplify the DnsOverHttps logic

- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Reader.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Writer.kt
- okhttp/src/main/kotlin/okhttp3/internal/http2/Settings.kt
This makes the code difficult to understand.
> Remove renumbering indirection in settings frames

- mkdocs.yml
- Fix pymdownx.emoji extension warning
- `mkdocs build`
```
❯ mkdocs build
INFO    -  DeprecationWarning: 'materialx.emoji.twemoji' is deprecated.
Material emoji logic has been officially moved into mkdocs-material
version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.
```
markdown_extensions:
- pymdownx.emoji:
emoji_index: !!python/name:material.extensions.emoji.twemoji
emoji_generator: !!python/name:material.extensions.emoji.to_svg
```
'mkdocs_material_extensions' is deprecated and will no longer be
supported moving forward. This is the last release.
File "/opt/homebrew/lib/python3.12/site-packages/materialx/emoji.py", line 118, in twemoji
return _patch_index(options)
File …
```
> Fix pymdownx.emoji extension warning

- okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/test/java/okhttp3/internal/concurrent/TaskRunnerTest.kt
- okhttp/src/test/java/okhttp3/internal/connection/ConnectionPoolTest.kt
Previously each run did this:
- acquire a lock to take a task
- acquire a lock to finish a task
- if crashed, acquire a lock to start a new thread
So to run 10 tasks without any crashes, we'd acquire the lock 20 times.
With this update, we do this:
- acquire a lock to take the first task
- acquire a lock to release task N and take task N + 1
So to run 10 tasks without any crashes, we now acquire the lock 11 times.
> Acquire fewer locks in TaskRunner

- .github/workflows/build.yml
- build.gradle.kts
- buildSrc/build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- okcurl/build.gradle.kts
- okhttp-coroutines/src/test/kotlin/okhttp3/coroutines/ExecuteAsyncTest.kt
- okhttp/build.gradle.kts
Want to separate these dependency bumps from 
https://github.com/square/okhttp/pull/8600
Okio leading the push to 2.1.0 in https://github.com/square/okio/pull/1552
> Dependency bumps

- samples/guide/src/main/java/okhttp3/recipes/UploadProgress.java
Dear. @swankjesse
I improved the `upload progress recipe` discussed in #1471 #1528
It was rewritten based on the discussed requirements.
After discussion, I would like to write a Kotlin recipe
I'm awaiting your comments. 
Thank you for your time
> Upload progress recipe

- okhttp/build.gradle.kts
Add add-opens and also fails to run.
> Avoid robolectric added add-opens on JDK 1.8

- okhttp/src/jvmTest/kotlin/okhttp3/internal/connection/ConnectionPoolTest.kt
The assertion `taskRunner.activeQueues()` was commented out due to a race condition causing flaky tests. This ensures more consistent test results while the underlying issue is investigated.
It's trivial to turn it from flaky to permanently failing by adding delay such as printlns.
```
assertThat(taskRunner.activeQueues()).isNotEmpty()
val qq = taskRunner.activeQueues()
println(qq)
println(qq.first().activeTask)
println(qq.first().scheduledTasks)
assertThat(taskRunner.activeQueues()).isNotEmpty() <-- Fails here
```
> Disable flaky test assertion in ConnectionPoolTest

- okhttp/src/main/kotlin/okhttp3/MultipartReader.kt
- okhttp/src/main/kotlin/okhttp3/internal/FixedLengthSource.kt
- okhttp/src/test/java/okhttp3/MultipartReaderTest.kt
* Demonstrate poor buffering case
* Fix for repeated reads of small byteCount from large part
(cherry picked from commit 3cc87c3fc4bee09642cc22a561060da7af2b939c)
> [4.x] Fix poor buffering case for MultipartReader

- .github/renovate.json
With weekly we will _never_ be able to catch up to latest.
> Speed up dependency updates

- build.gradle.kts
- gradle/libs.versions.toml
Also adds junit-platform-launch explicit dependency and bump version
We could do more and use the BOM https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-bom
But making the minimal change for now
> Update junit5 monorepo

- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Handshake.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilJvm.kt
`Arrays.asList` creates unmodifiable list, also, the new version creates fewer temp lists and arrays.
> refactor: simplify internal immutable list extensions

- mockwebserver/src/test/java/mockwebserver3/RecordedRequestTest.kt
- okhttp/api/android/okhttp.api
- okhttp/api/jvm/okhttp.api
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Cache.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Headers.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Request.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/RequestBody.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Response.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/ResponseBody.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilCommon.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilJvm.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/jvmTest/kotlin/okhttp3/HeadersJvmTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http2/Http2ConnectionTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http2/HttpOverHttp2Test.kt
removed informal internal constants
closes #8670
> `Empty` constant of Headers, RequestBody, ResponseBody

- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilJvm.kt
> fix: real unmodifiable list

- .github/renovate.json
Just because someone put a colon in their commit message doesn't mean we want this system.
> Disable Renovate semantic commits

- mockwebserver-deprecated/src/test/java/okhttp3/mockwebserver/MockWebServerTest.kt
- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.kt
Change in https://bugs.openjdk.org/browse/JDK-8335135
> HttpInputStream does not throw IOException when response is truncated
> Fix test with latest JDKs

- .github/workflows/build.yml
- build.gradle.kts
- okhttp/build.gradle.kts
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/Locks.kt
For ALPN and other niche workflows, run only the core tests.
> Remove JDK 8 ALPN runs of module-specific tests

- okhttp-testing-support/src/main/kotlin/okhttp3/internal/concurrent/TaskFaker.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Dispatcher.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-UtilJvm.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/cache/DiskLruCache.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/cache2/Relay.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/concurrent/Lockable.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/concurrent/TaskQueue.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/concurrent/TaskRunner.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/Locks.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealCall.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Http2Connection.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Http2Writer.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/ws/RealWebSocket.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http2/Http2ConnectionTest.kt
We migrated to ReentrantReadWriteLock to better support Loom, but now we can use synchronized and still support Loom. This old mechanism may be faster than ReentrantReadWriteLock.
> Change the locking mechanism to 'synchronized'

- .github/workflows/build.yml
I recently broke support for Loom on earlier JDKs
> Run the loom tests on JDK 24

- android-test/src/test/kotlin/okhttp/android/test/BaseOkHttpClientUnitTest.kt
- android-test/src/test/kotlin/okhttp/android/test/NonRobolectricOkHttpClientTest.kt
- okhttp/src/androidMain/kotlin/okhttp3/internal/platform/android/AndroidLog.kt
If Robolectric not active, then unit tests for Android will fail annoyingly.
> Add a test and fix for non-robolectric android test.

- .github/workflows/build.yml
- build.gradle.kts
See (internally) http://go/central-portal-migration-com-squareup for context.
> Migrate to Sonatype Central Portal

- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/DeprecationBridge.kt
- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/QueueDispatcher.kt
- mockwebserver-junit4/src/main/kotlin/mockwebserver3/junit4/MockWebServerRule.kt
- mockwebserver-junit5/src/main/kotlin/mockwebserver3/junit5/internal/MockWebServerExtension.kt
- mockwebserver/api/mockwebserver3.api
- mockwebserver/build.gradle.kts
- mockwebserver/src/main/kotlin/mockwebserver3/Dispatcher.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockResponse.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockResponseBody.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/main/kotlin/mockwebserver3/PushPromise.kt
- mockwebserver/src/main/kotlin/mockwebserver3/QueueDispatcher.kt
- mockwebserver/src/main/kotlin/mockwebserver3/RecordedRequest.kt
- mockwebserver/src/main/kotlin/mockwebserver3/SocketHandler.kt
- mockwebserver/src/main/kotlin/mockwebserver3/SocketPolicy.kt
- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.kt
- okhttp-testing-support/build.gradle.kts
- okhttp-testing-support/src/main/kotlin/okhttp3/internal/duplex/MockSocketHandler.kt
- okhttp/src/jvmTest/kotlin/okhttp3/CacheTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/CallKotlinTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/CallTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/DuplexTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/FastFallbackTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/InterceptorTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/RouteFailureTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/URLConnectionTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http2/HttpOverHttp2Test.kt
Enable explicit API mode in mockwebserver3.
Also remove @ExperimentalOkHttpApi in a few places.
Also rename 'shutdown' to 'close' in MockWebServer and Dispatcher.
Also rename QueueDispatcher.enqueueResponse() to QueueDispatcher.enqueue.
> Enable explicit API mode in mockwebserver3.

- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/main/kotlin/mockwebserver3/internal/SleepNanos.kt
- mockwebserver/src/main/kotlin/mockwebserver3/internal/ThrottledSink.kt
It was possible to configure delays that would be honored after MockWebServer was shut down. With this fix any delay will be abandoned once the server is closed.
> Fix a liveness bug in MockWebServer

- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/MockWebServer.kt
- mockwebserver/api/mockwebserver3.api
- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/test/java/mockwebserver3/MockResponseSniTest.kt
- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/CallTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/ConnectionListenerTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/EventListenerTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/RouteFailureTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/URLConnectionTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/WholeOperationTimeoutTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http2/HttpOverHttp2Test.kt
Now calling MockWebServer.port and similar functions will not implicity start the server. It is instead necessary to explicitly call the start() function.
The problem with the old behavior was that reading the port field could fail with an IOException, which is weird behavior for reading a property.
> Change some MockWebServer ergonomics

- mockwebserver-deprecated/src/main/kotlin/okhttp3/mockwebserver/DeprecationBridge.kt
- mockwebserver/src/main/kotlin/mockwebserver3/MockWebServer.kt
- mockwebserver/src/main/kotlin/mockwebserver3/RecordedRequest.kt
- mockwebserver/src/main/kotlin/mockwebserver3/internal/RecordedRequestFactory.kt
- mockwebserver/src/test/java/mockwebserver3/MockWebServerTest.kt
- mockwebserver/src/test/java/mockwebserver3/RecordedRequestTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/CallTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/InterceptorTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/URLConnectionTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http2/HttpOverHttp2Test.kt
Null if we didn't capture a body, and empty if we
captured an empty body.
> Permit RecordedRequest.body to be null or empty

- okhttp-coroutines/src/main/kotlin/okhttp3/coroutines/ExecuteAsync.kt
- okhttp-coroutines/src/test/kotlin/okhttp3/coroutines/ExecuteAsyncTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/publicsuffix/PublicSuffixListGenerator.kt
> Stop using experimental coroutines APIs

- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Response.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/jvmTest/kotlin/okhttp3/TrailersTest.kt
We only need to read the response body if its coming from a real server.
Closes: https://github.com/square/okhttp/issues/8902
> Don't force a response body read on all trailers

- okhttp/api/android/okhttp.api
- okhttp/api/jvm/okhttp.api
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Response.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/TrailersSource.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/Exchange.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http/CallServerInterceptor.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http/ExchangeCodec.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http1/Http1ExchangeCodec.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Http2ExchangeCodec.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/Http2Stream.kt
- okhttp/src/jvmTest/kotlin/okhttp3/ResponseJvmTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/TrailersTest.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/http2/Http2ConnectionTest.kt
This restores behavior we had in OkHttp 4.x that I broke when I changed Response.trailers() to block
until trailers were available.
Closes: https://github.com/square/okhttp/issues/8916
> New Response.peekTrailers() API

- .github/workflows/build.yml
- okcurl/src/test/kotlin/okhttp3/curl/OkcurlTest.kt
Seems that the filtered set is not a popular approach. Assuming we have mostly non flaky builds, run more things on all builds (main, branches, prs).
> Run most builds on PRs

- android-test/build.gradle.kts
- android-test/src/test/kotlin/okhttp/android/test/BaseOkHttpClientUnitTest.kt
- android-test/src/test/kotlin/okhttp/android/test/NonRobolectricOkHttpClientTest.kt
- android-test/src/test/kotlin/okhttp/android/test/RobolectricOkHttpClientTest.kt
- okhttp/src/androidMain/kotlin/okhttp3/internal/platform/Android10Platform.kt
- okhttp/src/androidMain/kotlin/okhttp3/internal/platform/android/AndroidLog.kt
Part of an analysis of https://github.com/square/okhttp/issues/8927
Working with includeTestResources and use of an internal method `PlatformRegistry.applicationContext`
> Add test demonstrating topPrivateDomain on Robolectric

- .github/workflows/build.yml
These are run multiple times, but the check job, and windows seems anecdotally most flaky.
> Reduce flakes by not unit testing in check

- okhttp/src/jvmTest/kotlin/okhttp3/internal/publicsuffix/PublicSuffixListGenerator.kt
Looks like this got missed when the directory structure was changed awhile back
> Fix PublicSuffixListGenerator testResources path

- android-test/src/test/kotlin/okhttp/android/test/AndroidLoggingTest.kt
- okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt
- okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.kt
When there's lots of messages, it is difficult to map the failure messages to the start messages without the url.
> Print URLs in HttpLoggingInterceptor when the call fails

- docs/recipes.md
- samples/guide/src/main/java/okhttp3/recipes/UploadProgress.java
- samples/guide/src/main/java/okhttp3/recipes/kt/UploadPorgress.kt
- samples/guide/src/main/java/okhttp3/recipes/kt/UploadProgress.kt
Upload Progress Recipe (#8493)
This is follow-up work. 
1. Created a Kotlin version of the UploadProgress Recipe.
2. Adjusted the indentation of Recipe #8493.
3. Added java and kt to the recipe page.
Example image below
> add Kotlin version and update UploadProgress recipe

- okhttp/src/jvmMain/java9/module-info.java
```
> Task :logging-interceptor:compileKotlin FAILED
e: file:///home/runner/work/okhttp/okhttp/okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt:273:27 Symbol is declared in module 'okhttp3' which does not export package 'okhttp3.internal.connection'.
```
> Fix merge issue with modules and logging

- okhttp/src/commonJvmAndroid/kotlin/okhttp3/Cache.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/cache/CacheInterceptor.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http/HttpMethod.kt
- okhttp/src/jvmTest/kotlin/okhttp3/CacheTest.kt
Reuse tests from https://github.com/square/okhttp/pull/9027
But with minimal support requiring a specific override.
> Enable QUERY caching via cacheUrlOverride

- okhttp-testing-support/src/main/kotlin/okhttp3/TestValueFactory.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/ConnectionPool.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/OkHttpClient.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealConnection.kt
- okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealConnectionPool.kt
- okhttp/src/jvmTest/kotlin/okhttp3/FakeRoutePlanner.kt
- okhttp/src/jvmTest/kotlin/okhttp3/internal/connection/ConnectionPoolTest.kt
It's currently unused.
I'd like to bring this feature back soon, but using regular Calls to make it happen rather than having Connections created without a Call object. That should avoid some special cases.
> Tear down AddressPolicy
